import type { ReviewData, QnaItem, Review } from "@/app/lib/types";
import { calculateReviewSummary } from "@/lib/reviews";

const reviewItems: Review[] = [
  {
    id: "r-a01",
    userName: "lm*****",
    rating: 5,
    date: "2026.06.23",
    variant: "차콜",
    content: "컬러나 질감이 마음에 듭니다.",
  },
  {
    id: "r-a02",
    userName: "pa*****",
    rating: 5,
    date: "2026.06.15",
    variant: "화이트",
    content: "깔끔한 디자인에 맘에 들어요!",
  },
  {
    id: "r-a03",
    userName: "he*****",
    rating: 5,
    date: "2026.05.31",
    variant: "화이트",
    content: "배송도 빠르고 상품도 만족합니다",
  },
  {
    id: "r-a04",
    userName: "ky*****",
    rating: 5,
    date: "2026.05.24",
    variant: "화이트",
    content: "조이 침대랑도 색깔이 딱 맞고 튼튼해서 좋습니다",
  },
  {
    id: "r-a05",
    userName: "ma*****",
    rating: 5,
    date: "2026.05.16",
    variant: "화이트",
    content: "3단 서랍장이고 화장대랑 같이 놓아서 쓰고 있어요",
  },
  {
    id: "r-a06",
    userName: "hl*****",
    rating: 5,
    date: "2026.05.08",
    variant: "화이트",
    content: "생각보다 크고 튼튼하고 고급져보여요 좀 비싸도 한샘으로하길 잘한듯요",
  },
  {
    id: "r-a07",
    userName: "bh*****",
    rating: 5,
    date: "2026.04.11",
    variant: "차콜",
    content: "깔끔하고 이뻐요 레일이 스스르 닫혀서 좋네요",
  },
  {
    id: "r-a08",
    userName: "nj*****",
    rating: 5,
    date: "2026.04.11",
    variant: "화이트",
    content: "튼튼하고 좋아요 기사님 친절하셨어요",
  },
  {
    id: "r-a09",
    userName: "sm*****",
    rating: 5,
    date: "2026.03.30",
    variant: "화이트",
    content: "빠른배송 상품 만족합니다.",
  },
  {
    id: "r-a10",
    userName: "ka*****",
    rating: 5,
    date: "2026.03.28",
    variant: "화이트",
    content: "깔끔하고 고급스럽습니다. 소재가 크림색으로 고급스럽습니다. 엄마방에 설치해드렸는데 매우 만족하세요. 서랍도 부드럽게 닫힙니다.",
  },
  {
    id: "r-a11",
    userName: "mh*****",
    rating: 5,
    date: "2026.02.22",
    variant: "화이트",
    content: "수납력이 좋고 디자인도 심플해서 좋아요.",
  },
  {
    id: "r-a12",
    userName: "gk*****",
    rating: 5,
    date: "2026.02.15",
    variant: "화이트",
    content: "서랍장 수납 넉넉하고 화장대랑 세트로 넘 예쁩니당",
  },
  {
    id: "r-a13",
    userName: "ch*****",
    rating: 5,
    date: "2026.01.02",
    variant: "차콜",
    content: "생각보다 넉넉한 사이즈라 수납이 많이 될거같습니다!",
  },
  {
    id: "r-a14",
    userName: "hs*****",
    rating: 5,
    date: "2026.01.01",
    variant: "차콜",
    content: "디자인도 좋고 만듦새도 좋네요",
  },
  {
    id: "r-a15",
    userName: "ss*****",
    rating: 5,
    date: "2025.11.22",
    variant: "화이트",
    content: "색상도 마음에 들고 수납공간도 적정하고 편리합니다.",
  },
  {
    id: "r-a16",
    userName: "ju*****",
    rating: 5,
    date: "2025.11.15",
    variant: "화이트",
    content: "레일 퀄리티도 좋고 공간도 아주 넓어서 좋습니다",
  },
  {
    id: "r-a17",
    userName: "lt*****",
    rating: 5,
    date: "2025.10.25",
    variant: "차콜",
    content: "한샘 매장에서 친절하게 안내해주셔서 화장대set와 3단 서랍장까지 잘 구매하였습니다~! 튼튼하고 색상도 깔끔하니 이쁩니다~~~~",
  },
  {
    id: "r-a18",
    userName: "my*****",
    rating: 4,
    date: "2025.10.16",
    variant: "화이트",
    content: "깔끔하고 이쁘네요~~ 때도 덜타는 색상이라 더 맘에 들어요",
  },
  {
    id: "r-a19",
    userName: "sk*****",
    rating: 5,
    date: "2025.10.12",
    variant: "화이트",
    content: "안방에 티비 올려놓았는데 수납도 되고 좋습니다",
  },
  {
    id: "r-a20",
    userName: "yo*****",
    rating: 5,
    date: "2025.09.16",
    variant: "화이트",
    content: "이사하면서 안방에 서랍장이 필요해서 구입했어요~ 디자인도 깔끔하고 서랍장도 깊어서 좋아요. 잘 사용하겠습니다.",
  },
];

export const sharedReviews: ReviewData = {
  ...calculateReviewSummary(reviewItems),
  items: reviewItems,
};

export const sharedQnaItems: QnaItem[] = [
  {
    id: "q-a01",
    category: "상품",
    question: "모노침대옆에 붙여둘껀데 벽고정해야되나요?",
    questioner: "ra*****",
    date: "2026.03.14",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 해당 제품은 벽고정 필수인 제품으로, 침대 프레임 혹은 다른 단품과 나란히 놓을 경우에도 벽고정은 필수적으로 시공이 필요합니다.",
    answerDate: "2026.03.16",
  },
  {
    id: "q-a02",
    category: "상품",
    question: "동일상품 2개 구입 설치할경우 벽고정 필수인가요?",
    questioner: "om*****",
    date: "2026.02.20",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 해당 제품은 2개 구매시에도 벽고정이 필수입니다. 1400 와이드 3단 서랍장의 경우 제품 자체의 하중으로 인해 전도위험이 없으므로, 벽고정이 없는 제품을 찾으실 경우 1400 와이드 3단 서랍장을 제안드립니다.",
    answerDate: "2026.02.20",
  },
  {
    id: "q-a03",
    category: "상품",
    question: "옷장이 무광화이트라고해서요. 바이엘채널옷장이랑 색감차이가 심할까요?",
    questioner: "ra*****",
    date: "2026.02.02",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 바이엘 옷장 & 모노 모두 화이트 계열이나, 바이엘 옷장은 깨끗한 화이트톤, 모노는 따뜻하고 아늑한 크림 화이트톤으로 색상이 상이합니다. 다만, 두 제품 다 화이트 계열로 색상이 다르더라도, 조화롭게 잘 매치될 것으로 예상됩니다.",
    answerDate: "2026.02.04",
  },
  {
    id: "q-a04",
    category: "배송",
    question: "안녕하세요 대만인데요 해외배송될까요?",
    questioner: "sa*****",
    date: "2026.01.05",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 해외 배송은 불가한 점 양해 바랍니다.",
    answerDate: "2026.01.05",
  },
  {
    id: "q-a05",
    category: "상품",
    question: "60킬로 정도의 어항을 올려놓아도 될까요?",
    questioner: "ec*****",
    date: "2025.11.23",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 서랍장 상품 권장 하중은 30kg 이내입니다.",
    answerDate: "2025.11.24",
  },
  {
    id: "q-a06",
    category: "상품",
    question: "반드시 벽고정이 필요한가요?",
    questioner: "ar*****",
    date: "2025.11.17",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 해당 상품은 벽고정이 필수이므로 하단 '구매 전 필수 확인사항!'을 참고 부탁드립니다.",
    answerDate: "2025.11.17",
  },
];
