import type { ReviewData, QnaItem, Review } from "@/app/lib/types";
import { calculateReviewSummary } from "@/lib/reviews";

const reviewItems: Review[] = [
  {
    id: "r-a01",
    userName: "ah*****",
    rating: 5,
    date: "2026.05.22",
    variant: "오트밀",
    content: "오트밀 컬러가 너무 예뻐요. 사진보다 실물이 훨씬 더 고급스럽습니다.",
    images: ["/images/reviews/1111100030/review-01-1.webp"],
  },
  {
    id: "r-a02",
    userName: "bi*****",
    rating: 5,
    date: "2026.05.08",
    variant: "오트밀",
    content: "210cm 거실장인데 압박감이 전혀 없어요. 가로로 넓어서 TV 배치에 딱 좋습니다.",
  },
  {
    id: "r-a03",
    userName: "cj*****",
    rating: 5,
    date: "2026.04.24",
    variant: "오트밀",
    content: "플리츠 패턴이 특이하면서도 고급스럽습니다. 거실 인테리어 완성도가 한층 올라갔어요.",
    images: ["/images/reviews/1111100030/review-03-1.webp"],
  },
  {
    id: "r-a04",
    userName: "dk*****",
    rating: 4,
    date: "2026.04.10",
    variant: "오트밀",
    content: "오트밀 색감이 어떤 인테리어에도 잘 어울려요. 다만 수납공간이 생각보다 깊지 않은 편입니다.",
  },
  {
    id: "r-a05",
    userName: "el*****",
    rating: 5,
    date: "2026.03.27",
    variant: "오트밀",
    content: "도어 패턴이 섬세하게 잘 만들어졌어요. 고급 인테리어 가구 같은 느낌입니다.",
  },
  {
    id: "r-a06",
    userName: "fm*****",
    rating: 5,
    date: "2026.03.13",
    variant: "오트밀",
    content: "가격이 있지만 그 이상의 퀄리티를 제공합니다. 거실 분위기가 완전히 달라졌어요.",
    images: ["/images/reviews/1111100030/review-06-1.webp"],
  },
  {
    id: "r-a07",
    userName: "gn*****",
    rating: 3,
    date: "2026.02.27",
    variant: "오트밀",
    content: "디자인은 마음에 드는데 설치 후 살짝 화학 냄새가 나서 며칠 환기했습니다. 시간이 지나니 괜찮아졌어요.",
  },
  {
    id: "r-a08",
    userName: "ho*****",
    rating: 5,
    date: "2026.02.13",
    variant: "오트밀",
    content: "넓은 거실에 210cm가 딱 맞아요. 비율이 아름답습니다.",
  },
  {
    id: "r-a09",
    userName: "ip*****",
    rating: 5,
    date: "2026.01.30",
    variant: "오트밀",
    content: "플리츠 도어가 빛 반사에 따라 달리 보여서 낮과 밤 분위기가 달라요. 너무 예뻐요.",
    images: ["/images/reviews/1111100030/review-09-1.webp"],
  },
  {
    id: "r-a10",
    userName: "jq*****",
    rating: 5,
    date: "2026.01.16",
    variant: "오트밀",
    content: "한샘 프리미엄 라인 처음 구매했는데 역시 다릅니다. 후회 없는 선택이에요.",
  },
  {
    id: "r-a11",
    userName: "kr*****",
    rating: 4,
    date: "2026.01.02",
    variant: "오트밀",
    content: "하단 수납공간이 넉넉하고 상단 오픈형 선반도 디스플레이 하기 좋아요. 다만 서랍 닫힘 소리가 조금 큰 편입니다.",
  },
  {
    id: "r-a12",
    userName: "ls*****",
    rating: 5,
    date: "2025.12.19",
    variant: "오트밀",
    content: "새해 맞이로 구매했는데 거실이 완전히 새로워졌어요. 추천합니다.",
  },
  {
    id: "r-a13",
    userName: "mt*****",
    rating: 5,
    date: "2025.12.05",
    variant: "오트밀",
    content: "마감 퀄리티 최고입니다. 실물로 보면 더 멋있어요.",
  },
  {
    id: "r-a14",
    userName: "nu*****",
    rating: 5,
    date: "2025.11.21",
    variant: "오트밀",
    content: "TV 크기에 맞춰 210cm 선택했는데 완벽한 비율이에요.",
  },
  {
    id: "r-a15",
    userName: "ov*****",
    rating: 5,
    date: "2025.11.07",
    variant: "오트밀",
    content: "은은한 오트밀 색이 조명 아래서 더 따뜻하게 보여요.",
  },
  {
    id: "r-a16",
    userName: "pw*****",
    rating: 5,
    date: "2025.10.24",
    variant: "오트밀",
    content: "고급 인테리어 가구 부럽지 않습니다. 한샘 거실장 최고예요.",
  },
  {
    id: "r-a17",
    userName: "qx*****",
    rating: 4,
    date: "2025.10.10",
    variant: "오트밀",
    content: "플리츠 패턴이 심플하면서도 특색 있어요. 다만 먼지가 패턴 사이에 잘 끼는 편이라 자주 닦아줘야 합니다.",
  },
  {
    id: "r-a18",
    userName: "ry*****",
    rating: 5,
    date: "2025.09.26",
    variant: "오트밀",
    content: "수납 도어 개폐가 부드럽고 소음이 없어요. 내구성도 좋아 보입니다.",
  },
  {
    id: "r-a19",
    userName: "sz*****",
    rating: 5,
    date: "2025.09.12",
    variant: "오트밀",
    content: "한번 보면 잊기 힘든 디자인이에요. 오래오래 쓸 것 같습니다.",
  },
  {
    id: "r-a20",
    userName: "ta*****",
    rating: 5,
    date: "2025.08.29",
    variant: "오트밀",
    content: "가족 모두 만족합니다. 설치팀도 친절하셨어요.",
  },
  {
    id: "r-a21",
    userName: "ub*****",
    rating: 3,
    date: "2025.08.15",
    variant: "오트밀",
    content: "디자인은 훌륭한데 배송 일정이 두 번 변경돼서 조금 불편했어요. 결과물 자체는 만족스럽습니다.",
  },
  {
    id: "r-a22",
    userName: "vc*****",
    rating: 5,
    date: "2025.08.01",
    variant: "오트밀",
    content: "깔끔한 마감, 넉넉한 수납. 완벽합니다.",
  },
  {
    id: "r-a23",
    userName: "wd*****",
    rating: 5,
    date: "2025.07.18",
    variant: "오트밀",
    content: "오트밀이 어떤 벽지 색과도 잘 어울려요. 범용성 최고입니다.",
  },
  {
    id: "r-a24",
    userName: "xe*****",
    rating: 4,
    date: "2025.07.04",
    variant: "오트밀",
    content: "전반적으로 만족합니다. 설치 시간이 두 시간 넘게 걸린 게 아쉽네요.",
  },
  {
    id: "r-a25",
    userName: "yf*****",
    rating: 4,
    date: "2025.06.20",
    variant: "오트밀",
    content: "디자인은 만족해요. 하단 도어 닫힘 소리가 생각보다 크네요.",
  },
  {
    id: "r-a26",
    userName: "zg*****",
    rating: 4,
    date: "2025.06.06",
    variant: "오트밀",
    content: "고급스러운 제품인데 배송 중 미세한 흠집이 있었어요. AS 접수는 했습니다.",
  },
  {
    id: "r-a27",
    userName: "ah*****",
    rating: 4,
    date: "2025.05.23",
    variant: "오트밀",
    content: "디자인 완벽합니다. 다만 상단 선반 높이 조절이 안 되는 게 아쉬워요.",
  },
  {
    id: "r-a28",
    userName: "bi*****",
    rating: 4,
    date: "2025.05.09",
    variant: "오트밀",
    content: "마감 좋고 공간 활용도 훌륭합니다. 설치 후 약간 냄새가 나서 하루 환기가 필요했어요.",
  },
  {
    id: "r-a29",
    userName: "cj*****",
    rating: 5,
    date: "2025.04.25",
    variant: "오트밀",
    content: "수납 용량이 정말 크네요. 리모컨, 게임기, 책 다 들어갑니다.",
  },
];

export const sharedReviews: ReviewData = {
  ...calculateReviewSummary(reviewItems),
  items: reviewItems,
};

export const sharedQnaItems: QnaItem[] = [
  {
    id: "q-a01",
    category: "상품",
    question: "뒷판도 마감 처리가 되어있나요?",
    questioner: "fm*****",
    date: "2026.06.24",
    answered: false,
  },
  {
    id: "q-a02",
    category: "상품",
    question: "플리츠 거실장 색상이 오트밀 하나뿐인가요? 다른 색상 출시 예정이 있나요?",
    questioner: "ah*****",
    date: "2026.04.20",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 현재 플리츠 거실장 210cm는 오트밀 단일 컬러로만 운영되고 있습니다. 추가 색상 출시 계획은 현재 확정된 사항이 없습니다. 더 많은 색상을 원하신다면 다른 거실장 라인을 참고해 주세요. 감사합니다.",
    answerDate: "2026.04.21",
  },
  {
    id: "q-a03",
    category: "상품",
    question: "내부 선반 위치 조절이 가능한가요?",
    questioner: "bi*****",
    date: "2026.03.18",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 네, 내부 선반 위치 조절이 가능합니다. 선반 높이는 32mm 단위로 조절할 수 있으며, 수납 물건의 높이에 따라 자유롭게 변경하실 수 있습니다. 감사합니다.",
    answerDate: "2026.03.19",
  },
  {
    id: "q-a04",
    category: "배송",
    question: "설치 완료까지 총 얼마나 걸리나요? 반나절 이상 비워야 하나요?",
    questioner: "cj*****",
    date: "2026.02.28",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 일반적인 거실 환경 기준 설치 소요 시간은 약 40~70분입니다. 기존 가구 이동이나 공간 상황에 따라 다소 차이가 있을 수 있습니다. 감사합니다.",
    answerDate: "2026.03.01",
  },
  {
    id: "q-a05",
    category: "상품",
    question: "도어 안쪽에 유리 도어 추가 옵션이 있나요?",
    questioner: "dk*****",
    date: "2026.01.25",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 플리츠 거실장은 현재 불투명 도어 구성으로만 제공됩니다. 유리 도어 옵션은 지원하지 않습니다. 감사합니다.",
    answerDate: "2026.01.26",
  },
  {
    id: "q-a06",
    category: "기타",
    question: "이 거실장을 전시해두는 쇼룸이 있을까요?",
    questioner: "el*****",
    date: "2026.01.08",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 전국 주요 한샘 플래그십 스토어 및 대리점에서 전시 제품을 확인하실 수 있습니다. 방문 전 가까운 매장에 재고 확인 후 방문하시길 권장드립니다. 감사합니다.",
    answerDate: "2026.01.09",
  },
];
