import type { ReviewData, QnaItem, Review } from "@/app/lib/types";
import { calculateReviewSummary } from "@/lib/reviews";

const reviewItems: Review[] = [
  // ── 허드 가죽 바체어 (단품) ──
  {
    id: "r-a01",
    userName: "hj*****",
    rating: 5,
    date: "2026.07.20",
    variant: "그레이",
    content: "홈바 스타일로 아일랜드 식탁을 꾸미고 싶어서 구매했는데 높이가 딱 맞아요. 그레이 컬러가 어떤 인테리어와도 잘 어울립니다.",
    images: ["/images/reviews/1211110010/review-01-1.webp"],
  },
  {
    id: "r-a02",
    userName: "sm*****",
    rating: 5,
    date: "2026.07.11",
    variant: "카멜",
    content: "카멜 컬러가 사진보다 훨씬 고급스러워요. 가죽 시트라 청소도 편합니다.",
  },
  {
    id: "r-a03",
    userName: "kt*****",
    rating: 5,
    date: "2026.07.02",
    variant: "그레이",
    content: "발받침이 있어서 오래 앉아도 다리가 편해요. 프레임도 튼튼합니다.",
    images: ["/images/reviews/1211110010/review-03-1.webp", "/images/reviews/1211110010/review-03-2.webp"],
  },
  {
    id: "r-a04",
    userName: "yn*****",
    rating: 5,
    date: "2026.06.23",
    variant: "카멜",
    content: "높이가 일반 식탁의자보다 높아서 홈바 느낌이 제대로 나요. 가격 대비 만족스럽습니다.",
  },
  {
    id: "r-a05",
    userName: "dw*****",
    rating: 3,
    date: "2026.06.14",
    variant: "그레이",
    content: "디자인은 마음에 드는데 배송이 예정보다 사흘 늦었어요. 조립 상태 자체는 괜찮습니다.",
  },
  {
    id: "r-a06",
    userName: "bg*****",
    rating: 5,
    date: "2026.06.05",
    variant: "카멜",
    content: "가죽 시트 촉감이 좋고 바느질도 꼼꼼해요. 카멜 컬러가 우드톤 가구랑 잘 어울립니다.",
    images: ["/images/reviews/1211110010/review-06-1.webp"],
  },
  {
    id: "r-a07",
    userName: "ej*****",
    rating: 5,
    date: "2026.05.27",
    variant: "그레이",
    content: "아일랜드 식탁 높이에 맞춰 구매했는데 딱 맞았어요. 스틸 프레임이라 흔들림도 없습니다.",
  },
  {
    id: "r-a08",
    userName: "ps*****",
    rating: 4,
    date: "2026.05.18",
    variant: "카멜",
    content: "전체적으로 만족하는데 시트 이음새 부분이 살짝 티가 나요. 사용에는 문제없습니다.",
  },
  {
    id: "r-a09",
    userName: "wc*****",
    rating: 5,
    date: "2026.05.09",
    variant: "그레이",
    content: "혼술 공간을 만들고 싶어서 구매했는데 분위기가 확 살아났어요. 가죽 재질도 고급스럽습니다.",
  },
  {
    id: "r-a10",
    userName: "mr*****",
    rating: 5,
    date: "2026.04.30",
    variant: "카멜",
    content: "조립이 간단해서 혼자서도 금방 끝냈어요. 완성도도 기대 이상입니다.",
  },
  {
    id: "r-a11",
    userName: "hb*****",
    rating: 5,
    date: "2026.04.21",
    variant: "그레이",
    content: "발받침 위치가 편안해서 오래 앉아도 무리가 없어요. 색상도 사진과 거의 동일합니다.",
    images: ["/images/reviews/1211110010/review-11-1.webp"],
  },
  {
    id: "r-a12",
    userName: "jy*****",
    rating: 5,
    date: "2026.04.12",
    variant: "카멜",
    content: "홈카페 느낌으로 꾸미고 싶었는데 딱 맞는 의자를 찾았어요. 만족스러운 구매입니다.",
  },
  {
    id: "r-a13",
    userName: "on*****",
    rating: 4,
    date: "2026.04.03",
    variant: "그레이",
    content: "가격 대비 좋은데 다리 고무캡 하나가 헐거웠어요. 직접 끼워서 지금은 괜찮습니다.",
  },
  {
    id: "r-a14",
    userName: "vs*****",
    rating: 5,
    date: "2026.03.25",
    variant: "카멜",
    content: "가죽 시트라 관리도 편하고 디자인도 세련됐어요. 다음에도 여기서 구매할 것 같습니다.",
  },
  // ── 1+1 허드 가죽 바체어 ──
  {
    id: "r-b01",
    userName: "qz*****",
    rating: 5,
    date: "2026.07.23",
    variant: "1+1 구성 / 그레이",
    content: "2개가 필요했는데 1+1이라 훨씬 저렴하게 구매했어요. 색상도 균일하게 와서 나란히 두니 세트 느낌이 잘 삽니다.",
    images: ["/images/reviews/1211110011/review-01-1.webp", "/images/reviews/1211110011/review-01-2.webp"],
  },
  {
    id: "r-b02",
    userName: "xr*****",
    rating: 5,
    date: "2026.07.14",
    variant: "1+1 구성 / 카멜",
    content: "아일랜드 식탁 양쪽에 하나씩 놓으려고 1+1로 주문했어요. 배송도 한 번에 와서 편했고 조립도 어렵지 않았습니다.",
  },
  {
    id: "r-b03",
    userName: "fn*****",
    rating: 4,
    date: "2026.07.05",
    variant: "1+1 구성 / 그레이",
    content: "가격 대비 두 개를 채울 수 있어서 만족스러워요. 다만 박스가 두 개라 개봉 정리하는 데 시간이 좀 걸렸습니다.",
    images: ["/images/reviews/1211110011/review-03-1.webp"],
  },
  {
    id: "r-b04",
    userName: "cw*****",
    rating: 5,
    date: "2026.06.26",
    variant: "1+1 구성 / 카멜",
    content: "홈바에 두 개를 나란히 놓으니 훨씬 완성도 있어 보여요. 가죽 시트 촉감도 좋고 카멜 컬러가 은은하게 고급스럽습니다.",
    images: ["/images/reviews/1211110011/review-04-1.webp"],
  },
  {
    id: "r-b05",
    userName: "tp*****",
    rating: 5,
    date: "2026.06.17",
    variant: "1+1 구성 / 그레이",
    content: "부모님댁 식탁에 놓으려고 두 개 필요했는데 1+1이라 부담 없이 구매했어요. 발받침 높이도 편안해서 만족합니다.",
  },
  {
    id: "r-b06",
    userName: "ny*****",
    rating: 5,
    date: "2026.06.08",
    variant: "1+1 구성 / 카멜",
    content: "친구랑 나눠서 하나씩 쓰려고 같이 주문했어요. 가죽 마감이 꼼꼼하고 무게감도 안정적입니다.",
  },
  {
    id: "r-b07",
    userName: "ig*****",
    rating: 3,
    date: "2026.05.30",
    variant: "1+1 구성 / 그레이",
    content: "구성 자체는 만족스러운데 두 박스 중 하나는 모서리가 살짝 눌려서 왔어요. 사용에는 지장 없어서 그냥 조립해서 쓰고 있습니다.",
  },
  {
    id: "r-b08",
    userName: "ru*****",
    rating: 4,
    date: "2026.05.21",
    variant: "1+1 구성 / 카멜",
    content: "카페 느낌 내려고 두 개를 나란히 뒀는데 분위기가 확 살아났어요. 시트 이음새가 하나는 살짝 티 나지만 크게 거슬리지 않습니다.",
  },
  {
    id: "r-b09",
    userName: "ae*****",
    rating: 5,
    date: "2026.05.12",
    variant: "1+1 구성 / 그레이",
    content: "혼자 조립했는데 두 개 다 15분 정도씩 걸려서 금방 끝났어요. 그레이 컬러라 어디에 둬도 무난하게 잘 어울립니다.",
    images: ["/images/reviews/1211110011/review-09-1.webp", "/images/reviews/1211110011/review-09-2.webp"],
  },
  {
    id: "r-b10",
    userName: "ok*****",
    rating: 5,
    date: "2026.05.03",
    variant: "1+1 구성 / 카멜",
    content: "홈바 두 자리를 한 번에 채우기 좋은 구성이에요. 가격도 합리적이고 마감도 기대 이상입니다.",
  },
];

export const sharedReviews: ReviewData = {
  ...calculateReviewSummary(reviewItems),
  items: reviewItems,
};

export const sharedQnaItems: QnaItem[] = [
  {
    id: "q-a01",
    category: "상품",
    question: "일반 식탁에도 사용할 수 있는 높이인가요?",
    questioner: "dg*****",
    date: "2026.06.20",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 시트 높이 약 65cm로 일반 식탁보다는 아일랜드·바 테이블(높이 90~110cm)에 적합합니다. 감사합니다.",
    answerDate: "2026.06.21",
  },
  {
    id: "q-a02",
    category: "배송",
    question: "조립 난이도가 어느 정도인가요?",
    questioner: "sk*****",
    date: "2026.06.02",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 다리와 발받침을 나사로 고정하는 간단한 조립으로 15분 내외 소요됩니다. 감사합니다.",
    answerDate: "2026.06.03",
  },
  {
    id: "q-a03",
    category: "상품",
    question: "천연가죽인가요?",
    questioner: "wm*****",
    date: "2026.05.10",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 관리가 편한 인조가죽(PU) 소재로 제작되었습니다. 감사합니다.",
    answerDate: "2026.05.11",
  },
  {
    id: "q-a04",
    category: "배송",
    question: "그레이, 카멜 각각 1개씩 따로 주문 가능한가요?",
    questioner: "hf*****",
    date: "2026.07.16",
    answered: false,
  },
];
