import type { ReviewData, QnaItem, Review } from "@/app/lib/types";
import { calculateReviewSummary } from "@/lib/reviews";

// 18 reviews: 15×5 + 3×4 = avg 4.833 → 4.8
const reviewItems: Review[] = [
  {
    id: "r-a01",
    userName: "bk*****",
    rating: 5,
    date: "2026.05.25",
    variant: "블랙",
    content: "소파 옆에 딱 어울립니다. 라운드 형태가 공간을 잘 활용하게 해줘요.",
    images: ["/images/reviews/1111120010/review-01-1.webp"],
  },
  {
    id: "r-a02",
    userName: "wh*****",
    rating: 5,
    date: "2026.05.05",
    variant: "화이트",
    content: "가격 대비 품질이 정말 좋습니다. 화이트 색상이 밝고 깔끔해요.",
    images: ["/images/reviews/1111120010/review-02-1.webp"],
  },
  {
    id: "r-a03",
    userName: "gy*****",
    rating: 5,
    date: "2026.04.14",
    variant: "그레이",
    content: "그레이 색상 예쁩니다. 조립이 간단하고 안정적이에요.",
  },
  {
    id: "r-a04",
    userName: "bj*****",
    rating: 5,
    date: "2026.03.22",
    variant: "베이지",
    content: "베이지 색상이 인테리어에 잘 녹아듭니다. 아담한 크기가 딱 좋아요.",
    images: ["/images/reviews/1111120010/review-04-1.webp"],
  },
  {
    id: "r-a05",
    userName: "tc*****",
    rating: 5,
    date: "2026.02.10",
    variant: "블랙",
    content: "튼튼하고 마감이 깔끔합니다. 가격이 저렴한데도 품질이 좋아요.",
  },
  {
    id: "r-a06",
    userName: "nw*****",
    rating: 5,
    date: "2026.01.18",
    variant: "화이트",
    content: "화분 받침대용으로 쓰고 있어요. 라운드 형태라 부딪혀도 안전하고 예쁘네요.",
    images: ["/images/reviews/1111120010/review-06-1.webp"],
  },
  {
    id: "r-a07",
    userName: "rl*****",
    rating: 5,
    date: "2025.12.28",
    variant: "그레이",
    content: "심플하고 예쁩니다. 조립도 10분도 안 걸렸어요.",
  },
  {
    id: "r-a08",
    userName: "fk*****",
    rating: 5,
    date: "2025.12.09",
    variant: "블랙",
    content: "블랙 색상이 공간에 포인트가 됩니다. 품질도 가격보다 훨씬 좋아요.",
  },
  {
    id: "r-a09",
    userName: "dp*****",
    rating: 5,
    date: "2025.11.21",
    variant: "베이지",
    content: "색감이 사진과 동일합니다. 가벼워서 이동도 편합니다.",
  },
  {
    id: "r-a10",
    userName: "qm*****",
    rating: 5,
    date: "2025.10.30",
    variant: "화이트",
    content: "재구매 합니다. 다른 공간에도 하나 더 두려고요.",
  },
  {
    id: "r-a11",
    userName: "es*****",
    rating: 5,
    date: "2025.09.17",
    variant: "그레이",
    content: "모던한 디자인이 마음에 듭니다.",
  },
  {
    id: "r-a12",
    userName: "vn*****",
    rating: 5,
    date: "2025.08.26",
    variant: "블랙",
    content: "이 가격에 이 퀄리티면 대만족입니다.",
  },
  {
    id: "r-a13",
    userName: "ua*****",
    rating: 5,
    date: "2025.07.14",
    variant: "화이트",
    content: "깔끔하고 예뻐요. 배송도 빠르고 좋았습니다.",
  },
  {
    id: "r-a14",
    userName: "zw*****",
    rating: 5,
    date: "2025.06.03",
    variant: "베이지",
    content: "작고 예뻐서 여러 공간에 활용하기 좋아요.",
  },
  {
    id: "r-a15",
    userName: "xo*****",
    rating: 5,
    date: "2025.05.11",
    variant: "그레이",
    content: "흔들림 없이 안정적입니다. 오래 쓸 것 같아요.",
  },
  {
    id: "r-a16",
    userName: "pb*****",
    rating: 4,
    date: "2025.11.05",
    variant: "블랙",
    content: "가격 대비 괜찮습니다. 상판이 좀 더 두꺼웠으면 좋겠어요.",
  },
  {
    id: "r-a17",
    userName: "oc*****",
    rating: 4,
    date: "2025.08.13",
    variant: "화이트",
    content: "조립은 쉬운데 나사가 조금 뻑뻑했습니다. 품질은 만족해요.",
  },
  {
    id: "r-a18",
    userName: "ij*****",
    rating: 4,
    date: "2025.04.22",
    variant: "그레이",
    content: "전반적으로 만족스럽습니다. 색상이 사진보다 약간 밝은 느낌이에요.",
  },
];

export const sharedReviews: ReviewData = {
  ...calculateReviewSummary(reviewItems),
  items: reviewItems,
};

export const sharedQnaItems: QnaItem[] = [
  {
    id: "q-a01",
    category: "상품",
    question: "다리 높이 조절이 가능한가요?",
    questioner: "pb*****",
    date: "2025.10.18",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 재크 400 라운드 사이드테이블은 높이 조절 기능이 없는 고정형 제품입니다. 제품 높이는 약 45cm로, 일반 소파 옆 사이드테이블로 사용하기에 적합한 높이로 설계되었습니다. 감사합니다.",
    answerDate: "2025.10.19",
  },
];
