// 패밀리 코드(상품코드 앞 9자리) → 이미지 폴더명 매핑.
// 새 패밀리 추가 시 아래 import 한 줄 + FAMILY_REGISTRY 항목 한 줄씩만 추가.
import { FAMILY_CODE as MONO_BED_CODE, FAMILY_PATH as MONO_BED_PATH } from "./bedroom/bed/101012001";
import { FAMILY_CODE as LUNESOFT_BED_CODE, FAMILY_PATH as LUNESOFT_BED_PATH } from "./bedroom/bed/101012002";
import { FAMILY_CODE as STEADY_COMPY_CODE, FAMILY_PATH as STEADY_COMPY_PATH } from "./bedroom/bed/101014001";
import { FAMILY_CODE as BALANCE_S_EUROTOP_CODE, FAMILY_PATH as BALANCE_S_EUROTOP_PATH } from "./bedroom/mattress/101111001";
import { FAMILY_CODE as STAY_TOPPER_CODE, FAMILY_PATH as STAY_TOPPER_PATH } from "./bedroom/mattress/101112001";
import { FAMILY_CODE as COMFORT_BASE_CODE, FAMILY_PATH as COMFORT_BASE_PATH } from "./bedroom/mattress/101112002";
import { FAMILY_CODE as FOSEASON_BASE_CODE, FAMILY_PATH as FOSEASON_BASE_PATH } from "./bedroom/mattress/101112003";
import { FAMILY_CODE as MONO_DRESSER_CODE, FAMILY_PATH as MONO_DRESSER_PATH } from "./bedroom/dresser/101210001";
import { FAMILY_CODE as MONO_CHEST_CODE, FAMILY_PATH as MONO_CHEST_PATH } from "./bedroom/dresser/101210002";
import { FAMILY_CODE as EURO_NIGHTSTAND_CODE, FAMILY_PATH as EURO_NIGHTSTAND_PATH } from "./bedroom/dresser/101212001";
import { FAMILY_CODE as MOA_SOFA_CODE, FAMILY_PATH as MOA_SOFA_PATH } from "./livingroom/sofa/111012001";
import { FAMILY_CODE as RIDO_SOFA_CODE, FAMILY_PATH as RIDO_SOFA_PATH } from "./livingroom/sofa/111010001";
import { FAMILY_CODE as MVME_RECLINER_CODE, FAMILY_PATH as MVME_RECLINER_PATH } from "./livingroom/sofa/111011001";
import { FAMILY_CODE as HYU_MODE_CODE, FAMILY_PATH as HYU_MODE_PATH } from "./livingroom/sofa/111013001";
import { FAMILY_CODE as HYU_LOUNGE_CODE, FAMILY_PATH as HYU_LOUNGE_PATH } from "./livingroom/sofa/111013002";
import { FAMILY_CODE as LAGONE_CODE, FAMILY_PATH as LAGONE_PATH } from "./livingroom/table/111111001";
import { FAMILY_CODE as PRINGLE_CODE, FAMILY_PATH as PRINGLE_PATH } from "./livingroom/table/111111002";
import { FAMILY_CODE as CLINT_LIFTUP_CODE, FAMILY_PATH as CLINT_LIFTUP_PATH } from "./livingroom/table/111111003";
import { FAMILY_CODE as JACK_ROUND_CODE, FAMILY_PATH as JACK_ROUND_PATH } from "./livingroom/table/111112001";
import { FAMILY_CODE as CLINT_HEIGHT_CODE, FAMILY_PATH as CLINT_HEIGHT_PATH } from "./livingroom/table/111112002";
import { FAMILY_CODE as CLINT_URBAN_CAB_CODE, FAMILY_PATH as CLINT_URBAN_CAB_PATH } from "./livingroom/cabinet/111110001";
import { FAMILY_CODE as CLINT_MODERN_CAB_CODE, FAMILY_PATH as CLINT_MODERN_CAB_PATH } from "./livingroom/cabinet/111110002";
import { FAMILY_CODE as PLEATS_CAB_CODE, FAMILY_PATH as PLEATS_CAB_PATH } from "./livingroom/cabinet/111110003";
import { FAMILY_CODE as MILAN_AV_CAB_CODE, FAMILY_PATH as MILAN_AV_CAB_PATH } from "./livingroom/cabinet/111110004";
import { FAMILY_CODE as DONO_EDGE_CODE, FAMILY_PATH as DONO_EDGE_PATH } from "./dining/table/121013001";
import { FAMILY_CODE as FORE_COMFORT_CODE, FAMILY_PATH as FORE_COMFORT_PATH } from "./dining/table/121012001";
import { FAMILY_CODE as MINA_NATURAL_OVAL_TABLE_CODE, FAMILY_PATH as MINA_NATURAL_OVAL_TABLE_PATH } from "./dining/table/121014001";
import { FAMILY_CODE as MINA_STEEL_SQUARE_TABLE_CODE, FAMILY_PATH as MINA_STEEL_SQUARE_TABLE_PATH } from "./dining/table/121010001";
import { FAMILY_CODE as DONO_SLIM_DINING_CHAIR_CODE, FAMILY_PATH as DONO_SLIM_DINING_CHAIR_PATH } from "./dining/chair/121110001";
import { FAMILY_CODE as MINA_ROUND_DINING_CHAIR_CODE, FAMILY_PATH as MINA_ROUND_DINING_CHAIR_PATH } from "./dining/chair/121110002";
import { FAMILY_CODE as WID_ROUND_DINING_CHAIR_CODE, FAMILY_PATH as WID_ROUND_DINING_CHAIR_PATH } from "./dining/chair/121110003";
import { FAMILY_CODE as HEARD_LEATHER_BAR_CHAIR_CODE, FAMILY_PATH as HEARD_LEATHER_BAR_CHAIR_PATH } from "./dining/chair/121111001";
import { FAMILY_CODE as EURO_501_FLAT_BAR_CHAIR_CODE, FAMILY_PATH as EURO_501_FLAT_BAR_CHAIR_PATH } from "./dining/chair/121111002";
import { FAMILY_CODE as LIBUP_BENCH_CODE, FAMILY_PATH as LIBUP_BENCH_PATH } from "./dining/chair/121112001";
import { FAMILY_CODE as BLANC_CHAIR_STOOL_CODE, FAMILY_PATH as BLANC_CHAIR_STOOL_PATH } from "./dining/chair/121112002";
import { FAMILY_CODE as MODI_PANTRY_CABINET_CODE, FAMILY_PATH as MODI_PANTRY_CABINET_PATH } from "./dining/kitchen-storage/121210001";
import { FAMILY_CODE as MODI_CAFE_CABINET_SERIES_CODE, FAMILY_PATH as MODI_CAFE_CABINET_SERIES_PATH } from "./dining/kitchen-storage/121210002";
import { FAMILY_CODE as MODI_RANGE_STAND_SERIES_CODE, FAMILY_PATH as MODI_RANGE_STAND_SERIES_PATH } from "./dining/kitchen-storage/121210003";
import { FAMILY_CODE as SOFT_COOLING_SET_CODE, FAMILY_PATH as SOFT_COOLING_SET_PATH } from "./home-deco/bedding/171012001";
import { FAMILY_CODE as MODAL_ALLERGY_SET_CODE, FAMILY_PATH as MODAL_ALLERGY_SET_PATH } from "./home-deco/bedding/171012002";
import { FAMILY_CODE as FOSEASON_TENCEL_SET_CODE, FAMILY_PATH as FOSEASON_TENCEL_SET_PATH } from "./home-deco/bedding/171012003";
import { FAMILY_CODE as POLAND_GOOSE_CODE, FAMILY_PATH as POLAND_GOOSE_PATH } from "./home-deco/bedding/171010001";
import { FAMILY_CODE as BALANCE_GOOSE_PILLOW_CODE, FAMILY_PATH as BALANCE_GOOSE_PILLOW_PATH } from "./home-deco/bedding/171011001";
import { FAMILY_CODE as SLEEPDIVER_PILLOW_CODE, FAMILY_PATH as SLEEPDIVER_PILLOW_PATH } from "./home-deco/bedding/171011002";
import { FAMILY_CODE as SOK_SLIDING_BOX_CODE, FAMILY_PATH as SOK_SLIDING_BOX_PATH } from "./home-deco/kitchen-organizer/171110001";
import { FAMILY_CODE as ALLSTEN_DISH_RACK_CODE, FAMILY_PATH as ALLSTEN_DISH_RACK_PATH } from "./home-deco/kitchen-organizer/171112001";
import { FAMILY_CODE as PRIME_KNIFE_RACK_CODE, FAMILY_PATH as PRIME_KNIFE_RACK_PATH } from "./home-deco/kitchen-organizer/171112002";
import { FAMILY_CODE as WINDOW_PACKAGE_CODE, FAMILY_PATH as WINDOW_PACKAGE_PATH } from "./home-deco/curtain-blind/171210001";
import { FAMILY_CODE as COZY_CURTAIN_CODE, FAMILY_PATH as COZY_CURTAIN_PATH } from "./home-deco/curtain-blind/171210002";
import { FAMILY_CODE as RELAX_BLACKOUT_CODE, FAMILY_PATH as RELAX_BLACKOUT_PATH } from "./home-deco/curtain-blind/171210003";
import { FAMILY_CODE as SHINY_LUNA_BLIND_CODE, FAMILY_PATH as SHINY_LUNA_BLIND_PATH } from "./home-deco/curtain-blind/171211001";
import { FAMILY_CODE as DOUBLE_ROLLSCREEN_CODE, FAMILY_PATH as DOUBLE_ROLLSCREEN_PATH } from "./home-deco/curtain-blind/171211002";
import { FAMILY_CODE as NEW_KLIMT_LAMP_CODE, FAMILY_PATH as NEW_KLIMT_LAMP_PATH } from "./home-deco/deco/171310001";
import { FAMILY_CODE as OLIVIA_LAMP_CODE, FAMILY_PATH as OLIVIA_LAMP_PATH } from "./home-deco/deco/171310002";
import { FAMILY_CODE as JOY_FLOOR_LAMP_CODE, FAMILY_PATH as JOY_FLOOR_LAMP_PATH } from "./home-deco/deco/171310003";
import { FAMILY_CODE as EMMA_SLUB_RUG_CODE, FAMILY_PATH as EMMA_SLUB_RUG_PATH } from "./home-deco/deco/171311001";
import { FAMILY_CODE as SAMKIDS_ROUND_RUG_CODE, FAMILY_PATH as SAMKIDS_ROUND_RUG_PATH } from "./home-deco/deco/171311002";
import { FAMILY_CODE as PRIME_TUFTING_RUG_CODE, FAMILY_PATH as PRIME_TUFTING_RUG_PATH } from "./home-deco/deco/171311003";
import { FAMILY_CODE as SOK_STEEL_CONTAINER_CODE, FAMILY_PATH as SOK_STEEL_CONTAINER_PATH } from "./home-deco/kitchen-organizer/171111001";
import { FAMILY_CODE as CLEAR_FOOD_CONTAINER_CODE, FAMILY_PATH as CLEAR_FOOD_CONTAINER_PATH } from "./home-deco/kitchen-organizer/171111002";
import { FAMILY_CODE as CLEAR_GLASS_RICE_CONTAINER_CODE, FAMILY_PATH as CLEAR_GLASS_RICE_CONTAINER_PATH } from "./home-deco/kitchen-organizer/171111003";
import { FAMILY_CODE as MOON_JAR_DIFFUSER_CODE, FAMILY_PATH as MOON_JAR_DIFFUSER_PATH } from "./home-deco/deco/171312001";
import { FAMILY_CODE as FOSEASON_DIFFUSER_CODE, FAMILY_PATH as FOSEASON_DIFFUSER_PATH } from "./home-deco/deco/171312002";
import { FAMILY_CODE as LEATHER_TISSUE_COVER_CODE, FAMILY_PATH as LEATHER_TISSUE_COVER_PATH } from "./home-deco/deco/171312003";
import { FAMILY_CODE as FELT_TISSUE_CASE_CODE, FAMILY_PATH as FELT_TISSUE_CASE_PATH } from "./home-deco/deco/171312004";
import { FAMILY_CODE as TARPAULIN_SHOPPING_BAG_CODE, FAMILY_PATH as TARPAULIN_SHOPPING_BAG_PATH } from "./home-deco/deco/171312005";

export const FAMILY_REGISTRY: Record<string, string> = {
  [MONO_BED_CODE]: MONO_BED_PATH,
  [LUNESOFT_BED_CODE]: LUNESOFT_BED_PATH,
  [STEADY_COMPY_CODE]: STEADY_COMPY_PATH,
  [BALANCE_S_EUROTOP_CODE]: BALANCE_S_EUROTOP_PATH,
  [STAY_TOPPER_CODE]: STAY_TOPPER_PATH,
  [COMFORT_BASE_CODE]: COMFORT_BASE_PATH,
  [FOSEASON_BASE_CODE]: FOSEASON_BASE_PATH,
  [MONO_DRESSER_CODE]: MONO_DRESSER_PATH,
  [MONO_CHEST_CODE]: MONO_CHEST_PATH,
  [EURO_NIGHTSTAND_CODE]: EURO_NIGHTSTAND_PATH,
  [MOA_SOFA_CODE]: MOA_SOFA_PATH,
  [RIDO_SOFA_CODE]: RIDO_SOFA_PATH,
  [MVME_RECLINER_CODE]: MVME_RECLINER_PATH,
  [HYU_MODE_CODE]: HYU_MODE_PATH,
  [HYU_LOUNGE_CODE]: HYU_LOUNGE_PATH,
  [LAGONE_CODE]: LAGONE_PATH,
  [PRINGLE_CODE]: PRINGLE_PATH,
  [CLINT_LIFTUP_CODE]: CLINT_LIFTUP_PATH,
  [JACK_ROUND_CODE]: JACK_ROUND_PATH,
  [CLINT_HEIGHT_CODE]: CLINT_HEIGHT_PATH,
  [CLINT_URBAN_CAB_CODE]: CLINT_URBAN_CAB_PATH,
  [CLINT_MODERN_CAB_CODE]: CLINT_MODERN_CAB_PATH,
  [PLEATS_CAB_CODE]: PLEATS_CAB_PATH,
  [MILAN_AV_CAB_CODE]: MILAN_AV_CAB_PATH,
  [DONO_EDGE_CODE]: DONO_EDGE_PATH,
  [FORE_COMFORT_CODE]: FORE_COMFORT_PATH,
  [MINA_NATURAL_OVAL_TABLE_CODE]: MINA_NATURAL_OVAL_TABLE_PATH,
  [MINA_STEEL_SQUARE_TABLE_CODE]: MINA_STEEL_SQUARE_TABLE_PATH,
  [DONO_SLIM_DINING_CHAIR_CODE]: DONO_SLIM_DINING_CHAIR_PATH,
  [MINA_ROUND_DINING_CHAIR_CODE]: MINA_ROUND_DINING_CHAIR_PATH,
  [WID_ROUND_DINING_CHAIR_CODE]: WID_ROUND_DINING_CHAIR_PATH,
  [HEARD_LEATHER_BAR_CHAIR_CODE]: HEARD_LEATHER_BAR_CHAIR_PATH,
  [EURO_501_FLAT_BAR_CHAIR_CODE]: EURO_501_FLAT_BAR_CHAIR_PATH,
  [LIBUP_BENCH_CODE]: LIBUP_BENCH_PATH,
  [BLANC_CHAIR_STOOL_CODE]: BLANC_CHAIR_STOOL_PATH,
  [MODI_PANTRY_CABINET_CODE]: MODI_PANTRY_CABINET_PATH,
  [MODI_CAFE_CABINET_SERIES_CODE]: MODI_CAFE_CABINET_SERIES_PATH,
  [MODI_RANGE_STAND_SERIES_CODE]: MODI_RANGE_STAND_SERIES_PATH,
  [SOFT_COOLING_SET_CODE]: SOFT_COOLING_SET_PATH,
  [MODAL_ALLERGY_SET_CODE]: MODAL_ALLERGY_SET_PATH,
  [FOSEASON_TENCEL_SET_CODE]: FOSEASON_TENCEL_SET_PATH,
  [POLAND_GOOSE_CODE]: POLAND_GOOSE_PATH,
  [BALANCE_GOOSE_PILLOW_CODE]: BALANCE_GOOSE_PILLOW_PATH,
  [SLEEPDIVER_PILLOW_CODE]: SLEEPDIVER_PILLOW_PATH,
  [SOK_SLIDING_BOX_CODE]: SOK_SLIDING_BOX_PATH,
  [ALLSTEN_DISH_RACK_CODE]: ALLSTEN_DISH_RACK_PATH,
  [PRIME_KNIFE_RACK_CODE]: PRIME_KNIFE_RACK_PATH,
  [WINDOW_PACKAGE_CODE]: WINDOW_PACKAGE_PATH,
  [COZY_CURTAIN_CODE]: COZY_CURTAIN_PATH,
  [RELAX_BLACKOUT_CODE]: RELAX_BLACKOUT_PATH,
  [SHINY_LUNA_BLIND_CODE]: SHINY_LUNA_BLIND_PATH,
  [DOUBLE_ROLLSCREEN_CODE]: DOUBLE_ROLLSCREEN_PATH,
  [NEW_KLIMT_LAMP_CODE]: NEW_KLIMT_LAMP_PATH,
  [OLIVIA_LAMP_CODE]: OLIVIA_LAMP_PATH,
  [JOY_FLOOR_LAMP_CODE]: JOY_FLOOR_LAMP_PATH,
  [EMMA_SLUB_RUG_CODE]: EMMA_SLUB_RUG_PATH,
  [SAMKIDS_ROUND_RUG_CODE]: SAMKIDS_ROUND_RUG_PATH,
  [PRIME_TUFTING_RUG_CODE]: PRIME_TUFTING_RUG_PATH,
  [SOK_STEEL_CONTAINER_CODE]: SOK_STEEL_CONTAINER_PATH,
  [CLEAR_FOOD_CONTAINER_CODE]: CLEAR_FOOD_CONTAINER_PATH,
  [CLEAR_GLASS_RICE_CONTAINER_CODE]: CLEAR_GLASS_RICE_CONTAINER_PATH,
  [MOON_JAR_DIFFUSER_CODE]: MOON_JAR_DIFFUSER_PATH,
  [FOSEASON_DIFFUSER_CODE]: FOSEASON_DIFFUSER_PATH,
  [LEATHER_TISSUE_COVER_CODE]: LEATHER_TISSUE_COVER_PATH,
  [FELT_TISSUE_CASE_CODE]: FELT_TISSUE_CASE_PATH,
  [TARPAULIN_SHOPPING_BAG_CODE]: TARPAULIN_SHOPPING_BAG_PATH,
};

export function getFamilyFolder(productId: string): string {
  const familyCode = productId.slice(0, 9);
  const folder = FAMILY_REGISTRY[familyCode];
  if (!folder) throw new Error(`No family folder registered for: ${productId}`);
  return folder;
}
