// 패밀리 코드(상품코드 앞 9자리) → 이미지 폴더명 매핑.
// 새 패밀리 추가 시 아래 import 한 줄 + FAMILY_REGISTRY 항목 한 줄씩만 추가.
import { FAMILY_CODE as MONO_BED_CODE, FAMILY_PATH as MONO_BED_PATH } from "./bedroom/bed/101012001";
import { FAMILY_CODE as LUNESOFT_BED_CODE, FAMILY_PATH as LUNESOFT_BED_PATH } from "./bedroom/bed/101012002";
import { FAMILY_CODE as STEADY_COMPY_CODE, FAMILY_PATH as STEADY_COMPY_PATH } from "./bedroom/bed/101014001";
import { FAMILY_CODE as BALANCE_S_EUROTOP_CODE, FAMILY_PATH as BALANCE_S_EUROTOP_PATH } from "./bedroom/mattress/101111001";
import { FAMILY_CODE as STAY_TOPPER_CODE, FAMILY_PATH as STAY_TOPPER_PATH } from "./bedroom/mattress/101112001";
import { FAMILY_CODE as COMFORT_BASE_CODE, FAMILY_PATH as COMFORT_BASE_PATH } from "./bedroom/mattress/101112002";
import { FAMILY_CODE as FOSEASON_BASE_CODE, FAMILY_PATH as FOSEASON_BASE_PATH } from "./bedroom/mattress/101112003";
import { FAMILY_CODE as MONO_DRESSER_CODE, FAMILY_PATH as MONO_DRESSER_PATH } from "./bedroom/dresser/101210001";
import { FAMILY_CODE as MONO_CHEST_CODE, FAMILY_PATH as MONO_CHEST_PATH } from "./bedroom/dresser/101210002";
import { FAMILY_CODE as EURO_NIGHTSTAND_CODE, FAMILY_PATH as EURO_NIGHTSTAND_PATH } from "./bedroom/dresser/101212001";
import { FAMILY_CODE as MOA_SOFA_CODE, FAMILY_PATH as MOA_SOFA_PATH } from "./livingroom/sofa/111012001";
import { FAMILY_CODE as RIDO_SOFA_CODE, FAMILY_PATH as RIDO_SOFA_PATH } from "./livingroom/sofa/111010001";
import { FAMILY_CODE as MVME_RECLINER_CODE, FAMILY_PATH as MVME_RECLINER_PATH } from "./livingroom/sofa/111011001";
import { FAMILY_CODE as HYU_MODE_CODE, FAMILY_PATH as HYU_MODE_PATH } from "./livingroom/sofa/111013001";
import { FAMILY_CODE as HYU_LOUNGE_CODE, FAMILY_PATH as HYU_LOUNGE_PATH } from "./livingroom/sofa/111013002";
import { FAMILY_CODE as LAGONE_CODE, FAMILY_PATH as LAGONE_PATH } from "./livingroom/table/111111001";
import { FAMILY_CODE as PRINGLE_CODE, FAMILY_PATH as PRINGLE_PATH } from "./livingroom/table/111111002";
import { FAMILY_CODE as CLINT_LIFTUP_CODE, FAMILY_PATH as CLINT_LIFTUP_PATH } from "./livingroom/table/111111003";
import { FAMILY_CODE as JACK_ROUND_CODE, FAMILY_PATH as JACK_ROUND_PATH } from "./livingroom/table/111112001";
import { FAMILY_CODE as CLINT_HEIGHT_CODE, FAMILY_PATH as CLINT_HEIGHT_PATH } from "./livingroom/table/111112002";
import { FAMILY_CODE as CLINT_URBAN_CAB_CODE, FAMILY_PATH as CLINT_URBAN_CAB_PATH } from "./livingroom/cabinet/111110001";
import { FAMILY_CODE as CLINT_MODERN_CAB_CODE, FAMILY_PATH as CLINT_MODERN_CAB_PATH } from "./livingroom/cabinet/111110002";
import { FAMILY_CODE as PLEATS_CAB_CODE, FAMILY_PATH as PLEATS_CAB_PATH } from "./livingroom/cabinet/111110003";
import { FAMILY_CODE as MILAN_AV_CAB_CODE, FAMILY_PATH as MILAN_AV_CAB_PATH } from "./livingroom/cabinet/111110004";
import { FAMILY_CODE as DONO_EDGE_CODE, FAMILY_PATH as DONO_EDGE_PATH } from "./dining/table/121013001";
import { FAMILY_CODE as FORE_COMFORT_CODE, FAMILY_PATH as FORE_COMFORT_PATH } from "./dining/table/121012001";
import { FAMILY_CODE as MINA_NATURAL_OVAL_TABLE_CODE, FAMILY_PATH as MINA_NATURAL_OVAL_TABLE_PATH } from "./dining/table/121014001";
import { FAMILY_CODE as MINA_STEEL_SQUARE_TABLE_CODE, FAMILY_PATH as MINA_STEEL_SQUARE_TABLE_PATH } from "./dining/table/121010001";
import { FAMILY_CODE as DONO_SLIM_DINING_CHAIR_CODE, FAMILY_PATH as DONO_SLIM_DINING_CHAIR_PATH } from "./dining/chair/121110001";
import { FAMILY_CODE as MINA_ROUND_DINING_CHAIR_CODE, FAMILY_PATH as MINA_ROUND_DINING_CHAIR_PATH } from "./dining/chair/121110002";
import { FAMILY_CODE as WID_ROUND_DINING_CHAIR_CODE, FAMILY_PATH as WID_ROUND_DINING_CHAIR_PATH } from "./dining/chair/121110003";
import { FAMILY_CODE as HEARD_LEATHER_BAR_CHAIR_CODE, FAMILY_PATH as HEARD_LEATHER_BAR_CHAIR_PATH } from "./dining/chair/121111001";
import { FAMILY_CODE as EURO_501_FLAT_BAR_CHAIR_CODE, FAMILY_PATH as EURO_501_FLAT_BAR_CHAIR_PATH } from "./dining/chair/121111002";
import { FAMILY_CODE as LIBUP_BENCH_CODE, FAMILY_PATH as LIBUP_BENCH_PATH } from "./dining/chair/121112001";
import { FAMILY_CODE as BLANC_CHAIR_STOOL_CODE, FAMILY_PATH as BLANC_CHAIR_STOOL_PATH } from "./dining/chair/121112002";
import { FAMILY_CODE as MODI_PANTRY_CABINET_CODE, FAMILY_PATH as MODI_PANTRY_CABINET_PATH } from "./dining/kitchen-storage/121210001";
import { FAMILY_CODE as MODI_CAFE_CABINET_SERIES_CODE, FAMILY_PATH as MODI_CAFE_CABINET_SERIES_PATH } from "./dining/kitchen-storage/121210002";
import { FAMILY_CODE as MODI_RANGE_STAND_SERIES_CODE, FAMILY_PATH as MODI_RANGE_STAND_SERIES_PATH } from "./dining/kitchen-storage/121210003";

export const FAMILY_REGISTRY: Record<string, string> = {
  [MONO_BED_CODE]: MONO_BED_PATH,
  [LUNESOFT_BED_CODE]: LUNESOFT_BED_PATH,
  [STEADY_COMPY_CODE]: STEADY_COMPY_PATH,
  [BALANCE_S_EUROTOP_CODE]: BALANCE_S_EUROTOP_PATH,
  [STAY_TOPPER_CODE]: STAY_TOPPER_PATH,
  [COMFORT_BASE_CODE]: COMFORT_BASE_PATH,
  [FOSEASON_BASE_CODE]: FOSEASON_BASE_PATH,
  [MONO_DRESSER_CODE]: MONO_DRESSER_PATH,
  [MONO_CHEST_CODE]: MONO_CHEST_PATH,
  [EURO_NIGHTSTAND_CODE]: EURO_NIGHTSTAND_PATH,
  [MOA_SOFA_CODE]: MOA_SOFA_PATH,
  [RIDO_SOFA_CODE]: RIDO_SOFA_PATH,
  [MVME_RECLINER_CODE]: MVME_RECLINER_PATH,
  [HYU_MODE_CODE]: HYU_MODE_PATH,
  [HYU_LOUNGE_CODE]: HYU_LOUNGE_PATH,
  [LAGONE_CODE]: LAGONE_PATH,
  [PRINGLE_CODE]: PRINGLE_PATH,
  [CLINT_LIFTUP_CODE]: CLINT_LIFTUP_PATH,
  [JACK_ROUND_CODE]: JACK_ROUND_PATH,
  [CLINT_HEIGHT_CODE]: CLINT_HEIGHT_PATH,
  [CLINT_URBAN_CAB_CODE]: CLINT_URBAN_CAB_PATH,
  [CLINT_MODERN_CAB_CODE]: CLINT_MODERN_CAB_PATH,
  [PLEATS_CAB_CODE]: PLEATS_CAB_PATH,
  [MILAN_AV_CAB_CODE]: MILAN_AV_CAB_PATH,
  [DONO_EDGE_CODE]: DONO_EDGE_PATH,
  [FORE_COMFORT_CODE]: FORE_COMFORT_PATH,
  [MINA_NATURAL_OVAL_TABLE_CODE]: MINA_NATURAL_OVAL_TABLE_PATH,
  [MINA_STEEL_SQUARE_TABLE_CODE]: MINA_STEEL_SQUARE_TABLE_PATH,
  [DONO_SLIM_DINING_CHAIR_CODE]: DONO_SLIM_DINING_CHAIR_PATH,
  [MINA_ROUND_DINING_CHAIR_CODE]: MINA_ROUND_DINING_CHAIR_PATH,
  [WID_ROUND_DINING_CHAIR_CODE]: WID_ROUND_DINING_CHAIR_PATH,
  [HEARD_LEATHER_BAR_CHAIR_CODE]: HEARD_LEATHER_BAR_CHAIR_PATH,
  [EURO_501_FLAT_BAR_CHAIR_CODE]: EURO_501_FLAT_BAR_CHAIR_PATH,
  [LIBUP_BENCH_CODE]: LIBUP_BENCH_PATH,
  [BLANC_CHAIR_STOOL_CODE]: BLANC_CHAIR_STOOL_PATH,
  [MODI_PANTRY_CABINET_CODE]: MODI_PANTRY_CABINET_PATH,
  [MODI_CAFE_CABINET_SERIES_CODE]: MODI_CAFE_CABINET_SERIES_PATH,
  [MODI_RANGE_STAND_SERIES_CODE]: MODI_RANGE_STAND_SERIES_PATH,
};

export function getFamilyFolder(productId: string): string {
  const familyCode = productId.slice(0, 9);
  const folder = FAMILY_REGISTRY[familyCode];
  if (!folder) throw new Error(`No family folder registered for: ${productId}`);
  return folder;
}
