import {
  ProductFamily,
  ProductSummary,
  ProductDetail,
  FilterAttributes,
  ProductDetailSection,
  DeliveryGuideGroup,
  ReviewData,
  QnaItem,
  Review,
} from "../../types";
import { calculateReviewSummary } from "../../../../lib/reviews";

export const FAMILY_FOLDER = "bed-mono-bed";
export const FAMILY_CODE = "101012001";


const deliveryGuides: DeliveryGuideGroup[] = [
  {
    title: "배송 안내",
    rows: [
      { label: "배송방법", value: "직배송 (한샘 전문 배송팀 설치 포함)" },
      { label: "배송기간", value: "주문 후 3~4주 내 순차 배송 (사전판매 상품)" },
      { label: "배송비", value: "구매금액 50,000원 이상 무료 / 미만 시 3,000원" },
      { label: "배송지역", value: "전국 배송 (단, 제주도 및 도서산간 지역 배송 불가)" },
      { label: "배송 안내", value: "배송 3~5일 전 배송팀에서 사전 연락 후 방문합니다. 설치 완료 후 포장재를 수거 및 처리해 드립니다." },
    ],
  },
  {
    title: "설치 서비스 안내",
    rows: [
      { label: "설치 서비스", value: "포함 (전문 설치팀 방문 설치)" },
      { label: "설치 소요시간", value: "약 60~90분" },
      { label: "주의사항", value: "설치 장소까지의 운반 경로(계단·복도·문틈) 확인이 필요합니다. 엘리베이터 미설치 건물은 사전 고객센터 문의를 요청드립니다." },
    ],
  },
  {
    title: "반품 / 교환 안내",
    rows: [
      { label: "반품·교환 기간", value: "상품 수령 후 7일 이내" },
      { label: "반품·교환 비용", value: "단순 변심 반품 시 왕복 배송비 고객 부담 / 제품 하자 시 무료 처리" },
      { label: "반품 불가 조건", value: "설치 완료 후 / 상품 사용·훼손·오염된 경우 / 포장 훼손으로 상품 가치 감소된 경우" },
      { label: "A/S", value: "한샘 고객센터 1688-4945 / 제품 하자 발생 시 1년 내 무상 A/S" },
    ],
  },
];

export const monoBedFamily: Omit<ProductFamily, "familyId"> = {
  breadcrumb: ["침실", "침대", "호텔침대"],
  promotions: [
    { title: "6월 쌤위크", image: "/images/promotions/saemweek-2026-06.webp" },
    { title: "침실이벤트 리뷰", image: "/images/promotions/bedroom-event-review.webp" },
  ],
  deliveryInfo: {
    method: "사전판매 (결제 후 순차 배송)",
    region: "전국 (제주/도서 지역 추가 배송비 발생)",
  },
  deliveryGuides,
  // 패밀리 공유 갤러리 이미지 — 전용 폴더에서 관리 (특정 SKU에 종속되지 않음)
  sharedImages: [
    `/images/products/${FAMILY_FOLDER}/${FAMILY_FOLDER}-shared-01.webp`,
    `/images/products/${FAMILY_FOLDER}/${FAMILY_FOLDER}-shared-02.webp`,
    `/images/products/${FAMILY_FOLDER}/${FAMILY_FOLDER}-shared-03.webp`,
    `/images/products/${FAMILY_FOLDER}/${FAMILY_FOLDER}-shared-04.webp`,
    `/images/products/${FAMILY_FOLDER}/${FAMILY_FOLDER}-shared-05.webp`,
    `/images/products/${FAMILY_FOLDER}/${FAMILY_FOLDER}-shared-06.webp`,
    `/images/products/${FAMILY_FOLDER}/${FAMILY_FOLDER}-shared-07.webp`,
    `/images/products/${FAMILY_FOLDER}/${FAMILY_FOLDER}-shared-08.webp`,
    `/images/products/${FAMILY_FOLDER}/${FAMILY_FOLDER}-shared-09.webp`,
    `/images/products/${FAMILY_FOLDER}/${FAMILY_FOLDER}-shared-10.webp`,
  ],
};

// ─── Shared sections (only basic.title / basic.body differs per variant) ─────
export function createSections(basic: { title: string; body: string }): ProductDetailSection[] {
  return [
    {
      id: "basic",
      label: "기본정보",
      blocks: [
        { type: "text", title: basic.title, body: basic.body },
        { type: "video", src: `/images/products/${FAMILY_FOLDER}/${FAMILY_FOLDER}-basic-01.mp4`, alt: "모노 침대 기본정보 비디오" },
        { type: "image", src: `/images/products/${FAMILY_FOLDER}/${FAMILY_FOLDER}-basic-02.webp`, alt: "모노 침대 기본정보" },
        {
          type: "text",
          title: "모노톤 컬러감에 어울리는 미니멀한 디자인",
          body: "주거공간에도 어울리는 모노톤에 낮고 와이드한 비례미가 더해져 미니멀한 침실룩을 연출합니다.",
        },
        { type: "image", src: `/images/products/${FAMILY_FOLDER}/${FAMILY_FOLDER}-basic-03.webp`, alt: "모노 침대 기본정보 이미지" },
      ],
    },
    {
      id: "function",
      label: "기능",
      blocks: [
        { type: "image", src: `/images/products/${FAMILY_FOLDER}/${FAMILY_FOLDER}-function-01.gif`, alt: "무드조명" },
        {
          type: "text",
          title: "아늑한 공간을 위한 헤드의 무드 조명",
          body: "침대 헤드 위 길게 위치한 바 형태의 무드등은 풍부한 간접조명 효과로 아늑한 분위기의 침실을 연출할 수 있습니다.",
        },
        { type: "image", src: `/images/products/${FAMILY_FOLDER}/${FAMILY_FOLDER}-function-02.webp`, alt: "기능설명" },
        { type: "image", src: `/images/products/${FAMILY_FOLDER}/${FAMILY_FOLDER}-function-03.webp`, alt: "기능설명" },
      ],
    },
    {
      id: "material",
      label: "소재",
      blocks: [
        { type: "video", src: `/images/products/${FAMILY_FOLDER}/${FAMILY_FOLDER}-material-01.mp4`, alt: "모노 침대 소재 정보 비디오" },
        {
          type: "text",
          title: "내구성이 강한 LPM 소재",
          body: "LPM 소재로 내구성이 강하고 표면이 매끈하여 관리에 용이하고, 엠보처리로 손자국을 최소화했습니다.",
        },
      ],
    },
    {
      id: "size",
      label: "사이즈",
      blocks: [
        { type: "image", src: `/images/products/${FAMILY_FOLDER}/${FAMILY_FOLDER}-size-01.webp`, alt: "사이즈 안내 이미지" },
      ],
    },
    {
      id: "warranty",
      label: "품질보증",
      blocks: [
        { type: "video", src: `/images/products/${FAMILY_FOLDER}/${FAMILY_FOLDER}-warranty-01.mp4`, alt: "품질보증 비디오" },
        {
          type: "text",
          title: "안심하고 사용하는 한샘 침대",
          body: "EO 등급의 안전한 자재와 KC 인증받은 전자기기 부품으로 유해물질, 전자파 걱정 없이 사용할 수 있습니다.",
        },
      ],
    },
  ];
}

// ─── Catalog summaries (single source of truth for all mono-bed SKUs) ────────
export const summaries: ProductSummary[] = [
  {
    id: "1010120010",
    familyId: "mono-bed",
    name: "호텔침대 모노침대 Q/K (색상2종, 하부서랍 선택)",
    variantLabel: "Q/K 단품",
    thumbnail: `/images/products/${FAMILY_FOLDER}/1010120010/1010120010-main-01.webp`,
    brand: "한샘",
    price: 588870,
    originalPrice: 727000,
    discountRate: 19,
    rating: 4.7,
    reviewCount: 12,
    category: ["침실", "침대", "호텔침대"],
  },
  {
    id: "1010120011",
    familyId: "mono-bed",
    name: "호텔침대 모노침대 KK (색상2종, 하부서랍 선택)",
    variantLabel: "KK 단품",
    thumbnail: `/images/products/${FAMILY_FOLDER}/1010120011/1010120011-main-01.webp`,
    brand: "한샘",
    price: 660150,
    originalPrice: 815000,
    discountRate: 19,
    rating: 4.7,
    reviewCount: 15,
    category: ["침실", "침대", "호텔침대"],
  },
  {
    id: "1010120012",
    familyId: "mono-bed",
    name: "호텔침대 모노침대 Q/K (색상2종, 하부서랍 선택) + 밸런스 볼륨탑 매트리스",
    variantLabel: "Q/K + 밸런스매트리스",
    thumbnail: `/images/products/${FAMILY_FOLDER}/1010120012/1010120012-main-01.webp`,
    brand: "한샘",
    price: 1008040,
    originalPrice: 1270000,
    discountRate: 21,
    rating: 4.8,
    reviewCount: 28,
    badge: { text: "호텔침대 판매 2위", bgColor: "#FE5A5D" },
    category: ["침실", "침대", "호텔침대"],
  },
  {
    id: "1010120013",
    familyId: "mono-bed",
    name: "호텔침대 모노침대 KK (색상2종, 하부서랍 선택) + 밸런스 볼륨탑 매트리스",
    variantLabel: "KK + 밸런스매트리스",
    thumbnail: `/images/products/${FAMILY_FOLDER}/1010120013/1010120013-main-01.webp`,
    brand: "한샘",
    price: 1280840,
    originalPrice: 1804000,
    discountRate: 29,
    rating: 4.9,
    reviewCount: 40,
    badge: { text: "호텔침대 판매 3위", bgColor: "#FE5A5D" },
    category: ["침실", "침대", "호텔침대"],
  },
];

// ─── Variant-specific detail data ────────────────────────────────────────────
type VariantData = {
  variantImages: string[];
  filterAttributes: FilterAttributes;
  sections: ProductDetailSection[];
};

const variantDetails: Record<string, VariantData> = {
  "1010120010": {
    variantImages: [],
    filterAttributes: { size: ["Q/K"], config: ["침대"], feature: ["조명리모컨형"] },
    sections: createSections({
      title: "모노 침대 Q/K 단품",
      body: "감각적인 모노톤 컬러에 낮고 와이드한 비례미, 패널까지 이어지는 풍부한 헤드 조명으로 미니멀하면서 트렌디한 호텔 침실을 완성합니다. 퀸·킹 사이즈 모두 지원하며, 보유하신 매트리스와 함께 사용 가능합니다.",
    }),
  },
  "1010120011": {
    variantImages: [],
    filterAttributes: { size: ["KK"], config: ["침대"], feature: ["조명리모컨형"] },
    sections: createSections({
      title: "모노 침대 KK 단품",
      body: "감각적인 모노톤 컬러에 낮고 와이드한 비례미, 패널까지 이어지는 풍부한 헤드 조명으로 미니멀하면서 트렌디한 호텔 침실을 완성합니다. 매트리스는 별도 구매하시거나 기존 보유 매트리스와 함께 사용 가능합니다.",
    }),
  },
  "1010120012": {
    variantImages: [
      `/images/products/${FAMILY_FOLDER}/1010120012/1010120012-variant-01.webp`,
      `/images/products/${FAMILY_FOLDER}/1010120012/1010120012-variant-02.webp`,
    ],
    filterAttributes: { size: ["Q/K"], config: ["침대+매트"], feature: ["조명리모컨형"] },
    sections: createSections({
      title: "모노 침대 Q/K + 밸런스 매트리스",
      body: "감각적인 모노톤 컬러에 낮고 와이드한 비례미, 패널까지 이어지는 풍부한 헤드 조명으로 미니멀하면서 트렌디한 호텔 침실을 완성합니다.",
    }),
  },
  "1010120013": {
    variantImages: [
      `/images/products/${FAMILY_FOLDER}/1010120013/1010120013-variant-01.webp`,
      `/images/products/${FAMILY_FOLDER}/1010120013/1010120013-variant-02.webp`,
      `/images/products/${FAMILY_FOLDER}/1010120013/1010120013-variant-03.webp`,
    ],
    filterAttributes: { size: ["KK"], config: ["침대+매트"], feature: ["조명리모컨형"] },
    sections: createSections({
      title: "모노 침대 KK + 밸런스 매트리스",
      body: "감각적인 모노톤 컬러에 낮고 와이드한 비례미, 패널까지 이어지는 풍부한 헤드 조명으로 미니멀하면서 트렌디한 호텔 침실을 완성합니다.",
    }),
  },
};

// ─── Shared reviews (all mono-bed variants) ───────────────────────────────────
const reviewItems: Review[] = [
  // ── KK + 밸런스매트리스 ──
  {
    id: "r-a01",
    userName: "홍*희",
    rating: 5,
    date: "2026.04.12",
    variant: "KK + 밸런스매트리스",
    content: "배송 전에 미리 연락 주셔서 설치 시간을 잘 조율했어요. 설치 기사분들이 깔끔하게 설치해주시고 포장재 정리까지 해주셨습니다. 무드등이 생각보다 훨씬 예쁘고 분위기가 있어요. 침실 전체 분위기가 바뀐 것 같아서 너무 만족스럽습니다. 매트리스도 딱 좋은 탄성감으로 허리 부담 없이 편하게 자고 있어요.",
    images: ["/images/reviews/1010120013/review-01-1.webp", "/images/reviews/1010120013/review-01-2.webp"],
  },
  {
    id: "r-a02",
    userName: "김*수",
    rating: 5,
    date: "2026.03.28",
    variant: "KK + 밸런스매트리스",
    content: "디자인이 정말 고급스럽고 모노톤 컬러가 인테리어에 잘 어울려요. LPM 소재라 지문이 잘 안 묻고 관리도 간편합니다. 사전판매라 좀 오래 기다렸지만 결과물이 기대 이상이에요.",
  },
  {
    id: "r-a03",
    userName: "이*진",
    rating: 5,
    date: "2026.03.15",
    variant: "KK + 밸런스매트리스",
    content: "헤드보드 무드등이 정말 예쁘고 은은해요. 밤에 방 불 끄고 무드등만 켜놓으면 호텔 느낌 물씬 납니다. 매트리스 볼륨탑이 포근해서 허리도 편하고 잘 자고 있어요.",
    images: ["/images/reviews/1010120013/review-03-1.webp"],
  },
  {
    id: "r-a04",
    userName: "박*현",
    rating: 4,
    date: "2026.02.20",
    variant: "KK + 밸런스매트리스",
    content: "제품 자체는 정말 만족스러운데 배송이 예정일보다 약 2주 늦어져서 별 하나를 빼요. 배송 오고 나서 설치는 신속하고 친절하게 해주셨습니다.",
  },
  {
    id: "r-a05",
    userName: "최*은",
    rating: 5,
    date: "2026.02.05",
    variant: "KK + 밸런스매트리스",
    content: "평소에 가구 사면 항상 조금씩 아쉬웠는데 이번엔 진짜 100% 만족해요. 색상은 다크그레이 선택했는데 사진보다 실물이 훨씬 세련되어 보입니다. 매트리스도 볼륨탑이라 포근하고 잘 푹 자요.",
    images: [
      "/images/reviews/1010120013/review-05-1.webp",
      "/images/reviews/1010120013/review-05-2.webp",
    ],
  },
  {
    id: "r-a06",
    userName: "이*혜",
    rating: 5,
    date: "2026.06.10",
    variant: "KK + 밸런스매트리스",
    content: "KK 사이즈인데 배송팀이 정말 꼼꼼하게 설치해주셨어요. 방이 호텔처럼 변한 것 같아서 너무 만족합니다.",
  },
  {
    id: "r-a07",
    userName: "박*준",
    rating: 5,
    date: "2026.06.07",
    variant: "KK + 밸런스매트리스",
    content: "무드등이 정말 예쁘고 LPM 소재라 관리가 편해요. 매트리스도 딱 적당한 탄성이에요.",
    images: ["/images/reviews/1010120013/review-07-1.webp"],
  },
  {
    id: "r-a08",
    userName: "최*민",
    rating: 4,
    date: "2026.06.02",
    variant: "KK + 밸런스매트리스",
    content: "제품 퀄리티는 정말 좋은데 배송 기간이 예상보다 길었어요. 받고 나니 만족합니다.",
  },
  {
    id: "r-a09",
    userName: "강*영",
    rating: 5,
    date: "2026.05.28",
    variant: "KK + 밸런스매트리스",
    content: "헤드보드 디자인이 감각적이에요. 와이드한 비율이 공간을 넓어 보이게 해줘서 좋아요.",
    images: ["/images/reviews/1010120013/review-09-1.webp"],
  },
  {
    id: "r-a10",
    userName: "정*아",
    rating: 5,
    date: "2026.05.22",
    variant: "KK + 밸런스매트리스",
    content: "신혼집에 들였는데 손님들마다 어디서 샀냐고 물어봐요. 그만큼 디자인이 예쁩니다.",
  },
  {
    id: "r-a11",
    userName: "손*우",
    rating: 3,
    date: "2026.05.16",
    variant: "KK + 밸런스매트리스",
    content: "제품 자체는 나쁘지 않은데 저한테는 매트리스 경도가 조금 딱딱하게 느껴졌어요. 취향 차이인 것 같아요.",
  },
  {
    id: "r-a12",
    userName: "안*진",
    rating: 5,
    date: "2026.05.12",
    variant: "KK + 밸런스매트리스",
    content: "이사하면서 같이 구매했는데 새 집 분위기에 딱 어울려요. 색상은 다크그레이 선택했고 너무 마음에 들어요.",
    images: ["/images/reviews/1010120013/review-12-1.webp"],
  },
  {
    id: "r-a13",
    userName: "홍*수",
    rating: 5,
    date: "2026.05.08",
    variant: "KK + 밸런스매트리스",
    content: "사전판매라 기다렸는데 도착하고 나니 기다린 보람이 있었어요. 설치 기사분이 꼼꼼하게 해주셨습니다.",
  },
  {
    id: "r-a14",
    userName: "오*현",
    rating: 5,
    date: "2026.05.04",
    variant: "KK + 밸런스매트리스",
    content: "하부서랍이 넓어서 이불 수납이 정말 편해요. 침대 세팅 완성되니 침실이 완전히 달라졌어요.",
    images: ["/images/reviews/1010120013/review-14-1.webp", "/images/reviews/1010120013/review-14-2.webp"],
  },
  {
    id: "r-a15",
    userName: "윤*결",
    rating: 5,
    date: "2026.04.30",
    variant: "KK + 밸런스매트리스",
    content: "사전판매라 좀 기다렸는데 받고 나니 기다린 보람이 있어요. 매트리스 탄성이 딱 좋아서 허리가 편해요.",
  },
  {
    id: "r-a16",
    userName: "나*솔",
    rating: 5,
    date: "2026.04.25",
    variant: "KK + 밸런스매트리스",
    content: "베이지 색상인데 실물이 사진보다 훨씬 예쁘고 따뜻한 느낌이에요. 방이 환해진 것 같아요.",
    images: ["/images/reviews/1010120013/review-16-1.webp"],
  },
  {
    id: "r-a17",
    userName: "임*후",
    rating: 5,
    date: "2026.04.20",
    variant: "KK + 밸런스매트리스",
    content: "KK 사이즈 넓어서 좋아요. 매트리스까지 같이 사니 따로 고민할 필요 없어서 편했어요.",
  },
  {
    id: "r-a18",
    userName: "서*연",
    rating: 5,
    date: "2026.04.15",
    variant: "KK + 밸런스매트리스",
    content: "설치 당일부터 바로 잘 수 있었어요. 매트리스 볼륨탑이 포근해서 아침에 일어나기 싫을 정도예요.",
    images: ["/images/reviews/1010120013/review-18-1.webp", "/images/reviews/1010120013/review-18-2.webp"],
  },
  {
    id: "r-a19",
    userName: "배*희",
    rating: 5,
    date: "2026.04.10",
    variant: "KK + 밸런스매트리스",
    content: "한샘 제품 처음 샀는데 역시 신뢰가 가는 브랜드예요. 마감이 꼼꼼하고 디자인도 고급스럽습니다.",
  },
  {
    id: "r-a20",
    userName: "황*준",
    rating: 5,
    date: "2026.04.06",
    variant: "KK + 밸런스매트리스",
    content: "헤드보드 터치로 간편하게 무드등을 켜고 끌 수 있어서 좋아요. 밤마다 분위기가 완전 달라져요.",
    images: ["/images/reviews/1010120013/review-20-1.webp"],
  },
  // ── Q/K + 밸런스매트리스 ──
  {
    id: "r-b01",
    userName: "송*연",
    rating: 5,
    date: "2026.04.18",
    variant: "Q/K + 밸런스매트리스",
    content: "Q/K 사이즈 선택했는데 퀸 사이즈 매트리스가 딱 맞게 들어왔어요. 무드등이 생각보다 훨씬 분위기 있고 LPM 소재라 청소도 정말 편합니다. 세트 구매라 가격 대비 만족도가 높아요.",
    images: ["/images/reviews/1010120012/review-01-1.webp", "/images/reviews/1010120012/review-01-2.webp"],
  },
  {
    id: "r-b02",
    userName: "류*현",
    rating: 5,
    date: "2026.04.02",
    variant: "Q/K + 밸런스매트리스",
    content: "신혼집에 들여놓을 침대를 고민하다가 한샘 모노 침대로 결정했어요. 매트리스까지 함께 구매했는데 볼륨탑 특유의 포근함이 마음에 듭니다. 색상은 베이지 선택했는데 방 분위기가 따뜻해졌어요.",
  },
  {
    id: "r-b03",
    userName: "장*민",
    rating: 5,
    date: "2026.03.22",
    variant: "Q/K + 밸런스매트리스",
    content: "배송 설치까지 정말 꼼꼼하게 해주셨어요. 헤드 무드등이 은은해서 좋고, 하부서랍도 생각보다 수납이 넓어요. 전반적으로 완성도가 높은 제품입니다.",
    images: ["/images/reviews/1010120012/review-03-1.webp"],
  },
  {
    id: "r-b04",
    userName: "윤*서",
    rating: 4,
    date: "2026.03.05",
    variant: "Q/K + 밸런스매트리스",
    content: "제품은 정말 예쁜데 사전판매라 배송까지 기다리는 시간이 좀 길었어요. 그래도 받고 나니 기대 이상이라 만족합니다. 매트리스 탄성이 딱 제 취향이에요.",
  },
  {
    id: "r-b05",
    userName: "오*진",
    rating: 5,
    date: "2026.02.18",
    variant: "Q/K + 밸런스매트리스",
    content: "방이 호텔처럼 변했어요. 낮은 헤드보드 디자인이 공간을 넓어 보이게 해주고 무드등이 정말 분위기를 살려줘요. 매트리스도 너무 딱딱하거나 너무 푹신하지 않아서 좋습니다.",
    images: ["/images/reviews/1010120012/review-05-1.webp", "/images/reviews/1010120012/review-05-2.webp"],
  },
  {
    id: "r-b06",
    userName: "정*현",
    rating: 5,
    date: "2026.06.08",
    variant: "Q/K + 밸런스매트리스",
    content: "퀸 사이즈 선택했는데 방 크기에 딱 맞아요. 매트리스까지 세트라 구매하기도 편했어요.",
  },
  {
    id: "r-b07",
    userName: "강*호",
    rating: 5,
    date: "2026.06.04",
    variant: "Q/K + 밸런스매트리스",
    content: "LPM 소재 마감이 너무 깔끔해요. 먼지나 지문이 잘 묻지 않아서 관리가 정말 편합니다.",
    images: ["/images/reviews/1010120012/review-07-1.webp"],
  },
  {
    id: "r-b08",
    userName: "이*민",
    rating: 5,
    date: "2026.05.29",
    variant: "Q/K + 밸런스매트리스",
    content: "킹 사이즈로 선택했는데 넓어서 좋아요. 헤드 무드등 켜놓으면 분위기가 완전 달라집니다.",
  },
  {
    id: "r-b09",
    userName: "박*영",
    rating: 4,
    date: "2026.05.24",
    variant: "Q/K + 밸런스매트리스",
    content: "제품 만족도는 높은데 사전판매 대기가 길었던 게 조금 아쉬웠어요. 받고 나선 만족합니다.",
  },
  {
    id: "r-b10",
    userName: "최*선",
    rating: 5,
    date: "2026.05.19",
    variant: "Q/K + 밸런스매트리스",
    content: "볼륨탑 매트리스가 생각보다 훨씬 포근해요. 딱딱하지도 않고 적당한 탄성이 허리에도 좋아요.",
    images: ["/images/reviews/1010120012/review-10-1.webp", "/images/reviews/1010120012/review-10-2.webp"],
  },
  {
    id: "r-b11",
    userName: "조*환",
    rating: 5,
    date: "2026.05.15",
    variant: "Q/K + 밸런스매트리스",
    content: "낮은 헤드보드 덕분에 방이 넓어 보이는 효과가 있어요. 미니멀한 인테리어와도 잘 어울립니다.",
  },
  {
    id: "r-b12",
    userName: "신*혁",
    rating: 3,
    date: "2026.05.10",
    variant: "Q/K + 밸런스매트리스",
    content: "디자인은 마음에 드는데 배송 과정에서 소통이 잘 안 됐어요. 설치 후 만족도는 나쁘지 않아요.",
  },
  {
    id: "r-b13",
    userName: "권*영",
    rating: 5,
    date: "2026.05.05",
    variant: "Q/K + 밸런스매트리스",
    content: "혼수용으로 구매했어요. 처음 가구 들어오는 날 설치 완료되니 신혼집이 완성된 느낌이에요.",
    images: ["/images/reviews/1010120012/review-13-1.webp"],
  },
  {
    id: "r-b14",
    userName: "한*은",
    rating: 5,
    date: "2026.04.30",
    variant: "Q/K + 밸런스매트리스",
    content: "다크그레이 컬러가 실물이 사진보다 훨씬 세련돼요. 인테리어 신경 쓰시는 분들께 추천드려요.",
  },
  {
    id: "r-b15",
    userName: "류*성",
    rating: 5,
    date: "2026.04.24",
    variant: "Q/K + 밸런스매트리스",
    content: "매트리스 포함 세트라 처음엔 비싸다 싶었는데 퀄리티 생각하면 납득이 돼요.",
    images: ["/images/reviews/1010120012/review-15-1.webp"],
  },
  {
    id: "r-b16",
    userName: "임*지",
    rating: 5,
    date: "2026.04.18",
    variant: "Q/K + 밸런스매트리스",
    content: "하부서랍 옵션 선택했는데 이불 두 세트는 거뜬히 들어가요. 수납공간이 넉넉해서 좋아요.",
  },
  {
    id: "r-b17",
    userName: "오*은",
    rating: 5,
    date: "2026.04.13",
    variant: "Q/K + 밸런스매트리스",
    content: "설치팀이 방 구조에 맞게 배치까지 도와주셔서 감사했어요. 완성된 모습이 정말 만족스러워요.",
    images: ["/images/reviews/1010120012/review-17-1.webp", "/images/reviews/1010120012/review-17-2.webp"],
  },
  {
    id: "r-b18",
    userName: "황*린",
    rating: 5,
    date: "2026.04.08",
    variant: "Q/K + 밸런스매트리스",
    content: "킹 사이즈 선택하길 잘했어요. 넓게 자도 매트리스 탄성이 유지돼서 잠자리가 쾌적합니다.",
  },
  {
    id: "r-b19",
    userName: "배*현",
    rating: 5,
    date: "2026.04.03",
    variant: "Q/K + 밸런스매트리스",
    content: "베이지 색상인데 흠집이 잘 안 나는 것 같아요. 세살짜리 아이가 있는데도 표면이 멀쩡해요.",
  },
  {
    id: "r-b20",
    userName: "석*민",
    rating: 5,
    date: "2026.03.28",
    variant: "Q/K + 밸런스매트리스",
    content: "무드등 불빛이 은은해서 취침 전 분위기 내기 딱 좋아요. 확실히 호텔 느낌이에요.",
  },
  // ── KK 단품 ──
  {
    id: "r-c01",
    userName: "남*준",
    rating: 5,
    date: "2026.04.25",
    variant: "KK 단품",
    content: "기존에 쓰던 매트리스가 아직 괜찮아서 침대 프레임만 교체했어요. 단품이라 가격 부담이 덜한데 디자인은 전혀 밀리지 않아요. 무드등이 너무 예쁘고 설치도 깔끔하게 해주셨습니다.",
    images: ["/images/reviews/1010120011/review-01-1.webp", "/images/reviews/1010120011/review-01-2.webp"],
  },
  {
    id: "r-c02",
    userName: "임*영",
    rating: 5,
    date: "2026.04.10",
    variant: "KK 단품",
    content: "침대 프레임 단품인데도 완성도가 정말 높아요. LPM 마감이 고급스럽고 헤드보드 조명이 방 분위기를 완전히 바꿔줬습니다. 하부서랍도 넓어서 이불이나 옷 수납하기 딱 좋아요.",
  },
  {
    id: "r-c03",
    userName: "한*솔",
    rating: 5,
    date: "2026.03.30",
    variant: "KK 단품",
    content: "색상은 다크그레이 선택했는데 실물이 훨씬 세련되어 보여요. 단품 구매라도 퀄리티가 전혀 뒤처지지 않아서 만족합니다.",
    images: ["/images/reviews/1010120011/review-03-1.webp"],
  },
  {
    id: "r-c04",
    userName: "서*현",
    rating: 4,
    date: "2026.03.10",
    variant: "KK 단품",
    content: "배송 대기가 길었지만 제품 자체는 만족해요. 설치 기사분이 꼼꼼하게 해주셨고 포장재도 가져가주셨습니다. 별 하나는 대기 기간 때문에 빼요.",
  },
  {
    id: "r-c05",
    userName: "권*아",
    rating: 5,
    date: "2026.02.28",
    variant: "KK 단품",
    content: "매트리스 따로, 프레임 따로 구매했는데 딱 맞게 잘 어울립니다. 프레임 완성도가 높아서 호텔 침실처럼 꾸밀 수 있었어요. 추천합니다.",
    images: ["/images/reviews/1010120011/review-05-1.webp"],
  },
  {
    id: "r-c06",
    userName: "윤*석",
    rating: 5,
    date: "2026.06.09",
    variant: "KK 단품",
    content: "기존에 쓰던 매트리스와 함께 써도 딱 맞아요. 프레임 단품인데도 완성도가 높습니다.",
  },
  {
    id: "r-c07",
    userName: "강*하",
    rating: 5,
    date: "2026.06.05",
    variant: "KK 단품",
    content: "베이지 컬러가 원목 협탁과 잘 어울려요. 공간 인테리어 전체 퀄리티가 올라간 느낌이에요.",
    images: ["/images/reviews/1010120011/review-07-1.webp", "/images/reviews/1010120011/review-07-2.webp"],
  },
  {
    id: "r-c08",
    userName: "차*영",
    rating: 5,
    date: "2026.05.31",
    variant: "KK 단품",
    content: "KK 사이즈라 넓어서 쾌적하게 잘 수 있어요. 프레임 자체 완성도가 높아서 만족해요.",
  },
  {
    id: "r-c09",
    userName: "이*수",
    rating: 4,
    date: "2026.05.26",
    variant: "KK 단품",
    content: "배송 담당자가 날짜를 두 번이나 변경해서 불편했지만 제품 자체는 기대 이상이에요.",
  },
  {
    id: "r-c10",
    userName: "김*현",
    rating: 5,
    date: "2026.05.21",
    variant: "KK 단품",
    content: "단품이라 가격이 합리적이고 디자인도 고급스러워요. 매트리스 따로 골라서 쓰고 싶은 분께 추천해요.",
    images: ["/images/reviews/1010120011/review-10-1.webp"],
  },
  {
    id: "r-c11",
    userName: "전*준",
    rating: 5,
    date: "2026.05.17",
    variant: "KK 단품",
    content: "무드등이 터치 방식이라 리모컨 없이도 편하게 쓸 수 있어요. 헤드보드 터치 위치도 찾기 쉽고요.",
  },
  {
    id: "r-c12",
    userName: "홍*진",
    rating: 3,
    date: "2026.05.13",
    variant: "KK 단품",
    content: "다크그레이 색상인데 밝은 조명 아래에서 보면 기대보다 조금 어두운 느낌이에요. 취향 타는 색상인 것 같아요.",
  },
  {
    id: "r-c13",
    userName: "박*서",
    rating: 5,
    date: "2026.05.08",
    variant: "KK 단품",
    content: "혼자 침실 꾸미는 분들한테 적극 추천해요. 설치도 빠르고 마감도 깔끔합니다.",
  },
  {
    id: "r-c14",
    userName: "유*빈",
    rating: 5,
    date: "2026.05.03",
    variant: "KK 단품",
    content: "오래 쓰던 침대 교체하고 새로 샀는데 공간이 훨씬 세련돼졌어요. 잘 산 것 같아요.",
  },
  {
    id: "r-c15",
    userName: "최*오",
    rating: 5,
    date: "2026.04.29",
    variant: "KK 단품",
    content: "하부서랍 옵션 선택했어요. 서랍이 2개라 계절 이불 정리에 너무 좋고 수납이 넉넉해요.",
    images: ["/images/reviews/1010120011/review-15-1.webp", "/images/reviews/1010120011/review-15-2.webp"],
  },
  {
    id: "r-c16",
    userName: "안*미",
    rating: 5,
    date: "2026.04.24",
    variant: "KK 단품",
    content: "LPM 표면이 지문도 안 묻고 깔끔하게 유지돼요. 청소할 때 그냥 닦으면 끝이에요.",
  },
  {
    id: "r-c17",
    userName: "오*진",
    rating: 5,
    date: "2026.04.19",
    variant: "KK 단품",
    content: "배송팀이 먼저 연락 주셔서 일정 맞추기 편했어요. 설치까지 한 번에 끝나서 좋았어요.",
  },
  {
    id: "r-c18",
    userName: "이*나",
    rating: 5,
    date: "2026.04.14",
    variant: "KK 단품",
    content: "프레임만 사도 완성도가 너무 높아요. 헤드보드 무드등이 침실 분위기를 확 바꿔줍니다.",
  },
  {
    id: "r-c19",
    userName: "송*주",
    rating: 5,
    date: "2026.04.09",
    variant: "KK 단품",
    content: "KK 사이즈 공간을 잘 활용할 수 있어서 좋아요. 낮은 헤드보드가 방을 훨씬 넓어 보이게 해줘요.",
    images: ["/images/reviews/1010120011/review-19-1.webp"],
  },
  {
    id: "r-c20",
    userName: "정*훈",
    rating: 5,
    date: "2026.04.04",
    variant: "KK 단품",
    content: "가구 배치하고 전체 방 사진 찍었는데 너무 예쁘게 나왔어요. 방문하는 분들마다 잘 어울린다고 해주세요.",
  },
  // ── Q/K 단품 ──
  {
    id: "r-d01",
    userName: "고*현",
    rating: 5,
    date: "2026.04.30",
    variant: "Q/K 단품",
    content: "퀸 사이즈로 구매했어요. 단품이라 가격이 합리적이고 기존 매트리스와 조합하기 좋아요. 헤드보드 무드등이 너무 예쁘고 LPM 소재라 관리가 정말 편합니다.",
    images: ["/images/reviews/1010120010/review-01-1.webp", "/images/reviews/1010120010/review-01-2.webp"],
  },
  {
    id: "r-d02",
    userName: "문*지",
    rating: 5,
    date: "2026.04.15",
    variant: "Q/K 단품",
    content: "킹 사이즈로 구매했는데 방 공간이 훨씬 넓어 보이는 효과가 있어요. 낮은 헤드보드 덕분에 공간이 답답하지 않고 세련된 느낌입니다. 설치도 깔끔하게 해주셨어요.",
  },
  {
    id: "r-d03",
    userName: "백*우",
    rating: 5,
    date: "2026.04.01",
    variant: "Q/K 단품",
    content: "혼수 가구로 구매했어요. 가성비가 정말 좋고 디자인도 예쁩니다. 기존에 쓰던 매트리스랑 잘 어울려서 새로 살 필요도 없었어요.",
    images: ["/images/reviews/1010120010/review-03-1.webp"],
  },
  {
    id: "r-d04",
    userName: "엄*민",
    rating: 4,
    date: "2026.03.18",
    variant: "Q/K 단품",
    content: "제품은 너무 마음에 드는데 사전판매 대기 기간이 좀 길었어요. 받고 보니 퀄리티가 훌륭해서 만족합니다. 다크그레이 컬러가 정말 세련돼요.",
  },
  {
    id: "r-d05",
    userName: "신*영",
    rating: 5,
    date: "2026.03.05",
    variant: "Q/K 단품",
    content: "인테리어 공사 마무리로 침대만 새로 샀는데 방 분위기가 완전히 달라졌어요. 무드등이 포인트가 되어 침실이 호텔 같아졌습니다. 강력 추천해요.",
    images: ["/images/reviews/1010120010/review-05-1.webp"],
  },
  {
    id: "r-d06",
    userName: "민*선",
    rating: 4,
    date: "2026.06.11",
    variant: "Q/K 단품",
    content: "퀸 사이즈로 구매했어요. 기존 매트리스랑 조합했는데 높이도 딱 맞고 디자인도 잘 어울려요.",
  },
  {
    id: "r-d07",
    userName: "구*현",
    rating: 5,
    date: "2026.06.06",
    variant: "Q/K 단품",
    content: "조명이 너무 은은하고 예뻐요. 침대 프레임 하나로 침실 분위기가 완전히 바뀌었어요.",
    images: ["/images/reviews/1010120010/review-07-1.webp"],
  },
  {
    id: "r-d08",
    userName: "심*호",
    rating: 5,
    date: "2026.06.01",
    variant: "Q/K 단품",
    content: "LPM 소재라 물걸레로 닦아도 끄떡없어요. 내구성 걱정 없이 오래 쓸 수 있을 것 같아요.",
  },
  {
    id: "r-d09",
    userName: "강*민",
    rating: 4,
    date: "2026.05.27",
    variant: "Q/K 단품",
    content: "디자인은 정말 마음에 드는데 설치 당일 기사님이 조금 서두르는 느낌이 있었어요. 제품은 좋아요.",
  },
  {
    id: "r-d10",
    userName: "고*란",
    rating: 5,
    date: "2026.05.22",
    variant: "Q/K 단품",
    content: "킹 사이즈로 바꿨는데 이 넓이가 맞는 것 같아요. 하부서랍도 넉넉하고 완성도 높은 제품이에요.",
    images: ["/images/reviews/1010120010/review-10-1.webp", "/images/reviews/1010120010/review-10-2.webp"],
  },
  {
    id: "r-d11",
    userName: "남*은",
    rating: 5,
    date: "2026.05.18",
    variant: "Q/K 단품",
    content: "혼수 가구 중 가장 만족도가 높은 아이템이에요. 방문하는 분들한테 칭찬 많이 받아요.",
  },
  {
    id: "r-d12",
    userName: "임*도",
    rating: 5,
    date: "2026.05.14",
    variant: "Q/K 단품",
    content: "기존 매트리스랑 같이 쓰려고 단품 구매했는데 사이즈도 딱 맞고 디자인도 정말 마음에 들어요.",
  },
  {
    id: "r-d13",
    userName: "탁*아",
    rating: 5,
    date: "2026.05.09",
    variant: "Q/K 단품",
    content: "Q/K라 퀸 킹 모두 지원되니 나중에 이사 가도 걱정 없겠다 싶어요. 유연하게 쓸 수 있어서 좋아요.",
    images: ["/images/reviews/1010120010/review-13-1.webp"],
  },
  {
    id: "r-d14",
    userName: "변*진",
    rating: 5,
    date: "2026.05.05",
    variant: "Q/K 단품",
    content: "다크그레이 색상 선택했어요. 사진으로 볼 때랑 실물이 훨씬 세련되어 보이고 만족스러워요.",
  },
  {
    id: "r-d15",
    userName: "진*현",
    rating: 5,
    date: "2026.04.30",
    variant: "Q/K 단품",
    content: "침대 프레임 단품인데도 완성도가 정말 높아요. 기존 매트리스와 함께 쓰기 딱 좋아요.",
    images: ["/images/reviews/1010120010/review-15-1.webp"],
  },
  {
    id: "r-d16",
    userName: "류*인",
    rating: 5,
    date: "2026.04.25",
    variant: "Q/K 단품",
    content: "배송기사님이 꼼꼼하게 설치해주셨어요. 설치 후 방 분위기가 확 달라져서 뿌듯해요.",
  },
  {
    id: "r-d17",
    userName: "도*원",
    rating: 5,
    date: "2026.04.20",
    variant: "Q/K 단품",
    content: "설치팀이 꼼꼼하게 마무리해줬어요. 포장재도 다 가져가주셔서 정리가 편했어요.",
    images: ["/images/reviews/1010120010/review-17-1.webp"],
  },
  {
    id: "r-d18",
    userName: "유*솔",
    rating: 5,
    date: "2026.04.15",
    variant: "Q/K 단품",
    content: "무드등 켜면 방 분위기가 완전히 달라져요. 잠들기 전에 책 읽을 때 딱 좋은 은은한 밝기예요.",
  },
  {
    id: "r-d19",
    userName: "원*준",
    rating: 5,
    date: "2026.04.10",
    variant: "Q/K 단품",
    content: "퀸 사이즈 딱 맞게 들어왔어요. 낮은 헤드보드 스타일이 방이 더 넓어 보이게 해줘서 마음에 들어요.",
    images: ["/images/reviews/1010120010/review-19-1.webp"],
  },
  {
    id: "r-d20",
    userName: "지*훈",
    rating: 5,
    date: "2026.04.05",
    variant: "Q/K 단품",
    content: "한샘 제품답게 마감이 정말 깔끔해요. 가구를 교체하고 나니 방 전체 분위기가 확 바뀌었습니다.",
  },
];

export const sharedReviews: ReviewData = {
  ...calculateReviewSummary(reviewItems),
  items: reviewItems,
};

// ─── Shared Q&A (all mono-bed variants) ──────────────────────────────────────
export const sharedQnaItems: QnaItem[] = [
  // ── KK + 밸런스매트리스 ──
  {
    id: "q-a01",
    category: "상품",
    question: "하부서랍 있는 옵션과 없는 옵션의 가격 차이가 얼마나 되나요? 나중에 하부서랍을 따로 추가 구매할 수 있나요?",
    questioner: "이*진",
    date: "2026.05.21",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 하부서랍 유/무에 따른 가격 차이는 약 8만 원입니다. 나중에 하부서랍만 따로 구매하시는 것은 어려우므로, 처음 구매 시 신중하게 선택해 주시기 바랍니다. 추가로 궁금한 점이 있으시면 고객센터(1688-4945)로 문의해 주세요.",
    answerDate: "2026.05.22",
  },
  {
    id: "q-a02",
    category: "배송",
    question: "제주도 배송이 가능한지, 추가 배송비가 얼마인지 알고 싶습니다.",
    questioner: "강*민",
    date: "2026.05.18",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 본 상품은 제주도 및 도서산간 지역 배송이 불가합니다. 가까운 한샘 플래그십 스토어를 방문하시거나 한샘직영 배송 가능 지역을 별도로 확인 후 구매해 주시기 바랍니다.",
    answerDate: "2026.05.19",
  },
  {
    id: "q-a03",
    category: "상품",
    question: "헤드 무드등 전구 종류가 어떻게 되나요? 나중에 직접 교체가 가능한지요?",
    questioner: "오*영",
    date: "2026.05.15",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 헤드 무드등은 LED 일체형으로 되어 있어 소비자가 직접 전구를 교체하기 어렵습니다. 제품 하자로 인한 LED 불량 시에는 A/S를 통해 무상으로 교체해 드리고 있으니 고객센터(1688-4945)로 연락 주세요.",
    answerDate: "2026.05.16",
  },
  {
    id: "q-a04",
    category: "배송",
    question: "사전판매 상품인데 정확한 배송 예정일을 알 수 있을까요? 이사 일정에 맞춰야 해서요.",
    questioner: "정*호",
    date: "2026.05.10",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 주문 순서에 따라 3~4주 내 순차 배송이 진행됩니다. 정확한 배송 일정은 배송 3~5일 전 담당 배송팀에서 별도 연락을 드릴 예정입니다. 이사 일정이 확정되신 분들은 고객센터로 날짜를 미리 알려주시면 최대한 맞춰 드리겠습니다.",
    answerDate: "2026.05.11",
  },
  {
    id: "q-a05",
    category: "상품",
    question: "색상이 베이지와 다크그레이 두 가지인데, 밝은 원목 가구와 함께 놓을 경우 어떤 색상이 더 잘 어울릴까요?",
    questioner: "윤*아",
    date: "2026.04.28",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 밝은 원목 가구와의 조합에서는 베이지 컬러가 보다 자연스럽고 따뜻한 인테리어를 연출하실 수 있습니다. 다크그레이는 모던하고 세련된 느낌을 주어 미니멀 인테리어에 잘 어울립니다.",
    answerDate: "2026.04.29",
  },
  {
    id: "q-a06",
    category: "기타",
    question: "기존 한샘 침대 프레임이 있는데 밸런스 볼륨탑 매트리스만 따로 구매할 수 있나요?",
    questioner: "한*준",
    date: "2026.06.01",
    answered: false,
  },
  // ── Q/K + 밸런스매트리스 ──
  {
    id: "q-b01",
    category: "상품",
    question: "Q/K 사이즈가 퀸과 킹 모두 해당되는 건가요? 각각 매트리스 규격이 다른데 어떻게 선택하나요?",
    questioner: "박*영",
    date: "2026.05.24",
    answered: true,
    answer: "안녕하세요, 한샘입니다. Q/K는 퀸(Q)과 킹(K) 사이즈를 선택할 수 있는 옵션입니다. 주문 시 옵션 선택란에서 원하시는 사이즈를 고르시면 됩니다. 퀸 사이즈는 1600×2000mm, 킹 사이즈는 1800×2000mm 기준입니다. 세트 상품이므로 선택한 사이즈에 맞는 매트리스가 함께 배송됩니다.",
    answerDate: "2026.05.25",
  },
  {
    id: "q-b02",
    category: "상품",
    question: "헤드 무드등은 밝기 조절이 가능한가요?",
    questioner: "김*희",
    date: "2026.05.12",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 현재 모델의 무드등은 ON/OFF 기능만 지원하며, 별도의 밝기 조절 기능은 없습니다. 간접조명으로서의 은은한 밝기로 설계되어 있습니다.",
    answerDate: "2026.05.13",
  },
  {
    id: "q-b03",
    category: "배송",
    question: "사전판매 배송 예정일을 알 수 있을까요? 이사 날짜에 맞추고 싶어요.",
    questioner: "정*호",
    date: "2026.05.08",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 주문 순서에 따라 3~4주 내 순차 배송이 진행됩니다. 배송 3~5일 전 배송팀에서 사전 연락을 드립니다. 이사 일정이 있으신 경우 고객센터(1688-4945)에 미리 날짜를 알려주시면 최대한 맞춰 드리겠습니다.",
    answerDate: "2026.05.09",
  },
  {
    id: "q-b04",
    category: "상품",
    question: "베이지 색상 실물이 사진과 많이 다른가요? 따뜻한 화이트인지 크림 계열인지 궁금합니다.",
    questioner: "이*수",
    date: "2026.04.30",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 베이지 색상은 따뜻한 크림 계열로, 순수 화이트보다 약간 웜톤이 가미되어 있습니다. 조명에 따라 색감 차이가 있을 수 있으므로 가까운 한샘 쇼룸에서 실물 확인을 권장드립니다.",
    answerDate: "2026.05.01",
  },
  {
    id: "q-b05",
    category: "기타",
    question: "밸런스 볼륨탑 매트리스 스펙을 더 자세히 알 수 있을까요? 경도나 소재가 궁금합니다.",
    questioner: "최*준",
    date: "2026.06.02",
    answered: false,
  },
  // ── KK 단품 ──
  {
    id: "q-c01",
    category: "상품",
    question: "단품 구매 시 KK 사이즈 기준 어떤 매트리스가 맞나요? 규격을 알고 싶습니다.",
    questioner: "이*준",
    date: "2026.05.22",
    answered: true,
    answer: "안녕하세요, 한샘입니다. KK(킹킹) 사이즈는 2000×2000mm 규격입니다. 시중에서 판매되는 슈퍼킹 또는 KK 규격 매트리스를 사용하시면 됩니다. 한샘 밸런스 볼륨탑 매트리스(KK)와의 세트 상품도 별도로 판매되고 있으니 참고해 주세요.",
    answerDate: "2026.05.23",
  },
  {
    id: "q-c02",
    category: "상품",
    question: "하부서랍이 양쪽에 모두 있나요, 한쪽에만 있나요?",
    questioner: "박*수",
    date: "2026.05.16",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 하부서랍은 침대 양쪽(좌우) 모두에 위치하며, 서랍 2개가 포함되어 있습니다. 수납 공간이 넓어 이불·베개·의류 등을 보관하기에 적합합니다.",
    answerDate: "2026.05.17",
  },
  {
    id: "q-c03",
    category: "배송",
    question: "배송 전 사전 연락을 꼭 받을 수 있나요? 회사 재직 중이라 일정 조율이 필요합니다.",
    questioner: "최*호",
    date: "2026.05.11",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 배송 3~5일 전 담당 배송팀에서 전화로 사전 연락을 드립니다. 연락 시 원하시는 배송 날짜와 시간대를 조율해 드리고 있으니 안심하고 주문해 주세요.",
    answerDate: "2026.05.12",
  },
  {
    id: "q-c04",
    category: "상품",
    question: "무드등 스위치는 어디에 위치하나요? 리모컨이 별도로 있나요?",
    questioner: "김*영",
    date: "2026.05.05",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 무드등 스위치는 헤드보드 측면에 위치하며, 터치 방식으로 작동합니다. 별도의 리모컨은 제공되지 않습니다.",
    answerDate: "2026.05.06",
  },
  {
    id: "q-c05",
    category: "상품",
    question: "베이지 컬러 실물을 쇼룸에서 확인할 수 있나요?",
    questioner: "정*은",
    date: "2026.04.25",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 전국 한샘 플래그십 스토어 및 주요 쇼룸에서 실물을 확인하실 수 있습니다. 방문 전 한샘 고객센터(1688-4945) 또는 홈페이지에서 전시 여부를 미리 확인해 주시기 바랍니다.",
    answerDate: "2026.04.26",
  },
  {
    id: "q-c06",
    category: "기타",
    question: "기존에 사용하던 침대 프레임 폐기 서비스도 함께 신청할 수 있나요?",
    questioner: "오*석",
    date: "2026.06.03",
    answered: false,
  },
  // ── Q/K 단품 ──
  {
    id: "q-d01",
    category: "상품",
    question: "Q/K 단품이 퀸과 킹 모두 선택 가능한 건가요? 퀸 사이즈와 킹 사이즈 가격이 같은가요?",
    questioner: "조*훈",
    date: "2026.05.26",
    answered: true,
    answer: "안녕하세요, 한샘입니다. Q/K 단품은 퀸(1600×2000mm)과 킹(1800×2000mm) 사이즈 중 선택 가능합니다. 두 사이즈의 가격은 동일합니다. 주문 시 옵션에서 원하시는 사이즈를 선택해 주세요.",
    answerDate: "2026.05.27",
  },
  {
    id: "q-d02",
    category: "상품",
    question: "하부서랍 없는 옵션도 있나요? 방 청소 시 활용하고 싶어서요.",
    questioner: "배*은",
    date: "2026.05.20",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 하부서랍 유/무 두 가지 옵션 중 선택 가능합니다. 서랍 없는 옵션은 바닥과의 공간이 열려있어 청소기 사용이 편리합니다. 주문 시 옵션 선택란을 확인해 주세요.",
    answerDate: "2026.05.21",
  },
  {
    id: "q-d03",
    category: "배송",
    question: "배송 기사님이 기존 침대 수거도 해주시나요?",
    questioner: "한*주",
    date: "2026.05.14",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 기존 가구 수거 서비스는 별도 신청이 필요하며, 유료로 진행됩니다. 자세한 사항은 배송팀 사전 연락 시 또는 고객센터(1688-4945)에 문의해 주세요.",
    answerDate: "2026.05.15",
  },
  {
    id: "q-d04",
    category: "상품",
    question: "퀸 사이즈 기준 침대 전체 폭이 어떻게 되나요? 방 배치를 미리 계획하고 싶습니다.",
    questioner: "나*현",
    date: "2026.05.07",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 퀸 사이즈(Q) 기준 침대 전체 폭은 약 1720mm, 길이는 약 2180mm, 헤드보드 높이는 약 870mm입니다. 정확한 치수는 상품 상세 페이지 사이즈 탭에서 확인하실 수 있습니다.",
    answerDate: "2026.05.08",
  },
  {
    id: "q-d05",
    category: "상품",
    question: "베이지와 다크그레이 중 흠집이 덜 나는 색상이 어느 쪽인가요?",
    questioner: "황*민",
    date: "2026.04.22",
    answered: true,
    answer: "안녕하세요, 한샘입니다. LPM 소재 특성상 두 색상 모두 흠집에 강하고 내구성이 우수합니다. 다만 밝은 색상(베이지)은 어두운 이물질이, 어두운 색상(다크그레이)은 밝은 이물질이 상대적으로 눈에 더 잘 띌 수 있습니다.",
    answerDate: "2026.04.23",
  },
  {
    id: "q-d06",
    category: "기타",
    question: "추후 같은 모노 라인 협탁도 구매 예정인데 같이 배송받을 수 있나요?",
    questioner: "류*서",
    date: "2026.06.04",
    answered: false,
  },
];

// ─── Detail assembly ──────────────────────────────────────────────────────────
export function getDetail(id: string): ProductDetail {
  const summary = summaries.find((s) => s.id === id);
  if (!summary) throw new Error(`mono-bed SKU not found: ${id}`);
  const variant = variantDetails[id];
  if (!variant) throw new Error(`mono-bed variant data missing: ${id}`);
  return {
    ...summary,
    ...monoBedFamily,
    ...variant,
    siblings: summaries,
    reviews: sharedReviews,
    qnaItems: sharedQnaItems,
  };
}
