import type { ReviewData, QnaItem, Review } from "@/app/lib/types";
import { calculateReviewSummary } from "@/lib/reviews";

const reviewItems: Review[] = [
  {
    id: "r-a01",
    userName: "so*****",
    rating: 5,
    date: "2026.07.06",
    variant: "베이지",
    content: "거실에 베이지로 달았는데 오후 햇살이 은은하게 걸러져 들어와요. 카페 같은 분위기가 나서 매일 기분이 좋습니다.",
    images: ["/images/reviews/1712100020/review-01-1.webp", "/images/reviews/1712100020/review-01-2.webp"],
  },
  {
    id: "r-a02",
    userName: "hn*****",
    rating: 5,
    date: "2026.06.27",
    variant: "화이트",
    content: "맞춤제작이라 창 폭에 딱 맞게 나왔어요. 화이트인데 속이 비치지 않아서 낮에도 안심됩니다.",
  },
  {
    id: "r-a03",
    userName: "dq*****",
    rating: 5,
    date: "2026.06.18",
    variant: "베이지",
    content: "린넨 커튼 느낌인데 관리는 훨씬 편해요. 세탁기에 돌렸는데 수축 없이 그대로라 놀랐습니다.",
    images: ["/images/reviews/1712100020/review-03-1.webp"],
  },
  {
    id: "r-a04",
    userName: "yb*****",
    rating: 4,
    date: "2026.06.09",
    variant: "화이트",
    content: "원단과 빛 느낌은 정말 좋은데 맞춤제작이라 배송까지 일주일 넘게 걸렸어요. 급하지 않다면 추천합니다.",
  },
  {
    id: "r-a05",
    userName: "wj*****",
    rating: 5,
    date: "2026.05.31",
    variant: "베이지",
    content: "가리고 싶은 건 가려지고 답답하진 않은 딱 그 중간이에요. 아침에 자연광으로 잠 깨는 게 좋아졌습니다.",
  },
  {
    id: "r-a06",
    userName: "pf*****",
    rating: 5,
    date: "2026.05.22",
    variant: "화이트",
    content: "원룸 통창에 50cm 단위로 계산해서 주문했는데 계산법 안내가 친절해서 어렵지 않았어요. 결과물도 딱 맞습니다.",
  },
  {
    id: "r-a07",
    userName: "km*****",
    rating: 3,
    date: "2026.05.13",
    variant: "베이지",
    content: "원단은 좋은데 생각보다 빛이 많이 들어와서 침실용으로는 아쉬워요. 거실이나 주방엔 잘 맞을 것 같습니다.",
  },
  {
    id: "r-a08",
    userName: "cg*****",
    rating: 5,
    date: "2026.05.04",
    variant: "화이트",
    content: "이사하면서 온 집 커튼을 이걸로 통일했어요. 은은한 워싱 결 덕분에 집이 한 톤 밝아졌습니다.",
    images: ["/images/reviews/1712100020/review-08-1.webp"],
  },
  {
    id: "r-a09",
    userName: "vt*****",
    rating: 5,
    date: "2026.04.25",
    variant: "베이지",
    content: "주름이 자연스럽게 떨어져서 따로 정리하지 않아도 예뻐요. 반려식물 키우는 창가에 두니 빛이 딱 좋습니다.",
  },
  {
    id: "r-a10",
    userName: "ne*****",
    rating: 5,
    date: "2026.04.16",
    variant: "화이트",
    content: "가격 대비 원단 두께가 탄탄해요. 맞춤인데 이 가격이면 기성 커튼 살 이유가 없는 것 같습니다.",
  },
  {
    id: "r-a11",
    userName: "ru*****",
    rating: 5,
    date: "2026.04.07",
    variant: "베이지",
    content: "촬영 배경용으로도 손색없다는 후기 보고 샀는데 정말 화면에 예쁘게 나와요. 재택 화상회의 배경으로도 좋습니다.",
  },
  {
    id: "r-a12",
    userName: "gb*****",
    rating: 5,
    date: "2026.03.29",
    variant: "화이트",
    content: "두 번째 창도 추가 주문했어요. 같은 원단으로 폭만 다르게 맞출 수 있으니 집 전체 통일하기 좋습니다.",
  },
];

export const sharedReviews: ReviewData = {
  ...calculateReviewSummary(reviewItems),
  items: reviewItems,
};

export const sharedQnaItems: QnaItem[] = [
  {
    id: "q-a01",
    category: "상품",
    question: "가로폭 50cm 단위라면 창 폭 180cm 창에는 몇 개를 주문해야 하나요?",
    questioner: "mz*****",
    date: "2026.06.14",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 커튼은 창 폭의 1.5~2배 여유를 권장드려 180cm 창 기준 6~7폭(300~350cm) 주문을 추천드립니다. 상세 페이지 사이즈 안내의 폭 계산 가이드를 참고 부탁드립니다. 감사합니다.",
    answerDate: "2026.06.15",
  },
  {
    id: "q-a02",
    category: "상품",
    question: "커튼봉 고리형인가요, 아일렛형인가요?",
    questioner: "tb*****",
    date: "2026.05.27",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 기본 봉제는 핀형(커튼핀 포함)으로 제작되며, 주문 옵션에서 아일렛형으로 변경 가능합니다. 레일과 봉 모두 사용 가능한 방식입니다. 감사합니다.",
    answerDate: "2026.05.28",
  },
  {
    id: "q-a03",
    category: "배송",
    question: "맞춤제작 주문 후 사이즈 변경이 가능한가요?",
    questioner: "eq*****",
    date: "2026.07.05",
    answered: false,
  },
];
