import type { ReviewData, QnaItem, Review } from "@/app/lib/types";
import { calculateReviewSummary } from "@/lib/reviews";

const reviewItems: Review[] = [
  // ── 라운지세트 ──
  {
    id: "r-a01",
    userName: "ho*****",
    rating: 5,
    date: "2026.06.21",
    variant: "라운지세트",
    content: "코너벤치까지 있어서 아이들과 함께 앉기에 정말 편해요. 원목 결이 살아 있어서 거실 분위기가 한결 따뜻해졌습니다.",
    images: ["/images/reviews/1210120011/review-01-1.webp", "/images/reviews/1210120011/review-01-2.webp", "/images/reviews/1210120011/review-01-3.webp"],
  },
  {
    id: "r-a02",
    userName: "ks*****",
    rating: 5,
    date: "2026.06.09",
    variant: "라운지세트",
    content: "벤치와 코너벤치 구성 덕분에 6명이 앉아도 전혀 비좁지 않아요. 가족 모임이 많은 저희 집에 딱 맞는 선택이었습니다.",
  },
  {
    id: "r-a03",
    userName: "lj*****",
    rating: 5,
    date: "2026.05.28",
    variant: "라운지세트",
    content: "원목의자 마감이 정말 매끈하고 고급스러워요. 베이지 컬러로 골랐는데 거실 인테리어와 자연스럽게 어우러집니다.",
    images: ["/images/reviews/1210120011/review-03-1.webp"],
  },
  {
    id: "r-a04",
    userName: "ph*****",
    rating: 4,
    date: "2026.05.15",
    variant: "라운지세트",
    content: "제품 자체는 만족스러운데 코너벤치 조립 부품이 많아서 설치 시간이 예상보다 길었어요. 결과물은 견고하고 좋습니다.",
  },
  {
    id: "r-a05",
    userName: "ce*****",
    rating: 5,
    date: "2026.05.03",
    variant: "라운지세트",
    content: "판매 2위인 이유가 있는 것 같아요. 벤치형 구성이라 아이들이 자유롭게 들락날락해도 의자 넘어질 걱정이 없습니다.",
    images: ["/images/reviews/1210120011/review-05-1.webp"],
  },
  {
    id: "r-a06",
    userName: "lh*****",
    rating: 5,
    date: "2026.04.22",
    variant: "라운지세트",
    content: "화이트 컬러로 선택했는데 거실이 한층 환해진 느낌이에요. 코너벤치 수납공간도 알차게 활용하고 있습니다.",
    images: ["/images/reviews/1210120011/review-06-1.webp"],
  },
  {
    id: "r-a07",
    userName: "pj*****",
    rating: 3,
    date: "2026.04.10",
    variant: "라운지세트",
    content: "디자인은 좋은데 벤치 쿠션이 생각보다 조금 딱딱하게 느껴졌어요. 방석을 추가로 깔아서 사용하고 있습니다.",
  },
  {
    id: "r-a08",
    userName: "cm*****",
    rating: 5,
    date: "2026.03.28",
    variant: "라운지세트",
    content: "이사하면서 거실 다이닝 공간을 새로 꾸몄는데 라운지세트 덕분에 카페 같은 분위기가 났어요. 매우 만족합니다.",
    images: ["/images/reviews/1210120011/review-08-1.webp"],
  },
  {
    id: "r-a09",
    userName: "ky*****",
    rating: 5,
    date: "2026.03.16",
    variant: "라운지세트",
    content: "원목의자와 벤치 색감이 정말 잘 맞아요. 손님들이 올 때마다 거실 다이닝존이 예쁘다고 칭찬해 주세요.",
  },
  {
    id: "r-a10",
    userName: "ja*****",
    rating: 5,
    date: "2026.03.04",
    variant: "라운지세트",
    content: "코너벤치 배치를 벽 쪽으로 했더니 공간 활용이 훨씬 좋아졌어요. 6인용인데도 답답하지 않습니다.",
  },
  {
    id: "r-a11",
    userName: "su*****",
    rating: 5,
    date: "2026.02.19",
    variant: "라운지세트",
    content: "전반적인 완성도가 높은 제품이에요. 벤치형이라 의자보다 동선이 자유로워서 아이 키우는 집에 추천합니다.",
  },
  // ── 베이직세트 ──
  {
    id: "r-b01",
    userName: "yk*****",
    rating: 5,
    date: "2026.06.17",
    variant: "베이직세트",
    content: "벤치 하나, 원목의자 둘로 구성된 베이직세트인데도 6인이 충분히 앉을 수 있어요. 가성비가 정말 좋습니다.",
    images: ["/images/reviews/1210120010/review-01-1.webp", "/images/reviews/1210120010/review-01-2.webp"],
  },
  {
    id: "r-b02",
    userName: "im*****",
    rating: 5,
    date: "2026.06.04",
    variant: "베이직세트",
    content: "원목 특유의 자연스러운 질감이 마음에 들어요. 화이트 컬러 의자와 함께 매칭하니 깔끔한 다이닝룸이 완성됐습니다.",
  },
  {
    id: "r-b03",
    userName: "sy*****",
    rating: 4,
    date: "2026.05.22",
    variant: "베이직세트",
    content: "전체적으로 만족스러운데 벤치 다리 부분에 작은 흠집이 있었어요. 사용에는 지장 없어서 그대로 쓰고 있습니다.",
  },
  {
    id: "r-b04",
    userName: "bh*****",
    rating: 5,
    date: "2026.05.09",
    variant: "베이직세트",
    content: "벤치형이라 아이들이 의자 없이도 편하게 앉을 수 있어서 좋아요. 베이지 컬러가 따뜻한 분위기를 만들어줍니다.",
    images: ["/images/reviews/1210120010/review-04-1.webp"],
  },
  {
    id: "r-b05",
    userName: "hw*****",
    rating: 5,
    date: "2026.04.27",
    variant: "베이직세트",
    content: "신혼집 다이닝 가구로 구매했어요. 원목 의자와 벤치 조합이 생각보다 훨씬 안정감 있고 예쁩니다.",
    images: ["/images/reviews/1210120010/review-05-1.webp"],
  },
  {
    id: "r-b06",
    userName: "so*****",
    rating: 5,
    date: "2026.04.14",
    variant: "베이직세트",
    content: "조립 설치까지 깔끔하게 끝났어요. 벤치 길이가 넉넉해서 손님 초대할 때도 자리 걱정이 없습니다.",
  },
  {
    id: "r-b07",
    userName: "ry*****",
    rating: 4,
    date: "2026.04.01",
    variant: "베이직세트",
    content: "제품은 좋은데 배송 일정이 한 번 변경돼서 조금 기다렸어요. 받고 나니 만족스러운 퀄리티입니다.",
  },
  {
    id: "r-b08",
    userName: "jm*****",
    rating: 5,
    date: "2026.03.19",
    variant: "베이직세트",
    content: "거실 한쪽에 베이직세트로 작은 다이닝존을 만들었는데 카페 같은 느낌이 나서 만족스러워요.",
    images: ["/images/reviews/1210120010/review-08-1.webp"],
  },
  {
    id: "r-b09",
    userName: "ys*****",
    rating: 5,
    date: "2026.03.06",
    variant: "베이직세트",
    content: "원목의자 등받이가 적당히 곡선이 있어서 편안해요. 벤치까지 있어서 다양한 자세로 앉을 수 있습니다.",
  },
  {
    id: "r-b10",
    userName: "oj*****",
    rating: 5,
    date: "2026.02.21",
    variant: "베이직세트",
    content: "가격 대비 구성이 알차서 만족도가 높아요. 원목 마감이 자연스럽고 다른 가구와도 잘 어울립니다.",
  },
];

export const sharedReviews: ReviewData = {
  ...calculateReviewSummary(reviewItems),
  items: reviewItems,
};

export const sharedQnaItems: QnaItem[] = [
  // ── 라운지세트 ──
  {
    id: "q-a01",
    category: "상품",
    question: "코너벤치 방향을 좌우로 바꿔서 설치할 수 있나요? 거실 구조상 반대 방향이 필요합니다.",
    questioner: "ej*****",
    date: "2026.05.23",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 코너벤치는 좌우 방향 변경이 가능하도록 설계되어 있습니다. 설치 전 배송팀에 원하시는 방향을 말씀해 주시면 맞춰서 설치해 드립니다.",
    answerDate: "2026.05.24",
  },
  {
    id: "q-a02",
    category: "상품",
    question: "벤치 쿠션 부분만 교체나 추가 구매가 가능한가요?",
    questioner: "kp*****",
    date: "2026.05.08",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 벤치 쿠션은 별도 단품 판매를 진행하지 않고 있습니다. 쿠션 관련 문의는 고객센터(1688-4945)로 연락 주시면 추가 안내 도와드리겠습니다.",
    answerDate: "2026.05.09",
  },
  {
    id: "q-a03",
    category: "배송",
    question: "라운지세트 설치 시 공간이 얼마나 필요한지 미리 알 수 있을까요?",
    questioner: "hz*****",
    date: "2026.06.13",
    answered: false,
  },
  // ── 베이직세트 ──
  {
    id: "q-b01",
    category: "상품",
    question: "베이직세트 원목의자만 추가로 더 구매할 수 있나요? 인원이 늘어서 의자가 더 필요합니다.",
    questioner: "pe*****",
    date: "2026.05.19",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 원목의자는 현재 세트 구성품으로만 제공되어 단품 추가 구매는 어렵습니다. 별도 구매를 원하실 경우 고객센터(1688-4945)로 문의해 주시면 가능 여부를 안내해 드리겠습니다.",
    answerDate: "2026.05.20",
  },
  {
    id: "q-b02",
    category: "배송",
    question: "베이직세트도 조립·설치 서비스가 기본 포함인가요?",
    questioner: "zq*****",
    date: "2026.05.02",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 베이직세트 역시 전문 설치팀의 조립·설치 서비스가 기본 포함되어 있어 별도 조립 없이 편하게 받아보실 수 있습니다.",
    answerDate: "2026.05.03",
  },
  {
    id: "q-b03",
    category: "기타",
    question: "화이트와 베이지 중 어느 색상이 흠집이 덜 눈에 띄나요?",
    questioner: "lt*****",
    date: "2026.06.15",
    answered: false,
  },
];
