import type { ReviewData, QnaItem, Review } from "@/app/lib/types";
import { calculateReviewSummary } from "@/lib/reviews";

const reviewItems: Review[] = [
  {
    id: "r-a01",
    userName: "hj*****",
    rating: 5,
    date: "2026.07.20",
    variant: "기본",
    content: "원룸이라 공간이 빠듯했는데 스틸다리가 얇아서 답답하지 않아요. 사각형이라 벽에 붙여서 반은 벤치처럼 쓰고 있습니다.",
    images: ["/images/reviews/1210100010/review-01-1.webp", "/images/reviews/1210100010/review-01-2.webp"],
  },
  {
    id: "r-a02",
    userName: "sm*****",
    rating: 5,
    date: "2026.07.11",
    variant: "기본",
    content: "생각보다 튼튼해서 노트북 올려놓고 작업하기도 좋아요. 다리 도장도 깔끔합니다.",
  },
  {
    id: "r-a03",
    userName: "kt*****",
    rating: 5,
    date: "2026.07.02",
    variant: "기본",
    content: "800mm라 둘이 마주 앉기엔 딱 적당한 크기예요. 오피스텔에 두기 좋습니다.",
  },
  {
    id: "r-a04",
    userName: "yn*****",
    rating: 5,
    date: "2026.06.23",
    variant: "기본",
    content: "우드 필름 마감이라 스틸인데도 차갑지 않은 느낌이에요. 인테리어에 힘 안 줘도 자연스럽게 어울립니다.",
  },
  {
    id: "r-a05",
    userName: "dw*****",
    rating: 5,
    date: "2026.06.14",
    variant: "기본",
    content: "조립이 정말 간단해서 기사님이 금방 끝내셨어요. 다리 나사가 헐거워질까 걱정했는데 튼튼하게 고정됐습니다.",
    images: ["/images/reviews/1210100010/review-05-1.webp", "/images/reviews/1210100010/review-05-2.webp"],
  },
  {
    id: "r-a06",
    userName: "bg*****",
    rating: 5,
    date: "2026.06.05",
    variant: "기본",
    content: "가격 대비 완성도가 좋아요. 상판 모서리 마감도 깔끔한 편입니다.",
  },
  {
    id: "r-a07",
    userName: "ej*****",
    rating: 5,
    date: "2026.05.27",
    variant: "기본",
    content: "미니멀한 디자인이라 좁은 주방에도 잘 어울려요. 청소도 물티슈로 쓱 닦으면 끝입니다.",
  },
  {
    id: "r-a08",
    userName: "ps*****",
    rating: 4,
    date: "2026.05.18",
    variant: "기본",
    content: "전체적으로 만족하는데 다리 하나 높이가 살짝 안 맞아서 흔들렸어요. 고무패드로 보정해서 지금은 괜찮습니다.",
  },
  {
    id: "r-a09",
    userName: "wc*****",
    rating: 5,
    date: "2026.05.09",
    variant: "기본",
    content: "혼자 쓰다가 손님 오면 둘이 앉기 좋아서 자주 활용해요. 스틸 다리가 얇아서 의자 넣고 빼기도 편합니다.",
    images: ["/images/reviews/1210100010/review-09-1.webp"],
  },
  {
    id: "r-a10",
    userName: "mr*****",
    rating: 5,
    date: "2026.04.30",
    variant: "기본",
    content: "택배 아니라 설치기사님이 직접 조립해주셔서 편했어요. 완성도도 기대 이상입니다.",
  },
  {
    id: "r-a11",
    userName: "hb*****",
    rating: 5,
    date: "2026.04.21",
    variant: "기본",
    content: "800mm가 생각보다 알차게 느껴져요. 노트북, 밥그릇 두 개 놓아도 여유롭습니다.",
  },
  {
    id: "r-a12",
    userName: "jy*****",
    rating: 5,
    date: "2026.04.12",
    variant: "기본",
    content: "스틸 프레임이라 그런지 원목보다 훨씬 가벼워서 청소할 때 옮기기 편해요.",
  },
  {
    id: "r-a13",
    userName: "on*****",
    rating: 5,
    date: "2026.04.03",
    variant: "기본",
    content: "심플한 디자인이라 어떤 의자를 매치해도 잘 어울려요. 다음엔 의자도 여기서 사려고요.",
  },
  {
    id: "r-a14",
    userName: "vs*****",
    rating: 5,
    date: "2026.03.25",
    variant: "기본",
    content: "오피스텔 좁은 다이닝 공간에 딱 맞았어요. 사각형이라 벽 붙임 배치도 깔끔합니다.",
    images: ["/images/reviews/1210100010/review-14-1.webp"],
  },
  {
    id: "r-a15",
    userName: "rq*****",
    rating: 4,
    date: "2026.03.16",
    variant: "기본",
    content: "제품은 만족스러운데 박스 모서리가 배송 중 조금 눌려 왔어요. 조립 후엔 티가 안 나서 그대로 씁니다.",
  },
  {
    id: "r-a16",
    userName: "az*****",
    rating: 5,
    date: "2026.03.07",
    variant: "기본",
    content: "얇은 다리 디자인이 마음에 들어서 골랐는데 실제로도 튼튼해서 안심하고 씁니다.",
  },
  {
    id: "r-a17",
    userName: "tf*****",
    rating: 5,
    date: "2026.02.26",
    variant: "기본",
    content: "1인 가구인데 식탁 하나로 공간이 확 정리된 느낌이에요. 사이즈가 딱 적당합니다.",
  },
  {
    id: "r-a18",
    userName: "gi*****",
    rating: 5,
    date: "2026.02.17",
    variant: "기본",
    content: "스틸이라 녹슬까 걱정했는데 분체도장이라 그런지 아직 문제없어요. 관리가 편합니다.",
  },
  {
    id: "r-a19",
    userName: "uj*****",
    rating: 5,
    date: "2026.02.08",
    variant: "기본",
    content: "가격대비 만족도가 높아요. 다리 나사 조임까지 꼼꼼하게 해주셔서 흔들림이 없습니다.",
    images: ["/images/reviews/1210100010/review-19-1.webp"],
  },
  {
    id: "r-a20",
    userName: "nx*****",
    rating: 5,
    date: "2026.01.30",
    variant: "기본",
    content: "심플한 디자인이 유행을 안 타서 오래 쓸 수 있을 것 같아요. 조립도 빠르게 끝났습니다.",
  },
  {
    id: "r-a21",
    userName: "pw*****",
    rating: 5,
    date: "2026.01.21",
    variant: "기본",
    content: "좁은 주방에 두기 딱 좋은 크기고 스틸 다리라 이동도 수월해요. 만족스러운 구매였습니다.",
  },
];

export const sharedReviews: ReviewData = {
  ...calculateReviewSummary(reviewItems),
  items: reviewItems,
};

export const sharedQnaItems: QnaItem[] = [
  {
    id: "q-a01",
    category: "상품",
    question: "의자는 몇 인용으로 매치하면 되나요?",
    questioner: "dg*****",
    date: "2026.06.28",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 2인용으로 설계된 식탁이라 마주보는 의자 2개를 매치하시는 것을 권장드립니다. 감사합니다.",
    answerDate: "2026.06.29",
  },
  {
    id: "q-a02",
    category: "배송",
    question: "설치까지 얼마나 걸리나요?",
    questioner: "sk*****",
    date: "2026.06.05",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 다리 조립 포함 20~30분 내외로 설치가 완료됩니다. 감사합니다.",
    answerDate: "2026.06.06",
  },
  {
    id: "q-a03",
    category: "상품",
    question: "다리 색상이 블랙만 있나요?",
    questioner: "wm*****",
    date: "2026.05.10",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 현재는 블랙 스틸 프레임 단일 구성으로만 판매하고 있습니다. 감사합니다.",
    answerDate: "2026.05.11",
  },
  {
    id: "q-a04",
    category: "기타",
    question: "야외테라스에 두고 사용해도 되나요?",
    questioner: "hf*****",
    date: "2026.07.16",
    answered: false,
  },
];
