import type { ReviewData, QnaItem, Review } from "@/app/lib/types";
import { calculateReviewSummary } from "@/lib/reviews";

const reviewItems: Review[] = [
  // ── 블랙 ──
  {
    id: "r-a01",
    userName: "jw*****",
    rating: 5,
    date: "2026.07.06",
    variant: "블랙",
    content: "블랙 스틸 바디가 미드센추리 인테리어에 딱이에요. 헤드 각도를 벽 쪽으로 돌리면 간접조명이 되는 게 제일 마음에 듭니다.",
    images: ["/images/reviews/1713100030/review-01-1.webp"],
  },
  {
    id: "r-a02",
    userName: "sp*****",
    rating: 5,
    date: "2026.06.27",
    variant: "블랙",
    content: "소파 옆 리딩 램프로 쓰는데 풋 스위치가 신의 한 수예요. 앉은 채로 발끝으로 켜고 끕니다.",
  },
  {
    id: "r-a03",
    userName: "mh*****",
    rating: 5,
    date: "2026.06.18",
    variant: "블랙",
    content: "가는 스탠드라 존재감이 부담스럽지 않은데 켜면 확실하게 분위기를 잡아줘요. 8만원대 가격이 믿기지 않습니다.",
    images: ["/images/reviews/1713100030/review-03-1.webp", "/images/reviews/1713100030/review-03-2.webp"],
  },
  {
    id: "r-a04",
    userName: "dc*****",
    rating: 4,
    date: "2026.06.09",
    variant: "블랙",
    content: "디자인과 빛은 만족인데 무광 블랙이라 먼지가 앉으면 조금 보여요. 자주 닦아주면 문제없습니다.",
  },
  {
    id: "r-a05",
    userName: "yk*****",
    rating: 5,
    date: "2026.05.31",
    variant: "블랙",
    content: "홈오피스 구석에 두고 모니터 뒤 벽을 비추게 했더니 눈 피로가 확 줄었어요. 재택러에게 추천합니다.",
  },
  {
    id: "r-a06",
    userName: "wt*****",
    rating: 5,
    date: "2026.05.22",
    variant: "블랙",
    content: "1위 상품이라길래 샀는데 이유가 있네요. 조립 5분, 배송 이틀, 만족은 계속입니다.",
  },
  {
    id: "r-a07",
    userName: "cv*****",
    rating: 3,
    date: "2026.05.13",
    variant: "블랙",
    content: "제품은 괜찮은데 배송 중 셰이드에 미세한 눌림 자국이 있었어요. 점등하면 안 보여서 그냥 쓰기로 했습니다.",
  },
  {
    id: "r-a08",
    userName: "hk*****",
    rating: 5,
    date: "2026.05.04",
    variant: "블랙",
    content: "원룸 자취방 조명으로 최고예요. 천장등 없이 이거 하나로 저녁을 보냅니다. 전기세 부담도 없어요.",
  },
  {
    id: "r-a09",
    userName: "tl*****",
    rating: 5,
    date: "2026.04.25",
    variant: "블랙",
    content: "베이스가 낮고 넓어서 로봇청소기가 지나가도 안 넘어져요. 디자인 조명 중에 실용성까지 갖춘 제품입니다.",
  },
  {
    id: "r-a10",
    userName: "lr*****",
    rating: 5,
    date: "2026.04.16",
    variant: "블랙",
    content: "거실 코너가 허전했는데 블랙 라인 하나로 공간이 완성됐어요. 사진보다 실물이 더 세련됩니다.",
    images: ["/images/reviews/1713100030/review-10-1.webp"],
  },
  {
    id: "r-a11",
    userName: "bz*****",
    rating: 5,
    date: "2026.04.07",
    variant: "블랙",
    content: "화이트랑 고민하다 블랙 샀는데 우드 가구와 대비가 좋아요. 시리즈로 침실엔 베이지 추가 주문했습니다.",
  },
  // ── 화이트 ──
  {
    id: "r-b01",
    userName: "kf*****",
    rating: 5,
    date: "2026.07.02",
    variant: "화이트",
    content: "화이트 인테리어 집이라 벽에 스며들 듯 자연스러워요. 켜면 셰이드 라인만 은은하게 드러나는 게 예쁩니다.",
    images: ["/images/reviews/1713100031/review-01-1.webp"],
  },
  {
    id: "r-b02",
    userName: "ez*****",
    rating: 5,
    date: "2026.06.23",
    variant: "화이트",
    content: "아이 방 수면등으로 쓰는데 각도를 천장으로 돌리면 은은한 간접광이 돼요. 아이가 무서워하지 않고 잘 잡니다.",
  },
  {
    id: "r-b03",
    userName: "vg*****",
    rating: 5,
    date: "2026.06.14",
    variant: "화이트",
    content: "신혼집 밝은 톤에 맞춰 화이트로 골랐어요. 낮에는 오브제, 밤에는 무드등. 이 가격에 이만한 게 없습니다.",
  },
  {
    id: "r-b04",
    userName: "rn*****",
    rating: 4,
    date: "2026.06.05",
    variant: "화이트",
    content: "예쁘고 실용적인데 화이트라 전선까지 흰색이었으면 완벽했을 거예요. 전선은 회색이라 살짝 아쉽습니다.",
  },
  {
    id: "r-b05",
    userName: "ay*****",
    rating: 5,
    date: "2026.05.27",
    variant: "화이트",
    content: "침대 옆 협탁 대신 세워뒀는데 자기 전 독서용으로 딱이에요. 헤드를 책 쪽으로 내리면 스팟 조명이 됩니다.",
  },
  {
    id: "r-b06",
    userName: "ox*****",
    rating: 5,
    date: "2026.05.18",
    variant: "화이트",
    content: "드레스룸 거울 옆에 두니 조명빨이 좋아졌어요. 옷 고르는 시간이 즐거워졌습니다.",
    images: ["/images/reviews/1713100031/review-06-1.webp"],
  },
  {
    id: "r-b07",
    userName: "fu*****",
    rating: 5,
    date: "2026.05.09",
    variant: "화이트",
    content: "부모님 댁 거실용으로 드렸는데 풋 스위치 덕분에 허리 굽힐 일 없다고 좋아하세요. 효도템입니다.",
  },
  {
    id: "r-b08",
    userName: "qd*****",
    rating: 5,
    date: "2026.04.30",
    variant: "화이트",
    content: "이사할 때마다 데려갈 조명이에요. 가볍고 분해도 쉬운데 만듦새는 단단합니다.",
  },
  {
    id: "r-b09",
    userName: "zh*****",
    rating: 5,
    date: "2026.04.21",
    variant: "화이트",
    content: "북유럽 감성 그 자체예요. 화이트 벽에 화이트 램프인데도 실루엣 라인 덕에 밋밋하지 않습니다.",
  },
  {
    id: "r-b10",
    userName: "gp*****",
    rating: 5,
    date: "2026.04.12",
    variant: "화이트",
    content: "피아노 옆 악보 조명으로 쓰고 있어요. 각도 조절 폭이 넓어서 용도가 계속 늘어납니다.",
  },
  // ── 베이지 ──
  {
    id: "r-c01",
    userName: "un*****",
    rating: 5,
    date: "2026.06.30",
    variant: "베이지",
    content: "베이지는 흔치 않은 컬러라 골랐는데 대성공이에요. 린넨 소파, 라탄 소품과 톤이 완벽하게 맞습니다.",
    images: ["/images/reviews/1713100032/review-01-1.webp"],
  },
  {
    id: "r-c02",
    userName: "ip*****",
    rating: 5,
    date: "2026.06.20",
    variant: "베이지",
    content: "따뜻한 톤의 침실에 두려고 베이지로 샀어요. 웜 전구와 만나니 공간 전체가 크림색으로 물듭니다.",
  },
  {
    id: "r-c03",
    userName: "eg*****",
    rating: 5,
    date: "2026.06.11",
    variant: "베이지",
    content: "블랙, 화이트에 없는 부드러움이 있어요. 아이보리 커튼 옆에 세웠는데 원래 한 세트 같습니다.",
  },
  {
    id: "r-c04",
    userName: "nk*****",
    rating: 4,
    date: "2026.06.02",
    variant: "베이지",
    content: "색감은 정말 예쁜데 화면과 실물 톤이 살짝 달라요. 실물이 조금 더 진한 베이지니 참고하세요.",
  },
  {
    id: "r-c05",
    userName: "sx*****",
    rating: 5,
    date: "2026.05.24",
    variant: "베이지",
    content: "카페 같은 거실을 만들고 싶어 골랐는데 딱 그 무드가 나와요. 손님들이 조명 어디 거냐고 다 물어봅니다.",
  },
  {
    id: "r-c06",
    userName: "jt*****",
    rating: 5,
    date: "2026.05.15",
    variant: "베이지",
    content: "우드+베이지 조합 좋아하시면 고민하지 마세요. 켜지 않아도 인테리어 소품 역할을 충분히 합니다.",
    images: ["/images/reviews/1713100032/review-06-1.webp"],
  },
  {
    id: "r-c07",
    userName: "wd*****",
    rating: 5,
    date: "2026.05.06",
    variant: "베이지",
    content: "누디한 컬러라 어느 방에 옮겨도 잘 어울려요. 계절 따라 자리를 바꿔주는 재미가 있습니다.",
  },
  {
    id: "r-c08",
    userName: "hc*****",
    rating: 4,
    date: "2026.04.27",
    variant: "베이지",
    content: "전체적으로 만족하는데 베이지는 손때가 타면 눈에 띄는 편이에요. 마른 천으로 닦으면 금방 깨끗해집니다.",
  },
  {
    id: "r-c09",
    userName: "pm*****",
    rating: 5,
    date: "2026.04.18",
    variant: "베이지",
    content: "화이트는 차갑고 블랙은 무거워서 베이지로 절충했는데 정답이었어요. 침실이 한 톤 포근해졌습니다.",
  },
  {
    id: "r-c10",
    userName: "ly*****",
    rating: 5,
    date: "2026.04.09",
    variant: "베이지",
    content: "시리즈 세 컬러 중에 제일 매력 있는 컬러라고 생각해요. 흔하지 않아서 우리 집만의 포인트가 됩니다.",
  },
];

export const sharedReviews: ReviewData = {
  ...calculateReviewSummary(reviewItems),
  items: reviewItems,
};

export const sharedQnaItems: QnaItem[] = [
  {
    id: "q-a01",
    category: "상품",
    question: "전구는 포함인가요? 최대 몇 와트까지 사용 가능한가요?",
    questioner: "bd*****",
    date: "2026.06.16",
    answered: true,
    answer: "안녕하세요, 한샘입니다. E26 규격 LED 전구(웜화이트)가 기본 포함되며, LED 기준 최대 12W까지 사용을 권장드립니다. 감사합니다.",
    answerDate: "2026.06.17",
  },
  {
    id: "q-b01",
    category: "상품",
    question: "화이트 컬러 셰이드 안쪽도 흰색인가요? 점등 색감이 궁금합니다.",
    questioner: "mm*****",
    date: "2026.05.29",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 셰이드 내부는 전 컬러 공통 화이트 도장으로 마감되어 점등 시 균일한 웜톤 빛을 냅니다. 외부 컬러와 무관하게 같은 색감의 빛을 즐기실 수 있습니다. 감사합니다.",
    answerDate: "2026.05.30",
  },
  {
    id: "q-c01",
    category: "상품",
    question: "베이지 컬러가 품절인데 재입고 일정이 있나요?",
    questioner: "yv*****",
    date: "2026.05.11",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 베이지 컬러는 5월 셋째 주 재입고 예정입니다. 상품 페이지에서 재입고 알림을 신청하시면 입고 즉시 안내드립니다. 감사합니다.",
    answerDate: "2026.05.12",
  },
  {
    id: "q-a02",
    category: "배송",
    question: "두 개 주문하면 합포장으로 오나요?",
    questioner: "ka*****",
    date: "2026.04.22",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 동일 주문 건은 가능한 합포장으로 출고되나 물류 상황에 따라 개별 발송될 수 있습니다. 배송비는 1회만 부과됩니다. 감사합니다.",
    answerDate: "2026.04.23",
  },
  {
    id: "q-b02",
    category: "상품",
    question: "셰이드만 다른 컬러로 교체 구매할 수 있나요?",
    questioner: "tr*****",
    date: "2026.07.04",
    answered: false,
  },
  {
    id: "q-c02",
    category: "기타",
    question: "테이블 램프 버전 출시 계획은 없나요?",
    questioner: "df*****",
    date: "2026.07.08",
    answered: false,
  },
];
