import type { ReviewData, QnaItem, Review } from "@/app/lib/types";
import { calculateReviewSummary } from "@/lib/reviews";

const reviewItems: Review[] = [
  // ── SS ──
  {
    id: "r-a01",
    userName: "hs*****",
    rating: 5,
    date: "2026.06.15",
    variant: "SS",
    content: "유로탑 특유의 폭신한 쿠션감이 정말 좋아요. 혼자 쓰는 싱글 침대에 딱 맞고 허리 지지력도 충분합니다. 수면 품질이 확실히 달라진 느낌이에요.",
    images: ["/images/reviews/1011110010/review-01-1.webp", "/images/reviews/1011110010/review-01-2.webp"],
  },
  {
    id: "r-a02",
    userName: "kb*****",
    rating: 5,
    date: "2026.06.08",
    variant: "SS",
    content: "예전 매트리스보다 훨씬 포근하고 탄성이 좋아요. 잠들기까지 시간이 줄었어요. 배송도 빠르고 설치까지 해주셔서 만족합니다.",
  },
  {
    id: "r-a03",
    userName: "mj*****",
    rating: 5,
    date: "2026.05.28",
    variant: "SS",
    content: "슈퍼싱글 사이즈라 혼자 쓰기에 딱 좋아요. 유로탑층이 있어서 등이 닿는 느낌이 정말 편안해요. 추천합니다.",
    images: ["/images/reviews/1011110010/review-03-1.webp"],
  },
  {
    id: "r-a04",
    userName: "ye*****",
    rating: 5,
    date: "2026.05.20",
    variant: "SS",
    content: "원룸 이사하면서 새로 구매했는데 침실 분위기가 달라졌어요. 매트리스 자체 무게감이 있어서 안정적이고 흔들리지 않아요.",
  },
  {
    id: "r-a05",
    userName: "jy*****",
    rating: 5,
    date: "2026.05.12",
    variant: "SS",
    content: "한샘 매트리스 처음 써보는데 이 정도면 가격 대비 정말 좋은 것 같아요. 유로탑 덕분에 침대 위에 올라가는 순간 포근한 느낌이 납니다.",
    images: ["/images/reviews/1011110010/review-05-1.webp", "/images/reviews/1011110010/review-05-2.webp"],
  },
  {
    id: "r-a06",
    userName: "cr*****",
    rating: 4,
    date: "2026.05.05",
    variant: "SS",
    content: "배송 기간이 생각보다 조금 걸렸지만 제품 퀄리티는 충분히 만족스러워요. 탄성이 딱 제 취향입니다.",
  },
  {
    id: "r-a07",
    userName: "sy*****",
    rating: 5,
    date: "2026.04.26",
    variant: "SS",
    content: "스프링이 견고해서 자다가 중간에 뒤척여도 흔들림이 없어요. 유로탑층이 체압 분산을 잘 해줘서 아침에 일어나도 몸이 가벼워요.",
    images: ["/images/reviews/1011110010/review-07-1.webp"],
  },
  {
    id: "r-a08",
    userName: "jo*****",
    rating: 5,
    date: "2026.04.18",
    variant: "SS",
    content: "혼자 1인 가구라 SS 사이즈 선택했는데 딱 맞아요. 매트리스 두께도 충분하고 포근해서 매일 잘 자고 있습니다.",
  },
  {
    id: "r-a09",
    userName: "pa*****",
    rating: 3,
    date: "2026.04.10",
    variant: "SS",
    content: "퀄리티는 나쁘지 않은데 유로탑이 생각보다 딱딱하게 느껴졌어요. 취향 차이일 수 있으니 참고하세요.",
  },
  {
    id: "r-a10",
    userName: "li*****",
    rating: 5,
    date: "2026.04.02",
    variant: "SS",
    content: "학생 자취방에 들였는데 이 가격에 이런 퀄리티 처음이에요. 유로탑 매트리스 처음 사봤는데 일반 매트리스랑 체감 차이가 크네요.",
  },
  // ── Q ──
  {
    id: "r-b01",
    userName: "kn*****",
    rating: 5,
    date: "2026.06.18",
    variant: "Q",
    content: "퀸 사이즈 선택했는데 신혼집에 딱 어울려요. 유로탑층이 포근해서 둘이 자도 스프링 소리 없이 조용하고 편안합니다. 만족스러운 구매예요.",
    images: ["/images/reviews/1011110011/review-01-1.webp"],
  },
  {
    id: "r-b02",
    userName: "so*****",
    rating: 5,
    date: "2026.06.12",
    variant: "Q",
    content: "배송기사님이 꼼꼼하게 올려주셔서 감사했어요. 오픈 후 바로 사용했는데 매트리스 상태가 완벽했어요. 유로탑 쿠션이 몸을 감싸는 느낌이라 잠자리가 편해요.",
  },
  {
    id: "r-b03",
    userName: "ds*****",
    rating: 5,
    date: "2026.06.01",
    variant: "Q",
    content: "이사하면서 새로 구매했어요. 가격 대비 퀄리티가 뛰어나고 체압 분산이 잘 돼서 아침에 일어나면 몸이 가뿐해요. 허리 안 아픈 매트리스 찾으시는 분 추천.",
  },
  {
    id: "r-b04",
    userName: "lw*****",
    rating: 5,
    date: "2026.05.24",
    variant: "Q",
    content: "유로탑 특유의 포근함이 기대 이상이에요. 침대 프레임에 올려놓으니 딱 맞고 높이도 적당해서 마음에 들어요.",
  },
  {
    id: "r-b05",
    userName: "hy*****",
    rating: 5,
    date: "2026.05.16",
    variant: "Q",
    content: "기존 매트리스 버리고 새로 샀는데 첫날부터 확 체감이 달라요. 허리가 덜 아프고 아침에 개운하게 일어나게 되었어요. 남편도 정말 좋다고 해요.",
  },
  {
    id: "r-b06",
    userName: "pk*****",
    rating: 4,
    date: "2026.05.08",
    variant: "Q",
    content: "배송까지 2주 정도 걸렸는데 받고 나니 만족합니다. 유로탑층이 꺼지지 않고 탄성을 잘 유지해줘요. 내구성 기대가 됩니다.",
  },
  {
    id: "r-b07",
    userName: "nk*****",
    rating: 5,
    date: "2026.04.29",
    variant: "Q",
    content: "퀸 사이즈 기준 침대 폭이 충분해요. 유로탑이 포근하면서도 지지력이 있어서 허리에도 좋아요. 수면 품질이 높아졌어요.",
  },
  {
    id: "r-b08",
    userName: "oj*****",
    rating: 5,
    date: "2026.04.22",
    variant: "Q",
    content: "한샘 오프라인 매장에서 직접 눕혀보고 주문했어요. 실물도 기대 이상이고 집에서 써보니 더 편안해요.",
  },
  {
    id: "r-b09",
    userName: "bw*****",
    rating: 5,
    date: "2026.04.14",
    variant: "Q",
    content: "처음엔 가격이 조금 부담스러웠는데 써보니 값어치를 충분히 해요. 스프링 반발력이 좋고 유로탑층이 쿠션을 잘 잡아줍니다.",
  },
  {
    id: "r-b10",
    userName: "vh*****",
    rating: 5,
    date: "2026.04.06",
    variant: "Q",
    content: "결혼하면서 구매했어요. 둘이 자도 움직임 전달이 거의 없어요. 유로탑 쿠션감이 포근해서 매일 잠자리가 기대됩니다.",
  },
  // ── K ──
  {
    id: "r-c01",
    userName: "gm*****",
    rating: 5,
    date: "2026.06.20",
    variant: "K",
    content: "킹 사이즈로 넓게 쓰고 싶어서 선택했어요. 유로탑층 덕분에 누웠을 때 등이 감싸지는 느낌이 정말 좋아요. 허리 통증이 줄었어요.",
    images: ["/images/reviews/1011110012/review-01-1.webp"],
  },
  {
    id: "r-c02",
    userName: "st*****",
    rating: 5,
    date: "2026.06.14",
    variant: "K",
    content: "킹 사이즈라 부부가 편하게 누워도 여유 있어요. 스프링 잡음 없이 조용하고 탄성이 일정하게 유지됩니다. 잘 구매했어요.",
  },
  {
    id: "r-c03",
    userName: "rh*****",
    rating: 5,
    date: "2026.06.05",
    variant: "K",
    content: "유로탑 매트리스는 처음인데 일반 매트리스랑 전혀 다른 포근함이 있어요. 체압 분산이 잘 돼서 옆으로 자도 어깨가 안 아파요.",
  },
  {
    id: "r-c04",
    userName: "zn*****",
    rating: 4,
    date: "2026.05.28",
    variant: "K",
    content: "배송이 예정일보다 조금 늦었지만 제품 자체는 만족해요. 유로탑층이 균일하게 쿠션을 잡아줘서 좋습니다.",
  },
  {
    id: "r-c05",
    userName: "ep*****",
    rating: 5,
    date: "2026.05.20",
    variant: "K",
    content: "킹 사이즈 선택 잘했어요. 넓게 자도 스프링이 흔들리지 않아서 좋아요. 유로탑 쿠션감이 처음엔 낯설었는데 이틀 지나니 완전 적응됩니다.",
  },
  {
    id: "r-c06",
    userName: "ws*****",
    rating: 5,
    date: "2026.05.12",
    variant: "K",
    content: "한샘 매장에서 직접 확인하고 주문했는데 가정에서도 동일한 느낌이에요. 매트리스 두께도 충분하고 커버 마감이 깔끔합니다.",
  },
  {
    id: "r-c07",
    userName: "qb*****",
    rating: 5,
    date: "2026.05.04",
    variant: "K",
    content: "가격이 좀 있지만 그만큼 퀄리티가 따라와요. 유로탑층이 꺼지지 않고 탄성을 잘 유지해서 내구성도 기대가 됩니다.",
  },
  {
    id: "r-c08",
    userName: "jm*****",
    rating: 4,
    date: "2026.04.26",
    variant: "K",
    content: "만족스럽게 사용 중이에요. 킹 사이즈라 혼자 자기엔 넓은데 오히려 더 여유롭고 좋아요.",
  },
  {
    id: "r-c09",
    userName: "tn*****",
    rating: 5,
    date: "2026.04.17",
    variant: "K",
    content: "유로탑 특유의 포근함이 일반 매트리스와 확실히 달라요. 허리 받쳐주는 느낌이 확실하고 자고 일어나면 몸이 개운합니다.",
  },
  {
    id: "r-c10",
    userName: "la*****",
    rating: 5,
    date: "2026.04.09",
    variant: "K",
    content: "새 집으로 이사하면서 구매했어요. 침실 세팅 완료되니 잠자리 기대감이 생겼어요. 실제로 첫날부터 숙면했습니다.",
  },
  // ── KK ──
  {
    id: "r-d01",
    userName: "iu*****",
    rating: 5,
    date: "2026.06.22",
    variant: "KK",
    content: "KK 사이즈라 정말 넓어요. 아이와 함께 자는데 뒤척여도 전달이 거의 없어서 서로 방해 안 돼요. 유로탑이 포근해서 가족 모두 만족합니다.",
    images: ["/images/reviews/1011110013/review-01-1.webp"],
  },
  {
    id: "r-d02",
    userName: "aj*****",
    rating: 5,
    date: "2026.06.16",
    variant: "KK",
    content: "KK 사이즈 처음 써봤는데 이 넓이가 맞네요. 유로탑 쿠션이 몸을 포근하게 감싸줘서 허리 피로 없이 잘 자고 있어요.",
  },
  {
    id: "r-d03",
    userName: "bh*****",
    rating: 5,
    date: "2026.06.07",
    variant: "KK",
    content: "배송팀이 큰 KK 사이즈를 능숙하게 올려주셨어요. 매트리스 자체 마감이 깔끔하고 유로탑층이 균일하게 분포되어 있어요.",
  },
  {
    id: "r-d04",
    userName: "yw*****",
    rating: 4,
    date: "2026.05.30",
    variant: "KK",
    content: "KK 사이즈라 배송 대기가 좀 있었지만 받고 나니 만족해요. 유로탑 쿠션감이 기대 이상으로 포근합니다.",
  },
  {
    id: "r-d05",
    userName: "sl*****",
    rating: 5,
    date: "2026.05.21",
    variant: "KK",
    content: "온 가족이 함께 자도 넉넉한 KK 사이즈예요. 유로탑이 체압을 골고루 분산해줘서 허리나 어깨 통증 없이 숙면합니다.",
  },
  {
    id: "r-d06",
    userName: "nm*****",
    rating: 5,
    date: "2026.05.13",
    variant: "KK",
    content: "스프링 품질이 좋아서 한쪽이 뒤척여도 반대쪽까지 흔들리지 않아요. KK 사이즈로 선택한 게 아주 만족스러워요.",
  },
  {
    id: "r-d07",
    userName: "cx*****",
    rating: 4,
    date: "2026.05.05",
    variant: "KK",
    content: "생각보다 유로탑이 조금 부드럽게 느껴지는 편이에요. 단단한 걸 선호하시면 참고하세요. 저는 적응되니 편하더라고요.",
  },
  {
    id: "r-d08",
    userName: "vp*****",
    rating: 5,
    date: "2026.04.27",
    variant: "KK",
    content: "아이 둘과 함께 자는데 KK 사이즈가 딱 맞아요. 유로탑이 아이들도 편안하게 해줘서 잠드는 시간이 빨라졌어요.",
  },
  {
    id: "r-d09",
    userName: "fx*****",
    rating: 5,
    date: "2026.04.19",
    variant: "KK",
    content: "KK 최고 사이즈라 주문부터 배송까지 조금 걸렸지만 결과물이 너무 만족스러워요. 매트리스 마감이 깔끔하고 탄성도 딱 좋아요.",
  },
];

export const sharedReviews: ReviewData = {
  ...calculateReviewSummary(reviewItems),
  items: reviewItems,
};

export const sharedQnaItems: QnaItem[] = [
  {
    id: "q-a01",
    category: "상품",
    question: "SS·Q·K·KK 사이즈별로 경도나 쿠션감 차이가 있나요? 아니면 사이즈만 다른 건가요?",
    questioner: "me*****",
    date: "2026.06.10",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 밸런스S 유로탑 매트리스는 사이즈만 다르고 경도와 유로탑 쿠션층 구성은 모두 동일합니다. 원하시는 침대 사이즈에 맞춰 선택해 주시면 됩니다.",
    answerDate: "2026.06.11",
  },
  {
    id: "q-a02",
    category: "배송",
    question: "KK 사이즈의 경우 배송 기간이 다른 사이즈와 동일한가요?",
    questioner: "po*****",
    date: "2026.06.05",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 모든 사이즈 공통으로 주문 후 2~3주 내 순차 배송을 진행하고 있습니다. 단, 재고 상황에 따라 일부 차이가 있을 수 있으며, 배송 3~5일 전 담당팀에서 사전 연락드립니다.",
    answerDate: "2026.06.06",
  },
  {
    id: "q-a03",
    category: "상품",
    question: "유로탑 매트리스인데 커버를 세탁할 수 있나요?",
    questioner: "ae*****",
    date: "2026.05.28",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 본 제품의 커버는 분리 세탁이 어려운 구조입니다. 오염 시 중성세제를 희석한 천으로 해당 부위를 닦아내는 방법을 권장드립니다. 자세한 관리법은 동봉된 제품 설명서를 참고해 주세요.",
    answerDate: "2026.05.29",
  },
  {
    id: "q-a04",
    category: "상품",
    question: "허리 디스크가 있는데 유로탑 매트리스가 맞을까요? 너무 푹신하지 않을지 걱정됩니다.",
    questioner: "dt*****",
    date: "2026.05.20",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 밸런스S 유로탑은 스프링 코어가 체중을 균형 있게 지지하고 유로탑층이 체압을 분산하는 구조입니다. 과도하게 푹신한 타입이 아니며 적절한 지지력을 제공합니다. 다만 건강 상태에 따라 개인차가 있으므로 가까운 한샘 매장에서 직접 체험 후 결정하시기를 권장드립니다.",
    answerDate: "2026.05.21",
  },
  {
    id: "q-a05",
    category: "배송",
    question: "아파트 엘리베이터가 좁은데 KK 사이즈 반입이 가능한가요?",
    questioner: "rl*****",
    date: "2026.05.12",
    answered: true,
    answer: "안녕하세요, 한샘입니다. KK 사이즈의 경우 매트리스 특성상 말거나 접어서 반입하기 어려운 경우가 있습니다. 배송팀이 방문 전 운반 경로를 사전 확인하고 있으며, 여의치 않을 경우 고객센터(1688-4945)로 사전 문의해 주시면 최선을 다해 안내드리겠습니다.",
    answerDate: "2026.05.13",
  },
  {
    id: "q-a06",
    category: "기타",
    question: "한샘 모노 침대 프레임과 사이즈 호환이 되나요?",
    questioner: "wt*****",
    date: "2026.06.14",
    answered: false,
  },
];
