import type { ReviewData, QnaItem, Review } from "@/app/lib/types";
import { calculateReviewSummary } from "@/lib/reviews";

const reviewItems: Review[] = [
  // ── 6종 낱개형 ──
  {
    id: "r-a01",
    userName: "hn*****",
    rating: 5,
    date: "2026.07.14",
    variant: "6종 낱개형 / 기본형 460ml",
    content: "건조식품 정리하려고 460ml, 700ml 여러 개 사서 팬트리에 쭉 정렬했어요. 투명해서 안에 뭐가 있는지 바로 보여서 편합니다.",
    images: ["/images/reviews/1711110020/review-01-1.webp"],
  },
  {
    id: "r-a02",
    userName: "st*****",
    rating: 5,
    date: "2026.06.30",
    variant: "6종 낱개형 / 롱타입 1500ml",
    content: "롱타입 1500ml는 파스타 보관에 딱 좋아요. 뚜껑도 잘 닫혀서 습기 걱정 없이 쓰고 있습니다.",
    images: ["/images/reviews/1711110020/review-02-1.webp"],
  },
  {
    id: "r-a03",
    userName: "gp*****",
    rating: 4,
    date: "2026.06.16",
    variant: "6종 낱개형 / 기본형 700ml",
    content: "가격이 저렴해서 여러 개 구매했는데 트라이탄 재질이라 가볍고 튼튼해요. 다만 뚜껑 색상이 조금 더 다양했으면 합니다.",
  },
  {
    id: "r-a04",
    userName: "ky*****",
    rating: 5,
    date: "2026.05.28",
    variant: "6종 낱개형 / 기본형 1800ml",
    content: "1800ml는 쌀이나 견과류 보관용으로 넉넉해요. 규격이 맞아서 쌓아둬도 잘 정리됩니다.",
  },
  {
    id: "r-a05",
    userName: "df*****",
    rating: 3,
    date: "2026.05.10",
    variant: "6종 낱개형 / 롱타입 2600ml",
    content: "제품 자체는 만족스러운데 하나가 배송 중 뚜껑이 살짝 눌려 왔어요. 사용에는 문제없어서 그대로 쓰고 있습니다.",
  },
  {
    id: "r-a06",
    userName: "ln*****",
    rating: 5,
    date: "2026.04.22",
    variant: "6종 낱개형 / 기본형 1300ml",
    content: "낱개로 필요한 용량만 골라 살 수 있어서 좋았어요. 냉장고 정리에 큰 도움이 됐습니다.",
    images: ["/images/reviews/1711110020/review-06-1.webp"],
  },
  {
    id: "r-a07",
    userName: "cw*****",
    rating: 4,
    date: "2026.04.03",
    variant: "6종 낱개형 / 기본형 460ml",
    content: "가벼워서 아이가 꺼내다 떨어뜨려도 안 깨져서 안심이에요. 세척도 쉬운 편입니다.",
  },
  // ── 4종 세트형 ──
  {
    id: "r-b01",
    userName: "mj*****",
    rating: 5,
    date: "2026.07.09",
    variant: "4종 세트형 / 홈카페팩",
    content: "홈카페팩으로 주문해서 재료들을 종류별로 나눠 담았어요. 세트로 사니 개별 구매보다 훨씬 이득입니다.",
    images: ["/images/reviews/1711110021/review-01-1.webp"],
  },
  {
    id: "r-b02",
    userName: "hs*****",
    rating: 5,
    date: "2026.06.25",
    variant: "4종 세트형 / 파스타팩",
    content: "파스타팩으로 구매해서 건면이랑 소스를 정리했는데 크기가 딱 맞아요. 팬트리가 훨씬 깔끔해졌습니다.",
    images: ["/images/reviews/1711110021/review-02-1.webp"],
  },
  {
    id: "r-b03",
    userName: "iq*****",
    rating: 4,
    date: "2026.06.11",
    variant: "4종 세트형 / 주방기본팩",
    content: "주방기본팩으로 이사 후 정리를 새로 했어요. 용도별 구성이라 고민 없이 바로 쓸 수 있어서 좋았습니다.",
  },
  {
    id: "r-b04",
    userName: "ov*****",
    rating: 5,
    date: "2026.05.20",
    variant: "4종 세트형 / 풀패키지",
    content: "풀패키지로 구매해서 주방 수납장 전체를 정리했어요. 가격은 있지만 그만큼 구성이 알차서 만족합니다.",
    images: ["/images/reviews/1711110021/review-05-1.webp"],
  },
  {
    id: "r-b05",
    userName: "zx*****",
    rating: 5,
    date: "2026.05.02",
    variant: "4종 세트형 / 풀패키지",
    content: "세트로 사니 사이즈별로 부족함 없이 다 갖춰져서 편해요. 선물용으로도 좋을 것 같습니다.",
  },
  {
    id: "r-b06",
    userName: "ta*****",
    rating: 4,
    date: "2026.04.16",
    variant: "4종 세트형 / 파스타팩",
    content: "파스타팩 구성이 딱 필요한 만큼이라 알뜰하게 잘 쓰고 있어요. 뚜껑 결합이 살짝 뻑뻑한 점만 아쉽습니다.",
  },
  {
    id: "r-b07",
    userName: "we*****",
    rating: 5,
    date: "2026.03.29",
    variant: "4종 세트형 / 홈카페팩",
    content: "홈카페 용품을 한 번에 정리하려고 세트로 샀는데 기대 이상이에요. 다음엔 주방기본팩도 추가할 예정입니다.",
    images: ["/images/reviews/1711110021/review-07-1.webp"],
  },
];

export const sharedReviews: ReviewData = {
  ...calculateReviewSummary(reviewItems),
  items: reviewItems,
};

export const sharedQnaItems: QnaItem[] = [
  {
    id: "q-a01",
    category: "상품",
    question: "낱개형과 세트형은 뚜껑 색상이 같나요?",
    questioner: "bh*****",
    date: "2026.06.19",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 낱개형과 세트형 모두 동일한 화이트 톤 뚜껑으로 제공되어 함께 두어도 통일감 있게 사용하실 수 있습니다. 감사합니다.",
    answerDate: "2026.06.20",
  },
  {
    id: "q-b01",
    category: "상품",
    question: "풀패키지 구성품 크기가 각각 몇 개씩 들어있나요?",
    questioner: "rk*****",
    date: "2026.05.30",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 풀패키지는 460ml·700ml·1300ml·1800ml·1500ml·2600ml 각 1개씩 총 6개로 구성되어 있습니다. 감사합니다.",
    answerDate: "2026.05.31",
  },
  {
    id: "q-a02",
    category: "기타",
    question: "전자레인지 사용이 가능한가요?",
    questioner: "fy*****",
    date: "2026.07.10",
    answered: false,
  },
];
