import type { ReviewData, QnaItem, Review } from "@/app/lib/types";
import { calculateReviewSummary } from "@/lib/reviews";

// 26 reviews: 21×5 + 5×4 = avg 4.808 → 4.8
const reviewItems: Review[] = [
  {
    id: "r-a01",
    userName: "kl*****",
    rating: 5,
    date: "2026.05.30",
    variant: "화이트",
    content: "높이 조절이 되어서 소파에서도 식사할 때 너무 편합니다.",
  },
  {
    id: "r-a02",
    userName: "jp*****",
    rating: 5,
    date: "2026.05.15",
    variant: "머드베이지",
    content: "머드베이지 색상이 우리 거실과 딱 어울려요. 리프트업도 부드럽게 작동합니다.",
  },
  {
    id: "r-a03",
    userName: "hn*****",
    rating: 5,
    date: "2026.04.27",
    variant: "화이트",
    content: "사이드테이블인데 높이 조절까지 되니 정말 실용적이에요.",
  },
  {
    id: "r-a04",
    userName: "gd*****",
    rating: 5,
    date: "2026.04.09",
    variant: "뉴메이플",
    content: "뉴메이플 색상이 원목 느낌이 나서 따뜻한 분위기를 만들어줍니다.",
  },
  {
    id: "r-a05",
    userName: "ab*****",
    rating: 5,
    date: "2026.03.20",
    variant: "화이트",
    content: "크기가 적당하고 리프트업 기능이 편리합니다. 추천합니다.",
  },
  {
    id: "r-a06",
    userName: "rs*****",
    rating: 5,
    date: "2026.03.01",
    variant: "머드베이지",
    content: "설치팀이 깔끔하게 해주셨어요. 제품 품질도 좋습니다.",
  },
  {
    id: "r-a07",
    userName: "cv*****",
    rating: 5,
    date: "2026.02.12",
    variant: "화이트",
    content: "소파 옆에 두니 인테리어가 완성된 느낌입니다.",
  },
  {
    id: "r-a08",
    userName: "mf*****",
    rating: 5,
    date: "2026.01.28",
    variant: "뉴메이플",
    content: "노트북 거치대로 활용하고 있어요. 높이가 딱 맞습니다.",
  },
  {
    id: "r-a09",
    userName: "tz*****",
    rating: 5,
    date: "2026.01.10",
    variant: "화이트",
    content: "마감이 깔끔하고 예쁩니다. 만족스러운 구매입니다.",
  },
  {
    id: "r-a10",
    userName: "ws*****",
    rating: 5,
    date: "2025.12.20",
    variant: "머드베이지",
    content: "흔들림 없고 안정적입니다. 가성비도 좋아요.",
  },
  {
    id: "r-a11",
    userName: "yg*****",
    rating: 5,
    date: "2025.11.29",
    variant: "화이트",
    content: "리프트업 각도 조절이 섬세하게 됩니다. 음료 올려두기 딱 좋아요.",
  },
  {
    id: "r-a12",
    userName: "le*****",
    rating: 5,
    date: "2025.11.08",
    variant: "뉴메이플",
    content: "색상이 너무 예뻐서 재구매했습니다. 다른 방에도 하나 더요.",
  },
  {
    id: "r-a13",
    userName: "fm*****",
    rating: 5,
    date: "2025.10.17",
    variant: "화이트",
    content: "배송이 빠르고 포장이 꼼꼼했어요.",
  },
  {
    id: "r-a14",
    userName: "io*****",
    rating: 5,
    date: "2025.09.26",
    variant: "머드베이지",
    content: "한샘답게 마감이 완벽합니다.",
  },
  {
    id: "r-a15",
    userName: "bn*****",
    rating: 5,
    date: "2025.09.05",
    variant: "화이트",
    content: "가족 모두 만족합니다. 특히 높이 조절 기능이 유용해요.",
  },
  {
    id: "r-a16",
    userName: "cr*****",
    rating: 5,
    date: "2025.08.14",
    variant: "뉴메이플",
    content: "원목 컬러가 인테리어와 잘 어울립니다.",
  },
  {
    id: "r-a17",
    userName: "pw*****",
    rating: 5,
    date: "2025.07.24",
    variant: "화이트",
    content: "크기가 딱 적당해요. 60cm 사이즈가 너무 크지도 작지도 않습니다.",
  },
  {
    id: "r-a18",
    userName: "xj*****",
    rating: 5,
    date: "2025.07.03",
    variant: "머드베이지",
    content: "리프트업이 부드럽고 소재 품질이 좋습니다.",
  },
  {
    id: "r-a19",
    userName: "vk*****",
    rating: 5,
    date: "2025.06.12",
    variant: "화이트",
    content: "침대 옆 독서 테이블로 쓰고 있어요. 매우 만족합니다.",
  },
  {
    id: "r-a20",
    userName: "qt*****",
    rating: 5,
    date: "2025.05.22",
    variant: "뉴메이플",
    content: "예쁘고 실용적이에요. 재구매 의사 있습니다.",
  },
  {
    id: "r-a21",
    userName: "ue*****",
    rating: 5,
    date: "2025.04.30",
    variant: "화이트",
    content: "높이 조절 범위가 넉넉해서 다양한 용도로 활용 가능합니다.",
  },
  {
    id: "r-a22",
    userName: "oh*****",
    rating: 4,
    date: "2026.04.18",
    variant: "화이트",
    content: "전체적으로 좋은데 높이 조절 레버가 조금 딱딱합니다.",
  },
  {
    id: "r-a23",
    userName: "dr*****",
    rating: 4,
    date: "2026.02.25",
    variant: "머드베이지",
    content: "색상이 사진보다 약간 어두운 편이에요. 실물도 예쁘긴 합니다.",
  },
  {
    id: "r-a24",
    userName: "sk*****",
    rating: 4,
    date: "2025.12.15",
    variant: "화이트",
    content: "디자인 좋고 기능도 좋습니다. 배송이 조금 늦었어요.",
  },
  {
    id: "r-a25",
    userName: "nb*****",
    rating: 4,
    date: "2025.09.28",
    variant: "뉴메이플",
    content: "만족스럽습니다. 조립이 조금 까다로운 편이에요.",
  },
  {
    id: "r-a26",
    userName: "gl*****",
    rating: 4,
    date: "2025.06.28",
    variant: "화이트",
    content: "가격 대비 품질 좋습니다. 높이 조절 범위가 더 넓으면 좋겠어요.",
  },
];

export const sharedReviews: ReviewData = {
  ...calculateReviewSummary(reviewItems),
  items: reviewItems,
};

export const sharedQnaItems: QnaItem[] = [
  {
    id: "q-a01",
    category: "상품",
    question: "높이 조절 범위가 어떻게 되나요? 최저·최고 높이를 알고 싶습니다.",
    questioner: "oh*****",
    date: "2026.04.01",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 클린트 어반 높이조절 리프트업 사이드테이블 60cm의 높이 조절 범위는 최저 약 45cm에서 최고 약 68cm입니다. 소파 암레스트 높이에 맞게 자유롭게 조절하실 수 있습니다. 추가 문의는 고객센터(1688-4945)로 연락 주세요. 감사합니다.",
    answerDate: "2026.04.02",
  },
  {
    id: "q-a02",
    category: "상품",
    question: "뉴메이플 색상이 원목인가요? 소재가 궁금합니다.",
    questioner: "gd*****",
    date: "2026.03.15",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 뉴메이플 색상 상판은 천연 원목이 아닌 MDF에 원목 패턴 시트지를 래핑한 소재입니다. 원목의 따뜻한 시각적 효과를 살리면서도 뒤틀림 없이 안정적으로 사용하실 수 있습니다. 감사합니다.",
    answerDate: "2026.03.16",
  },
  {
    id: "q-a03",
    category: "배송",
    question: "1인 가구인데 설치 시 도움이 필요한가요?",
    questioner: "hn*****",
    date: "2026.02.20",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 한샘 전문 배송팀이 방문하여 설치까지 완료해 드립니다. 고객님께서 별도로 도움을 준비하실 필요가 없으며, 성인 한 분만 계셔도 설치 진행이 가능합니다. 감사합니다.",
    answerDate: "2026.02.21",
  },
  {
    id: "q-a04",
    category: "상품",
    question: "60cm 사이즈 외에 다른 사이즈도 있나요?",
    questioner: "cr*****",
    date: "2025.08.05",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 현재 클린트 어반 높이조절 리프트업 사이드테이블은 60cm 사이즈 단일 구성으로 운영되고 있습니다. 다른 사이즈 출시 일정은 미정이며, 출시 시 공식몰을 통해 안내드리겠습니다. 감사합니다.",
    answerDate: "2025.08.06",
  },
  {
    id: "q-a05",
    category: "기타",
    question: "색상을 주문 후 변경할 수 있나요?",
    questioner: "sk*****",
    date: "2025.12.10",
    answered: false,
  },
];
