import type { ReviewData, QnaItem, Review } from "@/app/lib/types";
import { calculateReviewSummary } from "@/lib/reviews";

const reviewItems: Review[] = [
  {
    id: "r-a01",
    userName: "sj*****",
    rating: 5,
    date: "2026.07.25",
    variant: "소나무향",
    content: "판매 1위라길래 기대하고 샀는데 역시 다르네요. 소나무향이 인공적이지 않고 숲에 있는 듯한 느낌이라 매일 켜두고 있습니다.",
  },
  {
    id: "r-a02",
    userName: "yh*****",
    rating: 5,
    date: "2026.07.18",
    variant: "정원향",
    content: "정원향이 상큼하면서도 무겁지 않아서 거실에 두기 딱 좋아요. 유리병 디자인도 예뻐서 인테리어 소품으로도 손색없습니다.",
    images: ["/images/reviews/1713120020/review-02-1.webp"],
  },
  {
    id: "r-a03",
    userName: "mk*****",
    rating: 5,
    date: "2026.07.10",
    variant: "소나무향",
    content: "현관에 두니 들어올 때마다 기분이 좋아져요. 200ml라 용량도 넉넉해서 두 달 넘게 잘 쓰고 있습니다.",
  },
  {
    id: "r-a04",
    userName: "bn*****",
    rating: 5,
    date: "2026.07.02",
    variant: "정원향",
    content: "선물로 받았다가 향이 너무 좋아서 제가 재구매했어요. 리드스틱 개수로 향 조절이 되는 것도 마음에 듭니다.",
  },
  {
    id: "r-a05",
    userName: "ct*****",
    rating: 5,
    date: "2026.06.24",
    variant: "소나무향",
    content: "겨울에도 여름에도 부담 없이 쓸 수 있는 향이라 계속 재구매하게 됩니다. 원목 캡 마감이 고급스러워요.",
    images: ["/images/reviews/1713120020/review-05-1.webp"],
  },
  {
    id: "r-a06",
    userName: "fw*****",
    rating: 4,
    date: "2026.06.16",
    variant: "정원향",
    content: "향은 정말 만족스러운데 유리 용기가 생각보다 커서 협탁 위 자리를 꽤 차지해요. 그래도 향 지속력은 확실히 좋습니다.",
  },
  {
    id: "r-a07",
    userName: "qz*****",
    rating: 5,
    date: "2026.06.08",
    variant: "소나무향",
    content: "서재에서 책 읽을 때 은은하게 퍼지는 향이 집중에 도움이 돼요. 판매 1위인 이유를 알 것 같습니다.",
  },
  {
    id: "r-a08",
    userName: "up*****",
    rating: 5,
    date: "2026.05.31",
    variant: "정원향",
    content: "친구 집들이 선물로 준비했는데 반응이 폭발적이었어요. 다음엔 저도 하나 더 주문하려고 합니다.",
  },
  {
    id: "r-a09",
    userName: "ln*****",
    rating: 5,
    date: "2026.05.23",
    variant: "소나무향",
    content: "화장실에 두었더니 냄새 걱정이 확 줄었어요. 향이 자극적이지 않아서 매일 사용해도 부담이 없습니다.",
    images: ["/images/reviews/1713120020/review-09-1.webp"],
  },
  {
    id: "r-a10",
    userName: "ig*****",
    rating: 5,
    date: "2026.05.15",
    variant: "정원향",
    content: "반려동물 냄새 잡는 용도로 샀는데 생각보다 효과가 좋아요. 은은해서 두 마리 키우는 집에도 무리 없습니다.",
  },
  {
    id: "r-a11",
    userName: "vh*****",
    rating: 3,
    date: "2026.05.07",
    variant: "소나무향",
    content: "향은 좋은데 배송 중 포장이 조금 헐거워서 살짝 흘러나온 흔적이 있었어요. 그래도 사용에는 문제없었습니다.",
  },
  {
    id: "r-a12",
    userName: "ao*****",
    rating: 5,
    date: "2026.04.29",
    variant: "정원향",
    content: "봄에 어울리는 상큼한 향이라 계절 내내 잘 썼어요. 다음 계절엔 소나무향도 같이 써보려고 합니다.",
  },
  {
    id: "r-a13",
    userName: "we*****",
    rating: 5,
    date: "2026.04.21",
    variant: "소나무향",
    content: "가격 대비 향과 디자인 모두 만족스러워요. 백화점 브랜드 디퓨저 안 부러운 퀄리티입니다.",
  },
  {
    id: "r-a14",
    userName: "rk*****",
    rating: 5,
    date: "2026.04.13",
    variant: "정원향",
    content: "카페 같은 향이 나서 손님 올 때마다 물어보세요. 리드스틱을 넉넉하게 넣어주는 것도 좋았습니다.",
    images: ["/images/reviews/1713120020/review-14-1.webp"],
  },
  {
    id: "r-a15",
    userName: "zm*****",
    rating: 4,
    date: "2026.04.05",
    variant: "소나무향",
    content: "처음엔 향이 진하게 느껴졌는데 며칠 지나니 딱 적당해졌어요. 초반 세팅만 잘하면 만족도가 높습니다.",
  },
  {
    id: "r-a16",
    userName: "xu*****",
    rating: 5,
    date: "2026.03.28",
    variant: "정원향",
    content: "침실에 두고 자기 전마다 향을 맡는 게 소소한 힐링이에요. 두 가지 향 다 구비해두고 번갈아 쓰고 싶습니다.",
  },
  {
    id: "r-a17",
    userName: "ep*****",
    rating: 5,
    date: "2026.03.20",
    variant: "소나무향",
    content: "숲속 캠핑장에 있는 듯한 향이 정말 좋아요. 인공적인 향수 냄새가 아니라 자연스러운 게 최고입니다.",
  },
  {
    id: "r-a18",
    userName: "kd*****",
    rating: 5,
    date: "2026.03.12",
    variant: "정원향",
    content: "신혼집 인테리어 소품으로 구매했는데 향까지 만족스러워서 일석이조예요. 유리병도 예뻐서 다 쓰고도 화병으로 재활용할 것 같습니다.",
  },
  {
    id: "r-a19",
    userName: "fa*****",
    rating: 5,
    date: "2026.03.04",
    variant: "소나무향",
    content: "사무실 책상 위에 작게 두고 쓰는데 은은해서 동료들도 좋아해요. 향 취향 안 타는 무난한 선택인 것 같습니다.",
    images: ["/images/reviews/1713120020/review-19-1.webp"],
  },
  {
    id: "r-a20",
    userName: "ju*****",
    rating: 5,
    date: "2026.02.24",
    variant: "정원향",
    content: "재구매만 세 번째인데 매번 만족스러워요. 이 가격에 이 정도 퀄리티면 계속 이 제품만 쓸 것 같습니다.",
  },
  {
    id: "r-a21",
    userName: "ny*****",
    rating: 4,
    date: "2026.02.16",
    variant: "소나무향",
    content: "향은 취향에 딱 맞았는데 생각보다 빨리 줄어드는 느낌이에요. 스틱 개수를 줄여서 조절해가며 쓰고 있습니다.",
  },
  {
    id: "r-a22",
    userName: "ol*****",
    rating: 5,
    date: "2026.02.08",
    variant: "정원향",
    content: "선물로도 좋고 제가 쓰기에도 좋아서 두 개씩 주문했어요. 포장 상태도 깔끔하게 잘 왔습니다.",
  },
  {
    id: "r-a23",
    userName: "sd*****",
    rating: 5,
    date: "2026.01.31",
    variant: "소나무향",
    content: "겨울 건조한 실내 공기에 향까지 더해지니 분위기가 살아나요. 다음엔 정원향도 함께 구비해두려고 합니다.",
  },
  {
    id: "r-a24",
    userName: "hc*****",
    rating: 5,
    date: "2026.01.23",
    variant: "정원향",
    content: "매장에서 맡아본 향과 비슷해서 놀랐어요. 이 가격에 이 정도 향이면 정말 가성비 최고입니다.",
  },
  {
    id: "r-a25",
    userName: "tw*****",
    rating: 5,
    date: "2026.01.15",
    variant: "소나무향",
    content: "부모님 댁에 선물로 드렸는데 향이 좋다고 계속 칭찬하세요. 다음엔 두 가지 향 모두 선물하려고 합니다.",
  },
  {
    id: "r-a26",
    userName: "vm*****",
    rating: 5,
    date: "2026.01.07",
    variant: "정원향",
    content: "1위 상품이라는 게 납득되는 완성도예요. 향과 디자인 둘 다 놓치지 않은 제품인 것 같습니다.",
  },
];

export const sharedReviews: ReviewData = {
  ...calculateReviewSummary(reviewItems),
  items: reviewItems,
};

export const sharedQnaItems: QnaItem[] = [
  {
    id: "q-a01",
    category: "상품",
    question: "소나무향과 정원향 중 어떤 향이 더 은은한가요?",
    questioner: "bk*****",
    date: "2026.06.20",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 두 향 모두 과하지 않게 조향했지만, 상대적으로 소나무향이 조금 더 묵직하고 정원향이 산뜻하게 느껴진다는 후기가 많습니다. 좁은 공간에는 정원향을, 거실처럼 넓은 공간에는 소나무향을 추천드립니다. 감사합니다.",
    answerDate: "2026.06.21",
  },
  {
    id: "q-a02",
    category: "배송",
    question: "리드스틱은 몇 개 들어있나요?",
    questioner: "ic*****",
    date: "2026.05.02",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 리드스틱은 8개 동봉되어 있으며, 원하시는 향의 세기에 따라 꽂는 개수를 조절해 사용하시면 됩니다. 감사합니다.",
    answerDate: "2026.05.03",
  },
  {
    id: "q-a03",
    category: "기타",
    question: "재구매할 때 향만 다르게 선택해서 주문할 수 있나요?",
    questioner: "ry*****",
    date: "2026.07.12",
    answered: false,
  },
];
