import type { ReviewData, QnaItem, Review } from "@/app/lib/types";
import { calculateReviewSummary } from "@/lib/reviews";

const reviewItems: Review[] = [
  {
    id: "r-a01",
    userName: "hl*****",
    rating: 5,
    date: "2026.07.26",
    variant: "아이보리",
    content: "가격이 이렇게 저렴한데 만듦새가 좋아서 놀랐어요. 식탁 위에 두니 분위기가 확 달라졌습니다.",
  },
  {
    id: "r-a02",
    userName: "es*****",
    rating: 5,
    date: "2026.07.19",
    variant: "베이지",
    content: "각티슈 큰 사이즈도 여유 있게 들어가서 편해요. 스티치 디테일이 은근히 고급스러운 느낌을 줍니다.",
    images: ["/images/reviews/1713120030/review-02-1.webp"],
  },
  {
    id: "r-a03",
    userName: "on*****",
    rating: 5,
    date: "2026.07.12",
    variant: "그레이",
    content: "그레이 컬러라 어느 인테리어에도 무난하게 어울려요. 하단 미끄럼 방지 덕분에 잡아당겨도 흔들리지 않습니다.",
  },
  {
    id: "r-a04",
    userName: "tf*****",
    rating: 5,
    date: "2026.07.05",
    variant: "아이보리",
    content: "3개 색상 다 예뻐서 고민했는데 아이보리으로 하길 잘했어요. 거실 소파와 정말 잘 어울립니다.",
    images: ["/images/reviews/1713120030/review-04-1.webp"],
  },
  {
    id: "r-a05",
    userName: "wq*****",
    rating: 5,
    date: "2026.06.28",
    variant: "베이지",
    content: "선물로 몇 개 더 사려고 하는데 색상별로 다르게 구성해서 드릴 예정입니다. 이 가격에 이 품질은 정말 만족스러워요.",
    images: ["/images/reviews/1713120030/review-05-1.webp"],
  },
  {
    id: "r-a06",
    userName: "bj*****",
    rating: 5,
    date: "2026.06.21",
    variant: "그레이",
    content: "사무실 데스크 위에 두었는데 깔끔한 인상을 줘서 만족합니다. 각진 라인이 생각보다 예쁘게 잘 잡혀있어요.",
  },
  {
    id: "r-a07",
    userName: "ku*****",
    rating: 5,
    date: "2026.06.14",
    variant: "아이보리",
    content: "호텔 감성 그대로 재현한 디자인이라 마음에 들어요. 이 정도 완성도면 훨씬 비싸도 살 것 같습니다.",
  },
  {
    id: "r-a08",
    userName: "vy*****",
    rating: 4,
    date: "2026.06.07",
    variant: "베이지",
    content: "디자인은 정말 만족스러운데 초반에 가죽 특유의 냄새가 조금 나서 며칠 환기시켜 사용했어요. 지금은 냄새가 다 빠져서 잘 쓰고 있습니다.",
  },
  {
    id: "r-a09",
    userName: "ao*****",
    rating: 5,
    date: "2026.05.31",
    variant: "그레이",
    content: "식탁 위에 두니 주방 분위기가 정돈된 느낌이 나요. 가벼운 무게라 위치를 자주 옮겨도 부담이 없습니다.",
    images: ["/images/reviews/1713120030/review-09-1.webp"],
  },
  {
    id: "r-a10",
    userName: "cz*****",
    rating: 5,
    date: "2026.05.24",
    variant: "아이보리",
    content: "손님 오실 때마다 어디서 샀냐는 질문을 받아요. 가격 말하면 다들 놀라워하는 반응이 재밌습니다.",
  },
  {
    id: "r-a11",
    userName: "if*****",
    rating: 5,
    date: "2026.05.17",
    variant: "베이지",
    content: "베이지 컬러가 화이트 인테리어에 정말 잘 스며들어요. 각티슈 교체할 때도 여닫기가 편합니다.",
  },
  {
    id: "r-a12",
    userName: "rp*****",
    rating: 5,
    date: "2026.05.10",
    variant: "그레이",
    content: "차 안에 두려고 하나 더 주문했어요. 콤팩트한 사이즈라 어디에 두어도 자리를 많이 차지하지 않습니다.",
  },
  {
    id: "r-a13",
    userName: "dh*****",
    rating: 5,
    date: "2026.05.03",
    variant: "아이보리",
    content: "가죽 결이 살아있어서 저렴한 제품 같지 않아요. 눌려도 금방 형태가 돌아옵니다.",
    images: ["/images/reviews/1713120030/review-13-1.webp"],
  },
  {
    id: "r-a14",
    userName: "eg*****",
    rating: 5,
    date: "2026.04.26",
    variant: "베이지",
    content: "결혼 준비하면서 소품 하나씩 채우는 중인데 이 제품이 제일 만족스러워요. 다음 소품 고를 때도 이 브랜드로 찾아보려고 합니다.",
  },
  {
    id: "r-a15",
    userName: "sm*****",
    rating: 3,
    date: "2026.04.19",
    variant: "그레이",
    content: "제품 자체는 좋은데 배송이 예상보다 하루 정도 늦어졌어요. 물건은 이상 없이 잘 받았습니다.",
  },
  {
    id: "r-a16",
    userName: "ny*****",
    rating: 5,
    date: "2026.04.12",
    variant: "아이보리",
    content: "재구매해서 다른 방에도 두었어요. 가격 대비 이 정도 만족도면 정말 잘 산 것 같습니다.",
  },
  {
    id: "r-a17",
    userName: "qa*****",
    rating: 5,
    date: "2026.04.05",
    variant: "베이지",
    content: "부모님 댁에 선물했는데 티슈케이스 하나로 이렇게 좋아하실 줄 몰랐어요. 다음엔 다른 색상도 선물하려고 합니다.",
  },
  {
    id: "r-a18",
    userName: "lu*****",
    rating: 5,
    date: "2026.03.29",
    variant: "그레이",
    content: "책상 위 정리템으로 최고예요. 각 잡힌 디자인이라 정돈된 느낌을 줍니다.",
    images: ["/images/reviews/1713120030/review-18-1.webp"],
  },
  {
    id: "r-a19",
    userName: "xh*****",
    rating: 5,
    date: "2026.03.22",
    variant: "아이보리",
    content: "이 가격에 이 디자인이면 정말 가성비 최고예요. 지인들에게도 추천하고 있습니다.",
  },
  {
    id: "r-a20",
    userName: "fk*****",
    rating: 4,
    date: "2026.03.15",
    variant: "베이지",
    content: "디자인은 만족스러운데 개봉했을 때 살짝 눌린 자국이 있었어요. 사용에는 문제없어서 그냥 쓰고 있습니다.",
  },
  {
    id: "r-a21",
    userName: "wp*****",
    rating: 5,
    date: "2026.03.08",
    variant: "그레이",
    content: "회의실 테이블에 두려고 여러 개 주문했어요. 통일된 디자인으로 맞추니 훨씬 정돈된 느낌이 납니다.",
  },
  {
    id: "r-a22",
    userName: "zt*****",
    rating: 5,
    date: "2026.03.01",
    variant: "아이보리",
    content: "가죽 스티치가 정교해서 자꾸 만지게 돼요. 저렴한 소품인데 만족도가 정말 높습니다.",
  },
  {
    id: "r-a23",
    userName: "ov*****",
    rating: 5,
    date: "2026.02.22",
    variant: "베이지",
    content: "이사하면서 새집 분위기에 맞춰 구매했어요. 심플하면서도 고급스러운 느낌을 잘 살려줍니다.",
    images: ["/images/reviews/1713120030/review-23-1.webp"],
  },
  {
    id: "r-a24",
    userName: "yc*****",
    rating: 5,
    date: "2026.02.15",
    variant: "그레이",
    content: "매트한 그레이 컬러가 고급스러워요. 각티슈 상자 없이도 하나만 두면 오브제처럼 보입니다.",
  },
  {
    id: "r-a25",
    userName: "jm*****",
    rating: 5,
    date: "2026.02.08",
    variant: "아이보리",
    content: "3종 다 사고 싶었는데 결국 아이보리으로 정했어요. 어디에 두어도 무난하게 잘 어울려서 만족합니다.",
  },
  {
    id: "r-a26",
    userName: "pd*****",
    rating: 5,
    date: "2026.02.01",
    variant: "베이지",
    content: "출산 선물로 준비하는 육아용품 사이에 하나 끼워 넣었는데 반응이 좋았어요. 실용적이면서 예쁜 선물인 것 같습니다.",
  },
  {
    id: "r-a27",
    userName: "kb*****",
    rating: 5,
    date: "2026.01.25",
    variant: "그레이",
    content: "가벼운데도 잘 서있어서 애매하게 흔들리는 느낌이 없어요. 세워두는 소품 중에 이만한 가격대가 없는 것 같습니다.",
  },
  {
    id: "r-a28",
    userName: "gs*****",
    rating: 5,
    date: "2026.01.18",
    variant: "아이보리",
    content: "카페 느낌 나는 인테리어를 좋아하는데 딱 그 감성이에요. 저렴한 가격에 분위기를 확 살려줍니다.",
  },
  {
    id: "r-a29",
    userName: "hw*****",
    rating: 5,
    date: "2026.01.11",
    variant: "베이지",
    content: "여러 개 사서 집안 곳곳에 두었어요. 통일감 있게 꾸미니 훨씬 정돈된 느낌이 듭니다.",
  },
  {
    id: "r-a30",
    userName: "ru*****",
    rating: 5,
    date: "2026.01.04",
    variant: "그레이",
    content: "사무실 파티션 위에 두니 삭막한 느낌이 좀 줄었어요. 작은 소품 하나가 이렇게 티가 날 줄 몰랐습니다.",
  },
  {
    id: "r-a31",
    userName: "mx*****",
    rating: 5,
    date: "2025.12.28",
    variant: "아이보리",
    content: "연말 선물로 여러 개 포장해서 나눠드렸어요. 가격 부담 없이 주기 좋은 선물이었습니다.",
  },
];

export const sharedReviews: ReviewData = {
  ...calculateReviewSummary(reviewItems),
  items: reviewItems,
};

export const sharedQnaItems: QnaItem[] = [
  {
    id: "q-a01",
    category: "상품",
    question: "각티슈 큰 사이즈도 들어가나요?",
    questioner: "el*****",
    date: "2026.05.12",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 시중에 판매되는 대부분의 각티슈 규격에 여유 있게 맞도록 제작되어, 큰 사이즈도 문제없이 사용 가능합니다. 감사합니다.",
    answerDate: "2026.05.13",
  },
  {
    id: "q-a02",
    category: "배송",
    question: "주문하면 보통 며칠 만에 받아볼 수 있나요?",
    questioner: "ta*****",
    date: "2026.07.08",
    answered: false,
  },
];
