import type { ReviewData, QnaItem, Review } from "@/app/lib/types";
import { calculateReviewSummary } from "@/lib/reviews";

const reviewItems: Review[] = [
  // ── 일반형 ──
  {
    id: "r-a01",
    userName: "hj*****",
    rating: 5,
    date: "2026.05.20",
    variant: "일반형 / 화이트",
    content: "거실 분위기가 확 달라졌어요. 마감이 정말 깔끔하고 모서리 처리도 매끄럽습니다.",
    images: ["/images/reviews/1111100010/review-01-1.webp"],
  },
  {
    id: "r-a02",
    userName: "sm*****",
    rating: 5,
    date: "2026.05.08",
    variant: "일반형 / 머드베이지",
    content: "베이지 컬러가 인테리어에 자연스럽게 녹아들어요. 수납공간도 생각보다 넉넉합니다.",
    images: ["/images/reviews/1111100010/review-02-1.webp"],
  },
  {
    id: "r-a03",
    userName: "yk*****",
    rating: 5,
    date: "2026.04.17",
    variant: "일반형 / 그린",
    content: "그린 컬러 포인트가 예상보다 훨씬 예쁘네요. 거실에 포인트를 주고 싶었는데 딱 맞는 선택이었어요.",
  },
  {
    id: "r-a04",
    userName: "nk*****",
    rating: 4,
    date: "2026.03.29",
    variant: "일반형 / 화이트",
    content: "설치팀이 친절하고 빠르게 해주셨습니다. 다만 서랍 손잡이 부분이 약간 헐겁게 느껴졌어요.",
    images: ["/images/reviews/1111100010/review-04-1.webp"],
  },
  {
    id: "r-a05",
    userName: "bw*****",
    rating: 5,
    date: "2026.03.10",
    variant: "일반형 / 머드베이지",
    content: "서랍 레일이 부드럽고 닫힘 소리도 조용합니다. 가격 대비 고급스러운 느낌이 들어요.",
    images: ["/images/reviews/1111100010/review-05-1.webp"],
  },
  {
    id: "r-a06",
    userName: "jy*****",
    rating: 5,
    date: "2026.02.22",
    variant: "일반형 / 화이트",
    content: "180cm 사이즈가 거실 벽에 딱 맞아요. TV를 올려두니 전체적인 균형이 좋습니다.",
  },
  {
    id: "r-a07",
    userName: "kr*****",
    rating: 5,
    date: "2026.02.05",
    variant: "일반형 / 화이트",
    content: "심플하고 모던한 디자인이라 오래 써도 질리지 않을 것 같아요. 마감 품질도 만족스럽습니다.",
    images: ["/images/reviews/1111100010/review-07-1.webp"],
  },
  {
    id: "r-a08",
    userName: "es*****",
    rating: 3,
    date: "2026.01.18",
    variant: "일반형 / 머드베이지",
    content: "원목 느낌의 패턴은 마음에 드는데 도어 개폐 시 약간 뻑뻑한 느낌이 있어요. 시간이 지나면 나아질지 지켜보고 있습니다.",
  },
  {
    id: "r-a09",
    userName: "pa*****",
    rating: 5,
    date: "2025.12.30",
    variant: "일반형 / 그린",
    content: "그린 포인트로 거실이 한층 싱그러워졌어요. 가족 모두 만족하고 있습니다.",
  },
  {
    id: "r-a10",
    userName: "wh*****",
    rating: 5,
    date: "2025.12.11",
    variant: "일반형 / 화이트",
    content: "조립 없이 바로 설치해주셔서 정말 편했어요. 완성도가 기대 이상입니다.",
  },
  {
    id: "r-a11",
    userName: "ch*****",
    rating: 4,
    date: "2025.11.23",
    variant: "일반형 / 화이트",
    content: "서랍 수납력이 좋아서 리모컨이나 충전기 등을 깔끔하게 정리했어요. 다만 서랍을 빠르게 닫으면 소리가 조금 나는 편입니다.",
  },
  {
    id: "r-a12",
    userName: "dl*****",
    rating: 5,
    date: "2025.11.05",
    variant: "일반형 / 머드베이지",
    content: "전체적인 라인이 깔끔하고 바닥과의 높이도 청소하기 좋습니다. 인테리어 효과가 확실해요.",
  },
  {
    id: "r-a13",
    userName: "mj*****",
    rating: 5,
    date: "2025.10.18",
    variant: "일반형 / 화이트",
    content: "한샘 제품은 역시 믿을 수 있어요. 이번에도 기대 이상으로 만족스럽습니다.",
  },
  {
    id: "r-a14",
    userName: "st*****",
    rating: 5,
    date: "2025.09.29",
    variant: "일반형 / 그린",
    content: "그린 색상이 너무 예쁩니다. 사진보다 실물이 훨씬 차분하고 고급스러워요.",
  },
  {
    id: "r-a15",
    userName: "ij*****",
    rating: 4,
    date: "2025.09.10",
    variant: "일반형 / 화이트",
    content: "디자인은 정말 좋은데 배송이 예상보다 하루 늦었습니다. 제품 자체는 만족스러워요.",
  },
  {
    id: "r-a16",
    userName: "ow*****",
    rating: 5,
    date: "2025.08.22",
    variant: "일반형 / 머드베이지",
    content: "가격 대비 정말 좋은 선택이었습니다. 베이지 컬러가 거실을 따뜻하게 만들어줘요.",
  },
  {
    id: "r-a17",
    userName: "hk*****",
    rating: 4,
    date: "2025.08.04",
    variant: "일반형 / 화이트",
    content: "전반적으로 만족하지만 서랍 손잡이가 시간이 지나면 헐거워질 것 같은 느낌이 있어요. 마감 자체는 깔끔합니다.",
  },
  {
    id: "r-a18",
    userName: "yp*****",
    rating: 5,
    date: "2025.07.16",
    variant: "일반형 / 그린",
    content: "색감이 예쁘고 마감도 좋습니다. 거실에 포인트가 생겨서 만족해요.",
  },
  {
    id: "r-a19",
    userName: "gb*****",
    rating: 5,
    date: "2025.06.28",
    variant: "일반형 / 화이트",
    content: "만족스럽습니다. 설치 기사님도 친절하셨고 마감 상태도 좋았어요.",
  },
  {
    id: "r-a20",
    userName: "tn*****",
    rating: 4,
    date: "2025.06.10",
    variant: "일반형 / 머드베이지",
    content: "다용도로 쓰기 좋은 거실장입니다. 베이지 컬러가 공간을 한층 따뜻하게 해줘요.",
  },
  // ── 다릿발형 ──
  {
    id: "r-b01",
    userName: "lm*****",
    rating: 5,
    date: "2026.05.15",
    variant: "다릿발형 / 화이트",
    content: "다릿발형을 선택했는데 바닥 청소가 훨씬 편해졌어요. 룩도 한층 세련돼 보입니다.",
    images: ["/images/reviews/1111100011/review-01-1.webp"],
  },
  {
    id: "r-b02",
    userName: "rk*****",
    rating: 5,
    date: "2026.04.28",
    variant: "다릿발형 / 그린",
    content: "그린에 다릿발 조합이 북유럽 감성이 나서 너무 좋아요. 거실 분위기가 확 달라졌습니다.",
  },
  {
    id: "r-b03",
    userName: "se*****",
    rating: 5,
    date: "2026.04.09",
    variant: "다릿발형 / 머드베이지",
    content: "다릿발이 흔들림 없이 탄탄합니다. 설치팀도 꼼꼼하게 작업해주셨어요.",
    images: ["/images/reviews/1111100011/review-03-1.webp"],
  },
  {
    id: "r-b04",
    userName: "jo*****",
    rating: 4,
    date: "2026.03.21",
    variant: "다릿발형 / 화이트",
    content: "다릿발형이 인테리어 감성에 더 잘 맞아요. 다만 다릿발 높이가 생각보다 낮은 편입니다.",
  },
  {
    id: "r-b05",
    userName: "fw*****",
    rating: 5,
    date: "2026.03.02",
    variant: "다릿발형 / 화이트",
    content: "발 높이가 있어서 좁은 거실도 더 넓어 보이는 효과가 있어요. 청소할 때도 편리합니다.",
    images: ["/images/reviews/1111100011/review-05-1.webp"],
  },
  {
    id: "r-b06",
    userName: "pl*****",
    rating: 5,
    date: "2026.02.11",
    variant: "다릿발형 / 머드베이지",
    content: "다릿발 소재가 금속이라 내구성이 좋아 보입니다. 오래 쓸 수 있을 것 같아요.",
  },
  {
    id: "r-b07",
    userName: "vn*****",
    rating: 5,
    date: "2026.01.25",
    variant: "다릿발형 / 그린",
    content: "색상도 디자인도 완벽해요. 거실이 카페 같은 분위기로 바뀌었습니다.",
  },
  {
    id: "r-b08",
    userName: "cq*****",
    rating: 3,
    date: "2026.01.07",
    variant: "다릿발형 / 화이트",
    content: "화이트에 다릿발 조합은 깔끔한데 다릿발 나사가 한쪽이 살짝 흔들리는 느낌이 있었어요. AS 문의해서 조치는 받았습니다.",
  },
  {
    id: "r-b09",
    userName: "xt*****",
    rating: 5,
    date: "2025.12.19",
    variant: "다릿발형 / 화이트",
    content: "배송부터 설치까지 완벽했어요. 제품 마감도 훌륭합니다.",
  },
  {
    id: "r-b10",
    userName: "ql*****",
    rating: 5,
    date: "2025.11.30",
    variant: "다릿발형 / 머드베이지",
    content: "서랍 개폐가 부드럽고 소음이 거의 없어요. 만족스러운 구매였습니다.",
    images: ["/images/reviews/1111100011/review-10-1.webp"],
  },
  {
    id: "r-b11",
    userName: "zi*****",
    rating: 4,
    date: "2025.11.12",
    variant: "다릿발형 / 그린",
    content: "어느 방향에서 봐도 예쁜 디자인이에요. 다만 다릿발 부분에 먼지가 잘 보이는 편이라 자주 닦아줘야 합니다.",
  },
  {
    id: "r-b12",
    userName: "at*****",
    rating: 5,
    date: "2025.10.24",
    variant: "다릿발형 / 화이트",
    content: "한샘 특유의 깔끔한 마감. 역시 믿고 구매할 만합니다.",
  },
  {
    id: "r-b13",
    userName: "bu*****",
    rating: 4,
    date: "2025.10.05",
    variant: "다릿발형 / 머드베이지",
    content: "예쁜데 다릿발 높이가 생각보다 낮아서 로봇청소기가 들어가지 못해요. 디자인은 충분히 만족스럽습니다.",
  },
  {
    id: "r-b14",
    userName: "cx*****",
    rating: 5,
    date: "2025.09.17",
    variant: "다릿발형 / 화이트",
    content: "디자인은 완벽합니다. 설치 시간이 조금 걸렸지만 결과물에 만족해요.",
  },
  {
    id: "r-b15",
    userName: "dy*****",
    rating: 5,
    date: "2025.08.29",
    variant: "다릿발형 / 그린",
    content: "전반적으로 만족합니다. 서랍 손잡이가 없는 미니멀한 디자인이 마음에 들어요.",
  },
  {
    id: "r-b16",
    userName: "ez*****",
    rating: 4,
    date: "2025.08.10",
    variant: "다릿발형 / 화이트",
    content: "깔끔하고 좋습니다. 뒷면 마감이 조금 더 신경 쓰였으면 하는 아쉬움이 있어요.",
  },
  {
    id: "r-b17",
    userName: "fa*****",
    rating: 5,
    date: "2025.07.22",
    variant: "다릿발형 / 머드베이지",
    content: "가격이 조금 높지만 품질로 충분히 납득이 됩니다. 다릿발형 선택 잘한 것 같아요.",
  },
];

export const sharedReviews: ReviewData = {
  ...calculateReviewSummary(reviewItems),
  items: reviewItems,
};

export const sharedQnaItems: QnaItem[] = [
  {
    id: "q-a01",
    category: "상품",
    question: "화이트 색상 시간이 지나면 황변이 생기나요?",
    questioner: "hj*****",
    date: "2026.04.10",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 클린트 어반 거실장의 화이트 마감은 UV 코팅 처리가 되어 있어 일반적인 사용 환경에서는 황변이 거의 발생하지 않습니다. 다만 직사광선이 장시간 닿는 환경은 피해주시길 권장드립니다. 감사합니다.",
    answerDate: "2026.04.11",
  },
  {
    id: "q-a02",
    category: "배송",
    question: "설치 시 TV 배선 정리도 도와주시나요?",
    questioner: "sm*****",
    date: "2026.03.15",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 배선 정리는 별도 서비스 범위에 포함되지 않으며, 가구 설치 완료 후 고객님께서 직접 정리하셔야 합니다. 거실장 후면에 배선 구멍이 있어 정리에 도움이 됩니다. 감사합니다.",
    answerDate: "2026.03.16",
  },
  {
    id: "q-a03",
    category: "상품",
    question: "상판에 수납장을 얹어도 되나요? 무게 한도가 궁금합니다.",
    questioner: "yk*****",
    date: "2026.02.01",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 상판 권장 하중은 30kg 이내입니다. 무거운 물건을 장기간 올려두실 경우 상판 변형이 발생할 수 있으니 유의 부탁드립니다. 감사합니다.",
    answerDate: "2026.02.02",
  },
  {
    id: "q-b01",
    category: "기타",
    question: "일반형과 다릿발형 중 어떤 게 더 인기 있나요?",
    questioner: "rk*****",
    date: "2026.06.28",
    answered: false,
  },
  {
    id: "q-b02",
    category: "상품",
    question: "다릿발 높이가 정확히 몇 cm인지 알 수 있을까요?",
    questioner: "lm*****",
    date: "2026.04.22",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 클린트 어반 다릿발형의 다릿발 높이는 약 12cm입니다. 로봇청소기 진입 여부는 기기 높이에 따라 다를 수 있으니 사전 확인 부탁드립니다. 감사합니다.",
    answerDate: "2026.04.23",
  },
];
