import type { ReviewData, QnaItem, Review } from "@/app/lib/types";
import { calculateReviewSummary } from "@/lib/reviews";

// 23 reviews: 16×5 + 7×4 = avg 4.696 → 4.7
const reviewItems: Review[] = [
  {
    id: "r-a01",
    userName: "jy*****",
    rating: 5,
    date: "2026.05.28",
    variant: "화이트",
    content: "리프트업 기능이 정말 편리해요. 노트북 쓸 때 높이가 딱 맞습니다.",
    images: ["/images/reviews/1111110030/review-01-1.webp"],
  },
  {
    id: "r-a02",
    userName: "ms*****",
    rating: 5,
    date: "2026.05.10",
    variant: "화이트",
    content: "상판을 들어올리면 수납공간이 나와서 너무 실용적이에요. 디자인도 깔끔합니다.",
    images: ["/images/reviews/1111110030/review-02-1.webp"],
  },
  {
    id: "r-a03",
    userName: "hb*****",
    rating: 5,
    date: "2026.04.19",
    variant: "머드베이지",
    content: "머드베이지 색상이 정말 예쁩니다. 거실 분위기가 따뜻해졌어요.",
    images: ["/images/reviews/1111110030/review-03-1.webp"],
  },
  {
    id: "r-a04",
    userName: "ej*****",
    rating: 5,
    date: "2026.03.30",
    variant: "화이트",
    content: "플랩도어 열리는 방식이 독특하고 신기합니다. 안쪽에 수납도 충분해요.",
    images: ["/images/reviews/1111110030/review-04-1.webp"],
  },
  {
    id: "r-a05",
    userName: "ow*****",
    rating: 5,
    date: "2026.02.22",
    variant: "머드베이지",
    content: "가족 모두 이 테이블 좋아합니다. 리프트업 기능 덕분에 소파에서 식사도 편하게 해요.",
    images: ["/images/reviews/1111110030/review-05-1.webp"],
  },
  {
    id: "r-a06",
    userName: "ph*****",
    rating: 5,
    date: "2026.01.14",
    variant: "화이트",
    content: "사진보다 실물이 훨씬 예쁩니다. 마감도 깔끔하고요.",
    images: ["/images/reviews/1111110030/review-06-1.webp"],
  },
  {
    id: "r-a07",
    userName: "kh*****",
    rating: 5,
    date: "2025.12.25",
    variant: "화이트",
    content: "리프트업이 부드럽게 작동합니다. 만족스러워요.",
  },
  {
    id: "r-a08",
    userName: "by*****",
    rating: 5,
    date: "2025.11.18",
    variant: "머드베이지",
    content: "수납력과 디자인 모두 훌륭합니다.",
  },
  {
    id: "r-a09",
    userName: "cl*****",
    rating: 5,
    date: "2025.10.07",
    variant: "화이트",
    content: "기능성 테이블 중 디자인이 가장 예뻐서 선택했는데 역시나 좋습니다.",
  },
  {
    id: "r-a10",
    userName: "ak*****",
    rating: 5,
    date: "2025.09.14",
    variant: "화이트",
    content: "사이즈도 딱 적당하고 무게도 안정감 있어요.",
  },
  {
    id: "r-a11",
    userName: "dh*****",
    rating: 5,
    date: "2025.08.03",
    variant: "머드베이지",
    content: "리프트업 메커니즘이 탄탄합니다. 오래 써도 될 것 같아요.",
  },
  {
    id: "r-a12",
    userName: "wr*****",
    rating: 5,
    date: "2025.07.22",
    variant: "화이트",
    content: "구매 후 바로 배송 왔고 설치팀도 친절했습니다.",
  },
  {
    id: "r-a13",
    userName: "tp*****",
    rating: 5,
    date: "2025.06.11",
    variant: "화이트",
    content: "거실 인테리어가 확 달라졌어요. 주변 지인들한테도 추천합니다.",
  },
  {
    id: "r-a14",
    userName: "gn*****",
    rating: 5,
    date: "2025.05.01",
    variant: "머드베이지",
    content: "색상이 너무 예쁘고 기능도 훌륭합니다.",
  },
  {
    id: "r-a15",
    userName: "sl*****",
    rating: 5,
    date: "2025.04.09",
    variant: "화이트",
    content: "한샘 제품 믿고 구매했는데 역시 퀄리티가 다르네요.",
  },
  {
    id: "r-a16",
    userName: "rm*****",
    rating: 5,
    date: "2025.03.17",
    variant: "화이트",
    content: "리프트업이 이렇게 유용할 줄 몰랐어요. 이제 없으면 불편할 것 같습니다.",
  },
  {
    id: "r-a17",
    userName: "ij*****",
    rating: 4,
    date: "2026.05.02",
    variant: "화이트",
    content: "기능은 만족스럽지만 상판을 올렸을 때 약간 덜컹거리는 느낌이 있어요.",
  },
  {
    id: "r-a18",
    userName: "vs*****",
    rating: 4,
    date: "2026.02.08",
    variant: "머드베이지",
    content: "디자인 좋고 수납도 넉넉합니다. 배송이 조금 늦어서 별 하나 뺐어요.",
  },
  {
    id: "r-a19",
    userName: "zk*****",
    rating: 4,
    date: "2025.12.01",
    variant: "화이트",
    content: "가격 대비 만족합니다. 조립 설명서가 좀 더 자세했으면 좋겠어요.",
  },
  {
    id: "r-a20",
    userName: "qb*****",
    rating: 4,
    date: "2025.10.19",
    variant: "화이트",
    content: "전체적으로 좋습니다. 리프트업 각도 조절이 가능하면 더 좋을 것 같아요.",
  },
  {
    id: "r-a21",
    userName: "xe*****",
    rating: 4,
    date: "2025.08.28",
    variant: "머드베이지",
    content: "색상이 사진과 약간 다른 느낌이었지만 실물도 예쁩니다.",
  },
  {
    id: "r-a22",
    userName: "fc*****",
    rating: 4,
    date: "2025.06.16",
    variant: "화이트",
    content: "다용도로 쓰기 좋고 수납 공간도 충분합니다.",
  },
  {
    id: "r-a23",
    userName: "vt*****",
    rating: 4,
    date: "2025.04.24",
    variant: "화이트",
    content: "리프트업이 편리하네요. 전반적으로 만족스럽습니다.",
  },
];

export const sharedReviews: ReviewData = {
  ...calculateReviewSummary(reviewItems),
  items: reviewItems,
};

export const sharedQnaItems: QnaItem[] = [
  {
    id: "q-a01",
    category: "상품",
    question: "리프트업 상판 위에 무거운 물건을 올려도 괜찮나요? 최대 하중이 궁금합니다.",
    questioner: "ij*****",
    date: "2026.04.15",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 리프트업 상판의 권장 최대 하중은 5kg입니다. 노트북, 태블릿, 음식 등 일상적인 사용에는 충분하지만, 무거운 물건을 장기간 올려두시면 리프트업 메커니즘에 부하가 걸릴 수 있으니 주의해 주세요. 추가 문의는 고객센터(1688-4945)로 연락 주시면 안내드리겠습니다. 감사합니다.",
    answerDate: "2026.04.16",
  },
  {
    id: "q-a02",
    category: "배송",
    question: "배송 시 혼자 계신 경우에도 설치 가능한가요?",
    questioner: "vs*****",
    date: "2026.01.20",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 한샘 전문 배송팀이 직접 방문하여 설치까지 완료해 드리므로 고객님께서 별도로 도움을 받으실 필요가 없습니다. 배송 당일 성인 한 분만 계셔도 설치 진행이 가능합니다. 감사합니다.",
    answerDate: "2026.01.21",
  },
];
