import type { ReviewData, QnaItem, Review } from "@/app/lib/types";
import { calculateReviewSummary } from "@/lib/reviews";

const reviewItems: Review[] = [
  {
    id: "r-a01",
    userName: "jh*****",
    rating: 5,
    date: "2026.07.07",
    variant: "높은형",
    content: "옆으로 자는 편이라 높은형 골랐는데 어깨가 뜨지 않고 딱 받쳐줘요. 호텔 베개처럼 폭 안기는 느낌이 정말 좋습니다.",
    images: ["/images/reviews/1710110010/review-01-1.webp", "/images/reviews/1710110010/review-01-2.webp"],
  },
  {
    id: "r-a02",
    userName: "sk*****",
    rating: 5,
    date: "2026.07.01",
    variant: "낮은형",
    content: "베개가 높으면 목이 아픈 체질인데 낮은형이 딱 맞아요. 푹신한데 금방 꺼지지 않아서 아침까지 편안합니다.",
  },
  {
    id: "r-a03",
    userName: "mh*****",
    rating: 4,
    date: "2026.06.25",
    variant: "높은형",
    content: "볼륨감은 기대만큼 좋은데 처음 며칠은 충전재 냄새가 살짝 났어요. 하루 이틀 널어두니 사라져서 지금은 만족하며 씁니다.",
  },
  {
    id: "r-a04",
    userName: "yn*****",
    rating: 5,
    date: "2026.06.18",
    variant: "높은형",
    content: "호캉스 때 쓰던 베개가 그리워서 샀는데 그 느낌이 나요. 눌러도 복원이 빨라서 형태가 오래 갈 것 같습니다.",
    images: ["/images/reviews/1710110010/review-04-1.webp"],
  },
  {
    id: "r-a05",
    userName: "dw*****",
    rating: 5,
    date: "2026.06.11",
    variant: "낮은형",
    content: "구스 베개는 비싸서 망설였는데 구스필로 충분하네요. 촉감이 부드럽고 뒤척여도 소리가 안 나서 좋습니다.",
  },
  {
    id: "r-a06",
    userName: "he*****",
    rating: 5,
    date: "2026.06.04",
    variant: "높은형",
    content: "남편 코골이가 베개 바꾸고 줄었어요. 높이가 맞으니 확실히 수면의 질이 달라지는 것 같습니다.",
  },
  {
    id: "r-a07",
    userName: "ws*****",
    rating: 3,
    date: "2026.05.28",
    variant: "낮은형",
    content: "품질은 괜찮은데 저한테는 낮은형도 살짝 높게 느껴졌어요. 높이 선택 가이드가 더 자세했으면 좋겠습니다.",
  },
  {
    id: "r-a08",
    userName: "kh*****",
    rating: 5,
    date: "2026.05.21",
    variant: "높은형",
    content: "부모님 선물로 두 개 샀는데 두 분 다 푹 잘 주무신대요. 가격 대비 이 정도 볼륨이면 충분히 만족스럽습니다.",
    images: ["/images/reviews/1710110010/review-08-1.webp"],
  },
  {
    id: "r-a09",
    userName: "ep*****",
    rating: 5,
    date: "2026.05.14",
    variant: "낮은형",
    content: "기존 솜베개는 몇 달 쓰면 납작해졌는데 이건 복원력이 확실히 달라요. 커버 원단도 도톰해서 믿음이 갑니다.",
  },
  {
    id: "r-a10",
    userName: "un*****",
    rating: 5,
    date: "2026.05.07",
    variant: "높은형",
    content: "베개솜만 바꿨을 뿐인데 침구 전체가 업그레이드된 기분이에요. 세탁 후에도 뭉침 없이 볼륨이 살아납니다.",
  },
  {
    id: "r-a11",
    userName: "rn*****",
    rating: 4,
    date: "2026.04.30",
    variant: "낮은형",
    content: "촉감이나 볼륨은 좋은데 배송 박스가 압축 포장이라 첫날은 형태가 덜 살아났어요. 이틀 지나니 제대로 부풀었습니다.",
  },
  {
    id: "r-a12",
    userName: "og*****",
    rating: 5,
    date: "2026.04.23",
    variant: "높은형",
    content: "게스트룸용으로 샀다가 너무 편해서 제 것도 추가 주문했어요. 손님들이 베개 어디 거냐고 물어봅니다.",
    images: ["/images/reviews/1710110010/review-12-1.webp"],
  },
  {
    id: "r-a13",
    userName: "bh*****",
    rating: 5,
    date: "2026.04.16",
    variant: "낮은형",
    content: "정수리까지 폭 감싸는 느낌이 좋아요. 땀이 많은 편인데 통기성도 나쁘지 않아 쾌적하게 쓰고 있습니다.",
  },
  {
    id: "r-a14",
    userName: "tm*****",
    rating: 5,
    date: "2026.04.09",
    variant: "높은형",
    content: "목 디스크 때문에 베개를 자주 바꾸는데 이건 정착할 것 같아요. 높이가 일정하게 유지되는 게 제일 큰 장점입니다.",
  },
  {
    id: "r-a15",
    userName: "cj*****",
    rating: 4,
    date: "2026.04.02",
    variant: "높은형",
    content: "전체적으로 만족하는데 표준 베개커버보다 살짝 빵빵해서 커버 씌우기가 조금 힘들어요. 볼륨감의 반대급부라 생각합니다.",
  },
  {
    id: "r-a16",
    userName: "iy*****",
    rating: 5,
    date: "2026.03.26",
    variant: "낮은형",
    content: "아이 것까지 세 개째 구매예요. 세탁기 통세탁이 가능해서 관리가 편하고 말리면 금방 다시 부풀어요.",
  },
  {
    id: "r-a17",
    userName: "vb*****",
    rating: 5,
    date: "2026.03.19",
    variant: "높은형",
    content: "만원대 베개솜 중에 최고인 것 같아요. 호텔 침구 좋아하시는 분들은 후회 안 하실 겁니다.",
  },
];

export const sharedReviews: ReviewData = {
  ...calculateReviewSummary(reviewItems),
  items: reviewItems,
};

export const sharedQnaItems: QnaItem[] = [
  {
    id: "q-a01",
    category: "상품",
    question: "낮은형과 높은형의 실제 높이 차이가 어느 정도인가요?",
    questioner: "nr*****",
    date: "2026.06.20",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 낮은형은 누웠을 때 약 9cm, 높은형은 약 13cm 높이로 설계되었습니다. 바로 누워 주무시면 낮은형, 옆으로 주무시면 높은형을 권장드립니다. 감사합니다.",
    answerDate: "2026.06.21",
  },
  {
    id: "q-a02",
    category: "상품",
    question: "일반 50x70 베개커버와 호환되나요?",
    questioner: "wt*****",
    date: "2026.05.30",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 본 제품은 50x70cm 표준 규격으로 시중 50x70 베개커버와 호환됩니다. 볼륨감이 있는 제품 특성상 신축성 있는 커버 사용 시 더욱 편리합니다. 감사합니다.",
    answerDate: "2026.05.31",
  },
  {
    id: "q-a03",
    category: "배송",
    question: "낮은형, 높은형 하나씩 주문하면 각각 포장되어 오나요?",
    questioner: "hd*****",
    date: "2026.07.05",
    answered: false,
  },
];
