import type { ReviewData, QnaItem, Review } from "@/app/lib/types";
import { calculateReviewSummary } from "@/lib/reviews";

const reviewItems: Review[] = [
  // ── Q/K (매트별도) ──
  {
    id: "r-a01",
    userName: "je*****",
    rating: 5,
    date: "2026.05.30",
    variant: "Q/K (매트별도)",
    content: "리모컨 하나로 헤드 각도를 조절할 수 있어서 정말 편해요. 책 읽을 때 딱 맞는 각도로 맞추고, 잘 때는 평평하게 내리면 되니까 너무 좋아요. 패브릭 헤드보드가 생각보다 훨씬 고급스럽고 포근해서 기대서 있으면 호텔 느낌 납니다.",
    images: ["/images/reviews/1010120020/review-01-1.webp", "/images/reviews/1010120020/review-01-2.webp"],
  },
  {
    id: "r-a02",
    userName: "hs*****",
    rating: 5,
    date: "2026.05.18",
    variant: "Q/K (매트별도)",
    content: "모터 소리가 거의 안 나요. 이전에 쓰던 전동침대는 소음이 있었는데 룬소프트는 부드럽고 조용하게 움직여서 밤에 각도 바꿔도 옆 사람이 안 깨요. 설치도 꼼꼼하게 해주셨고 작동 방법도 상세히 설명해주셨어요.",
  },
  {
    id: "r-a03",
    userName: "lk*****",
    rating: 5,
    date: "2026.05.05",
    variant: "Q/K (매트별도)",
    content: "헤드보드 패브릭 색상이 실물이 사진보다 훨씬 따뜻하고 예뻐요. 방 인테리어가 확 달라진 느낌입니다. 기존 매트리스랑 높이도 잘 맞고 전체적인 완성도가 높아요.",
    images: ["/images/reviews/1010120020/review-03-1.webp"],
  },
  {
    id: "r-a04",
    userName: "pm*****",
    rating: 4,
    date: "2026.04.22",
    variant: "Q/K (매트별도)",
    content: "사전판매라 배송 대기가 길었는데 받고 나니 만족해요. 리모컨 조작이 직관적이고 각도 조절 범위도 충분합니다. 별 하나는 배송 기다린 시간 때문에 빼요.",
  },
  {
    id: "r-a05",
    userName: "rj*****",
    rating: 5,
    date: "2026.04.10",
    variant: "Q/K (매트별도)",
    content: "뒤척임 때문에 서로 잠을 못자서 새로 맞췄는데 확실히 효과가 있어요. 두 개를 따로 놓으니 수면의 질이 좋아졌어요. 패브릭 질감도 부드럽고 청소도 쉽게 할 수 있어서 만족합니다.",
    images: ["/images/reviews/1010120020/review-05-1.webp"],
  },
  {
    id: "r-a06",
    userName: "nw*****",
    rating: 5,
    date: "2026.06.10",
    variant: "Q/K (매트별도)",
    content: "킹 사이즈로 선택했는데 방 크기에 딱 맞아요. 헤드보드가 넓어서 침실 포인트가 되고 분위기도 고급스러워요.",
  },
  {
    id: "r-a07",
    userName: "ot*****",
    rating: 5,
    date: "2026.06.05",
    variant: "Q/K (매트별도)",
    content: "리모컨 버튼이 단순하고 직관적이에요. 부모님도 쉽게 사용하실 수 있을 것 같아요. 모터 소음도 거의 없고 부드럽게 올라가고 내려와요.",
    images: ["/images/reviews/1010120020/review-07-1.webp"],
  },
  {
    id: "r-a08",
    userName: "cb*****",
    rating: 4,
    date: "2026.05.28",
    variant: "Q/K (매트별도)",
    content: "제품 자체는 정말 좋아요. 다만 배송 날짜 조율이 한 번 바뀌어서 조금 불편했어요. 설치 후 만족도는 100%입니다.",
  },
  {
    id: "r-a09",
    userName: "ml*****",
    rating: 5,
    date: "2026.05.22",
    variant: "Q/K (매트별도)",
    content: "패브릭 헤드보드에 등 기대고 독서하면 정말 편해요. 쿠션감이 딱 적당해서 오래 기대도 불편하지 않습니다. 퀸 사이즈 선택했는데 침실 크기에 딱 맞아요.",
  },
  {
    id: "r-a10",
    userName: "yd*****",
    rating: 5,
    date: "2026.05.15",
    variant: "Q/K (매트별도)",
    content: "신혼 첫 침대로 룬소프트 선택했는데 정말 잘한 것 같아요. 호텔 느낌 물씬 나고 리모컨 기능도 편리해서 매일 만족하며 사용하고 있어요.",
  },
  // ── KK (매트별도) ──
  {
    id: "r-b01",
    userName: "aw*****",
    rating: 5,
    date: "2026.06.02",
    variant: "KK (매트별도)",
    content: "KK 사이즈로 구매했는데 방이 완전히 호텔처럼 변했어요. 패브릭 헤드보드가 워낙 크고 포근해 보여서 방 전체 분위기가 달라집니다. 리모컨으로 각도 조절하는 기능도 매일 쓰고 있어요.",
    images: ["/images/reviews/1010120021/review-01-1.webp", "/images/reviews/1010120021/review-01-2.webp"],
  },
  {
    id: "r-b02",
    userName: "if*****",
    rating: 5,
    date: "2026.05.25",
    variant: "KK (매트별도)",
    content: "허리가 안 좋아서 헤드 각도 살짝 올려서 자고 있는데 훨씬 편해졌어요. 모터가 조용하게 작동하고 리모컨도 간단해서 어르신들도 쉽게 쓸 수 있을 것 같아요.",
  },
  {
    id: "r-b03",
    userName: "sw*****",
    rating: 5,
    date: "2026.05.12",
    variant: "KK (매트별도)",
    content: "KK 사이즈라 두 명이 자도 여유롭고 각자 각도를 다르게 설정할 수 있어서 좋아요. 설치 기사분이 작동 방법을 친절하게 안내해주셔서 바로 쓸 수 있었어요.",
    images: ["/images/reviews/1010120021/review-03-1.webp"],
  },
  {
    id: "r-b04",
    userName: "vy*****",
    rating: 4,
    date: "2026.04.28",
    variant: "KK (매트별도)",
    content: "사전판매 기다림이 있었지만 받고 나니 기다린 보람이 있어요. 패브릭 헤드보드 완성도가 정말 높고 리모컨 조작도 부드러워요. 별 하나는 배송 대기 기간 때문입니다.",
  },
  {
    id: "r-b05",
    userName: "gh*****",
    rating: 5,
    date: "2026.04.15",
    variant: "KK (매트별도)",
    content: "친정 부모님 선물로 구입했어요. 연세가 있으시다 보니 각도 조절 침대를 찾고 있었는데 딱이에요. 리모컨이 심플해서 부모님도 편하게 쓰신다고 해요. 설치팀도 친절했습니다.",
    images: ["/images/reviews/1010120021/review-05-1.webp"],
  },
  {
    id: "r-b06",
    userName: "pf*****",
    rating: 5,
    date: "2026.06.12",
    variant: "KK (매트별도)",
    content: "KK 사이즈 헤드보드 존재감이 어마어마해요. 방이 완전히 프리미엄 호텔 수준으로 바뀌었어요. 기존 매트리스와도 높이가 잘 맞아요.",
  },
  {
    id: "r-b07",
    userName: "tm*****",
    rating: 5,
    date: "2026.06.07",
    variant: "KK (매트별도)",
    content: "모터 소음이 없다시피 해요. 자다가 각도 올리거나 내려도 옆 사람이 전혀 안 깨요. 패브릭 소재도 부드럽고 고급스럽습니다.",
    images: ["/images/reviews/1010120021/review-07-1.webp"],
  },
  {
    id: "r-b08",
    userName: "ev*****",
    rating: 4,
    date: "2026.05.31",
    variant: "KK (매트별도)",
    content: "제품 품질은 정말 좋아요. 설치 일정이 한 번 연기됐던 점만 아쉬웠고 받고 난 이후로는 100% 만족입니다.",
  },
  {
    id: "r-b09",
    userName: "ku*****",
    rating: 5,
    date: "2026.05.20",
    variant: "KK (매트별도)",
    content: "TV 보면서 헤드 각도 올려두면 목이 안 아파요. 이전엔 베개 여러 개 쌓았는데 이제는 리모컨 하나면 끝이에요. 일상이 바뀐 것 같아요.",
    images: ["/images/reviews/1010120021/review-09-1.webp"],
  },
  {
    id: "r-b10",
    userName: "az*****",
    rating: 5,
    date: "2026.05.08",
    variant: "KK (매트별도)",
    content: "한샘 제품 신뢰하고 구매했는데 역시 기대 이상이에요. 마감도 꼼꼼하고 패브릭 헤드보드 퀄리티가 정말 좋습니다. 침실이 완전히 달라졌어요.",
  },
];

export const sharedReviews: ReviewData = {
  ...calculateReviewSummary(reviewItems),
  items: reviewItems,
};

export const sharedQnaItems: QnaItem[] = [
  // ── Q/K (매트별도) ──
  {
    id: "q-a01",
    category: "상품",
    question: "리모컨으로 헤드 각도만 조절되나요, 풋 부분도 조절이 가능한가요?",
    questioner: "bh*****",
    date: "2026.05.28",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 룬소프트 리모컨형은 헤드보드 상단 각도 조절 기능을 제공합니다. 풋(발쪽) 부분의 각도 조절은 해당 모델에서는 지원되지 않습니다. 추가로 궁금한 점이 있으시면 고객센터(1688-4945)로 문의해 주세요.",
    answerDate: "2026.05.29",
  },
  {
    id: "q-a02",
    category: "상품",
    question: "기존에 사용하던 매트리스를 그대로 사용할 수 있나요? 맞는 사이즈 규격이 궁금합니다.",
    questioner: "rl*****",
    date: "2026.05.15",
    answered: true,
    answer: "안녕하세요, 한샘입니다. Q/K 사이즈는 퀸(1600×2000mm) 또는 킹(1800×2000mm) 매트리스를 사용할 수 있습니다. 주문 시 원하시는 사이즈를 선택해 주세요. 기존 보유 매트리스 규격이 위 치수에 맞는 경우 그대로 사용 가능합니다.",
    answerDate: "2026.05.16",
  },
  {
    id: "q-a03",
    category: "배송",
    question: "전동침대인데 설치 시 전기 콘센트가 가까이 있어야 하나요?",
    questioner: "oc*****",
    date: "2026.05.08",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 리모컨형 전동 기능 작동을 위해 침대 근처에 콘센트가 있어야 합니다. 전선 길이는 약 1.8m로, 침대 설치 위치와 콘센트 간 거리를 미리 확인해 주시기 바랍니다. 설치팀 방문 시 코드 정리까지 도와드립니다.",
    answerDate: "2026.05.09",
  },
  // ── KK (매트별도) ──
  {
    id: "q-b01",
    category: "상품",
    question: "KK 사이즈 기준 헤드보드 전체 폭이 어떻게 되나요? 방 배치를 미리 계획하고 싶습니다.",
    questioner: "jb*****",
    date: "2026.05.26",
    answered: true,
    answer: "안녕하세요, 한샘입니다. KK 사이즈 기준 침대 전체 폭은 약 2120mm, 길이는 약 2200mm, 헤드보드 높이는 약 1050mm입니다. 정확한 치수는 상품 상세 페이지 사이즈 탭에서 확인하실 수 있습니다.",
    answerDate: "2026.05.27",
  },
  {
    id: "q-b02",
    category: "상품",
    question: "패브릭 커버 세탁이나 교체가 가능한가요?",
    questioner: "sy*****",
    date: "2026.05.14",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 헤드보드 패브릭 커버는 탈부착이 어렵게 설계되어 있어 직접 세탁은 권장드리지 않습니다. 오염 시 중성세제를 희석한 물로 부드럽게 닦아내시는 것을 권장합니다. 심한 오염이나 손상의 경우 고객센터(1688-4945)를 통해 A/S를 요청해 주세요.",
    answerDate: "2026.05.15",
  },
  {
    id: "q-b03",
    category: "기타",
    question: "리모컨을 분실했을 경우 별도 구매가 가능한가요?",
    questioner: "np*****",
    date: "2026.06.05",
    answered: false,
  },
];
