import type { ReviewData, QnaItem, Review } from "@/app/lib/types";
import { calculateReviewSummary } from "@/lib/reviews";

const reviewItems: Review[] = [
  {
    id: "r-a01",
    userName: "sy*****",
    rating: 5,
    date: "2026.07.05",
    variant: "기본",
    content: "플라스틱 건조대 쓰다가 바꿨는데 관리가 훨씬 편해요. 물때가 껴도 쓱 닦으면 새것처럼 돌아옵니다.",
    images: ["/images/reviews/1711120010/review-01-1.webp"],
  },
  {
    id: "r-a02",
    userName: "km*****",
    rating: 5,
    date: "2026.06.27",
    variant: "기본",
    content: "2단이라 4인 가족 설거지가 한 번에 다 올라가요. 싱크대 위가 정리되니 주방이 넓어 보입니다.",
    images: ["/images/reviews/1711120010/review-02-1.webp", "/images/reviews/1711120010/review-02-2.webp"],
  },
  {
    id: "r-a03",
    userName: "jd*****",
    rating: 4,
    date: "2026.06.19",
    variant: "기본",
    content: "튼튼하고 마감도 깔끔한데 조립할 때 나사 조이는 게 살짝 뻑뻑했어요. 완성하고 나니 흔들림 없이 아주 만족합니다.",
  },
  {
    id: "r-a04",
    userName: "wn*****",
    rating: 5,
    date: "2026.06.10",
    variant: "기본",
    content: "물받이를 통째로 빼서 비울 수 있는 게 제일 편해요. 스텐이라 뜨거운 물 소독도 부담 없이 합니다.",
  },
  {
    id: "r-a05",
    userName: "he*****",
    rating: 5,
    date: "2026.06.01",
    variant: "기본",
    content: "반년 넘게 쓴 지인 추천으로 샀는데 녹 하나 없이 그대로라고 해요. 컵걸이랑 수저통까지 구성이 알찹니다.",
  },
  {
    id: "r-a06",
    userName: "bu*****",
    rating: 3,
    date: "2026.05.23",
    variant: "기본",
    content: "품질은 좋은데 배송 중 박스 모서리가 찌그러져 왔고 프레임에 미세한 스크래치가 있었어요. 사용에는 지장이 없어 그냥 씁니다.",
  },
  {
    id: "r-a07",
    userName: "ls*****",
    rating: 5,
    date: "2026.05.14",
    variant: "기본",
    content: "신혼집 주방에 들였는데 인테리어를 해치지 않는 깔끔한 디자인이에요. 접시 꽂는 간격도 넉넉해서 큰 접시도 잘 들어갑니다.",
    images: ["/images/reviews/1711120010/review-07-1.webp"],
  },
  {
    id: "r-a08",
    userName: "gn*****",
    rating: 4,
    date: "2026.05.05",
    variant: "기본",
    content: "만듦새는 값어치를 하는데 하단 컵 자리가 조금 더 많았으면 좋겠어요. 그 외에는 흠잡을 데가 없습니다.",
  },
  {
    id: "r-a09",
    userName: "td*****",
    rating: 5,
    date: "2026.04.26",
    variant: "기본",
    content: "저가 건조대 두 번 버리고 나서야 정착했어요. 무게감이 있어서 그릇을 많이 올려도 기울지 않습니다.",
  },
  {
    id: "r-a10",
    userName: "mv*****",
    rating: 5,
    date: "2026.04.17",
    variant: "기본",
    content: "설거지 후 물기가 트레이로만 떨어지니 싱크대 주변이 항상 뽀송해요. 위생 때문에 스트레스받던 게 사라졌습니다.",
  },
  {
    id: "r-a11",
    userName: "cp*****",
    rating: 4,
    date: "2026.04.08",
    variant: "기본",
    content: "생각보다 사이즈가 커서 저희 싱크대엔 꽉 차게 들어갔어요. 구매 전에 치수 확인은 꼭 하시길. 제품 자체는 튼튼합니다.",
  },
  {
    id: "r-a12",
    userName: "ez*****",
    rating: 5,
    date: "2026.03.30",
    variant: "기본",
    content: "부모님 댁 주방 정리하면서 선물했는데 매일 잘 쓰고 계세요. 스텐이라 오래 쓸 생각하면 가격이 아깝지 않습니다.",
  },
];

export const sharedReviews: ReviewData = {
  ...calculateReviewSummary(reviewItems),
  items: reviewItems,
};

export const sharedQnaItems: QnaItem[] = [
  {
    id: "q-a01",
    category: "상품",
    question: "싱크대 폭이 60cm인데 설치 가능한 사이즈인가요?",
    questioner: "or*****",
    date: "2026.06.15",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 본 제품의 가로 폭은 56cm로 60cm 싱크대 위에 설치 가능합니다. 상세 페이지 사이즈 안내의 상세 치수를 함께 확인 부탁드립니다. 감사합니다.",
    answerDate: "2026.06.16",
  },
  {
    id: "q-a02",
    category: "상품",
    question: "조립이 어려운 편인가요? 여자 혼자서도 가능할까요?",
    questioner: "dh*****",
    date: "2026.05.28",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 동봉된 육각렌치로 프레임을 결합하는 단순 조립 방식으로, 통상 15~20분 내 혼자서 조립 가능합니다. 동봉된 설명서를 참고 부탁드립니다. 감사합니다.",
    answerDate: "2026.05.29",
  },
  {
    id: "q-a03",
    category: "배송",
    question: "재입고 알림 신청은 어디서 하나요? 지금 품절로 나옵니다.",
    questioner: "wb*****",
    date: "2026.07.06",
    answered: false,
  },
];
