import type { ReviewData, QnaItem, Review } from "@/app/lib/types";
import { calculateReviewSummary } from "@/lib/reviews";

const reviewItems: Review[] = [
  // ── 일반형 (a) ──
  {
    id: "r-a01",
    userName: "ks*****",
    rating: 5,
    date: "2026.06.18",
    variant: "SS 일반형",
    content: "아이와 함께 자려고 구매했어요. SS 사이즈가 생각보다 훨씬 넓어서 셋이 자도 여유 있을 것 같아요. 패브릭 헤드보드가 부드럽고 등 기대기도 편합니다. 설치팀이 꼼꼼하게 해주셔서 좋았어요.",
    images: ["/images/reviews/1010140010/review-01-1.webp", "/images/reviews/1010140010/review-01-2.webp"],
  },
  {
    id: "r-a02",
    userName: "lm*****",
    rating: 5,
    date: "2026.06.10",
    variant: "SS 일반형",
    content: "패밀리침대 찾다가 한샘 스테디 컴피로 결정했어요. 디자인이 깔끔하고 헤드보드 패브릭 소감이 정말 좋아요. 아이가 너무 좋아해서 기분 좋게 잘 사용하고 있습니다.",
  },
  {
    id: "r-a03",
    userName: "pk*****",
    rating: 5,
    date: "2026.06.03",
    variant: "SS 일반형",
    content: "일반형은 헤드보드가 심플해서 인테리어에 잘 녹아들어요. 아이와 같이 자기 시작했는데 침대 너비가 충분해서 불편함이 없어요.",
    images: ["/images/reviews/1010140010/review-03-1.webp"],
  },
  {
    id: "r-a04",
    userName: "jh*****",
    rating: 4,
    date: "2026.05.28",
    variant: "SS 일반형",
    content: "제품 자체는 정말 만족스러워요. 배송이 예정일보다 약 열흘 늦어져서 아쉬웠지만, 설치 후엔 퀄리티에 만족합니다. LPM 프레임이 지문도 잘 안 묻어요.",
  },
  {
    id: "r-a05",
    userName: "sy*****",
    rating: 5,
    date: "2026.05.21",
    variant: "SS 일반형",
    content: "5살짜리 아이가 밤에 자꾸 부모 침대로 오는데, 이참에 패밀리침대로 바꿨어요. 넓어서 온 가족이 불편함 없이 잘 수 있어 너무 만족해요.",
    images: ["/images/reviews/1010140010/review-05-1.webp"],
  },
  {
    id: "r-a06",
    userName: "ch*****",
    rating: 5,
    date: "2026.05.14",
    variant: "SS 일반형",
    content: "헤드보드 패브릭이 정말 보드라워요. 아이도 기대는 걸 좋아하고 저도 등 기대고 책 읽기 딱 좋아요. 일반형 선택한 게 후회 없어요.",
    images: ["/images/reviews/1010140010/review-06-1.webp"],
  },
  {
    id: "r-a07",
    userName: "ho*****",
    rating: 5,
    date: "2026.05.07",
    variant: "SS 일반형",
    content: "LPM 프레임 마감이 깔끔하고 스크래치에 강한 것 같아요. 아이가 올라오고 내려오기도 딱 좋은 높이예요.",
  },
  {
    id: "r-a08",
    userName: "ns*****",
    rating: 4,
    date: "2026.04.30",
    variant: "SS 일반형",
    content: "가격 대비 퀄리티가 좋아요. 배송팀이 설치 전 미리 연락 주셔서 일정 맞추기 편했어요. 만족하며 사용 중입니다.",
  },
  {
    id: "r-a09",
    userName: "bw*****",
    rating: 5,
    date: "2026.04.22",
    variant: "SS 일반형",
    content: "이사하면서 패밀리침대로 교체했는데 잘한 것 같아요. 아이도 넓어서 좋아하고, 저도 여유 있게 잘 수 있어요.",
  },
  {
    id: "r-a10",
    userName: "ry*****",
    rating: 3,
    date: "2026.04.15",
    variant: "SS 일반형",
    content: "제품 자체는 나쁘지 않은데 패브릭 헤드보드에 먼지가 좀 타는 편이에요. 주기적으로 청소해주면 괜찮긴 한데 관리가 약간 번거로워요.",
  },
  {
    id: "r-a11",
    userName: "jy*****",
    rating: 5,
    date: "2026.04.08",
    variant: "SS 일반형",
    content: "신혼집에 들이자마자 아이가 태어나서 같이 쓰게 됐는데 딱 맞는 선택이었어요. 넓고 안전하고 예뻐요.",
  },
  // ── 와이드헤드형 (b) ──
  {
    id: "r-b01",
    userName: "mj*****",
    rating: 5,
    date: "2026.06.20",
    variant: "SS 와이드헤드형",
    content: "와이드헤드형 선택했어요. 헤드보드가 넓고 쿠션감이 좋아서 아이와 나란히 앉아서 영상 보기 딱 좋아요. 아이가 헤드보드에 기대는 걸 너무 좋아해요.",
  },
  {
    id: "r-b02",
    userName: "oj*****",
    rating: 5,
    date: "2026.06.12",
    variant: "SS 와이드헤드형",
    content: "헤드보드 높이가 충분해서 등 기댈 때 정말 편안해요. 아이랑 침대에서 그림책 읽는 시간이 더 좋아졌어요.",
  },
  {
    id: "r-b03",
    userName: "ah*****",
    rating: 5,
    date: "2026.06.05",
    variant: "SS 와이드헤드형",
    content: "와이드헤드형이라 헤드보드 면적이 커서 아이도 같이 기댈 수 있어요. 패브릭 감촉이 정말 부드럽고 세련돼 보여서 만족합니다.",
  },
  {
    id: "r-b04",
    userName: "sp*****",
    rating: 4,
    date: "2026.05.29",
    variant: "SS 와이드헤드형",
    content: "헤드보드가 풍성해서 인테리어 포인트가 되네요. 조금 비싸지만 그만큼 만족도가 높아요. 배송도 예정일에 딱 맞게 왔어요.",
  },
  {
    id: "r-b05",
    userName: "ew*****",
    rating: 5,
    date: "2026.05.22",
    variant: "SS 와이드헤드형",
    content: "사전판매라 좀 기다렸는데 도착하고 나서 정말 잘 샀다 싶었어요. 헤드보드 넓은 게 확실히 달라요. 아이도 자기 침대라고 너무 좋아해요.",
  },
  {
    id: "r-b06",
    userName: "nk*****",
    rating: 5,
    date: "2026.05.15",
    variant: "SS 와이드헤드형",
    content: "와이드헤드 패브릭이 집의 분위기를 한층 업그레이드해줬어요. 아이와 함께 쓰기에도 충분한 너비고 안전해서 마음이 편해요.",
  },
  {
    id: "r-b07",
    userName: "tm*****",
    rating: 5,
    date: "2026.05.08",
    variant: "SS 와이드헤드형",
    content: "설치팀이 너무 친절하고 꼼꼼하게 설치해주셨어요. 헤드보드가 넓고 쿠션감이 있어서 아이가 기대도 전혀 불편하지 않아요.",
  },
  {
    id: "r-b08",
    userName: "pg*****",
    rating: 3,
    date: "2026.05.01",
    variant: "SS 와이드헤드형",
    content: "헤드보드 자체는 좋은데 패브릭 색이 사진보다 조금 어두운 편이에요. 그래도 품질은 만족스럽고 아이도 잘 쓰고 있어요.",
  },
  {
    id: "r-b09",
    userName: "cr*****",
    rating: 5,
    date: "2026.04.24",
    variant: "SS 와이드헤드형",
    content: "헤드보드가 넓고 높아서 전반적으로 고급스러워 보여요. 방 전체 인테리어 분위기가 달라진 느낌이에요.",
  },
  {
    id: "r-b10",
    userName: "dj*****",
    rating: 4,
    date: "2026.04.17",
    variant: "SS 와이드헤드형",
    content: "퀄리티는 좋아요. 사전판매 대기가 길었지만 받고 나니 기다린 보람이 있어요. 헤드보드 기댈 때 정말 편합니다.",
  },
  {
    id: "r-b11",
    userName: "ls*****",
    rating: 5,
    date: "2026.04.10",
    variant: "SS 와이드헤드형",
    content: "아이와 함께 자는 용도로 샀는데 너무 만족해요. 와이드헤드 덕분에 등 기대고 책 읽어주기 딱 좋아요.",
  },
  // ── 가드형 (c) ──
  {
    id: "r-c01",
    userName: "hy*****",
    rating: 5,
    date: "2026.06.22",
    variant: "SS 가드형",
    content: "24개월 아이와 함께 자려고 가드형 선택했어요. 가드가 있어서 아이가 자다가 떨어질 걱정이 없어졌어요. 접이식이라 필요할 때만 펼 수 있어서 편리해요. 정말 잘 샀어요.",
    images: ["/images/reviews/1010140012/review-01-1.webp"],
  },
  {
    id: "r-c02",
    userName: "sw*****",
    rating: 5,
    date: "2026.06.15",
    variant: "SS 가드형",
    content: "가드가 튼튼하게 고정되어서 아이가 발로 차도 흔들리지 않아요. 아이 안전 때문에 고민하셨다면 가드형 강력 추천드려요.",
  },
  {
    id: "r-c03",
    userName: "kp*****",
    rating: 5,
    date: "2026.06.08",
    variant: "SS 가드형",
    content: "가드 접는 게 정말 간단해요. 아이 재운 뒤에 접어두면 공간이 넓게 쓰여요. 설치팀도 친절하게 설치해주셨습니다.",
    images: ["/images/reviews/1010140012/review-03-1.webp"],
  },
  {
    id: "r-c04",
    userName: "im*****",
    rating: 4,
    date: "2026.06.01",
    variant: "SS 가드형",
    content: "가드 기능이 확실히 안심이 돼요. 아이가 가끔 뒤척이다 침대 끝까지 가는데 가드가 막아줘서 마음이 놓여요. 사전판매 대기가 좀 길었던 게 아쉬워요.",
  },
  {
    id: "r-c05",
    userName: "jl*****",
    rating: 5,
    date: "2026.05.25",
    variant: "SS 가드형",
    content: "3살 아이와 함께 쓰려고 가드형 샀어요. 가드 덕분에 마음 놓고 같이 잘 수 있어요. 패브릭 헤드보드도 아이가 기대도 안전하게 느껴져요.",
    images: ["/images/reviews/1010140012/review-05-1.webp"],
  },
  {
    id: "r-c06",
    userName: "bu*****",
    rating: 5,
    date: "2026.05.18",
    variant: "SS 가드형",
    content: "접이식 가드가 생각보다 훨씬 편리해요. 아이 재울 때는 올려두고, 어른만 있을 때는 내려두면 되니까요. 디자인도 깔끔하고 좋아요.",
  },
  {
    id: "r-c07",
    userName: "ts*****",
    rating: 5,
    date: "2026.05.11",
    variant: "SS 가드형",
    content: "가드 너비가 충분해서 아이가 자다 옆으로 굴러도 안전하게 막아줘요. SS 사이즈도 넓어서 부모와 아이가 함께 자기 딱 좋아요.",
    images: ["/images/reviews/1010140012/review-07-1.webp"],
  },
  {
    id: "r-c08",
    userName: "ay*****",
    rating: 4,
    date: "2026.05.04",
    variant: "SS 가드형",
    content: "가드 자체는 정말 만족스러워요. 프레임 조립이 처음엔 복잡해 보였는데 설치팀이 알아서 다 해주셔서 편했어요.",
  },
  {
    id: "r-c09",
    userName: "rj*****",
    rating: 5,
    date: "2026.04.27",
    variant: "SS 가드형",
    content: "아이 낙상 걱정 없이 잘 수 있어서 정말 안심돼요. 가드가 견고하고 LPM 프레임 마감도 깔끔해서 오래 쓸 것 같아요.",
    images: ["/images/reviews/1010140012/review-09-1.webp"],
  },
  {
    id: "r-c10",
    userName: "hj*****",
    rating: 5,
    date: "2026.04.20",
    variant: "SS 가드형",
    content: "아이 두 명이랑 같이 자는데 SS 사이즈가 딱 맞아요. 가드형이라 안전하고 아이들도 자기 공간이 생겨서 좋아해요.",
  },
];

export const sharedReviews: ReviewData = {
  ...calculateReviewSummary(reviewItems),
  items: reviewItems,
};

export const sharedQnaItems: QnaItem[] = [
  {
    id: "q-a01",
    category: "상품",
    question: "가드형의 가드는 완전히 분리도 되나요? 아이가 크면 가드 없이도 쓰고 싶어서요.",
    questioner: "kn*****",
    date: "2026.06.05",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 가드형의 사이드 가드는 접이식으로 제작되어 필요 시 완전히 접어서 눕힐 수 있습니다. 분리는 되지 않으나 접었을 때 침대 사용에 불편함이 없도록 설계되어 있으며, 아이가 성장한 후에도 그대로 사용하실 수 있습니다.",
    answerDate: "2026.06.06",
  },
  {
    id: "q-a02",
    category: "상품",
    question: "세 가지 타입(일반형/와이드헤드형/가드형) 중 헤드보드 높이가 제일 낮은 게 어떤 건가요?",
    questioner: "jw*****",
    date: "2026.05.28",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 헤드보드 높이는 일반형이 가장 낮으며, 와이드헤드형은 면적과 높이가 더 크게 설계되어 있습니다. 가드형은 일반형과 동일한 헤드보드에 사이드 가드가 추가된 구성입니다. 정확한 치수는 상품 상세 페이지의 사이즈 탭을 참고해 주세요.",
    answerDate: "2026.05.29",
  },
  {
    id: "q-a03",
    category: "배송",
    question: "사전판매 상품인데 대략 몇 주나 기다려야 하나요? 이사 일정이 있어서요.",
    questioner: "bh*****",
    date: "2026.05.15",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 주문 순서에 따라 3~4주 내 순차 배송이 진행됩니다. 배송 3~5일 전 담당 배송팀에서 사전 연락을 드리며, 이사 일정이 있으신 분들은 고객센터(1688-4945)에 날짜를 미리 알려주시면 최대한 맞춰 드리겠습니다.",
    answerDate: "2026.05.16",
  },
  {
    id: "q-a04",
    category: "상품",
    question: "매트리스는 어떤 규격을 사용해야 하나요? SS 사이즈 기준 치수가 궁금합니다.",
    questioner: "ys*****",
    date: "2026.05.08",
    answered: true,
    answer: "안녕하세요, 한샘입니다. SS(슈퍼싱글) 사이즈 기준 매트리스 권장 규격은 1100×2000mm입니다. 시중 SS 규격 매트리스라면 대부분 호환되나, 구매 전 정확한 내부 프레임 치수를 상세 페이지 사이즈 탭에서 확인해 주시기 바랍니다.",
    answerDate: "2026.05.09",
  },
  {
    id: "q-a05",
    category: "기타",
    question: "패브릭 헤드보드 세탁이나 커버 교체가 가능한가요?",
    questioner: "ep*****",
    date: "2026.06.10",
    answered: false,
  },
];
