import type { ReviewData, QnaItem, Review } from "@/app/lib/types";
import { calculateReviewSummary } from "@/lib/reviews";

const reviewItems: Review[] = [
  {
    id: "r-a01",
    userName: "je*****",
    rating: 5,
    date: "2026.07.07",
    variant: "테이블+플로어",
    content: "불 켜는 순간 거실이 갤러리가 돼요. 글라스 컬러가 벽에 은은하게 번지는데 매일 봐도 질리지 않습니다.",
    images: ["/images/reviews/1713100010/review-01-1.webp", "/images/reviews/1713100010/review-01-2.webp"],
  },
  {
    id: "r-a02",
    userName: "sk*****",
    rating: 5,
    date: "2026.06.29",
    variant: "테이블+플로어",
    content: "60만원대 정가가 부담스러웠는데 할인가에 세트로 들여서 너무 만족해요. 낮에 꺼두어도 오브제 역할을 톡톡히 합니다.",
  },
  {
    id: "r-a03",
    userName: "mo*****",
    rating: 5,
    date: "2026.06.21",
    variant: "테이블+플로어",
    content: "신혼집 거실 포인트로 샀는데 집들이마다 제일 먼저 칭찬받는 아이템이에요. 수공예라 그런지 디테일이 정말 섬세합니다.",
    images: ["/images/reviews/1713100010/review-03-1.webp"],
  },
  {
    id: "r-a04",
    userName: "dh*****",
    rating: 5,
    date: "2026.06.13",
    variant: "테이블+플로어",
    content: "플로어는 소파 옆, 테이블은 침실 협탁에 두고 씁니다. 같은 무늬라 떨어져 있어도 공간이 이어져 보여요.",
  },
  {
    id: "r-a05",
    userName: "yr*****",
    rating: 5,
    date: "2026.06.05",
    variant: "테이블+플로어",
    content: "저녁에 메인 등 끄고 이것만 켜면 분위기가 완성돼요. 와인 한잔이 어울리는 거실이 됐습니다.",
  },
  {
    id: "r-a06",
    userName: "wp*****",
    rating: 4,
    date: "2026.05.28",
    variant: "테이블+플로어",
    content: "제품은 예술인데 배송 포장 뜯을 때 긴장했어요. 다행히 이상 없었지만 완충재 확인은 꼭 하세요.",
  },
  {
    id: "r-a07",
    userName: "cb*****",
    rating: 5,
    date: "2026.05.20",
    variant: "테이블+플로어",
    content: "빛이 유리를 통과하면서 만드는 색 그림자가 예술이에요. 전구 색만 바꿔도 완전히 다른 느낌이 납니다.",
    images: ["/images/reviews/1713100010/review-07-1.webp"],
  },
  {
    id: "r-a08",
    userName: "hg*****",
    rating: 5,
    date: "2026.05.12",
    variant: "테이블+플로어",
    content: "부모님 결혼기념일 선물로 드렸는데 어머니가 감동하셨어요. 클래식한 거실에 정말 잘 어울립니다.",
  },
  {
    id: "r-a09",
    userName: "tu*****",
    rating: 5,
    date: "2026.05.04",
    variant: "테이블+플로어",
    content: "주물 베이스가 묵직해서 반려묘가 스쳐도 흔들림이 없어요. 유리 제품 걱정했는데 안정감이 좋습니다.",
  },
  {
    id: "r-a10",
    userName: "ln*****",
    rating: 5,
    date: "2026.04.26",
    variant: "테이블+플로어",
    content: "수작업 제품이라 하나하나 무늬가 다르다는데 저희 집 것은 특히 색 조합이 예쁘게 나온 것 같아요. 소장 가치가 있습니다.",
  },
  {
    id: "r-a11",
    userName: "bf*****",
    rating: 5,
    date: "2026.04.18",
    variant: "테이블+플로어",
    content: "호텔 스위트룸에서 봤던 무드를 집에 들였어요. 세트라 따로 맞출 고민이 없는 것도 장점입니다.",
    images: ["/images/reviews/1713100010/review-11-1.webp"],
  },
  {
    id: "r-a12",
    userName: "ku*****",
    rating: 5,
    date: "2026.04.10",
    variant: "테이블+플로어",
    content: "거실 인테리어 마지막 퍼즐이었는데 이걸로 완성됐습니다. 1위 상품이라는 게 납득되는 퀄리티예요.",
  },
  {
    id: "r-a13",
    userName: "vr*****",
    rating: 5,
    date: "2026.04.02",
    variant: "테이블+플로어",
    content: "밤에 은은하게 켜두면 아이가 무서워하지 않고 잘 자요. 수유등 대용으로도 뜻밖에 활약 중입니다.",
  },
  {
    id: "r-a14",
    userName: "np*****",
    rating: 5,
    date: "2026.03.25",
    variant: "테이블+플로어",
    content: "설치라고 할 것도 없이 꺼내서 전구만 끼우면 끝이에요. 배송도 이틀 만에 와서 놀랐습니다.",
  },
  {
    id: "r-a15",
    userName: "ei*****",
    rating: 4,
    date: "2026.03.17",
    variant: "테이블+플로어",
    content: "빛 컬러와 무드는 최고인데 먼지 닦기가 조금 번거로워요. 그래도 이 아름다움이면 감수할 만합니다.",
  },
  {
    id: "r-a16",
    userName: "qh*****",
    rating: 5,
    date: "2026.03.09",
    variant: "테이블+플로어",
    content: "서재 분위기를 바꾸고 싶어 플로어만 서재에 두었는데 독서 시간이 늘었어요. 빛이 눈에 부담스럽지 않습니다.",
  },
  {
    id: "r-a17",
    userName: "zc*****",
    rating: 5,
    date: "2026.03.01",
    variant: "테이블+플로어",
    content: "SNS에서 보고 반신반의하며 샀는데 실물이 훨씬 좋아요. 사진으로는 이 빛을 다 담을 수 없습니다.",
  },
  {
    id: "r-a18",
    userName: "xf*****",
    rating: 5,
    date: "2026.02.21",
    variant: "테이블+플로어",
    content: "겨울밤 이 램프 아래에서 보내는 시간이 하루의 낙이었어요. 계절이 바뀌어도 여전히 매일 켭니다.",
  },
  {
    id: "r-a19",
    userName: "ga*****",
    rating: 5,
    date: "2026.02.13",
    variant: "테이블+플로어",
    content: "친구 집에서 보고 바로 따라 샀어요. 두 집 무늬가 미묘하게 달라서 세상에 하나뿐인 조명이라는 말이 맞네요.",
  },
  {
    id: "r-a20",
    userName: "os*****",
    rating: 5,
    date: "2026.02.05",
    variant: "테이블+플로어",
    content: "화려한데 과하지 않은 그 경계를 잘 지킨 디자인이에요. 모던한 집에도 클래식한 집에도 어울릴 것 같습니다.",
  },
  {
    id: "r-a21",
    userName: "ud*****",
    rating: 5,
    date: "2026.01.28",
    variant: "테이블+플로어",
    content: "결혼 10주년 기념으로 저희 부부가 저희에게 준 선물이에요. 거실에서 보내는 저녁이 특별해졌습니다.",
  },
];

export const sharedReviews: ReviewData = {
  ...calculateReviewSummary(reviewItems),
  items: reviewItems,
};

export const sharedQnaItems: QnaItem[] = [
  {
    id: "q-a01",
    category: "상품",
    question: "전구가 포함되어 있나요? 규격이 어떻게 되는지 궁금합니다.",
    questioner: "hb*****",
    date: "2026.06.17",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 테이블·플로어 램프 모두 E26 규격 LED 전구가 기본 포함되어 배송됩니다. 색온도 변경을 원하시면 동일 규격의 시중 전구로 교체 가능합니다. 감사합니다.",
    answerDate: "2026.06.18",
  },
  {
    id: "q-a02",
    category: "상품",
    question: "테이블 램프만 단품으로 구매할 수는 없나요?",
    questioner: "ry*****",
    date: "2026.05.30",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 본 상품은 테이블+플로어 세트 구성으로만 판매되고 있습니다. 단품 구성 출시 시 상품 페이지를 통해 안내드리겠습니다. 감사합니다.",
    answerDate: "2026.05.31",
  },
  {
    id: "q-a03",
    category: "기타",
    question: "갓이 파손되면 부분 구매가 가능한가요?",
    questioner: "fw*****",
    date: "2026.07.05",
    answered: false,
  },
];
