import type { ReviewData, QnaItem, Review } from "@/app/lib/types";
import { calculateReviewSummary } from "@/lib/reviews";

const reviewItems: Review[] = [
  {
    id: "r-a01",
    userName: "sj*****",
    rating: 5,
    date: "2026.07.06",
    variant: "Q",
    content: "열대야에 냉감면으로 덮고 자는데 확실히 이불 속이 덜 후끈해요. 보들면도 부드러워서 에어컨 켜고 잘 때 딱 좋습니다.",
    images: ["/images/reviews/1710120010/review-01-1.webp", "/images/reviews/1710120010/review-01-2.webp"],
  },
  {
    id: "r-a02",
    userName: "mk*****",
    rating: 5,
    date: "2026.07.02",
    variant: "SS",
    content: "자취방 여름 이불로 샀는데 가볍고 세탁기에 그냥 돌려도 돼서 편해요. 냉감 원단이 생각보다 확실히 시원합니다.",
    images: ["/images/reviews/1710120010/review-02-1.webp"],
  },
  {
    id: "r-a03",
    userName: "yh*****",
    rating: 4,
    date: "2026.06.27",
    variant: "Q",
    content: "양면으로 골라 덮을 수 있는 게 제일 만족스러워요. 다만 베개커버가 살짝 얇은 느낌이라 별 하나 뺐습니다.",
  },
  {
    id: "r-a04",
    userName: "eb*****",
    rating: 5,
    date: "2026.06.21",
    variant: "Q",
    content: "색감이 화면보다 차분하고 고급스러워요. 여름 내내 이거 하나로 버틸 수 있을 것 같아 색 추가 구매 고민 중입니다.",
    images: ["/images/reviews/1710120010/review-04-1.webp"],
  },
  {
    id: "r-a05",
    userName: "wj*****",
    rating: 5,
    date: "2026.06.15",
    variant: "SS",
    content: "아이 방에 깔아줬는데 촉감이 좋다고 잘 덮고 자요. 통세탁 가능한 게 육아 입장에서 최고 장점입니다.",
  },
  {
    id: "r-a06",
    userName: "hn*****",
    rating: 5,
    date: "2026.06.09",
    variant: "Q",
    content: "냉감 이불 처음 써보는데 닿는 순간 서늘한 느낌이 확실히 있어요. 땀이 많은 편인데 아침에 눅눅함이 덜합니다.",
    images: ["/images/reviews/1710120010/review-06-1.webp"],
  },
  {
    id: "r-a07",
    userName: "kr*****",
    rating: 3,
    date: "2026.06.02",
    variant: "SS",
    content: "제품 자체는 무난한데 배송 박스가 눌려서 왔고 첫 세탁 때 보풀이 조금 생겼어요. 시원한 건 맞아서 그냥 쓰고는 있습니다.",
  },
  {
    id: "r-a08",
    userName: "dh*****",
    rating: 5,
    date: "2026.05.27",
    variant: "Q",
    content: "신혼집 여름 침구로 구매했어요. 퀸 사이즈가 넉넉하게 떨어지고 충전재가 얇아서 덮었을 때 부담이 없습니다.",
  },
  {
    id: "r-a09",
    userName: "so*****",
    rating: 5,
    date: "2026.05.21",
    variant: "SS",
    content: "기숙사용으로 SS 샀는데 세트 구성이라 따로 맞출 필요가 없어 편했어요. 이 가격에 양면 냉감이면 가성비 충분합니다.",
    images: ["/images/reviews/1710120010/review-09-1.webp"],
  },
  {
    id: "r-a10",
    userName: "jm*****",
    rating: 5,
    date: "2026.05.14",
    variant: "Q",
    content: "장마철에는 보들면, 더운 날엔 냉감면으로 뒤집어 쓰는데 활용도가 좋아요. 봉제 마감도 꼼꼼한 편입니다.",
  },
  {
    id: "r-a11",
    userName: "ph*****",
    rating: 5,
    date: "2026.05.07",
    variant: "Q",
    content: "부모님 댁에 선물로 보냈는데 시원하고 가볍다고 좋아하세요. 여름 이불 중에 이 가격대면 만족도가 높은 것 같아요.",
  },
  {
    id: "r-a12",
    userName: "ck*****",
    rating: 5,
    date: "2026.04.29",
    variant: "SS",
    content: "초여름부터 미리 준비하려고 샀어요. 냉감면은 아직 조금 서늘할 정도라 한여름에 진가를 발휘할 것 같습니다.",
  },
  {
    id: "r-a13",
    userName: "yr*****",
    rating: 4,
    date: "2026.04.22",
    variant: "Q",
    content: "촉감이나 무게는 만족스러운데 냉감 효과는 에어컨 없이 쓰기엔 살짝 아쉬워요. 그래도 여름 차렵이불로는 충분합니다.",
  },
  {
    id: "r-a14",
    userName: "bs*****",
    rating: 5,
    date: "2026.04.15",
    variant: "SS",
    content: "세탁 후에도 충전재가 뭉치지 않고 금방 말라요. 여름 이불은 자주 빨게 되는데 관리가 쉬워서 좋습니다.",
    images: ["/images/reviews/1710120010/review-14-1.webp"],
  },
  {
    id: "r-a15",
    userName: "ny*****",
    rating: 5,
    date: "2026.04.08",
    variant: "Q",
    content: "작년에 쓰던 여름 이불이 무거워서 바꿨는데 확실히 가볍고 시원해요. 커버 색상이 침실 톤이랑 잘 어울립니다.",
  },
  {
    id: "r-a16",
    userName: "tj*****",
    rating: 5,
    date: "2026.04.01",
    variant: "SS",
    content: "이사하면서 침구를 새로 맞췄는데 세트라 통일감이 있어요. 피치스킨 면이 정말 보들보들해서 간절기에도 잘 쓰고 있습니다.",
  },
];

export const sharedReviews: ReviewData = {
  ...calculateReviewSummary(reviewItems),
  items: reviewItems,
};

export const sharedQnaItems: QnaItem[] = [
  {
    id: "q-a01",
    category: "상품",
    question: "냉감면은 세탁을 반복해도 냉감 기능이 유지되나요?",
    questioner: "hj*****",
    date: "2026.06.19",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 냉감 기능은 원단 자체의 접촉냉감 소재 특성으로 구현되어 세탁 후에도 기능이 유지됩니다. 다만 원단 보호를 위해 중성세제 사용과 단독 세탁을 권장드립니다. 감사합니다.",
    answerDate: "2026.06.20",
  },
];
