import type { ReviewData, QnaItem, Review } from "@/app/lib/types";
import { calculateReviewSummary } from "@/lib/reviews";

const reviewItems: Review[] = [
  {
    id: "r-a01",
    userName: "hy*****",
    rating: 5,
    date: "2026.07.04",
    variant: "Q",
    content: "양면 컬러가 달라서 뒤집을 때마다 침실 분위기가 바뀌는 게 재미있어요. 텐셀이라 그런지 촉감이 정말 매끄럽습니다.",
    images: ["/images/reviews/1710120030/review-01-1.webp", "/images/reviews/1710120030/review-01-2.webp"],
  },
  {
    id: "r-a02",
    userName: "kj*****",
    rating: 5,
    date: "2026.06.26",
    variant: "K",
    content: "할인 폭이 커서 반신반의했는데 원단 퀄리티가 기대 이상이에요. 킹 사이즈인데도 가볍고 세탁 후 건조도 빠릅니다.",
  },
  {
    id: "r-a03",
    userName: "sw*****",
    rating: 5,
    date: "2026.06.19",
    variant: "SS",
    content: "톤이 다른 양면이라 커버 두 개 산 기분이에요. 자취방 침구로 이만한 가성비가 없는 것 같습니다.",
    images: ["/images/reviews/1710120030/review-03-1.webp"],
  },
  {
    id: "r-a04",
    userName: "eh*****",
    rating: 4,
    date: "2026.06.11",
    variant: "Q",
    content: "촉감과 색감은 만족스러운데 한여름에 쓰기엔 살짝 도톰한 감이 있어요. 봄가을에는 정말 완벽할 것 같습니다.",
  },
  {
    id: "r-a05",
    userName: "nb*****",
    rating: 5,
    date: "2026.06.03",
    variant: "Q",
    content: "땀이 많은 편인데 텐셀 원단이라 그런지 자고 나도 보송해요. 사계절 내내 쓸 수 있다는 말이 이해됩니다.",
  },
  {
    id: "r-a06",
    userName: "tk*****",
    rating: 5,
    date: "2026.05.26",
    variant: "K",
    content: "신혼 침구로 구매했는데 양가 부모님께도 한 세트씩 보내드렸어요. 호텔 침구 같은 광택과 촉감이 고급스럽습니다.",
    images: ["/images/reviews/1710120030/review-06-1.webp"],
  },
  {
    id: "r-a07",
    userName: "ml*****",
    rating: 3,
    date: "2026.05.18",
    variant: "SS",
    content: "제품은 괜찮은데 첫 수령 시 포장에서 미세한 실밥이 몇 군데 보였어요. 교환 없이 쓸 정도라 그냥 사용 중입니다.",
  },
  {
    id: "r-a08",
    userName: "ry*****",
    rating: 5,
    date: "2026.05.10",
    variant: "Q",
    content: "리버서블이라 세탁 주기 사이에 면을 바꿔 쓰니 훨씬 쾌적해요. 퀼팅 간격이 촘촘해서 충전재 쏠림도 없습니다.",
  },
  {
    id: "r-a09",
    userName: "ab*****",
    rating: 5,
    date: "2026.05.02",
    variant: "K",
    content: "이불이 몸에 스르륵 감기는 느낌이 좋아서 잠드는 시간이 빨라졌어요. 이 가격에 텐셀 모달 혼방이면 무조건 이득입니다.",
  },
  {
    id: "r-a10",
    userName: "gu*****",
    rating: 5,
    date: "2026.04.24",
    variant: "Q",
    content: "환절기용으로 샀는데 두께가 적당해서 초여름까지 계속 쓰고 있어요. 뒤집었을 때 색이 더 마음에 들어서 그 면만 씁니다.",
    images: ["/images/reviews/1710120030/review-10-1.webp"],
  },
  {
    id: "r-a11",
    userName: "wd*****",
    rating: 5,
    date: "2026.04.16",
    variant: "SS",
    content: "아이 혼자 자기 시작하면서 사줬는데 부드럽다고 잘 덮고 자요. 세탁기 통세탁 가능해서 관리 부담이 없습니다.",
  },
  {
    id: "r-a12",
    userName: "qp*****",
    rating: 5,
    date: "2026.04.08",
    variant: "Q",
    content: "정가면 고민했을 텐데 할인가에 사서 더 만족스러워요. 원단 광택이 사진보다 실물이 훨씬 고급스럽습니다.",
  },
];

export const sharedReviews: ReviewData = {
  ...calculateReviewSummary(reviewItems),
  items: reviewItems,
};

export const sharedQnaItems: QnaItem[] = [
  {
    id: "q-a01",
    category: "상품",
    question: "리버서블 양면이 두께나 소재도 다른가요, 컬러만 다른 건가요?",
    questioner: "dm*****",
    date: "2026.06.14",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 양면 모두 동일한 텐셀 모달 혼방 원단이며 컬러만 다르게 제작되었습니다. 어느 면을 사용하셔도 동일한 촉감으로 사용 가능합니다. 감사합니다.",
    answerDate: "2026.06.15",
  },
  {
    id: "q-a02",
    category: "배송",
    question: "SS와 Q를 같이 주문하면 한 박스로 배송되나요?",
    questioner: "bn*****",
    date: "2026.05.22",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 동일 주문 건은 가능한 합포장으로 출고되나, 물류 상황에 따라 개별 박스로 나뉘어 배송될 수 있습니다. 배송비는 주문 건 기준으로 1회만 부과됩니다. 감사합니다.",
    answerDate: "2026.05.23",
  },
  {
    id: "q-a03",
    category: "상품",
    question: "한겨울에도 이 이불 하나로 충분할까요?",
    questioner: "xc*****",
    date: "2026.07.01",
    answered: false,
  },
];
