import type { ReviewData, QnaItem, Review } from "@/app/lib/types";
import { calculateReviewSummary } from "@/lib/reviews";

const reviewItems: Review[] = [
  {
    id: "r-a01",
    userName: "hn*****",
    rating: 5,
    date: "2026.07.19",
    variant: "내추럴",
    content: "내추럴 컬러로 주문했는데 원목 식탁이랑 톤이 자연스럽게 어우러져요. 시트가 가벼워서 청소할 때 옮기기도 편합니다.",
  },
  {
    id: "r-a02",
    userName: "ks*****",
    rating: 5,
    date: "2026.07.10",
    variant: "코튼화이트",
    content: "화이트 톤 주방이라 코튼화이트로 골랐는데 깔끔하게 잘 어울려요. 등받이 곡선이 편안합니다.",
    images: ["/images/reviews/1211100020/review-02-1.webp"],
  },
  {
    id: "r-a03",
    userName: "th*****",
    rating: 5,
    date: "2026.07.01",
    variant: "웜블랙",
    content: "웜블랙이 사진보다 훨씬 고급스러워요. 어떤 식탁과 매치해도 포인트가 됩니다.",
    images: ["/images/reviews/1211100020/review-03-1.webp"],
  },
  {
    id: "r-a04",
    userName: "ny*****",
    rating: 5,
    date: "2026.06.22",
    variant: "러스트",
    content: "러스트 컬러가 흔치 않아서 골랐는데 톤이 예뻐요. 주방 분위기가 한층 따뜻해졌습니다.",
    images: ["/images/reviews/1211100020/review-04-1.webp"],
  },
  {
    id: "r-a05",
    userName: "ig*****",
    rating: 5,
    date: "2026.06.13",
    variant: "매트그린",
    content: "매트그린이 인테리어 포인트로 정말 좋아요. 앉았을 때 시트 곡선이 몸에 잘 맞습니다.",
  },
  {
    id: "r-a06",
    userName: "ce*****",
    rating: 4,
    date: "2026.06.04",
    variant: "내추럴",
    content: "전체적으로 만족하는데 다리 색이 사진보다 살짝 밝게 왔어요. 앉는 느낌 자체는 편안합니다.",
  },
  {
    id: "r-a07",
    userName: "dm*****",
    rating: 5,
    date: "2026.05.26",
    variant: "코튼화이트",
    content: "가벼워서 식탁 아래로 넣고 빼기 편해요. 화이트 톤이라 어디에 둬도 깨끗해 보입니다.",
    images: ["/images/reviews/1211100020/review-07-1.webp", "/images/reviews/1211100020/review-07-2.webp"],
  },
  {
    id: "r-a08",
    userName: "ru*****",
    rating: 5,
    date: "2026.05.17",
    variant: "웜블랙",
    content: "블랙 계열 원해서 골랐는데 매트한 질감이 고급스러워요. 흠집도 잘 안 보입니다.",
  },
  {
    id: "r-a09",
    userName: "ao*****",
    rating: 5,
    date: "2026.05.08",
    variant: "러스트",
    content: "러스트 컬러가 사진과 실물 차이가 거의 없어요. 다이닝 공간에 포인트 컬러로 딱입니다.",
  },
  {
    id: "r-a10",
    userName: "wl*****",
    rating: 5,
    date: "2026.04.29",
    variant: "매트그린",
    content: "그린 계열이라 식물이랑 놓으니 분위기가 좋아요. 앉는 느낌도 부드럽습니다.",
  },
  {
    id: "r-a11",
    userName: "qb*****",
    rating: 4,
    date: "2026.04.20",
    variant: "내추럴",
    content: "무난한 색이라 어디에도 잘 어울리는데, 다리 나사 하나가 헐거워서 다시 조였어요. 그 외엔 만족합니다.",
  },
  {
    id: "r-a12",
    userName: "ef*****",
    rating: 5,
    date: "2026.04.11",
    variant: "코튼화이트",
    content: "1개씩 낱개로 살 수 있어서 원하는 개수만 맞출 수 있어 좋았어요. 색상도 깨끗한 화이트입니다.",
    images: ["/images/reviews/1211100020/review-12-1.webp", "/images/reviews/1211100020/review-12-2.webp"],
  },
  {
    id: "r-a13",
    userName: "xh*****",
    rating: 5,
    date: "2026.04.02",
    variant: "웜블랙",
    content: "튼튼하고 무게도 가벼워서 이동하기 편해요. 색감도 차분하니 마음에 듭니다.",
  },
  {
    id: "r-a14",
    userName: "ov*****",
    rating: 5,
    date: "2026.03.24",
    variant: "러스트",
    content: "러스트 컬러로 포인트를 주고 싶었는데 딱 원하던 톤이 왔어요. 앉음새도 편안합니다.",
  },
  {
    id: "r-a15",
    userName: "yk*****",
    rating: 5,
    date: "2026.03.15",
    variant: "매트그린",
    content: "매트한 질감이라 지문이 잘 안 남아서 관리가 편해요. 그린 컬러도 예쁩니다.",
  },
  {
    id: "r-a16",
    userName: "bs*****",
    rating: 4,
    date: "2026.03.06",
    variant: "내추럴",
    content: "가격 대비 만족스러운데 배송이 하루 늦었어요. 색상과 마감은 기대한 만큼입니다.",
  },
  {
    id: "r-a17",
    userName: "ml*****",
    rating: 5,
    date: "2026.02.25",
    variant: "코튼화이트",
    content: "화이트라 어떤 식탁과도 잘 어울려서 후회 없는 선택이었어요. 시트도 편안합니다.",
  },
  {
    id: "r-a18",
    userName: "cq*****",
    rating: 5,
    date: "2026.02.16",
    variant: "웜블랙",
    content: "블랙 계열 의자를 찾다가 골랐는데 만족스러워요. 조립도 간단했습니다.",
  },
  {
    id: "r-a19",
    userName: "fw*****",
    rating: 4,
    date: "2026.02.07",
    variant: "러스트",
    content: "컬러는 정말 예쁜데 시트 표면에 자잘한 스크래치가 살짝 보였어요. 사용에는 문제없습니다.",
  },
];

export const sharedReviews: ReviewData = {
  ...calculateReviewSummary(reviewItems),
  items: reviewItems,
};

export const sharedQnaItems: QnaItem[] = [
  {
    id: "q-a01",
    category: "상품",
    question: "다섯 가지 색상 중 재질 차이가 있나요?",
    questioner: "dg*****",
    date: "2026.06.18",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 색상만 다를 뿐 시트·다리 소재와 구조는 모두 동일합니다. 감사합니다.",
    answerDate: "2026.06.19",
  },
  {
    id: "q-a02",
    category: "배송",
    question: "1개만 주문해도 배송비가 붙나요?",
    questioner: "sk*****",
    date: "2026.06.02",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 5만원 미만 주문 시 3,000원의 배송비가 발생하며, 이상 구매 시 무료 배송됩니다. 감사합니다.",
    answerDate: "2026.06.03",
  },
  {
    id: "q-a03",
    category: "상품",
    question: "야외 테라스에서 사용해도 되나요?",
    questioner: "wm*****",
    date: "2026.05.12",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 실내용으로 제작된 제품이라 장시간 야외 사용 시 스틸 프레임이 변색될 수 있어 권장하지 않습니다. 감사합니다.",
    answerDate: "2026.05.13",
  },
  {
    id: "q-a04",
    category: "기타",
    question: "매트그린 외 그린 계열 다른 톤도 있나요?",
    questioner: "hf*****",
    date: "2026.04.15",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 현재 그린 계열은 매트그린 단일 톤으로만 판매하고 있습니다. 감사합니다.",
    answerDate: "2026.04.16",
  },
  {
    id: "q-a05",
    category: "배송",
    question: "같은 색상으로 4개 한 번에 주문하면 할인되나요?",
    questioner: "zb*****",
    date: "2026.07.14",
    answered: false,
  },
];
