import type { ReviewData, QnaItem, Review } from "@/app/lib/types";
import { calculateReviewSummary } from "@/lib/reviews";

const reviewItems: Review[] = [
  {
    id: "r-a01",
    userName: "yj*****",
    rating: 5,
    date: "2026.07.08",
    variant: "기본",
    content: "낮잠 전쟁이 끝났어요. 놀다가 그대로 스르륵 잠들면 이불만 덮어주면 됩니다. 육아템 중 최고예요.",
    images: ["/images/reviews/1713110020/review-01-1.webp", "/images/reviews/1713110020/review-01-2.webp"],
  },
  {
    id: "r-a02",
    userName: "sb*****",
    rating: 5,
    date: "2026.07.01",
    variant: "기본",
    content: "18개월 아기가 자꾸 넘어지는데 쿠션이 두툼해서 울지 않아요. 원형이라 방 가운데 두면 그림이 됩니다.",
  },
  {
    id: "r-a03",
    userName: "mk*****",
    rating: 5,
    date: "2026.06.24",
    variant: "기본",
    content: "아랫집 눈치 보였는데 발소리가 확실히 줄었어요. 층간소음 매트보다 예쁘고 토퍼 기능까지 있으니 일석삼조입니다.",
    images: ["/images/reviews/1713110020/review-03-1.webp"],
  },
  {
    id: "r-a04",
    userName: "dh*****",
    rating: 5,
    date: "2026.06.17",
    variant: "기본",
    content: "커버 분리 세탁이 정말 편해요. 이유식 흘려도 커버만 벗겨 빨면 되니 스트레스가 없습니다.",
  },
  {
    id: "r-a05",
    userName: "wn*****",
    rating: 4,
    date: "2026.06.10",
    variant: "기본",
    content: "품질은 만족스러운데 쿠션이 도톰한 만큼 방문이 스치는 위치엔 못 둬요. 배치만 잘 잡으면 최고의 육아템입니다.",
  },
  {
    id: "r-a06",
    userName: "eb*****",
    rating: 5,
    date: "2026.06.03",
    variant: "기본",
    content: "둘째 출산 선물로 받았는데 첫째까지 둘이 뒹굴며 놀아요. 원형이라 아이들이 자기 영역처럼 아낍니다.",
  },
  {
    id: "r-a07",
    userName: "hs*****",
    rating: 5,
    date: "2026.05.27",
    variant: "기본",
    content: "신생아 터미타임용으로 쓰다가 지금은 놀이매트로 쓰고 있어요. 개월수 따라 용도가 늘어나는 제품입니다.",
    images: ["/images/reviews/1713110020/review-07-1.webp"],
  },
  {
    id: "r-a08",
    userName: "cj*****",
    rating: 5,
    date: "2026.05.20",
    variant: "기본",
    content: "색감이 튀지 않아서 거실에 둬도 인테리어를 해치지 않아요. 어른이 앉아도 될 만큼 쿠션이 탄탄합니다.",
  },
  {
    id: "r-a09",
    userName: "tk*****",
    rating: 5,
    date: "2026.05.13",
    variant: "기본",
    content: "조리원 동기들 사이에서 유명해서 샀는데 소문대로예요. 1위 상품인 이유가 있습니다.",
  },
  {
    id: "r-a10",
    userName: "lg*****",
    rating: 5,
    date: "2026.05.06",
    variant: "기본",
    content: "아이가 원형 러그 가장자리를 따라 도는 걸 좋아해요. 놀이·낮잠·소음방지까지 하나로 해결됩니다.",
  },
  {
    id: "r-a11",
    userName: "bq*****",
    rating: 5,
    date: "2026.04.29",
    variant: "기본",
    content: "순면 커버라 아기 볼이 닿아도 안심이에요. 태열 있는 아기인데 트러블 없이 잘 쓰고 있습니다.",
    images: ["/images/reviews/1713110020/review-11-1.webp"],
  },
  {
    id: "r-a12",
    userName: "kv*****",
    rating: 5,
    date: "2026.04.22",
    variant: "기본",
    content: "할머니 댁에 하나 더 사서 보냈어요. 아이가 어디 가든 자기 자리가 있으니 낯가림이 줄었습니다.",
  },
  {
    id: "r-a13",
    userName: "nf*****",
    rating: 5,
    date: "2026.04.15",
    variant: "기본",
    content: "매트 특유의 PVC 냄새가 없어서 놀랐어요. 개봉하자마자 바로 사용했는데 아무 냄새도 안 납니다.",
  },
  {
    id: "r-a14",
    userName: "ir*****",
    rating: 5,
    date: "2026.04.08",
    variant: "기본",
    content: "책 읽어주는 자리로 정착했어요. 러그에 앉으면 책 읽는 시간인 걸 아이가 알아서 루틴 잡기 좋습니다.",
  },
  {
    id: "r-a15",
    userName: "vy*****",
    rating: 4,
    date: "2026.04.01",
    variant: "기본",
    content: "대체로 만족하는데 토퍼로 쓰기엔 4살 아이는 살짝 작아요. 3살까지는 낮잠 토퍼로 완벽합니다.",
  },
  {
    id: "r-a16",
    userName: "qw*****",
    rating: 5,
    date: "2026.03.25",
    variant: "기본",
    content: "여름엔 시원한 면 커버, 겨울엔 이불 깔면 포근해서 사계절 내내 씁니다. 벌써 1년째 현역이에요.",
  },
  {
    id: "r-a17",
    userName: "zu*****",
    rating: 5,
    date: "2026.03.18",
    variant: "기본",
    content: "쿠션 복원력이 좋아서 아이가 뛰어도 꺼진 자국이 안 남아요. 마감 박음질도 튼튼합니다.",
  },
  {
    id: "r-a18",
    userName: "xp*****",
    rating: 5,
    date: "2026.03.11",
    variant: "기본",
    content: "출산 선물로 세 번째 구매예요. 받는 분마다 만족도가 높아서 선물 리스트에 고정됐습니다.",
  },
  {
    id: "r-a19",
    userName: "gd*****",
    rating: 5,
    date: "2026.03.04",
    variant: "기본",
    content: "이사하면서 아이 방 새로 꾸몄는데 이 러그가 중심을 잡아줘요. 사진 찍으면 스튜디오 같습니다.",
  },
  {
    id: "r-a20",
    userName: "oa*****",
    rating: 5,
    date: "2026.02.25",
    variant: "기본",
    content: "기저귀 갈이·놀이·낮잠까지 하루 종일 이 위에서 해결해요. 육아 필수템이라는 후기가 과장이 아닙니다.",
  },
  {
    id: "r-a21",
    userName: "uf*****",
    rating: 5,
    date: "2026.02.18",
    variant: "기본",
    content: "반려견과 아기가 같이 쓰는데 털이 잘 안 붙고 청소도 쉬워요. 걱정했던 위생 문제가 없습니다.",
  },
  {
    id: "r-a22",
    userName: "jh*****",
    rating: 5,
    date: "2026.02.11",
    variant: "기본",
    content: "겨울에 바닥 냉기를 확실히 막아줘서 감기 걱정이 줄었어요. 두께가 주는 안정감이 다릅니다.",
  },
  {
    id: "r-a23",
    userName: "pe*****",
    rating: 5,
    date: "2026.02.04",
    variant: "기본",
    content: "샘키즈 라인은 믿고 사는데 이번에도 실망시키지 않네요. 아이가 제일 좋아하는 자리가 됐습니다.",
  },
];

export const sharedReviews: ReviewData = {
  ...calculateReviewSummary(reviewItems),
  items: reviewItems,
};

export const sharedQnaItems: QnaItem[] = [
  {
    id: "q-a01",
    category: "상품",
    question: "신생아부터 사용 가능한가요? 권장 연령이 궁금합니다.",
    questioner: "sr*****",
    date: "2026.06.27",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 신생아기부터 사용 가능하며, 토퍼 용도는 36개월 전후까지 권장드립니다. 이후에는 놀이러그로 계속 사용하실 수 있습니다. 감사합니다.",
    answerDate: "2026.06.28",
  },
  {
    id: "q-a02",
    category: "상품",
    question: "커버만 추가 구매할 수 있나요? 세탁할 때 여분이 필요해서요.",
    questioner: "dm*****",
    date: "2026.06.09",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 현재 커버 단품 판매는 준비 중입니다. 출시 시 상품 페이지를 통해 안내드리겠습니다. 감사합니다.",
    answerDate: "2026.06.10",
  },
  {
    id: "q-a03",
    category: "상품",
    question: "쿠션 내장재도 통세탁이 가능한가요?",
    questioner: "wf*****",
    date: "2026.05.22",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 내장 쿠션은 세탁 시 형태 변형의 우려가 있어 커버만 분리 세탁을 권장드립니다. 내장재는 통풍이 잘 되는 곳에서 주기적으로 건조해 주세요. 감사합니다.",
    answerDate: "2026.05.23",
  },
  {
    id: "q-a04",
    category: "배송",
    question: "출산 예정일에 맞춰 배송일 지정이 가능한가요?",
    questioner: "hp*****",
    date: "2026.05.04",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 주문 시 요청사항에 희망 수령일을 남겨주시면 출고 일정을 조율해 드립니다. 택배사 사정에 따라 1~2일 오차가 있을 수 있는 점 양해 부탁드립니다. 감사합니다.",
    answerDate: "2026.05.05",
  },
  {
    id: "q-a05",
    category: "상품",
    question: "지름이 어떻게 되나요? 아이 방이 좁아서요.",
    questioner: "cy*****",
    date: "2026.04.16",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 본 제품의 지름은 120cm입니다. 상세 페이지 사이즈 안내 이미지에서 공간 배치 예시를 확인하실 수 있습니다. 감사합니다.",
    answerDate: "2026.04.17",
  },
  {
    id: "q-a06",
    category: "기타",
    question: "선물 포장 서비스가 있나요?",
    questioner: "bz*****",
    date: "2026.07.06",
    answered: false,
  },
];
