import type { ReviewData, QnaItem, Review } from "@/app/lib/types";
import { calculateReviewSummary } from "@/lib/reviews";

const reviewItems: Review[] = [
  {
    id: "r-a01",
    userName: "hj*****",
    rating: 5,
    date: "2026.07.22",
    variant: "부클아이보리",
    content: "부클아이보리 컬러가 사진보다 더 포근하고 고급스러워요. 두 개를 나란히 두니 카페 같은 분위기가 납니다.",
    images: ["/images/reviews/1211100030/review-01-1.webp", "/images/reviews/1211100030/review-01-2.webp"],
  },
  {
    id: "r-a02",
    userName: "sm*****",
    rating: 5,
    date: "2026.07.13",
    variant: "코튼화이트",
    content: "화이트 톤이라 어떤 식탁이랑도 잘 어울려요. 등받이 곡선이 몸을 편안하게 감싸줍니다.",
  },
  {
    id: "r-a03",
    userName: "kt*****",
    rating: 5,
    date: "2026.07.04",
    variant: "부클아이보리",
    content: "부클 원단이 도톰해서 겨울에 앉아도 차갑지 않아요. 2개입이라 가성비도 좋습니다.",
  },
  {
    id: "r-a04",
    userName: "yn*****",
    rating: 5,
    date: "2026.06.25",
    variant: "코튼화이트",
    content: "심플한 화이트라 인테리어에 부담이 없어요. 프레임도 튼튼하고 흔들림이 없습니다.",
  },
  {
    id: "r-a05",
    userName: "dw*****",
    rating: 5,
    date: "2026.06.16",
    variant: "부클아이보리",
    content: "부클 소재가 고급스러워서 손님 오실 때마다 어디서 샀냐고 물어봐요. 앉을 때마다 만족스럽습니다.",
  },
  {
    id: "r-a06",
    userName: "bg*****",
    rating: 5,
    date: "2026.06.07",
    variant: "코튼화이트",
    content: "화이트 부클이 화사해서 밝은 주방이랑 정말 잘 어울려요. 둥근 등받이 디자인도 세련됐습니다.",
    images: ["/images/reviews/1211100030/review-06-1.webp"],
  },
  {
    id: "r-a07",
    userName: "ej*****",
    rating: 5,
    date: "2026.05.29",
    variant: "부클아이보리",
    content: "스틸 프레임이 단단해서 앉을 때 흔들림이 전혀 없어요. 부클 촉감도 부드럽습니다.",
  },
  {
    id: "r-a08",
    userName: "ps*****",
    rating: 5,
    date: "2026.05.20",
    variant: "코튼화이트",
    content: "2개입이라 색상 통일감 있게 배치할 수 있어서 좋았어요. 조립도 어렵지 않았습니다.",
  },
  {
    id: "r-a09",
    userName: "wc*****",
    rating: 4,
    date: "2026.05.11",
    variant: "부클아이보리",
    content: "전체적으로 만족스러운데 부클 원단에 먼지가 잘 붙는 편이에요. 롤러로 관리하고 있습니다.",
  },
  {
    id: "r-a10",
    userName: "mr*****",
    rating: 5,
    date: "2026.05.02",
    variant: "코튼화이트",
    content: "등받이가 둥글어서 시각적으로도 부드러운 느낌이에요. 앉는 자세도 편안합니다.",
  },
  {
    id: "r-a11",
    userName: "hb*****",
    rating: 5,
    date: "2026.04.23",
    variant: "부클아이보리",
    content: "겨울에 부클 소재라 그런지 앉는 순간부터 따뜻한 느낌이 들어요. 색상도 사진과 동일합니다.",
    images: ["/images/reviews/1211100030/review-11-1.webp"],
  },
  {
    id: "r-a12",
    userName: "jy*****",
    rating: 5,
    date: "2026.04.14",
    variant: "코튼화이트",
    content: "심플한 디자인이 유행 안 타서 오래 쓸 수 있을 것 같아요. 만족스러운 구매였습니다.",
  },
  {
    id: "r-a13",
    userName: "on*****",
    rating: 5,
    date: "2026.04.05",
    variant: "부클아이보리",
    content: "친구 집에서 보고 반해서 구매했는데 실제로 앉아보니 왜 인기인지 알겠어요. 편안함이 남다릅니다.",
  },
  {
    id: "r-a14",
    userName: "vs*****",
    rating: 5,
    date: "2026.03.27",
    variant: "코튼화이트",
    content: "화이트 부클이라 먼지가 티가 안 나서 관리하기 편해요. 프레임도 견고합니다.",
  },
  {
    id: "r-a15",
    userName: "rq*****",
    rating: 5,
    date: "2026.03.18",
    variant: "부클아이보리",
    content: "2개 다 색상 편차 없이 균일하게 와서 만족스러워요. 조립도 금방 끝났습니다.",
  },
  {
    id: "r-a16",
    userName: "az*****",
    rating: 5,
    date: "2026.03.09",
    variant: "코튼화이트",
    content: "라운드 등받이라 자세가 편안하게 잡혀요. 화이트 컬러라 어떤 소품과도 잘 어울립니다.",
    images: ["/images/reviews/1211100030/review-16-1.webp"],
  },
  {
    id: "r-a17",
    userName: "tf*****",
    rating: 5,
    date: "2026.02.28",
    variant: "부클아이보리",
    content: "부클 원단이 고급스러워서 카페 인테리어 느낌이 나요. 가족 모두 만족하고 있습니다.",
  },
  {
    id: "r-a18",
    userName: "gi*****",
    rating: 5,
    date: "2026.02.19",
    variant: "코튼화이트",
    content: "가볍지만 앉았을 때 안정감이 확실해요. 흰색이라 청소도 눈에 잘 띄어서 편합니다.",
  },
  {
    id: "r-a19",
    userName: "uj*****",
    rating: 4,
    date: "2026.02.10",
    variant: "부클아이보리",
    content: "디자인은 정말 마음에 드는데 다리 높이가 살짝 안 맞아서 흔들렸어요. 패드로 보정해서 쓰고 있습니다.",
  },
  {
    id: "r-a20",
    userName: "nx*****",
    rating: 5,
    date: "2026.02.01",
    variant: "코튼화이트",
    content: "2개입이라 부부가 마주 앉기 딱 좋아요. 등받이 곡선이 편안해서 오래 앉아도 괜찮습니다.",
  },
  {
    id: "r-a21",
    userName: "pw*****",
    rating: 5,
    date: "2026.01.23",
    variant: "부클아이보리",
    content: "부클아이보리 컬러가 인테리어 사진처럼 예쁘게 나왔어요. 포근한 소재감이 마음에 듭니다.",
    images: ["/images/reviews/1211100030/review-21-1.webp"],
  },
  {
    id: "r-a22",
    userName: "lc*****",
    rating: 5,
    date: "2026.01.14",
    variant: "코튼화이트",
    content: "심플하면서 포인트가 되는 디자인이라 만족해요. 다음에도 여기서 가구를 살 것 같습니다.",
  },
];

export const sharedReviews: ReviewData = {
  ...calculateReviewSummary(reviewItems),
  items: reviewItems,
};

export const sharedQnaItems: QnaItem[] = [
  {
    id: "q-a01",
    category: "상품",
    question: "부클 원단이 오염에 약하지 않나요?",
    questioner: "dg*****",
    date: "2026.06.30",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 발수 코팅 처리가 되어 있어 가벼운 오염은 마른 천으로 닦아내실 수 있습니다. 다만 진한 오염물은 바로 닦아주시길 권장드립니다. 감사합니다.",
    answerDate: "2026.07.01",
  },
  {
    id: "q-a02",
    category: "배송",
    question: "조립은 어느 정도 난이도인가요?",
    questioner: "sk*****",
    date: "2026.06.14",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 다리를 나사로 고정하는 간단한 조립으로, 기본 공구가 함께 제공되어 10분 내외로 완료하실 수 있습니다. 감사합니다.",
    answerDate: "2026.06.15",
  },
  {
    id: "q-a03",
    category: "상품",
    question: "부클아이보리와 코튼화이트 차이가 큰가요?",
    questioner: "wm*****",
    date: "2026.05.25",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 부클아이보리는 도톰한 부클 원단, 코튼화이트는 매끈한 코튼 원단으로 소재 질감에 차이가 있습니다. 감사합니다.",
    answerDate: "2026.05.26",
  },
  {
    id: "q-a04",
    category: "기타",
    question: "다른 부클 색상(그레이 등) 추가 예정 있나요?",
    questioner: "hf*****",
    date: "2026.04.18",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 현재는 두 가지 색상으로만 판매 중이며, 추가 색상 출시 여부는 정해지지 않았습니다. 감사합니다.",
    answerDate: "2026.04.19",
  },
  {
    id: "q-a05",
    category: "상품",
    question: "성인 두 명이 번갈아 앉아도 내구성에 문제 없나요?",
    questioner: "zb*****",
    date: "2026.03.20",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 스틸 프레임으로 제작되어 일반적인 가정용 사용 환경에서 안정적으로 사용하실 수 있습니다. 감사합니다.",
    answerDate: "2026.03.21",
  },
  {
    id: "q-a06",
    category: "배송",
    question: "낱개로 1개만 구매할 수는 없나요?",
    questioner: "ip*****",
    date: "2026.02.22",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 해당 상품은 2개입 세트로만 판매되고 있습니다. 감사합니다.",
    answerDate: "2026.02.23",
  },
  {
    id: "q-a07",
    category: "배송",
    question: "이번 주말 전에 받아볼 수 있을까요?",
    questioner: "oc*****",
    date: "2026.07.19",
    answered: false,
  },
];
