import type { ReviewData, QnaItem, Review } from "@/app/lib/types";
import { calculateReviewSummary } from "@/lib/reviews";

const reviewItems: Review[] = [
  {
    id: "r-a01",
    userName: "hj*****",
    rating: 5,
    date: "2026.07.05",
    variant: "아이보리",
    content: "쏟은 커피 자국이 세탁 한 번에 사라졌어요. 워셔블 러그는 처음인데 이제 다른 러그는 못 살 것 같습니다.",
    images: ["/images/reviews/1713110010/review-01-1.webp", "/images/reviews/1713110010/review-01-2.webp"],
  },
  {
    id: "r-a02",
    userName: "sm*****",
    rating: 5,
    date: "2026.06.26",
    variant: "웜그레이",
    content: "슬러브 결 때문에 단색인데도 밋밋하지 않아요. 웜그레이가 우드 가구랑 톤이 정말 잘 맞습니다.",
  },
  {
    id: "r-a03",
    userName: "dy*****",
    rating: 5,
    date: "2026.06.17",
    variant: "애쉬그레이",
    content: "반려견이 있어서 세탁 가능한 러그만 찾았는데 정답이었어요. 털도 잘 안 박히고 청소기가 수월합니다.",
    images: ["/images/reviews/1713110010/review-03-1.webp"],
  },
  {
    id: "r-a04",
    userName: "wk*****",
    rating: 5,
    date: "2026.06.08",
    variant: "아이보리",
    content: "발에 닿는 촉감이 보들보들해서 아이가 러그 위에서만 놀아요. 먼지 날림이 적다는 게 체감됩니다.",
  },
  {
    id: "r-a05",
    userName: "yc*****",
    rating: 4,
    date: "2026.05.30",
    variant: "웜그레이",
    content: "품질과 색감은 만족인데 처음 펼쳤을 때 접힘 자국이 하루 정도 갔어요. 지금은 평평하게 잘 깔려 있습니다.",
  },
  {
    id: "r-a06",
    userName: "bh*****",
    rating: 5,
    date: "2026.05.21",
    variant: "애쉬그레이",
    content: "논슬립이 확실해서 로봇청소기가 지나가도 안 밀려요. 러그 밀림 스트레스가 사라졌습니다.",
  },
  {
    id: "r-a07",
    userName: "km*****",
    rating: 5,
    date: "2026.05.12",
    variant: "아이보리",
    content: "밝은 색이라 오염 걱정했는데 세탁이 되니 겁 없이 골랐어요. 거실이 두 배는 넓고 환해 보입니다.",
    images: ["/images/reviews/1713110010/review-07-1.webp"],
  },
  {
    id: "r-a08",
    userName: "ep*****",
    rating: 5,
    date: "2026.05.03",
    variant: "웜그레이",
    content: "여름에도 덥지 않은 두께라 사계절 내내 깔아둘 수 있어요. 계절마다 러그 바꾸는 수고가 없어졌습니다.",
  },
  {
    id: "r-a09",
    userName: "tn*****",
    rating: 5,
    date: "2026.04.24",
    variant: "애쉬그레이",
    content: "세탁 후 건조가 빨라서 오전에 빨면 저녁에 다시 깔 수 있어요. 위생에 민감한 분께 강력 추천합니다.",
  },
  {
    id: "r-a10",
    userName: "lj*****",
    rating: 5,
    date: "2026.04.15",
    variant: "아이보리",
    content: "신혼집 거실에 깔았는데 이 가격이 맞나 싶은 퀄리티예요. 두 번째 컬러도 주문했습니다.",
  },
  {
    id: "r-a11",
    userName: "cq*****",
    rating: 5,
    date: "2026.04.06",
    variant: "웜그레이",
    content: "층간소음 때문에 깔았는데 발소리가 확실히 줄었어요. 아랫집 민원이 사라진 것만으로 제값을 합니다.",
  },
  {
    id: "r-a12",
    userName: "ng*****",
    rating: 5,
    date: "2026.03.28",
    variant: "애쉬그레이",
    content: "2위 상품이라길래 골랐는데 실물 색감이 사진보다 고급스러워요. 슬러브 텍스처가 살아 있습니다.",
  },
  {
    id: "r-a13",
    userName: "iz*****",
    rating: 5,
    date: "2026.03.19",
    variant: "아이보리",
    content: "맨발 생활하는 집이라 촉감이 중요한데 첫 발부터 합격이었어요. 잔털 빠짐도 거의 없습니다.",
  },
  {
    id: "r-a14",
    userName: "vp*****",
    rating: 5,
    date: "2026.03.10",
    variant: "웜그레이",
    content: "부모님 댁 거실에 선물로 보냈는데 어머니가 관리 편하다고 제일 좋아하세요. 색도 때가 안 타는 톤입니다.",
  },
];

export const sharedReviews: ReviewData = {
  ...calculateReviewSummary(reviewItems),
  items: reviewItems,
};

export const sharedQnaItems: QnaItem[] = [
  {
    id: "q-a01",
    category: "상품",
    question: "일반 가정용 세탁기(12kg)에 들어가는 사이즈인가요?",
    questioner: "os*****",
    date: "2026.06.21",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 본 제품은 접어서 12kg 이상 가정용 세탁기에 세탁 가능하도록 설계되었습니다. 중성세제 사용, 단독 세탁을 권장드립니다. 감사합니다.",
    answerDate: "2026.06.22",
  },
  {
    id: "q-a02",
    category: "상품",
    question: "바닥난방(온돌)에서 사용해도 되나요?",
    questioner: "rd*****",
    date: "2026.06.03",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 네, 온돌 바닥에서 사용 가능합니다. 논슬립 코팅은 통상적인 난방 온도에서 변형되지 않으나, 장시간 고온 난방 시에는 주기적으로 환기해 주시면 더욱 오래 사용하실 수 있습니다. 감사합니다.",
    answerDate: "2026.06.04",
  },
  {
    id: "q-a03",
    category: "상품",
    question: "건조기 사용이 가능한가요?",
    questioner: "fq*****",
    date: "2026.05.16",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 논슬립 코팅 보호를 위해 건조기 사용은 권장하지 않습니다. 세탁 후 그늘에서 펼쳐 말리시면 빠르게 건조됩니다. 감사합니다.",
    answerDate: "2026.05.17",
  },
  {
    id: "q-a04",
    category: "배송",
    question: "두 장 주문 시 한 박스로 배송되나요?",
    questioner: "uk*****",
    date: "2026.04.28",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 동일 주문 건은 가능한 합포장으로 출고되며, 부피 관계로 개별 발송 시에도 배송비는 1회만 부과됩니다. 감사합니다.",
    answerDate: "2026.04.29",
  },
  {
    id: "q-a05",
    category: "기타",
    question: "러그 폭 다른 사이즈 출시 계획이 있나요?",
    questioner: "jb*****",
    date: "2026.07.07",
    answered: false,
  },
];
