import type { ReviewData, QnaItem, Review } from "@/app/lib/types";
import { calculateReviewSummary } from "@/lib/reviews";

const reviewItems: Review[] = [
  // ── 900벤치 ──
  {
    id: "r-a01",
    userName: "hj*****",
    rating: 5,
    date: "2026.07.21",
    variant: "900벤치",
    content: "2인 식탁 옆에 뒀는데 사이즈가 딱 맞아요. 원목 프레임이 튼튼해서 안정감이 좋습니다.",
    images: ["/images/reviews/1211120010/review-01-1.webp"],
  },
  {
    id: "r-a02",
    userName: "sm*****",
    rating: 5,
    date: "2026.07.12",
    variant: "900벤치",
    content: "좁은 주방에도 부담 없이 들어가는 사이즈예요. 패브릭 시트 촉감도 좋습니다.",
  },
  {
    id: "r-a03",
    userName: "kt*****",
    rating: 5,
    date: "2026.07.03",
    variant: "900벤치",
    content: "가격은 있지만 마감이 꼼꼼해서 값어치를 하는 느낌이에요. 두 명이 앉기에 넉넉합니다.",
  },
  {
    id: "r-a04",
    userName: "yn*****",
    rating: 5,
    date: "2026.06.24",
    variant: "900벤치",
    content: "식탁 한쪽을 벤치로 바꾸니 공간이 훨씬 여유로워 보여요. 색상도 은은하니 마음에 듭니다.",
  },
  {
    id: "r-a05",
    userName: "dw*****",
    rating: 5,
    date: "2026.06.15",
    variant: "900벤치",
    content: "조립 없이 바로 사용할 수 있게 배송팀이 설치까지 해주셔서 편했어요. 완성도가 높습니다.",
    images: ["/images/reviews/1211120010/review-05-1.webp"],
  },
  {
    id: "r-a06",
    userName: "bg*****",
    rating: 5,
    date: "2026.06.06",
    variant: "900벤치",
    content: "아이랑 나란히 앉기 좋은 사이즈라 자주 활용해요. 시트 쿠션감도 적당합니다.",
  },
  {
    id: "r-a07",
    userName: "ej*****",
    rating: 5,
    date: "2026.05.28",
    variant: "900벤치",
    content: "심플한 디자인이라 어떤 식탁과도 잘 어울려요. 프레임 마감도 꼼꼼합니다.",
  },
  {
    id: "r-a08",
    userName: "ps*****",
    rating: 4,
    date: "2026.05.19",
    variant: "900벤치",
    content: "전체적으로 만족하는데 배송이 예정일보다 이틀 늦었어요. 제품 자체는 튼튼합니다.",
  },
  {
    id: "r-a09",
    userName: "wc*****",
    rating: 5,
    date: "2026.05.10",
    variant: "900벤치",
    content: "혼자 살아도 손님 오면 벤치가 유용해요. 좁은 공간에 딱 맞는 사이즈입니다.",
  },
  {
    id: "r-a10",
    userName: "mr*****",
    rating: 5,
    date: "2026.05.01",
    variant: "900벤치",
    content: "원목 프레임이라 그런지 고급스러운 느낌이 나요. 오래 써도 좋을 것 같습니다.",
  },
  {
    id: "r-a11",
    userName: "hb*****",
    rating: 5,
    date: "2026.04.22",
    variant: "900벤치",
    content: "식탁 의자 대신 벤치로 바꿨는데 훨씬 여유롭게 앉을 수 있어요. 패브릭 컬러도 무난합니다.",
    images: ["/images/reviews/1211120010/review-11-1.webp"],
  },
  {
    id: "r-a12",
    userName: "jy*****",
    rating: 5,
    date: "2026.04.13",
    variant: "900벤치",
    content: "설치 기사님이 수평까지 맞춰주고 가셔서 편했어요. 마감 상태도 훌륭합니다.",
  },
  {
    id: "r-a13",
    userName: "on*****",
    rating: 5,
    date: "2026.04.04",
    variant: "900벤치",
    content: "2인용으로 딱 좋은 크기라 신혼집에 잘 맞았어요. 튼튼해서 안심하고 씁니다.",
  },
  {
    id: "r-a14",
    userName: "vs*****",
    rating: 5,
    date: "2026.03.26",
    variant: "900벤치",
    content: "가격대가 있지만 그만큼 소재와 마감이 좋아요. 만족스러운 구매였습니다.",
  },
  {
    id: "r-a15",
    userName: "rq*****",
    rating: 5,
    date: "2026.03.17",
    variant: "900벤치",
    content: "좁은 다이닝 공간에 의자 대신 벤치를 놓으니 훨씬 정돈된 느낌이에요. 시트도 편안합니다.",
  },
  {
    id: "r-a16",
    userName: "az*****",
    rating: 5,
    date: "2026.03.08",
    variant: "900벤치",
    content: "심플하면서 고급스러운 디자인이라 인테리어 포인트가 됐어요. 튼튼한 프레임이 믿음직합니다.",
    images: ["/images/reviews/1211120010/review-16-1.webp"],
  },
  {
    id: "r-a17",
    userName: "tf*****",
    rating: 5,
    date: "2026.02.27",
    variant: "900벤치",
    content: "설치까지 깔끔하게 마쳐주셔서 번거로움이 없었어요. 앉을 때마다 안정감이 느껴집니다.",
  },
  {
    id: "r-a18",
    userName: "gi*****",
    rating: 5,
    date: "2026.02.18",
    variant: "900벤치",
    content: "2인 식탁에 벤치 하나 더하니 훨씬 여유로운 다이닝 공간이 됐어요. 만족스러운 구매입니다.",
  },
  // ── 1800벤치 ──
  {
    id: "r-b01",
    userName: "uj*****",
    rating: 5,
    date: "2026.07.16",
    variant: "1800벤치",
    content: "가족 넷이 앉아도 넉넉한 사이즈예요. 원목 프레임이 무게감 있게 지지해줍니다.",
    images: ["/images/reviews/1211120011/review-01-1.webp"],
  },
  {
    id: "r-b02",
    userName: "nx*****",
    rating: 5,
    date: "2026.07.07",
    variant: "1800벤치",
    content: "긴 식탁에 맞춰 벤치로 배치했는데 훨씬 여유로운 좌석이 됐어요. 패브릭 시트도 편안합니다.",
  },
  {
    id: "r-b03",
    userName: "pw*****",
    rating: 5,
    date: "2026.06.28",
    variant: "1800벤치",
    content: "설치까지 전문 배송팀이 꼼꼼하게 해주셔서 만족스러웠어요. 마감도 훌륭합니다.",
  },
  {
    id: "r-b04",
    userName: "lc*****",
    rating: 5,
    date: "2026.06.19",
    variant: "1800벤치",
    content: "아이들과 함께 앉아도 넉넉해서 좋아요. 색상도 자연스럽게 잘 어울립니다.",
  },
  {
    id: "r-b05",
    userName: "fe*****",
    rating: 4,
    date: "2026.06.10",
    variant: "1800벤치",
    content: "전체적으로 만족하는데 배송 일정이 한 번 조율됐어요. 제품 완성도는 훌륭합니다.",
  },
  {
    id: "r-b06",
    userName: "on*****",
    rating: 5,
    date: "2026.06.01",
    variant: "1800벤치",
    content: "긴 식탁 한쪽을 벤치로 바꾸니 손님 초대할 때 훨씬 편해요. 튼튼한 프레임이 믿음직합니다.",
    images: ["/images/reviews/1211120011/review-06-1.webp"],
  },
  {
    id: "r-b07",
    userName: "vs*****",
    rating: 5,
    date: "2026.05.23",
    variant: "1800벤치",
    content: "가족 모임이 많은 집이라 넉넉한 좌석이 필요했는데 딱 맞았어요. 시트 쿠션도 편안합니다.",
    images: ["/images/reviews/1211120011/review-07-1.webp"],
  },
  {
    id: "r-b08",
    userName: "rq*****",
    rating: 5,
    date: "2026.05.14",
    variant: "1800벤치",
    content: "원목 프레임의 무게감이 고급스러워요. 설치도 깔끔하게 마쳐주셨습니다.",
  },
  {
    id: "r-b09",
    userName: "az*****",
    rating: 5,
    date: "2026.05.05",
    variant: "1800벤치",
    content: "3~4인이 앉아도 여유로운 사이즈라 만족해요. 패브릭 컬러도 차분합니다.",
  },
  {
    id: "r-b10",
    userName: "tf*****",
    rating: 5,
    date: "2026.04.26",
    variant: "1800벤치",
    content: "긴 다이닝 테이블과 함께 두니 완성도 높은 공간이 됐어요. 마감도 꼼꼼합니다.",
  },
  {
    id: "r-b11",
    userName: "gi*****",
    rating: 5,
    date: "2026.04.17",
    variant: "1800벤치",
    content: "아이들 등하교 준비할 때 다 같이 앉기 좋아요. 튼튼해서 안심하고 씁니다.",
    images: ["/images/reviews/1211120011/review-11-1.webp"],
  },
  {
    id: "r-b12",
    userName: "uj*****",
    rating: 4,
    date: "2026.04.08",
    variant: "1800벤치",
    content: "가격은 있지만 그만큼 고급스러운 소재감이에요. 다만 배송이 하루 늦어 아쉬웠습니다.",
  },
  {
    id: "r-b13",
    userName: "nx*****",
    rating: 5,
    date: "2026.03.30",
    variant: "1800벤치",
    content: "긴 벤치라 손님 초대가 잦은 집에 정말 유용해요. 설치까지 깔끔하게 끝났습니다.",
  },
  {
    id: "r-b14",
    userName: "pw*****",
    rating: 5,
    date: "2026.03.21",
    variant: "1800벤치",
    content: "가족 모두 만족한 구매였어요. 넉넉한 사이즈 덕분에 다이닝 공간이 여유로워졌습니다.",
  },
  // ── 2520 라운지세트 ──
  {
    id: "r-c01",
    userName: "lc*****",
    rating: 5,
    date: "2026.07.11",
    variant: "2520 라운지세트",
    content: "라운지 소파처럼 편안해서 다이닝 겸 거실 공간으로 쓰고 있어요. 큰 사이즈라 존재감도 확실합니다.",
    images: ["/images/reviews/1211120012/review-01-1.webp", "/images/reviews/1211120012/review-01-2.webp"],
  },
  {
    id: "r-c02",
    userName: "fe*****",
    rating: 5,
    date: "2026.07.01",
    variant: "2520 라운지세트",
    content: "가격은 높지만 그만큼 완성도와 편안함이 남달라요. 등받이 쿠션 덕분에 오래 앉아도 편합니다.",
    images: ["/images/reviews/1211120012/review-02-1.webp"],
  },
  {
    id: "r-c03",
    userName: "hj*****",
    rating: 5,
    date: "2026.06.21",
    variant: "2520 라운지세트",
    content: "설치팀이 정말 꼼꼼하게 조립해주셨어요. 넓은 공간에 두니 카페 라운지 같은 분위기가 납니다.",
  },
  {
    id: "r-c04",
    userName: "sm*****",
    rating: 5,
    date: "2026.06.11",
    variant: "2520 라운지세트",
    content: "가족 모임할 때 다 같이 편하게 앉을 수 있어서 좋아요. 쿠션감이 너무 좋아요.",
    images: ["/images/reviews/1211120012/review-02-1.webp"],
  },
  {
    id: "r-c05",
    userName: "kt*****",
    rating: 4,
    date: "2026.06.01",
    variant: "2520 라운지세트",
    content: "전체적으로 만족하는데 부피가 커서 운반 경로 확인이 꼭 필요해요. 제품 자체는 훌륭합니다.",
  },
  {
    id: "r-c06",
    userName: "yn*****",
    rating: 5,
    date: "2026.05.22",
    variant: "2520 라운지세트",
    content: "넓은 다이닝룸에 포인트 가구로 놓았는데 반응이 좋아요. 편안함도 기대 이상입니다.",
    images: ["/images/reviews/1211120012/review-06-1.webp"],
  },
  {
    id: "r-c07",
    userName: "dw*****",
    rating: 5,
    date: "2026.05.12",
    variant: "2520 라운지세트",
    content: "라운지 느낌을 원했는데 정확히 그 느낌이에요. 가격이 있는 만큼 소재도 고급스럽습니다.",
  },
  {
    id: "r-c08",
    userName: "bg*****",
    rating: 5,
    date: "2026.05.02",
    variant: "2520 라운지세트",
    content: "손님들이 앉을 때마다 편안하다고 감탄해요. 큰 사이즈라 존재감이 확실합니다.",
  },
  {
    id: "r-c09",
    userName: "ej*****",
    rating: 5,
    date: "2026.04.22",
    variant: "2520 라운지세트",
    content: "다이닝과 거실 사이 공간에 두니 두 공간을 자연스럽게 이어줘요. 만족스러운 구매였습니다.",
  },
];

export const sharedReviews: ReviewData = {
  ...calculateReviewSummary(reviewItems),
  items: reviewItems,
};

export const sharedQnaItems: QnaItem[] = [
  {
    id: "q-a01",
    category: "상품",
    question: "900벤치는 성인 2명이 앉기에 넉넉한가요?",
    questioner: "dg*****",
    date: "2026.06.20",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 폭 900mm로 성인 2명이 나란히 앉기에 적당한 사이즈입니다. 감사합니다.",
    answerDate: "2026.06.21",
  },
  {
    id: "q-b01",
    category: "상품",
    question: "1800벤치는 최대 몇 명까지 앉을 수 있나요?",
    questioner: "sk*****",
    date: "2026.06.05",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 성인 기준 3~4명까지 편안하게 앉으실 수 있습니다. 감사합니다.",
    answerDate: "2026.06.06",
  },
  {
    id: "q-c01",
    category: "상품",
    question: "2520 라운지벤치 세트는 등받이 쿠션이 분리되나요?",
    questioner: "wm*****",
    date: "2026.05.22",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 등받이 쿠션은 커버 분리가 가능해 세탁 후 재사용하실 수 있습니다. 감사합니다.",
    answerDate: "2026.05.23",
  },
  {
    id: "q-a02",
    category: "배송",
    question: "조립도 배송팀이 다 해주시나요?",
    questioner: "hf*****",
    date: "2026.05.08",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 전문 배송팀이 방문하여 조립과 설치까지 완료해 드립니다. 감사합니다.",
    answerDate: "2026.05.09",
  },
  {
    id: "q-b02",
    category: "상품",
    question: "패브릭 색상이 900벤치와 동일한가요?",
    questioner: "zb*****",
    date: "2026.04.20",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 전 사이즈 동일한 패브릭 색상으로 제작되어 함께 배치해도 톤이 어긋나지 않습니다. 감사합니다.",
    answerDate: "2026.04.21",
  },
  {
    id: "q-c02",
    category: "배송",
    question: "2520 세트는 운반 시 엘리베이터 크기 제한이 있나요?",
    questioner: "ip*****",
    date: "2026.04.05",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 부피가 큰 편이라 사전에 엘리베이터·계단 폭을 확인해 주시고, 필요시 배송팀과 사전 협의해 주세요. 감사합니다.",
    answerDate: "2026.04.06",
  },
  {
    id: "q-b03",
    category: "기타",
    question: "1800벤치를 벽에 붙여서 사용해도 되나요?",
    questioner: "oc*****",
    date: "2026.03.18",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 벽면에 붙여 사용하셔도 무방하며, 등받이가 없는 구조라 양쪽에서 모두 착석 가능합니다. 감사합니다.",
    answerDate: "2026.03.19",
  },
  {
    id: "q-a03",
    category: "배송",
    question: "900벤치 재구매 시 앞서 구매한 것과 색상 편차가 있을까요?",
    questioner: "gt*****",
    date: "2026.07.17",
    answered: false,
  },
];
