import type { ReviewData, QnaItem, Review } from "@/app/lib/types";
import { calculateReviewSummary } from "@/lib/reviews";

// 16 reviews: 11×5 + 5×4 = avg 4.6875 → 4.7
const reviewItems: Review[] = [
  {
    id: "r-a01",
    userName: "pk*****",
    rating: 5,
    date: "2026.05.14",
    variant: "아이보리",
    content: "거실에 놓으니 너무 예뻐요. 소파랑 색감이 잘 어울립니다.",
    images: ["/images/reviews/1111110010/review-01-1.webp"],
  },
  {
    id: "r-a02",
    userName: "sh*****",
    rating: 5,
    date: "2026.04.22",
    variant: "아이보리",
    content: "상판이 넓어서 실용적이고 디자인도 깔끔합니다.",
    images: ["/images/reviews/1111110010/review-02-1.webp"],
  },
  {
    id: "r-a03",
    userName: "jm*****",
    rating: 5,
    date: "2026.03.10",
    variant: "화이트마블",
    content: "마블 패턴이 고급스러워서 만족합니다. 배송도 빠르고 설치도 깔끔하게 해주셨어요.",
    images: ["/images/reviews/1111110010/review-03-1.webp"],
  },
  {
    id: "r-a04",
    userName: "hy*****",
    rating: 5,
    date: "2026.02.18",
    variant: "아이보리",
    content: "튼튼하고 마감이 깔끔합니다. 아이보리 색상이 밝고 좋아요.",
  },
  {
    id: "r-a05",
    userName: "ck*****",
    rating: 5,
    date: "2026.01.07",
    variant: "화이트마블",
    content: "깔끔하고 고급스러운 느낌이에요. 공간이 화사해졌어요.",
    images: ["/images/reviews/1111110010/review-05-1.webp"],
  },
  {
    id: "r-a06",
    userName: "br*****",
    rating: 5,
    date: "2025.12.30",
    variant: "아이보리",
    content: "기대 이상으로 완성도가 높습니다.",
  },
  {
    id: "r-a07",
    userName: "yj*****",
    rating: 5,
    date: "2025.11.24",
    variant: "아이보리",
    content: "디자인이 세련되고 조립도 어렵지 않았어요.",
  },
  {
    id: "r-a08",
    userName: "hs*****",
    rating: 5,
    date: "2025.10.15",
    variant: "화이트마블",
    content: "소파 앞에 두니 인테리어 포인트가 됩니다.",
  },
  {
    id: "r-a09",
    userName: "nk*****",
    rating: 5,
    date: "2025.09.01",
    variant: "아이보리",
    content: "마감 품질이 좋고 흔들림 없이 안정적이에요.",
  },
  {
    id: "r-a10",
    userName: "wj*****",
    rating: 5,
    date: "2025.08.20",
    variant: "아이보리",
    content: "한샘 제품은 항상 믿고 삽니다. 이번에도 만족스럽네요.",
  },
  {
    id: "r-a11",
    userName: "dl*****",
    rating: 5,
    date: "2025.07.11",
    variant: "화이트마블",
    content: "사진보다 실물이 더 예뻐요.",
  },
  {
    id: "r-a12",
    userName: "sm*****",
    rating: 4,
    date: "2025.06.05",
    variant: "아이보리",
    content: "전체적으로 만족스럽지만 상판 두께가 조금 더 두꺼웠으면 좋겠어요.",
  },
  {
    id: "r-a13",
    userName: "gr*****",
    rating: 4,
    date: "2025.05.17",
    variant: "아이보리",
    content: "디자인은 좋은데 배송 시간이 예상보다 조금 길었습니다.",
  },
  {
    id: "r-a14",
    userName: "bj*****",
    rating: 4,
    date: "2025.04.09",
    variant: "화이트마블",
    content: "고급스럽고 예쁩니다. 가격 대비 괜찮아요.",
  },
  {
    id: "r-a15",
    userName: "km*****",
    rating: 4,
    date: "2025.03.22",
    variant: "아이보리",
    content: "전반적으로 만족합니다.",
  },
  {
    id: "r-a16",
    userName: "jh*****",
    rating: 4,
    date: "2025.02.14",
    variant: "아이보리",
    content: "다용도로 쓰기 좋습니다. 서랍 마감이 좀 더 부드러웠으면 해요.",
  },
];

export const sharedReviews: ReviewData = {
  ...calculateReviewSummary(reviewItems),
  items: reviewItems,
};

export const sharedQnaItems: QnaItem[] = [
  {
    id: "q-a01",
    category: "상품",
    question: "화이트마블 옵션의 상판은 진짜 대리석인가요, 아니면 패턴 인쇄인가요?",
    questioner: "pk*****",
    date: "2026.03.01",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 화이트마블 옵션의 상판은 대리석 패턴이 인쇄된 MDF 상판입니다. 천연 대리석이 아니므로 무게 부담 없이 가볍게 사용하실 수 있습니다. 추가 문의 사항은 고객센터(1688-4945)로 연락 주시면 안내드리겠습니다. 감사합니다.",
    answerDate: "2026.03.02",
  },
];
