import type { ReviewData, QnaItem, Review } from "@/app/lib/types";
import { calculateReviewSummary } from "@/lib/reviews";

const reviewItems: Review[] = [
  {
    id: "r-a01",
    userName: "yj*****",
    rating: 5,
    date: "2026.07.16",
    variant: "600ml",
    content: "국물 반찬을 담아도 새는 일이 전혀 없어요. 스텐이라 냄새도 안 배고 세척도 편합니다.",
    images: ["/images/reviews/1711110010/review-01-1.webp"],
  },
  {
    id: "r-a02",
    userName: "ks*****",
    rating: 5,
    date: "2026.07.02",
    variant: "1080ml",
    content: "1080ml로 카레를 소분해서 얼렸는데 색 배임 없이 깨끗하게 쓰고 있어요. 다음엔 큰 사이즈도 추가 구매할 예정입니다.",
  },
  {
    id: "r-a03",
    userName: "th*****",
    rating: 4,
    date: "2026.06.20",
    variant: "1500ml",
    content: "4방 잠금이 꽤 튼튼해서 국물 요리도 안심하고 담습니다. 다만 무게가 있어서 여러 개 들면 손목이 조금 아파요.",
    images: ["/images/reviews/1711110010/review-03-1.webp", "/images/reviews/1711110010/review-03-2.webp"],
  },
  {
    id: "r-a04",
    userName: "ny*****",
    rating: 5,
    date: "2026.06.05",
    variant: "600ml",
    content: "600ml는 밑반찬용으로 딱 좋은 크기예요. 냉장고에 여러 개 쌓아둬도 자리를 깔끔하게 차지합니다.",
  },
  {
    id: "r-a05",
    userName: "ig*****",
    rating: 5,
    date: "2026.05.24",
    variant: "1500ml",
    content: "1500ml로 국을 넉넉하게 소분해서 냉동 보관하고 있어요. 재가열해도 변형이 없어서 안심하고 씁니다.",

  },
  {
    id: "r-a06",
    userName: "ce*****",
    rating: 3,
    date: "2026.05.11",
    variant: "1080ml",
    content: "제품은 튼튼한데 배송이 하루 지연됐어요. 밀폐력은 확실해서 계속 쓸 것 같습니다.",
  },
  {
    id: "r-a07",
    userName: "dm*****",
    rating: 5,
    date: "2026.04.28",
    variant: "600ml",
    content: "예전에 쓰던 플라스틱 용기보다 훨씬 위생적인 느낌이에요. 김치를 담아도 색이 남지 않아서 만족합니다.",
  },
  {
    id: "r-a08",
    userName: "ru*****",
    rating: 4,
    date: "2026.04.14",
    variant: "1080ml",
    content: "세 가지 용량을 골고루 구매해서 용도별로 나눠 쓰고 있어요. 뚜껑 여닫는 손맛이 좋습니다.",
    images: ["/images/reviews/1711110010/review-08-1.webp"],
  },
  {
    id: "r-a09",
    userName: "ao*****",
    rating: 5,
    date: "2026.03.30",
    variant: "600ml",
    content: "스텐이라 전자레인지는 못 쓰지만 냉장고 반찬통으로는 최고예요. 세척 후에도 얼룩 없이 깨끗합니다.",
  },
  {
    id: "r-a10",
    userName: "wl*****",
    rating: 5,
    date: "2026.03.15",
    variant: "1080ml",
    content: "1080ml 용량이 국 한 끼 분량으로 딱 맞아요. 도시락 반찬통으로도 유용하게 쓰고 있습니다.",
    images: ["/images/reviews/1711110010/review-10-1.webp"],
  },
  {
    id: "r-a11",
    userName: "qb*****",
    rating: 4,
    date: "2026.02.27",
    variant: "1500ml",
    content: "밀폐력은 확실한데 크기가 큰 편이라 냉장고 칸에 맞춰 배치가 필요해요. 그래도 재구매 의향 있습니다.",
  },
  {
    id: "r-a12",
    userName: "ef*****",
    rating: 5,
    date: "2026.02.10",
    variant: "600ml",
    content: "선물용으로도 구매했는데 반응이 좋았어요. 스텐 재질이라 고급스러운 느낌도 납니다.",
  },
  {
    id: "r-a13",
    userName: "xh*****",
    rating: 5,
    date: "2026.01.24",
    variant: "1500ml",
    content: "국물 요리 소분에 이만한 게 없어요. 클립도 여러 번 여닫아도 헐거워지지 않습니다.",
  },
  {
    id: "r-a14",
    userName: "ov*****",
    rating: 4,
    date: "2026.01.09",
    variant: "1080ml",
    content: "600ml, 1080ml 두 개씩 구매해서 잘 쓰고 있어요. 다만 가격이 조금 있는 편이라 세일 때 더 사고 싶습니다.",
  },
  {
    id: "r-a15",
    userName: "yk*****",
    rating: 5,
    date: "2025.12.22",
    variant: "600ml",
    content: "밀폐력 덕분에 국물이 새서 냉장고를 더럽힐 걱정이 없어졌어요. 세척도 스텐이라 냄새 없이 깔끔합니다.",
  },
  {
    id: "r-a16",
    userName: "bs*****",
    rating: 5,
    date: "2025.12.05",
    variant: "1500ml",
    content: "1500ml로 카레와 국을 번갈아 소분하고 있어요. 튼튼해서 오래 쓸 수 있을 것 같습니다.",
  },
  {
    id: "r-a17",
    userName: "ml*****",
    rating: 4,
    date: "2025.11.18",
    variant: "1080ml",
    content: "생각보다 뚜껑이 뻑뻑해서 처음엔 힘이 좀 필요했어요. 몇 번 쓰니 부드러워져서 지금은 만족하며 쓰고 있습니다.",
  },
];

export const sharedReviews: ReviewData = {
  ...calculateReviewSummary(reviewItems),
  items: reviewItems,
};

export const sharedQnaItems: QnaItem[] = [
  {
    id: "q-a01",
    category: "배송",
    question: "세 가지를 주문했는데 하나씩 담아서 배송되나요, 아니면 옵션 선택한 용량이 한꺼번에 오나요?",
    questioner: "ip*****",
    date: "2026.07.02",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 동일 주소지로 주문한 제품들은 한 박스에 담겨 일괄 배송됩니다. 다만, 부피가 큰 상품들은 구매 수량에 따라 분리 배송 될 수 있습니다. 감사합니다.",
    answerDate: "2026.07.04",
  },
  {
    id: "q-a02",
    category: "상품",
    question: "전자레인지에 넣어서 데워도 되나요?",
    questioner: "gt*****",
    date: "2026.05.11",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 스테인리스 소재 특성상 전자레인지 사용은 불가하며, 가스레인지·인덕션 직화 조리도 권장하지 않습니다. 내용물을 다른 그릇에 옮겨 데워 주세요. 감사합니다.",
    answerDate: "2026.05.12",
  },
];
