import type { ReviewData, QnaItem, Review } from "@/app/lib/types";
import { calculateReviewSummary } from "@/lib/reviews";

const reviewItems: Review[] = [
  // ── 단품 ──
  {
    id: "r-a01",
    userName: "hj*****",
    rating: 5,
    date: "2026.07.19",
    variant: "단품 / 베이지 / M",
    content: "화장대 한쪽 공간에 딱 맞게 넣었더니 화장품들이 한눈에 정리됐어요. 슬라이딩으로 앞뒤로 밀어 쓰니 안쪽 물건도 꺼내기 편합니다.",
    images: ["/images/reviews/1711100010/review-01-1.webp"],
  },
  {
    id: "r-a02",
    userName: "sm*****",
    rating: 5,
    date: "2026.07.10",
    variant: "단품 / 화이트 / L",
    content: "마감도 고급스럽고 좋네요. 더 주문해서 서랍 안을 통째로 정리해야겠어요.",
  },
  {
    id: "r-a03",
    userName: "kt*****",
    rating: 4,
    date: "2026.07.01",
    variant: "단품 / 화이트 / M",
    content: "생각보다 튼튼해서 화장품을 넣어도 서랍이 잘 열립니다. 다만 손잡이 부분이 조금 더 크면 좋겠어요.",
    images: ["/images/reviews/1711100010/review-03-1.webp"],
  },
  {
    id: "r-a04",
    userName: "yn*****",
    rating: 5,
    date: "2026.06.23",
    variant: "단품 / 화이트 / M",
    content: "M 사이즈로 주문했는데 딱 맞게 주문했네요. 좁은 공간도 서랍처럼 쓸 수 있어서 만족합니다.",
    images: ["/images/reviews/1711100010/review-04-1.webp"],
  },
  {
    id: "r-a05",
    userName: "dw*****",
    rating: 5,
    date: "2026.06.14",
    variant: "단품 / 화이트 / L",
    content: "화이트 색상이 주방 톤이랑 잘 어울려서 군데군데 둬도 괜찮아요. 적층해도 안정감 있게 잘 고정됩니다.",
    images: ["/images/reviews/1711100010/review-05-1.webp", "/images/reviews/1711100010/review-05-2.webp"],
  },
  {
    id: "r-a06",
    userName: "bg*****",
    rating: 3,
    date: "2026.06.05",
    variant: "단품 / 베이지 / M",
    content: "제품 자체는 괜찮은데 배송이 예상보다 이틀 늦게 왔어요. 정리 효과는 확실해서 재구매 의향은 있습니다.",
  },
  {
    id: "r-a07",
    userName: "ej*****",
    rating: 5,
    date: "2026.05.27",
    variant: "단품 / 베이지 / L",
    content: "베이지 컬러로 주문했는데 실물이 사진보다 더 은은하고 고급스러워요. 팬트리 선반에 올려두니 분위기가 달라졌습니다.",
  },
  {
    id: "r-a08",
    userName: "ps*****",
    rating: 4,
    date: "2026.05.18",
    variant: "단품 / 화이트 / L",
    content: "슬라이딩이 처음엔 살짝 뻑뻑했는데 며칠 쓰니 부드러워졌어요. 사용에는 전혀 문제없습니다.",
  },
  {
    id: "r-a09",
    userName: "wc*****",
    rating: 5,
    date: "2026.05.09",
    variant: "단품 / 화이트 / M",
    content: "자취방 좁은 싱크대 서랍을 이걸로 구획 나눠서 쓰고 있어요. 크기도 딱 맞고 청소도 쉬워서 만족스럽습니다.",
  },
  {
    id: "r-a10",
    userName: "mr*****",
    rating: 5,
    date: "2026.04.30",
    variant: "단품 / 베이지 / L",
    content: "L 사이즈로 큰 봉지 라면이랑 각종 파우치 제품을 담았는데 넉넉하게 들어갑니다. 냄새도 안 배어서 좋아요.",
  },
  {
    id: "r-a11",
    userName: "hb*****",
    rating: 4,
    date: "2026.04.21",
    variant: "단품 / 베이지 / M",
    content: "가격 대비 마감이 깔끔한 편이에요. 다만 색상이 두 가지뿐이라 선택지가 조금 더 다양했으면 합니다.",
    images: ["/images/reviews/1711100010/review-11-1.webp"],
  },
  {
    id: "r-a12",
    userName: "jy*****",
    rating: 5,
    date: "2026.04.12",
    variant: "단품 / 화이트 / L",
    content: "이사하면서 새 주방에 맞춰 여러 개 구매했는데 사이즈별로 조합하니 수납이 확 늘었어요. 다음에도 여기서 구매할 것 같습니다.",
  },
  // ── 1+1 구성 ──
  {
    id: "r-b01",
    userName: "on*****",
    rating: 5,
    date: "2026.07.15",
    variant: "1+1 / 화이트 / M",
    content: "1+1이라 두 개를 색상 다르게 받아서 위아래 칸을 구분해 썼어요. 가성비가 정말 좋습니다.",
    images: ["/images/reviews/1711100011/review-01-1.webp", "/images/reviews/1711100011/review-01-2.webp"],
  },
  {
    id: "r-b02",
    userName: "vs*****",
    rating: 5,
    date: "2026.07.05",
    variant: "1+1 / 베이지 / L",
    content: "부모님 댁 냉장고 정리에 하나, 저희 집에 하나 나눠 썼어요. 두 집 다 만족해서 다음엔 더 주문할 계획입니다.",
  },
  {
    id: "r-b03",
    userName: "rq*****",
    rating: 4,
    date: "2026.06.27",
    variant: "1+1 / 화이트 / M",
    content: "구성 두 개가 와서 넉넉하게 정리했는데 하나는 M 하나는 L로 나눠 담으니 훨씬 효율적이에요. 포장도 각각 잘 되어 있었습니다.",
  },
  {
    id: "r-b04",
    userName: "az*****",
    rating: 5,
    date: "2026.06.18",
    variant: "1+1 / 화이트 / L",
    content: "화이트 두 개로 주문해서 통일감 있게 정리했어요. 슬라이딩 방식이라 안쪽까지 꺼내기 편합니다.",
  },
  {
    id: "r-b05",
    userName: "tf*****",
    rating: 3,
    date: "2026.06.09",
    variant: "1+1 / 베이지 / L",
    content: "제품은 만족하는데 박스 하나가 배송 중 살짝 눌려서 왔어요. 사용에는 지장 없어서 그대로 쓰고 있습니다.",
    images: ["/images/reviews/1711100011/review-05-1.webp"],
  },
  {
    id: "r-b06",
    userName: "gi*****",
    rating: 5,
    date: "2026.05.31",
    variant: "1+1 / 화이트 / M",
    content: "1+1으로 사서 싱크대 상부장, 하부장에 각각 넣었어요. 같은 디자인이라 주방 전체가 정돈된 느낌입니다.",
    images: ["/images/reviews/1711100011/review-06-1.webp"],
  },
  {
    id: "r-b07",
    userName: "uj*****",
    rating: 5,
    date: "2026.05.22",
    variant: "1+1 / 베이지 / L",
    content: "베이지 하나 화이트 하나로 받아서 용도별로 구분해 쓰고 있어요. 미니멀한 디자인이라 어디에 둬도 튀지 않습니다.",
  },
  {
    id: "r-b08",
    userName: "nx*****",
    rating: 4,
    date: "2026.05.13",
    variant: "1+1 / 화이트 / M",
    content: "두 개 다 슬라이딩이 매끄럽고 튼튼해요. 다만 사이즈 옵션 표기가 조금 더 명확했으면 좋겠어요.",
  },
  {
    id: "r-b09",
    userName: "pw*****",
    rating: 5,
    date: "2026.05.04",
    variant: "1+1 / 베이지 / L",
    content: "혼자 살아서 하나는 주방, 하나는 화장실 수납으로 쓰고 있어요. 어디에 둬도 잘 어울리는 디자인입니다.",
  },
  {
    id: "r-b10",
    userName: "lc*****",
    rating: 5,
    date: "2026.04.25",
    variant: "1+1 / 화이트 / M",
    content: "가격이 단품보다 훨씬 이득이라 망설임 없이 구매했어요. 정리 효과도 확실하고 배송도 빨랐습니다.",
    images: ["/images/reviews/1711100011/review-10-1.webp"],
  },
  {
    id: "r-b11",
    userName: "fe*****",
    rating: 4,
    date: "2026.04.16",
    variant: "1+1 / 베이지 / L",
    content: "실용적인 제품이라 만족합니다. 다음엔 다른 사이즈 조합으로 추가 구매할 예정이에요.",
  },
];

export const sharedReviews: ReviewData = {
  ...calculateReviewSummary(reviewItems),
  items: reviewItems,
};

export const sharedQnaItems: QnaItem[] = [
  {
    id: "q-a01",
    category: "상품",
    question: "M이랑 L 사이즈 실측 크기가 어떻게 되나요? 싱크대 하부장에 들어갈지 궁금합니다.",
    questioner: "dg*****",
    date: "2026.06.24",
    answered: true,
    answer: "안녕하세요, 한샘입니다. M 사이즈는 가로 26 x 세로 16 x 높이 12cm, L 사이즈는 가로 32 x 세로 20 x 높이 14cm입니다. 구매 전 수납 공간 치수를 먼저 확인해 주세요. 감사합니다.",
    answerDate: "2026.06.25",
  },
  {
    id: "q-b01",
    category: "상품",
    question: "1+1 구성은 같은 사이즈로만 받을 수 있나요, 아니면 M/L 섞어서 받을 수 있나요?",
    questioner: "sk*****",
    date: "2026.06.10",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 1+1 구성은 옵션에서 선택하신 사이즈 기준으로 동일하게 두 개가 발송됩니다. M/L을 섞어 받고 싶으시면 단품을 각각 주문해 주세요. 감사합니다.",
    answerDate: "2026.06.11",
  },
  {
    id: "q-a02",
    category: "배송",
    question: "화이트로 주문했는데 배송은 얼마나 걸리나요?",
    questioner: "wm*****",
    date: "2026.05.15",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 주문 후 영업일 기준 2~3일 내 출고되며, 도서산간 지역은 1~2일 추가될 수 있습니다. 감사합니다.",
    answerDate: "2026.05.15",
  },
  {
    id: "q-b02",
    category: "상품",
    question: "냉동실에 넣어도 변형되지 않나요?",
    questioner: "hf*****",
    date: "2026.04.28",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 냉장·냉동 환경에서 사용 가능한 식품용 PP 소재로 제작되어 변형 걱정 없이 사용하실 수 있습니다. 다만 전자레인지·오븐 등 고온 조리기구에는 사용하지 말아주세요. 감사합니다.",
    answerDate: "2026.04.29",
  },
  {
    id: "q-a03",
    category: "기타",
    question: "재입고 시 다른 색상도 추가될 예정인가요?",
    questioner: "zb*****",
    date: "2026.07.18",
    answered: false,
  },
];
