import type { ReviewData, QnaItem, Review } from "@/app/lib/types";
import { calculateReviewSummary } from "@/lib/reviews";

const reviewItems: Review[] = [
  {
    id: "r-a01",
    userName: "sh*****",
    rating: 5,
    date: "2026.07.04",
    variant: "테이블+플로어",
    content: "침실 협탁과 거실 소파 옆에 나눠 뒀는데 집 전체 무드가 통일됐어요. 패브릭을 거친 빛이 정말 아늑합니다.",
    images: ["/images/reviews/1713100020/review-01-1.webp"],
  },
  {
    id: "r-a02",
    userName: "kj*****",
    rating: 5,
    date: "2026.06.25",
    variant: "테이블+플로어",
    content: "어떤 인테리어에도 묻어가는 디자인이라 실패가 없어요. 세트 구성이라 가격도 합리적입니다.",
  },
  {
    id: "r-a03",
    userName: "mw*****",
    rating: 4,
    date: "2026.06.16",
    variant: "테이블+플로어",
    content: "빛과 디자인은 만족스러운데 플로어 램프 조립 시 셰이드 수평 맞추는 게 살짝 까다로웠어요. 완성 후엔 아주 만족합니다.",
  },
  {
    id: "r-a04",
    userName: "db*****",
    rating: 5,
    date: "2026.06.07",
    variant: "테이블+플로어",
    content: "자기 전 메인 등 대신 켜는 용도로 샀는데 수면 루틴이 좋아졌어요. 은은한 빛이 눈에 부담이 없습니다.",
  },
  {
    id: "r-a05",
    userName: "yf*****",
    rating: 5,
    date: "2026.05.29",
    variant: "테이블+플로어",
    content: "원목 가구가 많은 집인데 셰이드 질감이 잘 어우러져요. 낮에도 오브제처럼 예쁩니다.",
    images: ["/images/reviews/1713100020/review-05-1.webp", "/images/reviews/1713100020/review-05-2.webp"],
  },
  {
    id: "r-a06",
    userName: "wc*****",
    rating: 5,
    date: "2026.05.20",
    variant: "테이블+플로어",
    content: "이사 선물로 받았는데 제일 잘 쓰는 살림이 됐어요. 켜두기만 해도 집이 정돈돼 보입니다.",
  },
  {
    id: "r-a07",
    userName: "cl*****",
    rating: 3,
    date: "2026.05.11",
    variant: "테이블+플로어",
    content: "무드는 좋은데 밝기 조절이 안 되는 게 아쉬워요. 디머 전구로 교체해서 쓰니 해결되긴 했습니다.",
  },
  {
    id: "r-a08",
    userName: "hv*****",
    rating: 5,
    date: "2026.05.02",
    variant: "테이블+플로어",
    content: "화이트 톤 침실에 두니 호텔 객실 같아요. 스틸 바디 마감이 가격대 이상으로 고급스럽습니다.",
  },
  {
    id: "r-a09",
    userName: "tp*****",
    rating: 5,
    date: "2026.04.23",
    variant: "테이블+플로어",
    content: "재택 사무 공간 구석에 플로어를 두었는데 화상회의 때 조명빨이 좋아졌다는 말을 들어요. 뜻밖의 효과입니다.",
    images: ["/images/reviews/1713100020/review-09-1.webp"],
  },
  {
    id: "r-a10",
    userName: "lg*****",
    rating: 5,
    date: "2026.04.14",
    variant: "테이블+플로어",
    content: "셰이드 분리가 쉬워서 먼지 관리가 편해요. 패브릭 조명 걱정했던 부분이 깔끔하게 해결됐습니다.",
  },
  {
    id: "r-a11",
    userName: "bq*****",
    rating: 5,
    date: "2026.04.05",
    variant: "테이블+플로어",
    content: "거실 조도가 낮아 고민이었는데 플로어 램프 하나로 사각지대가 사라졌어요. 늦은 밤 거실이 포근해집니다.",
  },
  {
    id: "r-a12",
    userName: "kx*****",
    rating: 5,
    date: "2026.03.27",
    variant: "테이블+플로어",
    content: "부모님 댁 안방에 선물했어요. 스위치가 발로도 눌리는 위치라 어르신들이 쓰기 편하다고 하십니다.",
  },
  {
    id: "r-a13",
    userName: "ns*****",
    rating: 5,
    date: "2026.03.18",
    variant: "테이블+플로어",
    content: "미니멀한 디자인 찾다가 정착했어요. 존재감을 뽐내지 않으면서 공간을 완성하는 조명입니다.",
  },
  {
    id: "r-a14",
    userName: "ej*****",
    rating: 5,
    date: "2026.03.09",
    variant: "테이블+플로어",
    content: "세트라 망설임 없이 샀는데 결과적으로 두 공간이 해결됐어요. 가성비로도 감성으로도 추천합니다.",
  },
];

export const sharedReviews: ReviewData = {
  ...calculateReviewSummary(reviewItems),
  items: reviewItems,
};

export const sharedQnaItems: QnaItem[] = [
  {
    id: "q-a01",
    category: "상품",
    question: "밝기 조절(디밍) 기능이 있나요?",
    questioner: "ao*****",
    date: "2026.06.19",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 본 제품은 온·오프 스위치 방식으로 자체 디밍 기능은 없습니다. 다만 E26 규격 디머블 전구와 호환되어 전구 교체로 밝기 조절이 가능합니다. 감사합니다.",
    answerDate: "2026.06.20",
  },
  {
    id: "q-a02",
    category: "상품",
    question: "셰이드 컬러가 사진마다 달라 보이는데 실제 색상이 어떤가요?",
    questioner: "gy*****",
    date: "2026.06.02",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 셰이드는 아이보리에 가까운 내추럴 컬러이며, 점등 시 웜톤으로 조금 더 따뜻하게 보입니다. 상세 페이지 소재 컷을 참고 부탁드립니다. 감사합니다.",
    answerDate: "2026.06.03",
  },
  {
    id: "q-a03",
    category: "배송",
    question: "테이블 램프와 플로어 램프가 각각 다른 박스로 오나요?",
    questioner: "iw*****",
    date: "2026.05.15",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 세트 상품은 한 박스에 함께 포장되어 출고됩니다. 셰이드 보호를 위한 이중 완충 포장으로 발송되니 안심하셔도 됩니다. 감사합니다.",
    answerDate: "2026.05.16",
  },
  {
    id: "q-a04",
    category: "상품",
    question: "전선 길이가 어떻게 되나요? 콘센트가 멀어서요.",
    questioner: "um*****",
    date: "2026.04.27",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 전선 길이는 테이블 램프 1.8m, 플로어 램프 2.5m입니다. 배치 계획에 참고 부탁드립니다. 감사합니다.",
    answerDate: "2026.04.28",
  },
  {
    id: "q-a05",
    category: "기타",
    question: "쇼룸에서 실물을 볼 수 있는 매장이 있을까요?",
    questioner: "rc*****",
    date: "2026.07.06",
    answered: false,
  },
];
