import type { ReviewData, QnaItem, Review } from "@/app/lib/types";
import { calculateReviewSummary } from "@/lib/reviews";

const reviewItems: Review[] = [
  {
    id: "r-a01",
    userName: "hj*****",
    rating: 5,
    date: "2026.07.18",
    variant: "화이트 / 스툴",
    content: "화장대 앞에 스툴로 뒀는데 사이즈도 딱 맞고 예뻐요. 가벼워서 옮기기도 편합니다.",
    images: ["/images/reviews/1211120020/review-01-1.webp"],
  },
  {
    id: "r-a02",
    userName: "sm*****",
    rating: 5,
    date: "2026.07.07",
    variant: "블랙 / 체어",
    content: "홈바에 스툴로 뒀는데 심플해서 어디에나 잘 어울려요. 다리도 튼튼합니다.",
    images: ["/images/reviews/1211120020/review-02-1.webp", "/images/reviews/1211120020/review-02-2.webp"],
  },
  {
    id: "r-a03",
    userName: "kt*****",
    rating: 5,
    date: "2026.06.26",
    variant: "화이트 / 체어",
    content: "등받이가 있어서 식탁 의자로 쓰기 편해요. 화이트 컬러가 깔끔합니다.",
  },
  {
    id: "r-a04",
    userName: "yn*****",
    rating: 3,
    date: "2026.06.15",
    variant: "블랙 / 체어",
    content: "디자인은 마음에 드는데 체어 타입이라 추가금이 붙는 게 아쉬웠어요. 완성도는 나쁘지 않습니다.",
  },
  {
    id: "r-a05",
    userName: "dw*****",
    rating: 5,
    date: "2026.06.04",
    variant: "화이트 / 스툴",
    content: "가볍고 심플해서 여러 개 사서 화장대, 식탁에 나눠 쓰고 있어요. 만족스럽습니다.",
  },
  {
    id: "r-a06",
    userName: "bg*****",
    rating: 5,
    date: "2026.05.24",
    variant: "블랙 / 스툴",
    content: "블랙 스툴로 포인트를 주고 싶었는데 딱 맞는 디자인이에요. 다리 스틸이 고급스럽습니다.",
    images: ["/images/reviews/1211120020/review-06-1.webp"],
  },
  {
    id: "r-a07",
    userName: "ej*****",
    rating: 5,
    date: "2026.05.13",
    variant: "화이트 / 체어",
    content: "체어 타입으로 골랐는데 등받이 덕분에 오래 앉아도 편해요. 색상도 깨끗합니다.",
  },
  {
    id: "r-a08",
    userName: "ps*****",
    rating: 4,
    date: "2026.05.02",
    variant: "블랙 / 체어",
    content: "전반적으로 만족하는데 조립 설명서가 조금 부족했어요. 완성 후엔 튼튼합니다.",
  },
  {
    id: "r-a09",
    userName: "wc*****",
    rating: 5,
    date: "2026.04.21",
    variant: "화이트 / 스툴",
    content: "1개만 필요해서 스툴로 주문했는데 가성비가 좋아요. 심플한 디자인이 마음에 듭니다.",
  },
  {
    id: "r-a10",
    userName: "mr*****",
    rating: 5,
    date: "2026.04.10",
    variant: "블랙 / 스툴",
    content: "홈카페 공간에 블랙 스툴로 포인트를 줬어요. 무게도 가벼워서 이동이 편합니다.",
  },
  {
    id: "r-a11",
    userName: "hb*****",
    rating: 5,
    date: "2026.03.30",
    variant: "화이트 / 체어",
    content: "체어 타입이 생각보다 편안해서 만족스러워요. 화이트라 어디에 둬도 깔끔합니다.",
    images: ["/images/reviews/1211120020/review-11-1.webp"],
  },
  {
    id: "r-a12",
    userName: "jy*****",
    rating: 5,
    date: "2026.03.19",
    variant: "블랙 / 체어",
    content: "등받이가 있는 체어로 골랐는데 튼튼하고 안정감 있어요. 블랙이라 카페 느낌도 납니다.",
  },
  {
    id: "r-a13",
    userName: "on*****",
    rating: 3,
    date: "2026.03.08",
    variant: "화이트 / 스툴",
    content: "제품은 괜찮은데 배송이 예정보다 늦게 왔어요. 스툴 자체는 튼튼합니다.",
  },
  {
    id: "r-a14",
    userName: "vs*****",
    rating: 5,
    date: "2026.02.25",
    variant: "블랙 / 스툴",
    content: "가볍고 다용도로 쓸 수 있어서 여러 개 구매했어요. 다리 스틸 마감도 좋습니다.",
  },
  {
    id: "r-a15",
    userName: "rq*****",
    rating: 5,
    date: "2026.02.14",
    variant: "화이트 / 체어",
    content: "식탁 의자가 부족해서 체어 타입으로 추가 구매했어요. 기존 의자랑도 잘 어울립니다.",
  },
  {
    id: "r-a16",
    userName: "az*****",
    rating: 5,
    date: "2026.02.03",
    variant: "블랙 / 체어",
    content: "등받이 있는 타입이라 아이가 앉아도 안정적이에요. 만족스러운 구매였습니다.",
  },
];

export const sharedReviews: ReviewData = {
  ...calculateReviewSummary(reviewItems),
  items: reviewItems,
};

export const sharedQnaItems: QnaItem[] = [
  {
    id: "q-a01",
    category: "상품",
    question: "체어와 스툴 다리 길이가 같나요?",
    questioner: "dg*****",
    date: "2026.06.15",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 두 타입 모두 동일한 다리 구조와 높이로 제작되어 나란히 두어도 어색하지 않습니다. 감사합니다.",
    answerDate: "2026.06.16",
  },
  {
    id: "q-a02",
    category: "배송",
    question: "옵션에서 체어, 스툴을 섞어서 여러 개 주문할 수 있나요?",
    questioner: "sk*****",
    date: "2026.05.10",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 네, 주문 시 색상·타입을 각각 선택해 담으실 수 있어 원하는 조합으로 구성 가능합니다. 감사합니다.",
    answerDate: "2026.05.11",
  },
  {
    id: "q-a03",
    category: "배송",
    question: "화이트 스툴만 2개 주문하면 배송비가 어떻게 되나요?",
    questioner: "wm*****",
    date: "2026.07.14",
    answered: false,
  },
];
