import type { ReviewData, QnaItem, Review } from "@/app/lib/types";
import { calculateReviewSummary } from "@/lib/reviews";

const reviewItems: Review[] = [
  // ── 하부장 수납형 ──
  {
    id: "r-a01",
    userName: "hj*****",
    rating: 5,
    date: "2026.07.21",
    variant: "화이트 / 일반도어",
    content: "싱크대 아래 공간이 확 넓어졌어요. 화이트 컬러라 주방이 밝아 보입니다.",
    images: ["/images/reviews/1212100020/review-01-1.webp"],
  },
  {
    id: "r-a02",
    userName: "sm*****",
    rating: 5,
    date: "2026.07.12",
    variant: "메이플 / 유리도어",
    content: "유리도어라 안에 뭐가 있는지 바로 보여서 편해요. 자주 쓰는 그릇을 여기 뒀습니다.",
  },
  {
    id: "r-a03",
    userName: "kt*****",
    rating: 5,
    date: "2026.07.03",
    variant: "화이트 / 일반도어",
    content: "100cm라 수납량이 정말 넉넉해요. 설치도 깔끔하게 마쳐주셨습니다.",
  },
  {
    id: "r-a04",
    userName: "yn*****",
    rating: 5,
    date: "2026.06.24",
    variant: "메이플 / 일반도어",
    content: "조절 선반이라 냄비 크기에 맞춰 칸을 나눴어요. 메이플 컬러도 자연스럽습니다.",
    images: ["/images/reviews/1212100020/review-04-1.webp"],

  },
  {
    id: "r-a05",
    userName: "dw*****",
    rating: 5,
    date: "2026.06.15",
    variant: "화이트 / 유리도어",
    content: "유리도어 쪽에 자주 쓰는 컵을 뒀는데 꺼내기 편해요. 마감도 꼼꼼합니다.",
  },
  {
    id: "r-a06",
    userName: "bg*****",
    rating: 5,
    date: "2026.06.06",
    variant: "메이플 / 일반도어",
    content: "싱크대 하부가 정리되니 주방이 훨씬 넓어 보여요. 설치 기사님도 꼼꼼하셨습니다.",
    images: ["/images/reviews/1212100020/review-06-1.webp"],
  },
  {
    id: "r-a07",
    userName: "ej*****",
    rating: 5,
    date: "2026.05.28",
    variant: "화이트 / 유리도어",
    content: "물기 많은 공간인데도 변형 없이 튼튼해요. 유리도어 디자인도 세련됐습니다.",
  },
  {
    id: "r-a08",
    userName: "ps*****",
    rating: 4,
    date: "2026.05.19",
    variant: "메이플 / 일반도어",
    content: "전체적으로 만족하는데 설치 일정이 하루 밀렸어요. 완성도는 좋습니다.",
  },
  {
    id: "r-a09",
    userName: "wc*****",
    rating: 5,
    date: "2026.05.10",
    variant: "화이트 / 일반도어",
    content: "가성비 좋게 수납공간을 확 늘렸어요. 화이트라 어디에도 잘 어울립니다.",
  },
  {
    id: "r-a10",
    userName: "mr*****",
    rating: 5,
    date: "2026.05.01",
    variant: "메이플 / 유리도어",
    content: "유리도어로 골랐는데 안이 보여서 정리 습관도 좋아졌어요. 메이플 톤도 고급스럽습니다.",
  },
  {
    id: "r-a11",
    userName: "hb*****",
    rating: 5,
    date: "2026.04.22",
    variant: "화이트 / 유리도어",
    content: "100cm 하부장 덕분에 냄비를 다 넣을 수 있게 됐어요. 마감도 깔끔합니다.",
    images: ["/images/reviews/1212100020/review-11-1.webp", "/images/reviews/1212100020/review-11-2.webp"],
  },
  {
    id: "r-a12",
    userName: "jy*****",
    rating: 5,
    date: "2026.04.13",
    variant: "메이플 / 일반도어",
    content: "설치까지 문제없이 잘 끝났어요. 메이플 컬러가 우드톤 주방과 잘 어울립니다.",
  },
  {
    id: "r-a13",
    userName: "on*****",
    rating: 4,
    date: "2026.04.04",
    variant: "화이트 / 유리도어",
    content: "만족스러운데 도어 유리에 지문이 잘 남는 편이에요. 그 외엔 좋습니다.",
  },
  {
    id: "r-a14",
    userName: "vs*****",
    rating: 5,
    date: "2026.03.26",
    variant: "메이플 / 일반도어",
    content: "싱크대 밑 공간을 알차게 활용했어요. 조절 선반 덕분에 정리가 쉽습니다.",
  },
  {
    id: "r-a15",
    userName: "rq*****",
    rating: 5,
    date: "2026.03.17",
    variant: "화이트 / 일반도어",
    content: "가격 대비 수납력이 훌륭해요. 설치도 빠르고 깔끔했습니다.",
  },
  {
    id: "r-a16",
    userName: "az*****",
    rating: 3,
    date: "2026.03.08",
    variant: "메이플 / 유리도어",
    content: "제품 자체는 좋은데 배송이 예정보다 늦어졌어요. 유리도어 디자인은 만족스럽습니다.",
  },
  // ── 카페장 가전형 ──
  {
    id: "r-b01",
    userName: "tf*****",
    rating: 5,
    date: "2026.07.16",
    variant: "화이트 / 선반형",
    content: "전자레인지를 상부에 올려두니 동선이 훨씬 편해졌어요. 화이트 컬러가 깔끔합니다.",
    images: ["/images/reviews/1212100021/review-01-1.webp", "/images/reviews/1212100021/review-01-2.webp", "/images/reviews/1212100021/review-01-3.webp"],
  },
  {
    id: "r-b02",
    userName: "gi*****",
    rating: 5,
    date: "2026.07.07",
    variant: "메이플 / 오픈형",
    content: "오픈형이라 자주 쓰는 커피 용품을 바로 꺼낼 수 있어요. 메이플 톤도 예쁩니다.",
  },
  {
    id: "r-b03",
    userName: "uj*****",
    rating: 5,
    date: "2026.06.28",
    variant: "화이트 / 슬라이딩형",
    content: "슬라이딩 도어라 좁은 주방에서도 문 열 공간 걱정이 없어요. 마감도 꼼꼼합니다.",
  },
  {
    id: "r-b04",
    userName: "nx*****",
    rating: 5,
    date: "2026.06.19",
    variant: "메이플 / 선반형",
    content: "커피머신을 올려두는 홈카페 공간으로 딱이에요. 설치도 깔끔하게 끝났습니다.",
  },
  {
    id: "r-b05",
    userName: "pw*****",
    rating: 5,
    date: "2026.06.10",
    variant: "화이트 / 오픈형",
    content: "오픈형이라 소품을 바로 꺼낼 수 있어서 편해요. 화이트라 밝은 느낌입니다.",
  },
  {
    id: "r-b06",
    userName: "lc*****",
    rating: 5,
    date: "2026.06.01",
    variant: "메이플 / 슬라이딩형",
    content: "슬라이딩 도어가 부드럽게 움직여서 만족스러워요. 메이플 컬러도 고급스럽습니다.",
    images: ["/images/reviews/1212100021/review-06-1.webp"],
  },
  {
    id: "r-b07",
    userName: "fe*****",
    rating: 5,
    date: "2026.05.23",
    variant: "화이트 / 선반형",
    content: "가전을 올려두기 딱 좋은 사이즈예요. 설치 기사님이 수평까지 맞춰주셨습니다.",
  },
  {
    id: "r-b08",
    userName: "hj*****",
    rating: 5,
    date: "2026.05.14",
    variant: "메이플 / 오픈형",
    content: "오픈형 선반에 자주 쓰는 그릇을 두니 동선이 줄었어요. 톤도 자연스럽습니다.",
  },
  {
    id: "r-b09",
    userName: "sm*****",
    rating: 4,
    date: "2026.05.05",
    variant: "화이트 / 슬라이딩형",
    content: "전체적으로 만족하는데 슬라이딩 도어 소리가 살짝 나요. 사용에는 문제없습니다.",
  },
  {
    id: "r-b10",
    userName: "kt*****",
    rating: 5,
    date: "2026.04.26",
    variant: "메이플 / 선반형",
    content: "홈카페 공간을 완성했어요. 메이플 컬러가 원목 식탁과 잘 어울립니다.",
  },
  {
    id: "r-b11",
    userName: "yn*****",
    rating: 5,
    date: "2026.04.17",
    variant: "화이트 / 오픈형",
    content: "오픈형이라 인테리어 소품처럼 진열할 수 있어요. 화이트라 깔끔해 보입니다.",
    images: ["/images/reviews/1212100021/review-11-1.webp", "/images/reviews/1212100021/review-12-1.webp"],
  },
  {
    id: "r-b12",
    userName: "dw*****",
    rating: 5,
    date: "2026.04.08",
    variant: "메이플 / 슬라이딩형",
    content: "좁은 주방에 슬라이딩형이 정답이었어요. 설치도 문제없이 끝났습니다.",
  },
  {
    id: "r-b13",
    userName: "bg*****",
    rating: 5,
    date: "2026.03.30",
    variant: "화이트 / 선반형",
    content: "가전 놓는 자리가 확실히 생겨서 주방이 정리됐어요. 마감도 훌륭합니다.",
  },
  {
    id: "r-b14",
    userName: "ej*****",
    rating: 3,
    date: "2026.03.21",
    variant: "메이플 / 오픈형",
    content: "제품은 좋은데 오픈형이라 먼지가 좀 쌓이는 편이에요. 그 외엔 만족합니다.",
  },
  // ── 카페장 수납형 ──
  {
    id: "r-c01",
    userName: "ps*****",
    rating: 5,
    date: "2026.07.11",
    variant: "화이트 / 선반형+일반도어",
    content: "상부, 하부 모두 넉넉하게 수납할 수 있어서 좋아요. 화이트 컬러가 주방을 밝게 만들어줍니다.",
    images: ["/images/reviews/1212100022/review-01-1.webp"],
  },
  {
    id: "r-c02",
    userName: "wc*****",
    rating: 5,
    date: "2026.07.01",
    variant: "메이플 / 오픈형+유리도어",
    content: "오픈형 상부, 유리도어 하부 조합으로 골랐는데 정리하기 편해요. 메이플 톤도 고급스럽습니다.",
  },
  {
    id: "r-c03",
    userName: "mr*****",
    rating: 5,
    date: "2026.06.21",
    variant: "화이트 / 슬라이딩형+일반도어",
    content: "슬라이딩 상부장이라 좁은 공간에서도 편해요. 하부는 일반도어로 깔끔하게 가렸습니다.",
  },
  {
    id: "r-c04",
    userName: "hb*****",
    rating: 5,
    date: "2026.06.11",
    variant: "메이플 / 선반형+유리도어",
    content: "상하부 모두 수납이라 홈카페 용품과 식기를 한 번에 정리했어요. 마감도 꼼꼼합니다.",
  },
  {
    id: "r-c05",
    userName: "jy*****",
    rating: 5,
    date: "2026.06.01",
    variant: "화이트 / 오픈형+일반도어",
    content: "오픈형 선반에 자주 쓰는 컵을 두고 하부는 깔끔하게 가렸어요. 만족스러운 구성입니다.",
    images: ["/images/reviews/1212100022/review-05-1.webp"],
  },
  {
    id: "r-c06",
    userName: "on*****",
    rating: 5,
    date: "2026.05.22",
    variant: "메이플 / 슬라이딩형+유리도어",
    content: "슬라이딩 도어와 유리 하부장 조합이 세련돼 보여요. 수납력도 기대 이상입니다.",
  },
  {
    id: "r-c07",
    userName: "vs*****",
    rating: 5,
    date: "2026.05.12",
    variant: "화이트 / 선반형+일반도어",
    content: "가장 기본적인 조합으로 골랐는데 실용적이에요. 설치도 깔끔했습니다.",
  },
  {
    id: "r-c08",
    userName: "rq*****",
    rating: 5,
    date: "2026.05.02",
    variant: "메이플 / 오픈형+유리도어",
    content: "위아래 다 보이는 구성이라 정리 습관이 좋아졌어요. 톤도 자연스럽습니다.",
  },
  {
    id: "r-c09",
    userName: "az*****",
    rating: 5,
    date: "2026.04.22",
    variant: "화이트 / 슬라이딩형+일반도어",
    content: "좁은 주방인데 슬라이딩형이라 동선에 방해가 안 돼요. 만족스러운 구매입니다.",
  },
  {
    id: "r-c10",
    userName: "tf*****",
    rating: 4,
    date: "2026.04.12",
    variant: "메이플 / 선반형+유리도어",
    content: "전체적으로 만족하는데 가격이 있는 편이에요. 완성도는 확실히 좋습니다.",
  },
  {
    id: "r-c11",
    userName: "gi*****",
    rating: 5,
    date: "2026.04.02",
    variant: "화이트 / 오픈형+일반도어",
    content: "상하부 수납을 한 번에 해결해서 만족해요. 화이트라 깨끗한 느낌입니다.",
  },
  {
    id: "r-c12",
    userName: "uj*****",
    rating: 5,
    date: "2026.03.23",
    variant: "메이플 / 슬라이딩형+유리도어",
    content: "가족 모두 만족한 구매였어요. 조합을 자유롭게 고를 수 있어서 좋았습니다.",
  },
];

export const sharedReviews: ReviewData = {
  ...calculateReviewSummary(reviewItems),
  items: reviewItems,
};

export const sharedQnaItems: QnaItem[] = [
  {
    id: "q-a01",
    category: "상품",
    question: "하부장 도어를 나중에 일반도어에서 유리도어로 교체할 수 있나요?",
    questioner: "dg*****",
    date: "2026.06.20",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 도어 타입은 주문 시 선택하신 사양으로 제작되어 이후 교체는 어렵습니다. 감사합니다.",
    answerDate: "2026.06.21",
  },
  {
    id: "q-b01",
    category: "상품",
    question: "가전형 상부장에 전자레인지가 들어가나요?",
    questioner: "sk*****",
    date: "2026.06.05",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 일반 가정용 전자레인지 기준으로 넉넉하게 들어가는 사이즈입니다. 감사합니다.",
    answerDate: "2026.06.06",
  },
  {
    id: "q-c01",
    category: "상품",
    question: "수납형은 상부장, 하부장 타입을 따로따로 선택하는 건가요?",
    questioner: "wm*****",
    date: "2026.05.20",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 네, 상부장과 하부장 타입을 각각 선택하실 수 있어 원하는 조합으로 주문 가능합니다. 감사합니다.",
    answerDate: "2026.05.21",
  },
  {
    id: "q-a02",
    category: "배송",
    question: "설치까지 얼마나 걸리나요?",
    questioner: "hf*****",
    date: "2026.05.05",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 구성에 따라 60~120분 내외로 소요됩니다. 감사합니다.",
    answerDate: "2026.05.06",
  },
  {
    id: "q-b02",
    category: "배송",
    question: "슬라이딩형은 설치 시간이 더 걸리나요?",
    questioner: "zb*****",
    date: "2026.04.18",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 슬라이딩 레일 조정이 추가되어 다른 타입보다 20~30분 정도 더 소요될 수 있습니다. 감사합니다.",
    answerDate: "2026.04.19",
  },
  {
    id: "q-c02",
    category: "상품",
    question: "화이트, 메이플 외 다른 컬러 계획 있나요?",
    questioner: "ip*****",
    date: "2026.04.02",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 현재는 화이트, 메이플 두 가지 색상으로만 판매하고 있습니다. 감사합니다.",
    answerDate: "2026.04.03",
  },
  {
    id: "q-b03",
    category: "기타",
    question: "가전형과 수납형을 나란히 배치해도 톤이 맞나요?",
    questioner: "oc*****",
    date: "2026.03.15",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 모디 시리즈 전 제품이 동일한 컬러·마감으로 제작되어 나란히 배치하셔도 톤이 자연스럽게 이어집니다. 감사합니다.",
    answerDate: "2026.03.16",
  },
  {
    id: "q-a03",
    category: "배송",
    question: "하부장만 먼저 설치하고 나중에 카페장을 추가해도 되나요?",
    questioner: "gt*****",
    date: "2026.02.20",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 네, 개별 구매 후 순차적으로 설치하실 수 있습니다. 감사합니다.",
    answerDate: "2026.02.21",
  },
  {
    id: "q-c03",
    category: "배송",
    question: "수납형 카페장 설치 시 벽 타공이 필요한가요?",
    questioner: "ov*****",
    date: "2026.07.17",
    answered: false,
  },
];
