import type { ReviewData, QnaItem, Review } from "@/app/lib/types";
import { calculateReviewSummary } from "@/lib/reviews";

const reviewItems: Review[] = [
  {
    id: "r-a01",
    userName: "yj*****",
    rating: 5,
    date: "2026.07.05",
    variant: "Q",
    content: "비염이 있어서 알러지케어 침구만 찾는데 촉감까지 좋은 건 처음이에요. 모달 특유의 매끄러움이 실크 이불 느낌입니다.",
    images: ["/images/reviews/1710120020/review-01-1.webp", "/images/reviews/1710120020/review-01-2.webp"],
  },
  {
    id: "r-a02",
    userName: "sh*****",
    rating: 5,
    date: "2026.06.30",
    variant: "K",
    content: "킹 사이즈인데도 무겁지 않고 몸에 부드럽게 감겨요. 아침에 일어났을 때 재채기가 확실히 줄었습니다.",
  },
  {
    id: "r-a03",
    userName: "mn*****",
    rating: 5,
    date: "2026.06.24",
    variant: "SS",
    content: "아이가 아토피가 있어서 구매했는데 자극 없이 잘 쓰고 있어요. 세탁해도 기능이 유지된다는 점이 마음에 듭니다.",
    images: ["/images/reviews/1710120020/review-03-1.webp"],
  },
  {
    id: "r-a04",
    userName: "kd*****",
    rating: 4,
    date: "2026.06.18",
    variant: "Q",
    content: "촉감이나 퀄리티는 정말 좋은데 색상 선택지가 조금 더 다양했으면 좋겠어요. 이불 자체는 나무랄 데 없습니다.",
  },
  {
    id: "r-a05",
    userName: "wr*****",
    rating: 5,
    date: "2026.06.12",
    variant: "Q",
    content: "먼지가 잘 안 붙고 털어도 날림이 적어요. 진드기 걱정 때문에 바꿨는데 만족스러운 선택이었습니다.",
    images: ["/images/reviews/1710120020/review-05-1.webp"],
  },
  {
    id: "r-a06",
    userName: "hb*****",
    rating: 5,
    date: "2026.06.06",
    variant: "K",
    content: "부부 침대용으로 킹 구매했어요. 드레이프감이 좋아서 둘이 당겨 덮어도 들뜨지 않고 폭 감깁니다.",
  },
  {
    id: "r-a07",
    userName: "je*****",
    rating: 5,
    date: "2026.05.31",
    variant: "SS",
    content: "환절기마다 코가 고생이었는데 침구 바꾸고 한결 나아졌어요. 가격 대비 원단 밀도가 정말 촘촘합니다.",
  },
  {
    id: "r-a08",
    userName: "ds*****",
    rating: 5,
    date: "2026.05.25",
    variant: "Q",
    content: "차렵이불이라 커버 씌우는 번거로움이 없어 좋아요. 통세탁 후에도 충전재 쏠림 없이 형태가 잘 유지됩니다.",
    images: ["/images/reviews/1710120020/review-08-1.webp"],
  },
  {
    id: "r-a09",
    userName: "an*****",
    rating: 3,
    date: "2026.05.19",
    variant: "Q",
    content: "제품은 괜찮은데 배송이 예정보다 이틀 늦게 왔고 지퍼 마감이 살짝 뻑뻑해요. 사용감 자체는 나쁘지 않습니다.",
  },
  {
    id: "r-a10",
    userName: "pu*****",
    rating: 5,
    date: "2026.05.13",
    variant: "SS",
    content: "자취 시작하면서 세트로 장만했는데 베개커버까지 같은 원단이라 통일감 있어요. 촉감이 좋아서 잠드는 게 즐거워졌습니다.",
  },
  {
    id: "r-a11",
    userName: "gy*****",
    rating: 5,
    date: "2026.05.07",
    variant: "K",
    content: "호텔 이불처럼 매끈하고 시원한 촉감이에요. 여름에는 서늘하고 봄가을엔 포근해서 사계절 쓰기 좋습니다.",
    images: ["/images/reviews/1710120020/review-11-1.webp"],
  },
  {
    id: "r-a12",
    userName: "lm*****",
    rating: 5,
    date: "2026.05.01",
    variant: "Q",
    content: "반려동물 털 때문에 침구를 자주 빠는데 건조가 빠르고 구김도 적어요. 관리 편한 이불 찾는 분께 추천합니다.",
  },
  {
    id: "r-a13",
    userName: "os*****",
    rating: 5,
    date: "2026.04.25",
    variant: "SS",
    content: "부모님 침구로 선물했는데 가볍고 부드럽다고 좋아하세요. 알러지케어 기능까지 있어서 더 안심됩니다.",
  },
  {
    id: "r-a14",
    userName: "vn*****",
    rating: 4,
    date: "2026.04.19",
    variant: "K",
    content: "원단은 최고인데 첫 개봉 때 접힘 자국이 오래 가더라고요. 하루 널어두니 괜찮아졌고 그 뒤로는 만족하며 씁니다.",
  },
  {
    id: "r-a15",
    userName: "rj*****",
    rating: 5,
    date: "2026.04.13",
    variant: "Q",
    content: "임신하고 피부가 예민해져서 바꿨는데 자극이 없어요. 밤에 덥고 추운 게 반복돼도 온도 조절이 잘 되는 느낌입니다.",
  },
  {
    id: "r-a16",
    userName: "bg*****",
    rating: 5,
    date: "2026.04.07",
    variant: "SS",
    content: "기존에 쓰던 극세사 이불보다 먼지 날림이 확연히 적어요. 아침 콧물이 줄어든 것만으로 값어치를 합니다.",
  },
  {
    id: "r-a17",
    userName: "cw*****",
    rating: 5,
    date: "2026.03.31",
    variant: "Q",
    content: "색감이 은은해서 어떤 침실에도 잘 어울려요. 두께가 적당해서 간절기부터 초여름까지 계속 쓰고 있습니다.",
    images: ["/images/reviews/1710120020/review-17-1.webp"],
  },
  {
    id: "r-a18",
    userName: "im*****",
    rating: 5,
    date: "2026.03.24",
    variant: "K",
    content: "두 번째 구매예요. 본가 것까지 사드렸을 정도로 가족 모두 만족합니다. 세탁 후 촉감 변화가 거의 없어요.",
  },
  {
    id: "r-a19",
    userName: "fs*****",
    rating: 5,
    date: "2026.03.17",
    variant: "Q",
    content: "봉제선이 튼튼하고 퀼팅 간격이 일정해서 충전재가 안 몰려요. 기본기가 탄탄한 이불이라는 느낌입니다.",
  },
  {
    id: "r-a20",
    userName: "uh*****",
    rating: 5,
    date: "2026.03.10",
    variant: "SS",
    content: "알러지케어 침구 중에 가성비로는 최고인 것 같아요. 미세먼지 심한 계절에 침구 관리 스트레스가 줄었습니다.",
  },
  {
    id: "r-a21",
    userName: "zx*****",
    rating: 5,
    date: "2026.03.03",
    variant: "Q",
    content: "이불 무게가 가벼운데도 허전하지 않게 몸을 감싸줘요. 예민한 남편도 편하게 잔다고 해서 성공한 쇼핑입니다.",
  },
];

export const sharedReviews: ReviewData = {
  ...calculateReviewSummary(reviewItems),
  items: reviewItems,
};

export const sharedQnaItems: QnaItem[] = [
  {
    id: "q-a01",
    category: "상품",
    question: "알러지케어 기능이 세탁 후에도 유지되나요? 건조기 사용도 가능한지 궁금합니다.",
    questioner: "kh*****",
    date: "2026.06.22",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 본 제품은 약품 처리가 아닌 고밀도 원단 조직으로 알러지케어 기능을 구현해 세탁 후에도 기능이 유지됩니다. 건조기는 저온 코스에 한해 사용 가능합니다. 감사합니다.",
    answerDate: "2026.06.23",
  },
  {
    id: "q-a02",
    category: "상품",
    question: "K 사이즈 이불이 킹 매트리스(K20) 옆으로 어느 정도 떨어지나요?",
    questioner: "sm*****",
    date: "2026.06.10",
    answered: true,
    answer: "안녕하세요, 한샘입니다. K 사이즈 이불은 킹 매트리스 기준 양옆으로 약 25cm씩 여유 있게 떨어지는 사이즈입니다. 상세 페이지 사이즈 안내 이미지를 참고 부탁드립니다. 감사합니다.",
    answerDate: "2026.06.11",
  },
  {
    id: "q-a03",
    category: "배송",
    question: "지금 주문하면 이번 주 안에 받을 수 있을까요? 이사 날짜에 맞추고 싶습니다.",
    questioner: "jw*****",
    date: "2026.05.28",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 택배 상품은 주문 후 2~3일 내 출고되며, 평일 오전 주문 시 통상 주 내 수령 가능합니다. 다만 택배사 사정에 따라 1~2일 지연될 수 있는 점 양해 부탁드립니다. 감사합니다.",
    answerDate: "2026.05.28",
  },
  {
    id: "q-a04",
    category: "상품",
    question: "베개커버만 추가로 구매할 수 있나요?",
    questioner: "eu*****",
    date: "2026.05.09",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 현재 본 상품은 세트 구성으로만 판매되고 있어 베개커버 단품 구매는 어렵습니다. 단품 구성 출시 시 상품 페이지를 통해 안내드리겠습니다. 감사합니다.",
    answerDate: "2026.05.10",
  },
  {
    id: "q-a05",
    category: "기타",
    question: "선물 포장이나 쇼핑백 동봉이 가능한가요?",
    questioner: "og*****",
    date: "2026.07.03",
    answered: false,
  },
];
