import type { ReviewData, QnaItem, Review } from "@/app/lib/types";
import { calculateReviewSummary } from "@/lib/reviews";

const reviewItems: Review[] = [
  // ── 이불솜 ──
  {
    id: "r-a01",
    userName: "hs*****",
    rating: 5,
    date: "2026.07.06",
    variant: "이불솜",
    content: "구스 이불은 처음인데 왜 다들 구스구스 하는지 알겠어요. 가벼운데 덮는 순간 폭 감싸는 온기가 완전히 다릅니다.",
    images: ["/images/reviews/1710100011/review-01-1.webp", "/images/reviews/1710100011/review-01-2.webp"],
  },
  {
    id: "r-a02",
    userName: "mj*****",
    rating: 5,
    date: "2026.06.28",
    variant: "이불솜",
    content: "에어컨 켠 여름밤에도 덥지 않고 보송해서 신기해요. 사계절용이라는 말이 과장이 아니었습니다.",
  },
  {
    id: "r-a03",
    userName: "dk*****",
    rating: 5,
    date: "2026.06.20",
    variant: "이불솜",
    content: "10년 쓴 목화솜 이불을 드디어 바꿨어요. 무게가 절반도 안 되는데 훨씬 따뜻하고, 어깨가 눌리지 않아 편합니다.",
    images: ["/images/reviews/1710100011/review-03-1.webp"],
  },
  {
    id: "r-a04",
    userName: "yj*****",
    rating: 4,
    date: "2026.06.12",
    variant: "이불솜",
    content: "품질은 확실히 프리미엄인데 첫 개봉 때 다운 특유의 냄새가 조금 있어요. 반나절 통풍하니 사라졌고 이후로는 대만족입니다.",
  },
  {
    id: "r-a05",
    userName: "sb*****",
    rating: 5,
    date: "2026.06.03",
    variant: "이불솜",
    content: "호텔 이불 그 느낌 그대로예요. 커버를 씌워도 다운이 눌리지 않고 금방 부풀어서 침대가 매일 폭신합니다.",
  },
  {
    id: "r-a06",
    userName: "we*****",
    rating: 5,
    date: "2026.05.24",
    variant: "이불솜",
    content: "깃털 빠짐이 걱정이었는데 한 달 넘게 써도 삐져나온 게 거의 없어요. 원단이 촘촘해서 바스락거림도 적습니다.",
    images: ["/images/reviews/1710100011/review-06-1.webp"],
  },
  {
    id: "r-a07",
    userName: "pj*****",
    rating: 5,
    date: "2026.05.15",
    variant: "이불솜",
    content: "결혼 예단으로 준비했는데 받으신 부모님이 정말 좋아하세요. 포장도 고급스러워서 선물용으로 손색없습니다.",
  },
  {
    id: "r-a08",
    userName: "cn*****",
    rating: 3,
    date: "2026.05.06",
    variant: "이불솜",
    content: "제품 자체는 좋지만 가격 생각하면 기대가 너무 컸는지 감동까지는 아니에요. 그래도 가볍고 따뜻한 건 분명합니다.",
  },
  {
    id: "r-a09",
    userName: "ok*****",
    rating: 5,
    date: "2026.04.26",
    variant: "이불솜",
    content: "환절기 새벽 추위에 깨는 일이 없어졌어요. 다운이 온도에 맞춰 조절해준다는 게 체감이 됩니다.",
  },
  {
    id: "r-a10",
    userName: "ib*****",
    rating: 5,
    date: "2026.04.17",
    variant: "이불솜",
    content: "할인가에 폴란드 구스면 망설일 이유가 없죠. 필파워가 좋아서 살짝만 털어도 새 이불처럼 부풀어요.",
  },
  {
    id: "r-a11",
    userName: "ry*****",
    rating: 5,
    date: "2026.04.08",
    variant: "이불솜",
    content: "먼지 알레르기가 있는데 목화솜보다 재채기가 훨씬 덜해요. 커버만 자주 갈아주면 관리도 어렵지 않습니다.",
  },
  {
    id: "r-a12",
    userName: "gt*****",
    rating: 5,
    date: "2026.03.29",
    variant: "이불솜",
    content: "겨울 끝자락에 사서 봄까지 써봤는데 두 계절 모두 쾌적했어요. 이불 하나로 사계절 정리되니 수납 부담도 줄었습니다.",
  },
  {
    id: "r-a13",
    userName: "ax*****",
    rating: 5,
    date: "2026.03.20",
    variant: "이불솜",
    content: "부부가 온도 취향이 다른데 이 이불은 둘 다 만족해요. 덮은 듯 안 덮은 듯 가벼운데 새벽에 춥지 않습니다.",
  },
  // ── 베개솜 ──
  {
    id: "r-b01",
    userName: "sm*****",
    rating: 5,
    date: "2026.07.02",
    variant: "베개솜",
    content: "이불솜이 너무 좋아서 베개솜도 추가 구매했어요. 머리를 대는 순간 폭 가라앉았다가 부드럽게 받쳐주는 느낌이 일품입니다.",
    images: ["/images/reviews/1710100010/review-01-1.webp"],
  },
  {
    id: "r-b02",
    userName: "kw*****",
    rating: 5,
    date: "2026.06.23",
    variant: "베개솜",
    content: "호텔에서 자던 그 베개를 찾았어요. 푹신한데 금방 꺼지지 않고 아침까지 편안하게 받쳐줍니다.",
  },
  {
    id: "r-b03",
    userName: "eo*****",
    rating: 5,
    date: "2026.06.14",
    variant: "베개솜",
    content: "다운 베개는 처음인데 화이바 베개랑 차원이 다르네요. 뒤척일 때 머리 모양대로 부드럽게 맞춰집니다.",
    images: ["/images/reviews/1710100010/review-03-1.webp"],
  },
  {
    id: "r-b04",
    userName: "nh*****",
    rating: 4,
    date: "2026.06.05",
    variant: "베개솜",
    content: "촉감과 볼륨은 최고인데 푹신한 만큼 지지력은 약한 편이에요. 낮은 베개 좋아하시는 분께 잘 맞을 것 같습니다.",
  },
  {
    id: "r-b05",
    userName: "vu*****",
    rating: 5,
    date: "2026.05.27",
    variant: "베개솜",
    content: "목이 아니라 머리 전체를 감싸주는 느낌이라 잠드는 속도가 빨라졌어요. 선물용으로도 다시 구매할 생각입니다.",
  },
  {
    id: "r-b06",
    userName: "lj*****",
    rating: 5,
    date: "2026.05.18",
    variant: "베개솜",
    content: "베개에서 바스락 소리가 안 나는 게 이렇게 중요한지 몰랐어요. 예민한 잠귀인데 조용하고 포근합니다.",
  },
  {
    id: "r-b07",
    userName: "qe*****",
    rating: 5,
    date: "2026.05.09",
    variant: "베개솜",
    content: "필파워가 좋아서 아침에 한 번 털어주면 하루 종일 빵빵해요. 커버를 씌워도 고급스러운 볼륨이 살아 있습니다.",
    images: ["/images/reviews/1710100010/review-07-1.webp"],
  },
  {
    id: "r-b08",
    userName: "zn*****",
    rating: 4,
    date: "2026.04.29",
    variant: "베개솜",
    content: "베개 자체는 만족인데 배송 시 압축 포장이라 완전히 부풀 때까지 이틀 걸렸어요. 그 뒤로는 최고의 베개입니다.",
  },
  {
    id: "r-b09",
    userName: "fh*****",
    rating: 5,
    date: "2026.04.20",
    variant: "베개솜",
    content: "수면의 질에 투자한다 생각하고 샀는데 옳은 결정이었어요. 자다 깨는 횟수가 눈에 띄게 줄었습니다.",
  },
  {
    id: "r-b10",
    userName: "td*****",
    rating: 5,
    date: "2026.04.11",
    variant: "베개솜",
    content: "부모님 두 분 것과 저희 부부 것까지 네 개 구매했어요. 온 가족이 베개 하나로 이렇게 만족하기 쉽지 않은데 추천합니다.",
  },
  {
    id: "r-b11",
    userName: "uw*****",
    rating: 5,
    date: "2026.04.02",
    variant: "베개솜",
    content: "여름에도 머리에 열이 안 차고 보송해요. 다운의 통기성이 베개에서 더 크게 체감되는 것 같습니다.",
  },
  {
    id: "r-b12",
    userName: "gm*****",
    rating: 5,
    date: "2026.03.24",
    variant: "베개솜",
    content: "깃털 빠짐 걱정했는데 원단이 촘촘해서 한 달간 한두 개 수준이에요. 관리 걱정 없이 쓰고 있습니다.",
  },
  {
    id: "r-b13",
    userName: "bv*****",
    rating: 5,
    date: "2026.03.15",
    variant: "베개솜",
    content: "매일 밤 호텔에서 자는 기분이에요. 가격이 있지만 하루의 3분의 1을 보내는 자리라 아깝지 않습니다.",
  },
];

export const sharedReviews: ReviewData = {
  ...calculateReviewSummary(reviewItems),
  items: reviewItems,
};

export const sharedQnaItems: QnaItem[] = [
  {
    id: "q-a01",
    category: "상품",
    question: "이불솜 충전량과 필파워가 어떻게 되나요?",
    questioner: "js*****",
    date: "2026.06.25",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 이불솜은 폴란드산 구스 다운 솜털 90% 충전, 필파워 850 이상 제품입니다. 상세 페이지 소재 안내에서 충전량 정보를 확인하실 수 있습니다. 감사합니다.",
    answerDate: "2026.06.26",
  },
  {
    id: "q-a02",
    category: "상품",
    question: "이불솜 물세탁이 가능한가요? 드라이클리닝만 해야 하는지 궁금합니다.",
    questioner: "pl*****",
    date: "2026.06.07",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 구스 다운 제품은 다운 전용 중성세제로 물세탁 가능하나, 다운 손상 방지를 위해 전문 세탁을 권장드립니다. 평소에는 커버 세탁과 주기적인 통풍 관리로 충분합니다. 감사합니다.",
    answerDate: "2026.06.08",
  },
  {
    id: "q-a03",
    category: "상품",
    question: "이불솜 Q 사이즈 커버를 씌우면 되는 규격인가요?",
    questioner: "mr*****",
    date: "2026.05.19",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 본 이불솜은 퀸 규격으로 시중 Q 사이즈 이불커버와 호환됩니다. 모서리 고리가 있어 커버 끈과 고정하시면 쏠림 없이 사용하실 수 있습니다. 감사합니다.",
    answerDate: "2026.05.20",
  },
  {
    id: "q-b01",
    category: "상품",
    question: "베개솜은 어떤 사이즈 커버와 호환되나요?",
    questioner: "dn*****",
    date: "2026.05.02",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 베개솜은 50x70cm 표준 규격으로 시중 50x70 베개커버와 호환됩니다. 다운 볼륨을 살리려면 여유 있는 핏의 커버를 권장드립니다. 감사합니다.",
    answerDate: "2026.05.03",
  },
  {
    id: "q-b02",
    category: "배송",
    question: "이불솜과 베개솜을 함께 주문하면 같이 배송되나요?",
    questioner: "sc*****",
    date: "2026.04.15",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 동일 주문 건은 가능한 합포장으로 출고됩니다. 부피 관계로 개별 박스 배송 시에도 배송비는 1회만 부과되니 안심하고 주문해 주세요. 감사합니다.",
    answerDate: "2026.04.16",
  },
  {
    id: "q-a04",
    category: "기타",
    question: "예단용 선물 포장 서비스가 있나요?",
    questioner: "yb*****",
    date: "2026.07.04",
    answered: false,
  },
  {
    id: "q-b03",
    category: "상품",
    question: "베개솜 두 개 세트 구성은 없나요?",
    questioner: "tg*****",
    date: "2026.07.08",
    answered: false,
  },
];
