import type { ReviewData, QnaItem, Review } from "@/app/lib/types";
import { calculateReviewSummary } from "@/lib/reviews";

const reviewItems: Review[] = [
  {
    id: "r-a01",
    userName: "yh*****",
    rating: 5,
    date: "2026.07.02",
    variant: "시어솔리드",
    content: "호텔에서 자는 기분을 매일 느껴요. 낮엔 시어만 내려 은은하게, 밤엔 암막까지 내리면 완전한 어둠입니다.",
    images: ["/images/reviews/1712110020/review-01-1.webp"],
  },
  {
    id: "r-a02",
    userName: "kp*****",
    rating: 5,
    date: "2026.06.23",
    variant: "펀칭레이스",
    content: "펀칭레이스 패턴 사이로 들어오는 빛이 벽에 그림을 그려요. 기능만 보고 샀는데 감성까지 챙겼습니다.",
  },
  {
    id: "r-a03",
    userName: "sw*****",
    rating: 5,
    date: "2026.06.14",
    variant: "시어솔리드",
    content: "침실 커튼+속커튼 조합을 고민하다 이걸로 정리했어요. 스크린이 따로 움직이니 커튼보다 좋아요.",
    images: ["/images/reviews/1712110020/review-03-1.webp", "/images/reviews/1712110020/review-03-2.webp"],
  },
  {
    id: "r-a04",
    userName: "dl*****",
    rating: 4,
    date: "2026.06.05",
    variant: "펀칭레이스",
    content: "만족도는 높은데 더블 구조라 프레임이 일반 롤스크린보다 두꺼워요. 창틀 깊이가 얕으면 실측 때 확인 필수입니다.",
  },
  {
    id: "r-a05",
    userName: "jc*****",
    rating: 5,
    date: "2026.05.27",
    variant: "시어솔리드",
    content: "야간 근무자라 암막이 생명인데 커튼보다 빛샘이 적어요. 아침 햇빛에 깨는 일이 없어졌습니다.",
  },
  {
    id: "r-a06",
    userName: "bn*****",
    rating: 5,
    date: "2026.05.18",
    variant: "펀칭레이스",
    content: "거실 통창 세 폭으로 나눠 시공했는데 호텔 라운지가 됐어요. 손님들이 올 때마다 감탄합니다.",
  },
  {
    id: "r-a07",
    userName: "mg*****",
    rating: 3,
    date: "2026.05.09",
    variant: "시어솔리드",
    content: "제품은 고급스러운데 줄이 두 개라 처음엔 조작이 헷갈려요. 익숙해지니 괜찮지만 어르신들은 어려워하실 수 있습니다.",
  },
  {
    id: "r-a08",
    userName: "tv*****",
    rating: 5,
    date: "2026.04.30",
    variant: "펀칭레이스",
    content: "신혼집 침실에 시공했는데 아내가 제일 만족하는 아이템이에요. 아침엔 레이스 무늬 빛, 주말엔 완전 암막 늦잠입니다.",
    images: ["/images/reviews/1712110020/review-08-1.webp"],
  },
  {
    id: "r-a09",
    userName: "od*****",
    rating: 5,
    date: "2026.04.21",
    variant: "시어솔리드",
    content: "블랙라벨이라 가격대가 있지만 원단 질감과 부품 마감에서 값을 해요. 스크린 내려오는 소리도 조용합니다.",
  },
  {
    id: "r-a10",
    userName: "ff*****",
    rating: 5,
    date: "2026.04.12",
    variant: "펀칭레이스",
    content: "서향 침실 뜨거운 오후 햇빛이 고민이었는데 시어+암막 조합으로 해결했어요. 실내 온도까지 내려갑니다.",
  },
  {
    id: "r-a11",
    userName: "gz*****",
    rating: 5,
    date: "2026.04.03",
    variant: "시어솔리드",
    content: "시공 기사님이 창틀 상태까지 봐주면서 최적 위치에 달아주셨어요. 이래서 시공 포함 상품을 사는구나 싶었습니다.",
  },
  {
    id: "r-a12",
    userName: "hq*****",
    rating: 5,
    date: "2026.03.25",
    variant: "펀칭레이스",
    content: "안방에 달고 너무 만족해서 아이 방도 추가 주문했어요. 롤스크린인데 커튼의 낭만까지 있는 제품입니다.",
  },
];

export const sharedReviews: ReviewData = {
  ...calculateReviewSummary(reviewItems),
  items: reviewItems,
};

export const sharedQnaItems: QnaItem[] = [
  {
    id: "q-a01",
    category: "상품",
    question: "시어솔리드와 펀칭레이스 중 어떤 게 더 차광이 잘 되나요?",
    questioner: "wr*****",
    date: "2026.06.09",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 두 타입 모두 앞쪽 스크린은 반투명 채광용이며 차광은 뒤쪽 암막 스크린이 담당합니다. 시어솔리드는 균일하게 부드러운 빛, 펀칭레이스는 패턴 사이로 스미는 빛으로 무드 차이로 선택하시면 됩니다. 감사합니다.",
    answerDate: "2026.06.10",
  },
  {
    id: "q-a02",
    category: "상품",
    question: "전동으로 업그레이드할 수 있나요?",
    questioner: "cd*****",
    date: "2026.05.21",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 현재 본 상품은 수동 체인 방식으로만 제공되며 전동 옵션은 준비 중입니다. 전동 라인업 출시 시 상품 페이지를 통해 안내드리겠습니다. 감사합니다.",
    answerDate: "2026.05.22",
  },
  {
    id: "q-a03",
    category: "배송",
    question: "이사 예정일이 3주 뒤인데 그 전에 시공 가능할까요?",
    questioner: "np*****",
    date: "2026.07.08",
    answered: false,
  },
];
