import type { ReviewData, QnaItem, Review } from "@/app/lib/types";
import { calculateReviewSummary } from "@/lib/reviews";

const reviewItems: Review[] = [
  {
    id: "r-a01",
    userName: "hj*****",
    rating: 5,
    date: "2026.07.20",
    variant: "메이플 / 고급형-좌형",
    content: "좌형으로 주문했는데 동선에 딱 맞아서 편해요. 조절 선반이라 그릇 크기에 맞춰 칸을 나눴습니다.",
  },
  {
    id: "r-a02",
    userName: "sm*****",
    rating: 5,
    date: "2026.07.13",
    variant: "화이트 / 일반형",
    content: "냉장고 옆 자투리 공간에 딱 맞게 들어갔어요. 화이트 컬러라 주방이 더 밝아 보입니다.",
    images: ["/images/reviews/1212100010/review-02-1.webp", "/images/reviews/1212100010/review-02-2.webp", "/images/reviews/1212100010/review-02-3.webp"],
  },
  {
    id: "r-a03",
    userName: "kt*****",
    rating: 5,
    date: "2026.07.06",
    variant: "화이트 / 고급형-우형",
    content: "우형으로 설치했는데 문 열 때 걸리는 게 없어서 좋아요. 수납량도 생각보다 넉넉합니다.",
  },
  {
    id: "r-a04",
    userName: "yn*****",
    rating: 5,
    date: "2026.06.29",
    variant: "메이플 / 일반형",
    content: "메이플 컬러가 원목 식탁이랑 잘 어울려요. 설치도 깔끔하게 마쳐주셨습니다.",
    images: ["/images/reviews/1212100010/review-04-1.webp", "/images/reviews/1212100010/review-04-2.webp"],
  },
  {
    id: "r-a05",
    userName: "dw*****",
    rating: 5,
    date: "2026.06.22",
    variant: "화이트 / 일반형",
    content: "60cm라 좁은 자리에도 부담 없이 들어갔어요. 마감도 꼼꼼한 편입니다.",
  },
  {
    id: "r-a06",
    userName: "bg*****",
    rating: 5,
    date: "2026.06.15",
    variant: "메이플 / 고급형-좌형",
    content: "고급형이라 그런지 도어 마감이 확실히 좋아요. 좌형 선택해서 동선도 편합니다.",
  },
  {
    id: "r-a07",
    userName: "ej*****",
    rating: 5,
    date: "2026.06.08",
    variant: "화이트 / 고급형-우형",
    content: "설치 기사님이 수평까지 꼼꼼하게 맞춰주셨어요. 우형이 저희 집 구조에 딱 맞았습니다.",
  },
  {
    id: "r-a08",
    userName: "ps*****",
    rating: 5,
    date: "2026.06.01",
    variant: "메이플 / 일반형",
    content: "가격 대비 수납력이 훌륭해요. 자투리 공간 활용에 최고입니다.",
  },
  {
    id: "r-a09",
    userName: "wc*****",
    rating: 4,
    date: "2026.05.25",
    variant: "화이트 / 고급형-좌형",
    content: "전체적으로 만족하는데 설치 일정이 하루 밀렸어요. 완성도는 기대 이상입니다.",
  },
  {
    id: "r-a10",
    userName: "mr*****",
    rating: 5,
    date: "2026.05.18",
    variant: "메이플 / 일반형",
    content: "조절 선반이라 위아래 칸 높이를 조절할 수 있어서 편해요. 메이플 컬러도 고급스럽습니다.",
  },
  {
    id: "r-a11",
    userName: "hb*****",
    rating: 5,
    date: "2026.05.11",
    variant: "화이트 / 고급형-우형",
    content: "우형으로 주문했는데 싱크대 동선이랑 자연스럽게 이어져요. 화이트라 깨끗해 보입니다.",
    images: ["/images/reviews/1212100010/review-11-1.webp", "/images/reviews/1212100010/review-11-2.webp"],
  },
  {
    id: "r-a12",
    userName: "jy*****",
    rating: 5,
    date: "2026.05.04",
    variant: "메이플 / 고급형-좌형",
    content: "냉장고 옆 틈새를 활용하려고 구매했는데 완벽하게 맞았어요. 좌형 선택 잘한 것 같습니다.",
  },
  {
    id: "r-a13",
    userName: "on*****",
    rating: 5,
    date: "2026.04.27",
    variant: "화이트 / 일반형",
    content: "가성비 좋은 일반형으로 골랐는데 만족스러워요. 수납공간이 넉넉합니다.",
  },
  {
    id: "r-a14",
    userName: "vs*****",
    rating: 3,
    date: "2026.04.20",
    variant: "메이플 / 일반형",
    content: "제품은 괜찮은데 설치 예약이 밀려서 2주 정도 기다렸어요. 완성도 자체는 좋습니다.",
  },
  {
    id: "r-a15",
    userName: "rq*****",
    rating: 5,
    date: "2026.04.13",
    variant: "화이트 / 고급형-좌형",
    content: "좌형 도어라 동선에 안 걸려서 편해요. 화이트가 주방을 환하게 만들어줍니다.",
  },
  {
    id: "r-a16",
    userName: "az*****",
    rating: 5,
    date: "2026.04.06",
    variant: "메이플 / 고급형-우형",
    content: "고급형 우형으로 주문했는데 마감이 확실히 좋아요. 메이플 컬러도 고급스럽습니다.",
    images: ["/images/reviews/1212100010/review-16-1.webp"],
  },
  {
    id: "r-a17",
    userName: "tf*****",
    rating: 5,
    date: "2026.03.30",
    variant: "화이트 / 일반형",
    content: "60cm라 자리 활용도가 높아요. 설치도 빠르고 깔끔했습니다.",
  },
  {
    id: "r-a18",
    userName: "gi*****",
    rating: 5,
    date: "2026.03.23",
    variant: "메이플 / 고급형-좌형",
    content: "조절 선반 덕분에 큰 그릇도 넣을 수 있어요. 좌형 선택이 저희 주방과 잘 맞습니다.",
  },
  {
    id: "r-a19",
    userName: "uj*****",
    rating: 4,
    date: "2026.03.16",
    variant: "화이트 / 고급형-우형",
    content: "만족스러운데 도어 손잡이가 조금 헐거운 느낌이에요. 그 외엔 튼튼합니다.",
  },
  {
    id: "r-a20",
    userName: "nx*****",
    rating: 5,
    date: "2026.03.09",
    variant: "메이플 / 일반형",
    content: "가성비 좋게 수납공간을 늘렸어요. 메이플 톤이 자연스럽습니다.",
  },
  {
    id: "r-a21",
    userName: "pw*****",
    rating: 5,
    date: "2026.03.02",
    variant: "화이트 / 고급형-좌형",
    content: "좌형으로 주문해서 동선이 편해요. 화이트 컬러 마감도 깔끔합니다.",
    images: ["/images/reviews/1212100010/review-21-1.webp"],
  },
  {
    id: "r-a22",
    userName: "lc*****",
    rating: 5,
    date: "2026.02.23",
    variant: "메이플 / 고급형-우형",
    content: "우형 도어가 저희 집 구조에 딱 맞았어요. 설치 기사님도 친절하셨습니다.",
  },
  {
    id: "r-a23",
    userName: "fe*****",
    rating: 5,
    date: "2026.02.16",
    variant: "화이트 / 일반형",
    content: "냉장고 옆 자투리 공간이 확실히 정리됐어요. 화이트 컬러가 무난하게 잘 어울립니다.",
  },
  {
    id: "r-a24",
    userName: "on*****",
    rating: 3,
    date: "2026.02.09",
    variant: "메이플 / 일반형",
    content: "제품 자체는 좋은데 배송이 예정보다 늦어졌어요. 설치 후엔 만족스럽습니다.",
  },
  {
    id: "r-a25",
    userName: "vs*****",
    rating: 5,
    date: "2026.02.02",
    variant: "화이트 / 고급형-좌형",
    content: "고급형 좌형이 저희 주방 동선과 완벽하게 맞았어요. 마감도 훌륭합니다.",
  },
  {
    id: "r-a26",
    userName: "rq*****",
    rating: 5,
    date: "2026.01.26",
    variant: "화이트 / 고급형-우형",
    content: "우형으로 주문했는데 문 열림 각도가 넉넉해요. 화이트 컬러가 고급스럽습니다.",
    images: ["/images/reviews/1212100010/review-26-1.webp", "/images/reviews/1212100010/review-26-2.webp"],
  },
  {
    id: "r-a27",
    userName: "az*****",
    rating: 5,
    date: "2026.01.19",
    variant: "화이트 / 일반형",
    content: "합리적인 가격에 수납력이 좋아서 만족해요. 화이트라 어디에 둬도 깨끗해 보입니다.",
  },
  {
    id: "r-a28",
    userName: "tf*****",
    rating: 5,
    date: "2026.01.12",
    variant: "메이플 / 고급형-좌형",
    content: "좌형 선택해서 동선이 편해요. 조절 선반 덕분에 수납이 자유롭습니다.",
  },
  {
    id: "r-a29",
    userName: "gi*****",
    rating: 5,
    date: "2026.01.05",
    variant: "화이트 / 고급형-우형",
    content: "설치까지 깔끔하게 마쳐주셔서 만족스러워요. 우형이 저희 집과 잘 맞았습니다.",
  },
  {
    id: "r-a30",
    userName: "uj*****",
    rating: 5,
    date: "2025.12.29",
    variant: "메이플 / 일반형",
    content: "자투리 공간을 알차게 채웠어요. 메이플 컬러도 자연스럽습니다.",
  },
  {
    id: "r-a31",
    userName: "nx*****",
    rating: 5,
    date: "2025.12.22",
    variant: "화이트 / 고급형-좌형",
    content: "가족 모두 만족한 구매였어요. 좌형 도어라 동선에 전혀 방해되지 않습니다.",
  },
];

export const sharedReviews: ReviewData = {
  ...calculateReviewSummary(reviewItems),
  items: reviewItems,
};

export const sharedQnaItems: QnaItem[] = [
  {
    id: "q-a01",
    category: "상품",
    question: "좌형과 우형은 어떻게 구분하나요?",
    questioner: "dg*****",
    date: "2026.06.25",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 정면에서 바라봤을 때 문이 왼쪽으로 열리면 좌형, 오른쪽으로 열리면 우형입니다. 설치 공간의 동선을 먼저 확인해 주세요. 감사합니다.",
    answerDate: "2026.06.26",
  },
  {
    id: "q-a02",
    category: "배송",
    question: "설치까지 얼마나 걸리나요?",
    questioner: "sk*****",
    date: "2026.06.08",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 방문 설치 기준 60~90분 내외로 완료됩니다. 감사합니다.",
    answerDate: "2026.06.09",
  },
  {
    id: "q-a03",
    category: "상품",
    question: "일반형과 고급형 차이가 뭔가요?",
    questioner: "wm*****",
    date: "2026.05.20",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 고급형은 도어 마감과 경첩 사양이 강화되고 좌형·우형 방향을 선택하실 수 있습니다. 일반형은 방향 선택 없이 기본 사양으로 제공됩니다. 감사합니다.",
    answerDate: "2026.05.21",
  },
  {
    id: "q-a04",
    category: "상품",
    question: "내부 선반 높이 조절이 가능한가요?",
    questioner: "hf*****",
    date: "2026.04.25",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 내부 선반은 여러 단으로 높이 조절이 가능합니다. 감사합니다.",
    answerDate: "2026.04.26",
  },
  {
    id: "q-a05",
    category: "배송",
    question: "냉장고 폭이 65cm인데 옆에 설치 가능할까요?",
    questioner: "zb*****",
    date: "2026.03.28",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 제품 폭이 60cm이므로 설치 공간은 여유 있게 확보해 주시고, 정확한 설치는 방문 시 기사님과 확인하시는 것을 권장드립니다. 감사합니다.",
    answerDate: "2026.03.29",
  },
  {
    id: "q-a06",
    category: "기타",
    question: "다른 색상(그레이 등) 추가 예정 있나요?",
    questioner: "ip*****",
    date: "2026.02.20",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 현재는 화이트, 메이플 두 가지 색상으로만 판매하고 있습니다. 감사합니다.",
    answerDate: "2026.02.21",
  },
  {
    id: "q-a07",
    category: "상품",
    question: "고급형 좌형에서 우형으로 변경 요청도 가능한가요?",
    questioner: "oc*****",
    date: "2026.07.18",
    answered: false,
  },
];
