import type { ReviewData, QnaItem, Review } from "@/app/lib/types";
import { calculateReviewSummary } from "@/lib/reviews";

const reviewItems: Review[] = [
  {
    id: "r-a01",
    userName: "hj*****",
    rating: 5,
    date: "2026.07.21",
    variant: "베이지",
    content: "식탁 옆에 두 개 나란히 놓았는데 다리가 얇아서 공간이 훨씬 넓어 보여요. 베이지 컬러가 우드톤 식탁이랑 잘 어울립니다.",
    images: ["/images/reviews/1211100010/review-01-1.webp"],
  },
  {
    id: "r-a02",
    userName: "sm*****",
    rating: 5,
    date: "2026.07.12",
    variant: "그레이",
    content: "2개입이라 가격도 합리적이고 색상도 딱 원하던 톤이에요. 조립도 다리만 끼우면 끝나서 금방 완성했습니다.",
  },
  {
    id: "r-a03",
    userName: "kt*****",
    rating: 5,
    date: "2026.07.03",
    variant: "베이지",
    content: "시트 쿠션감이 적당해서 오래 앉아도 배기지 않아요. 프레임도 슬림한데 앉았을 때 흔들림이 없습니다.",
  },
  {
    id: "r-a04",
    userName: "yn*****",
    rating: 5,
    date: "2026.06.24",
    variant: "그레이",
    content: "그레이 컬러라 어떤 식탁이랑도 무난하게 어울려요. 패브릭 재질이라 그런지 촉감도 좋습니다.",
    images: ["/images/reviews/1211100010/review-04-1.webp"],
  },
  {
    id: "r-a05",
    userName: "dw*****",
    rating: 5,
    date: "2026.06.15",
    variant: "베이지",
    content: "혼자 조립했는데 나사 몇 개만 조이면 돼서 어렵지 않았어요. 완성도도 가격 대비 훌륭합니다.",
  },
  {
    id: "r-a06",
    userName: "bg*****",
    rating: 5,
    date: "2026.06.06",
    variant: "그레이",
    content: "식탁 의자를 슬림한 걸로 찾다가 골랐는데 실물이 사진보다 더 예뻐요. 다리가 얇아도 앉을 때 든든합니다.",
    images: ["/images/reviews/1211100010/review-06-1.webp"],
  },
  {
    id: "r-a07",
    userName: "ej*****",
    rating: 5,
    date: "2026.05.28",
    variant: "베이지",
    content: "2개 다 색상 편차 없이 동일하게 와서 만족스러워요. 등받이 각도도 편안한 편입니다.",
  },
  {
    id: "r-a08",
    userName: "ps*****",
    rating: 4,
    date: "2026.05.19",
    variant: "그레이",
    content: "전체적으로 만족하는데 시트 패브릭에 보풀이 살짝 생기더라고요. 그 외엔 튼튼하고 예쁩니다.",
  },
  {
    id: "r-a09",
    userName: "wc*****",
    rating: 5,
    date: "2026.05.10",
    variant: "베이지",
    content: "좁은 주방에 식탁이랑 같이 뒀는데 슬림해서 동선에 방해가 안 돼요. 색상도 은은해서 좋습니다.",
  },
  {
    id: "r-a10",
    userName: "mr*****",
    rating: 5,
    date: "2026.05.01",
    variant: "그레이",
    content: "다리 조립만 하면 되는 구조라 여자 혼자서도 금방 끝냈어요. 완성 후 안정감도 좋습니다.",
  },
  {
    id: "r-a11",
    userName: "hb*****",
    rating: 5,
    date: "2026.04.22",
    variant: "베이지",
    content: "패브릭 시트가 부드러워서 아이가 앉아도 편안해해요. 색상도 자극적이지 않아 오래 봐도 질리지 않습니다.",
    images: ["/images/reviews/1211100010/review-11-1.webp"],
  },
  {
    id: "r-a12",
    userName: "jy*****",
    rating: 5,
    date: "2026.04.13",
    variant: "그레이",
    content: "가격 대비 마감이 꼼꼼한 편이에요. 프레임 도장도 깔끔합니다.",
  },
  {
    id: "r-a13",
    userName: "on*****",
    rating: 5,
    date: "2026.04.04",
    variant: "베이지",
    content: "2개입이라 따로 안 맞춰도 돼서 편했어요. 식탁 전체 톤이 자연스럽게 맞춰졌습니다.",
  },
  {
    id: "r-a14",
    userName: "vs*****",
    rating: 5,
    date: "2026.03.26",
    variant: "그레이",
    content: "슬림한 라인이라 사진보다 실물이 훨씬 세련돼 보여요. 만족스러운 구매였습니다.",
  },
  {
    id: "r-a15",
    userName: "rq*****",
    rating: 5,
    date: "2026.03.17",
    variant: "베이지",
    content: "원목 프레임이 튼튼해서 성인이 앉아도 안정적이에요. 색상도 사진과 거의 동일합니다.",
    images: ["/images/reviews/1211100010/review-15-1.webp"],
  },
  {
    id: "r-a16",
    userName: "az*****",
    rating: 5,
    date: "2026.03.08",
    variant: "그레이",
    content: "식탁 리뉴얼하면서 의자만 바꿨는데 분위기가 확 달라졌어요. 슬림한 디자인이 마음에 듭니다.",
  },
  {
    id: "r-a17",
    userName: "tf*****",
    rating: 4,
    date: "2026.02.27",
    variant: "베이지",
    content: "만족스러운데 다리 끝 고무캡이 하나 헐거워서 직접 끼웠어요. 그 외엔 문제없이 잘 쓰고 있습니다.",
  },
  {
    id: "r-a18",
    userName: "gi*****",
    rating: 5,
    date: "2026.02.18",
    variant: "그레이",
    content: "가벼워서 청소할 때 옮기기 편해요. 슬림해도 앉았을 때 불안정하지 않습니다.",
  },
  {
    id: "r-a19",
    userName: "uj*****",
    rating: 5,
    date: "2026.02.09",
    variant: "베이지",
    content: "패브릭 컬러가 은은해서 어떤 식탁과도 잘 어울려요. 2개입 구성이라 가성비도 좋습니다.",
  },
  {
    id: "r-a20",
    userName: "nx*****",
    rating: 5,
    date: "2026.01.31",
    variant: "그레이",
    content: "다리가 얇아서 좁은 자취방 식탁에도 부담 없이 뒀어요. 조립도 간단해서 좋았습니다.",
  },
  {
    id: "r-a21",
    userName: "pw*****",
    rating: 5,
    date: "2026.01.22",
    variant: "베이지",
    content: "슬림한 디자인이 인테리어에 힘을 안 줘도 자연스럽게 잘 어울려요. 다음에도 여기서 의자를 살 것 같습니다.",
  },
];

export const sharedReviews: ReviewData = {
  ...calculateReviewSummary(reviewItems),
  items: reviewItems,
};

export const sharedQnaItems: QnaItem[] = [
  {
    id: "q-a01",
    category: "상품",
    question: "의자 2개 색상을 다르게 받을 수 있나요?",
    questioner: "dg*****",
    date: "2026.06.20",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 2개입은 동일한 색상 1세트로 구성되어 있어 색상을 섞어 받으실 수는 없습니다. 다른 색상을 원하시면 단품을 각각 주문해 주세요. 감사합니다.",
    answerDate: "2026.06.21",
  },
  {
    id: "q-a02",
    category: "배송",
    question: "조립이 얼마나 어려운가요?",
    questioner: "sk*****",
    date: "2026.06.03",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 다리를 나사로 고정하는 간단한 조립으로, 기본 공구가 함께 제공되어 10분 내외로 완료하실 수 있습니다. 감사합니다.",
    answerDate: "2026.06.04",
  },
  {
    id: "q-a03",
    category: "상품",
    question: "성인 남성이 앉아도 괜찮을 만큼 튼튼한가요?",
    questioner: "wm*****",
    date: "2026.05.15",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 원목 프레임으로 제작되어 성인 체중에도 안정적으로 사용하실 수 있습니다. 감사합니다.",
    answerDate: "2026.05.16",
  },
  {
    id: "q-a04",
    category: "기타",
    question: "패브릭이 아닌 가죽 시트 옵션도 있나요?",
    questioner: "hf*****",
    date: "2026.04.20",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 현재는 패브릭 시트 단일 구성으로만 판매하고 있습니다. 감사합니다.",
    answerDate: "2026.04.21",
  },
  {
    id: "q-a05",
    category: "상품",
    question: "식탁 높이 700mm 정도에 맞는 의자 높이인가요?",
    questioner: "zb*****",
    date: "2026.03.10",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 시트 높이는 약 45cm로 일반적인 700~750mm 식탁 높이와 잘 맞습니다. 감사합니다.",
    answerDate: "2026.03.11",
  },
  {
    id: "q-a06",
    category: "배송",
    question: "4개 주문하면 색상 다르게 2+2로 받을 수 있나요?",
    questioner: "ip*****",
    date: "2026.07.17",
    answered: false,
  },
];
