import type { ReviewData, QnaItem, Review } from "@/app/lib/types";
import { calculateReviewSummary } from "@/lib/reviews";

const reviewItems: Review[] = [
  // ── 6인용 ──
  {
    id: "r-a01",
    userName: "ho*****",
    rating: 5,
    date: "2026.06.18",
    variant: "6인용",
    content: "6인 가족이라 큰 식탁을 고민하다가 구매했는데 세라믹 상판이 사진보다 훨씬 고급스러워요. 위드의자까지 한 번에 세팅되니 따로 의자를 고를 필요가 없어서 정말 편했습니다.",
    images: ["/images/reviews/1210130011/review-01-1.webp", "/images/reviews/1210130011/review-01-2.webp"],
  },
  {
    id: "r-a02",
    userName: "ks*****",
    rating: 5,
    date: "2026.06.05",
    variant: "6인용",
    content: "화이트마블 컬러로 골랐는데 조명 아래서 은은한 무늬가 살아 있어 고급스러워요. 친정 식구들 모이는 날 6명이 앉아도 여유로워서 만족합니다.",
  },
  {
    id: "r-a03",
    userName: "lj*****",
    rating: 5,
    date: "2026.05.27",
    variant: "6인용",
    content: "세라믹 상판이라 뜨거운 냄비를 바로 올려도 자국이 안 남아서 너무 좋아요. 설치 기사님들이 무거운 상판도 깔끔하게 옮겨주셨습니다.",
    images: ["/images/reviews/1210130011/review-03-1.webp"],
  },
  {
    id: "r-a04",
    userName: "ph*****",
    rating: 4,
    date: "2026.05.14",
    variant: "6인용",
    content: "전체적으로 만족스러운데 의자 다리 고무패킹 하나가 살짝 헐거워서 직접 조여줬어요. 식탁 자체 퀄리티는 가격 대비 훌륭합니다.",
  },
  {
    id: "r-a05",
    userName: "ce*****",
    rating: 5,
    date: "2026.05.02",
    variant: "6인용",
    content: "코튼화이트로 선택했는데 거실 톤이랑 자연스럽게 어울려요. 의자 쿠션감도 생각보다 좋아서 오래 앉아도 불편하지 않습니다.",
  },
  {
    id: "r-a06",
    userName: "lh*****",
    rating: 5,
    date: "2026.04.21",
    variant: "6인용",
    content: "넓은 6인용이라 손님 초대할 때 정말 든든해요. 세라믹 상판 엣지 라인이 깔끔해서 사진보다 실물이 더 예쁩니다.",
    images: ["/images/reviews/1210130011/review-06-1.webp", "/images/reviews/1210130011/review-06-2.webp"],
  },
  {
    id: "r-a07",
    userName: "pj*****",
    rating: 5,
    date: "2026.04.09",
    variant: "6인용",
    content: "이사하면서 새로 들였는데 다이닝룸 분위기가 완전히 달라졌어요. 위드의자 등받이가 적당히 기울어 있어서 식사할 때 편합니다.",
  },
  {
    id: "r-a08",
    userName: "cm*****",
    rating: 3,
    date: "2026.03.27",
    variant: "6인용",
    content: "상판은 만족하는데 의자 색상이 식탁 컬러보다 살짝 더 누렇게 느껴졌어요. 조명에 따라 차이가 있는 것 같습니다.",
    images: ["/images/reviews/1210130011/review-08-1.webp", "/images/reviews/1210130011/review-08-2.webp"],
  },
  {
    id: "r-a09",
    userName: "ky*****",
    rating: 5,
    date: "2026.03.15",
    variant: "6인용",
    content: "친구들 불러서 식사 모임 했는데 다들 식탁 어디서 샀냐고 물어봤어요. 세라믹 특유의 매트한 광택이 정말 고급스럽습니다.",
  },
  {
    id: "r-a10",
    userName: "ja*****",
    rating: 4,
    date: "2026.03.02",
    variant: "6인용",
    content: "디자인은 정말 마음에 드는데 배송이 예정보다 며칠 늦어졌어요. 받고 나니 품질은 기대 이상입니다.",
  },
  {
    id: "r-a11",
    userName: "su*****",
    rating: 5,
    date: "2026.02.18",
    variant: "6인용",
    content: "신혼집에 들였는데 세라믹 상판이라 물 자국이나 얼룩 걱정 없이 편하게 쓰고 있어요. 의자까지 매칭되니 따로 코디할 필요가 없었습니다.",
  },
  {
    id: "r-a12",
    userName: "aj*****",
    rating: 5,
    date: "2026.02.05",
    variant: "6인용",
    content: "부모님 댁에 선물로 보내드렸는데 너무 좋아하세요. 세라믹 상판이 무겁지만 그만큼 견고한 느낌이라 안심이 됩니다.",
    images: ["/images/reviews/1210130011/review-12-1.webp"],
  },
  {
    id: "r-a13",
    userName: "hs*****",
    rating: 5,
    date: "2026.01.22",
    variant: "6인용",
    content: "엣지 라인이 너무 예뻐서 식탁만 봐도 인테리어가 완성된 느낌이에요. 6인용이라 명절에 가족 모이기에도 충분합니다.",
  },
  {
    id: "r-a14",
    userName: "ox*****",
    rating: 5,
    date: "2026.01.10",
    variant: "6인용",
    content: "설치 전 사전 연락도 정확하게 오고 조립도 빠르게 끝났어요. 의자 다리 높이도 균일해서 흔들림 없이 안정적입니다.",
  },
  // ── 4인용 ──
  {
    id: "r-b01",
    userName: "yk*****",
    rating: 5,
    date: "2026.06.20",
    variant: "4인용",
    content: "신혼집 4인 가족 기준으로 딱 맞는 사이즈예요. 세라믹 상판 덕분에 아이가 흘려도 바로 닦이고 자국도 안 남습니다.",
    images: ["/images/reviews/1210130010/review-01-1.webp", "/images/reviews/1210130010/review-01-2.webp"],
  },
  {
    id: "r-b02",
    userName: "im*****",
    rating: 5,
    date: "2026.06.08",
    variant: "4인용",
    content: "화이트마블 컬러 실물이 사진보다 훨씬 고급스럽고 은은해요. 좁은 다이닝 공간에도 답답하지 않게 잘 들어갑니다.",
  },
  {
    id: "r-b03",
    userName: "sy*****",
    rating: 4,
    date: "2026.05.25",
    variant: "4인용",
    content: "전체적으로 만족하는데 의자 포장이 조금 헐거워서 모서리에 살짝 눌린 자국이 있었어요. 사용에는 문제없습니다.",
  },
  {
    id: "r-b04",
    userName: "bh*****",
    rating: 5,
    date: "2026.05.11",
    variant: "4인용",
    content: "코튼화이트로 선택했는데 주방 인테리어랑 정말 잘 어울려요. 위드의자 쿠션감도 좋아서 오래 앉아도 편합니다.",
    images: ["/images/reviews/1210130010/review-04-1.webp"],
  },
  {
    id: "r-b05",
    userName: "hw*****",
    rating: 5,
    date: "2026.04.29",
    variant: "4인용",
    content: "혼수가구로 구매했는데 가성비가 정말 좋아요. 세라믹 상판이라 관리도 편하고 디자인도 세련됐습니다.",
    images: ["/images/reviews/1210130010/review-05-1.webp"],

  },
  {
    id: "r-b06",
    userName: "so*****",
    rating: 5,
    date: "2026.04.16",
    variant: "4인용",
    content: "4인용이라 자취방 다이닝 공간에 딱 맞게 들어왔어요. 식탁 다리도 안정적이라 흔들림이 전혀 없습니다.",
  },
  {
    id: "r-b07",
    userName: "ry*****",
    rating: 4,
    date: "2026.04.03",
    variant: "4인용",
    content: "디자인은 마음에 드는데 설치 당일 기사님이 시간이 좀 촉박해 보였어요. 결과물 자체는 깔끔합니다.",
  },
  {
    id: "r-b08",
    userName: "jm*****",
    rating: 5,
    date: "2026.03.21",
    variant: "4인용",
    content: "세라믹 상판 위에 뜨거운 그릇을 바로 올려도 변형이 없어서 너무 편해요. 의자도 식탁이랑 톤이 잘 맞습니다.",
    images: ["/images/reviews/1210130010/review-08-1.webp"],
  },
  {
    id: "r-b09",
    userName: "ys*****",
    rating: 5,
    date: "2026.03.08",
    variant: "4인용",
    content: "작은 평수 신혼집인데 4인용 사이즈가 공간을 많이 차지하지 않아서 좋아요. 디자인도 모던해서 거실과 잘 어울립니다.",
  },
  {
    id: "r-b10",
    userName: "oj*****",
    rating: 5,
    date: "2026.02.23",
    variant: "4인용",
    content: "위드의자 등받이 각도가 편안해서 식사 시간이 길어져도 불편함이 없어요. 전체적인 완성도가 높은 제품입니다.",
  },
  {
    id: "r-b11",
    userName: "jx*****",
    rating: 5,
    date: "2026.02.09",
    variant: "4인용",
    content: "부모님 댁 식탁 교체하면서 4인용으로 골랐는데 만족도가 높아요. 세라믹 상판 특유의 매끈한 질감이 고급스럽습니다.",
  },
  {
    id: "r-b12",
    userName: "gh*****",
    rating: 5,
    date: "2026.01.26",
    variant: "4인용",
    content: "조립 설치까지 한 번에 끝나서 편했어요. 식탁과 의자 색감이 통일감 있게 잘 매칭됩니다.",
  },
  {
    id: "r-b13",
    userName: "lm*****",
    rating: 5,
    date: "2026.01.13",
    variant: "4인용",
    content: "원룸 다이닝 공간에 맞춰 4인용으로 구매했는데 크기도 적당하고 디자인도 깔끔해서 만족스럽습니다.",
  },
];

export const sharedReviews: ReviewData = {
  ...calculateReviewSummary(reviewItems),
  items: reviewItems,
};

export const sharedQnaItems: QnaItem[] = [
  // ── 6인용 ──
  {
    id: "q-a01",
    category: "상품",
    question: "세라믹 상판은 뜨거운 냄비를 직접 올려도 괜찮나요? 따로 받침이 필요한지 궁금합니다.",
    questioner: "ej*****",
    date: "2026.05.20",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 강화 세라믹 상판은 내열성이 우수해 뜨거운 그릇이나 냄비를 직접 올려도 변형이나 자국이 거의 남지 않습니다. 다만 장기적인 사용감을 위해 냄비받침 사용을 권장드립니다.",
    answerDate: "2026.05.21",
  },
  {
    id: "q-a02",
    category: "상품",
    question: "위드의자 4개로 구성되어 있는데, 의자만 추가로 더 구매할 수 있나요?",
    questioner: "kp*****",
    date: "2026.05.05",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 위드의자는 현재 단품으로는 별도 판매하지 않고 있습니다. 추가 구매를 원하실 경우 고객센터(1688-4945)로 문의해 주시면 가능 여부를 안내해 드리겠습니다.",
    answerDate: "2026.05.06",
  },
  {
    id: "q-a03",
    category: "기타",
    question: "세라믹 상판 모서리에 충격이 가해지면 깨질 위험이 있나요? 아이가 있어서 걱정됩니다.",
    questioner: "hz*****",
    date: "2026.06.10",
    answered: false,
  },
  // ── 4인용 ──
  {
    id: "q-b01",
    category: "배송",
    question: "4인용 식탁세트도 설치 서비스가 포함되어 있나요? 조립을 직접 해야 하는지 궁금합니다.",
    questioner: "pe*****",
    date: "2026.05.16",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 4인용 세트 역시 전문 설치팀의 조립·설치 서비스가 기본 포함되어 있습니다. 별도로 조립하실 필요 없이 편하게 받아보실 수 있습니다.",
    answerDate: "2026.05.17",
  },
  {
    id: "q-b02",
    category: "기타",
    question: "코튼화이트와 화이트마블 색상 차이가 실물로 봤을 때 많이 다른가요?",
    questioner: "zq*****",
    date: "2026.06.12",
    answered: false,
  },
];
