import type { ReviewData, QnaItem, Review } from "@/app/lib/types";
import { calculateReviewSummary } from "@/lib/reviews";

const reviewItems: Review[] = [
  {
    id: "r-a01",
    userName: "kh*****",
    rating: 5,
    date: "2026.07.05",
    variant: "차콜",
    content: "야간 근무라 낮에 자야 하는데 이 커튼 달고 인생이 달라졌어요. 한낮에도 밤처럼 깜깜해서 수면제가 필요 없습니다.",
    images: ["/images/reviews/1712100030/review-01-1.webp"],
  },
  {
    id: "r-a02",
    userName: "jm*****",
    rating: 5,
    date: "2026.06.26",
    variant: "화이트",
    content: "암막인데 화이트라는 게 신기해서 샀는데 진짜 빛이 안 들어와요. 밝은 인테리어 유지하면서 암막 효과 원하는 분께 최고입니다.",
  },
  {
    id: "r-a03",
    userName: "bw*****",
    rating: 5,
    date: "2026.06.17",
    variant: "차콜",
    content: "아이 낮잠 시간마다 전쟁이었는데 커튼 치면 바로 잠들어요. 양면 컬러라 밖에서 보이는 면도 깔끔합니다.",
    images: ["/images/reviews/1712100030/review-03-1.webp"],
  },
  {
    id: "r-a04",
    userName: "sz*****",
    rating: 5,
    date: "2026.06.08",
    variant: "차콜",
    content: "코팅 암막은 비닐 느낌이라 싫었는데 이건 직조라 일반 커튼처럼 부드럽게 떨어져요. 세탁해도 성능 그대로입니다.",
  },
  {
    id: "r-a05",
    userName: "ty*****",
    rating: 4,
    date: "2026.05.30",
    variant: "화이트",
    content: "암막 성능은 완벽한데 3중직이라 무게가 좀 있어요. 튼튼한 레일에 설치하시길 권합니다.",
  },
  {
    id: "r-a06",
    userName: "nq*****",
    rating: 5,
    date: "2026.05.21",
    variant: "차콜",
    content: "서향 집이라 오후마다 집이 찜통이었는데 커튼 치니 실내 온도가 확실히 덜 올라가요. 단열 효과는 기대 이상입니다.",
  },
  {
    id: "r-a07",
    userName: "lp*****",
    rating: 5,
    date: "2026.05.12",
    variant: "화이트",
    content: "맞춤제작이라 우리 집 긴 창에도 길이가 딱 맞아요. 바닥에 끌리지도 뜨지도 않는 길이라 호텔처럼 떨어집니다.",
    images: ["/images/reviews/1712100030/review-07-1.webp"],
  },
  {
    id: "r-a08",
    userName: "xd*****",
    rating: 3,
    date: "2026.05.03",
    variant: "차콜",
    content: "암막은 확실한데 커튼 사이 틈으로 새는 빛까지는 못 막아요. 완전 암실을 원하면 창보다 넉넉하게 주문해야 합니다.",
  },
  {
    id: "r-a09",
    userName: "fg*****",
    rating: 5,
    date: "2026.04.24",
    variant: "차콜",
    content: "홈시네마 방에 설치했는데 낮에도 영화관 분위기가 나요. 방음까지는 아니어도 바깥 소음이 한 층 줄었습니다.",
  },
  {
    id: "r-a10",
    userName: "ae*****",
    rating: 5,
    date: "2026.04.15",
    variant: "화이트",
    content: "신생아 방에 달았는데 아기 수면 교육에 큰 도움이 됐어요. 통잠 자기 시작한 게 커튼 덕분인 것 같습니다.",
  },
  {
    id: "r-a11",
    userName: "uc*****",
    rating: 5,
    date: "2026.04.06",
    variant: "차콜",
    content: "1위 상품이라 기대하고 샀는데 기대 이상이에요. 두께감 있는 원단인데 결이 고급스러워서 침실 분위기가 살아납니다.",
  },
  {
    id: "r-a12",
    userName: "qs*****",
    rating: 5,
    date: "2026.03.28",
    variant: "화이트",
    content: "부모님 침실에 선물로 달아드렸어요. 새벽잠이 없으시던 아버지가 요즘 늦잠 주무신다고 하네요.",
  },
  {
    id: "r-a13",
    userName: "zr*****",
    rating: 5,
    date: "2026.03.19",
    variant: "차콜",
    content: "자취방 원룸 창에 달았는데 가로등 불빛이 완전히 차단돼요. 아침 알람 소리에만 깨는 삶을 되찾았습니다.",
  },
];

export const sharedReviews: ReviewData = {
  ...calculateReviewSummary(reviewItems),
  items: reviewItems,
};

export const sharedQnaItems: QnaItem[] = [
  {
    id: "q-a01",
    category: "상품",
    question: "양면 컬러는 화이트 면과 차콜 면 중 어느 쪽을 방 안쪽으로 다나요?",
    questioner: "vd*****",
    date: "2026.06.12",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 주문 시 선택하신 컬러가 실내 쪽 면으로 제작됩니다. 화이트 선택 시 실내는 화이트, 창밖은 차콜 면이 보이는 방식입니다. 감사합니다.",
    answerDate: "2026.06.13",
  },
  {
    id: "q-a02",
    category: "상품",
    question: "완전 암막을 원하는데 창 폭보다 얼마나 여유 있게 주문해야 하나요?",
    questioner: "gh*****",
    date: "2026.05.25",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 측면 빛샘 방지를 위해 창 폭 기준 좌우 각 15cm 이상 여유를 두고 주문하시길 권장드립니다. 천장형 레일 설치 시 상단 빛샘도 최소화됩니다. 감사합니다.",
    answerDate: "2026.05.26",
  },
  {
    id: "q-a03",
    category: "배송",
    question: "지금 주문하면 다음 주말 전에 받을 수 있나요?",
    questioner: "bk*****",
    date: "2026.07.07",
    answered: false,
  },
];
