import type { ReviewData, QnaItem, Review } from "@/app/lib/types";
import { calculateReviewSummary } from "@/lib/reviews";

const reviewItems: Review[] = [
  {
    id: "r-a01",
    userName: "hn*****",
    rating: 5,
    date: "2026.07.18",
    variant: "기본",
    content: "신혼집 주방이 좁아서 2인용으로 알아보다가 반타원이라 동선에 안 걸려서 딱 좋았어요. 원목 결도 예뻐서 사진보다 실물이 더 마음에 듭니다.",
    images: ["/images/reviews/1210140010/review-01-1.webp", "/images/reviews/1210140010/review-01-2.webp"],
  },
  {
    id: "r-a02",
    userName: "ks*****",
    rating: 5,
    date: "2026.07.08",
    variant: "기본",
    content: "1000mm라 자취방에도 여유롭게 들어갔어요. 조립도 다리만 끼우면 끝이라 설치 기사님이 금방 마치셨습니다.",
  },
  {
    id: "r-a03",
    userName: "th*****",
    rating: 4,
    date: "2026.06.28",
    variant: "기본",
    content: "오크 원목이라 그런지 사용할수록 색이 예쁘게 배어드는 느낌이에요. 다만 상판에 물기가 남으면 자국이 살짝 남아서 바로 닦아줘야 합니다.",
  },
  {
    id: "r-a04",
    userName: "ny*****",
    rating: 5,
    date: "2026.06.18",
    variant: "기본",
    content: "반타원이라 좁은 주방에서도 지나다닐 때 모서리에 안 부딪혀서 좋아요. 둘이 마주 앉기에 딱 맞는 크기입니다.",
  },
  {
    id: "r-a05",
    userName: "ig*****",
    rating: 5,
    date: "2026.06.07",
    variant: "기본",
    content: "원목 특유의 자연스러운 무늬가 살아있어서 인테리어 포인트가 됐어요. 친구들이 놀러올 때마다 어디서 샀냐고 물어봅니다.",
    images: ["/images/reviews/1210140010/review-05-1.webp"],
  },
  {
    id: "r-a06",
    userName: "ce*****",
    rating: 3,
    date: "2026.05.27",
    variant: "기본",
    content: "가격 대비 만족스러운데 배송이 예정일보다 이틀 늦었어요. 조립 상태나 마감은 깔끔합니다.",
  },
  {
    id: "r-a07",
    userName: "dm*****",
    rating: 5,
    date: "2026.05.16",
    variant: "기본",
    content: "오일 마감이라 관리가 어려울까 걱정했는데 마른 천으로 닦아주기만 하면 돼서 편해요. 색감도 은은하고 고급스럽습니다.",
  },
  {
    id: "r-a08",
    userName: "ru*****",
    rating: 4,
    date: "2026.05.05",
    variant: "기본",
    content: "다리 두께가 얇아 보였는데 실제로는 튼튼해서 흔들림이 없어요. 다만 상판 모서리가 조금 더 둥글었으면 하는 아쉬움이 있습니다.",
  },
  {
    id: "r-a09",
    userName: "ao*****",
    rating: 5,
    date: "2026.04.24",
    variant: "기본",
    content: "혼자 살아도 손님 왔을 때 둘이 앉기 좋은 크기라 만족해요. 좁은 주방인데도 답답하지 않습니다.",
  },
  {
    id: "r-a10",
    userName: "wl*****",
    rating: 5,
    date: "2026.04.13",
    variant: "기본",
    content: "원목 식탁을 알아보다가 가격이 합리적이라 골랐는데 만족도가 높아요. 반타원 디자인이 생각보다 훨씬 예쁩니다.",
  },
  {
    id: "r-a11",
    userName: "qb*****",
    rating: 4,
    date: "2026.04.02",
    variant: "기본",
    content: "설치 기사님이 친절하게 다리 수평까지 맞춰주고 가셨어요. 식탁 자체 마감도 꼼꼼한 편입니다.",
  },
  {
    id: "r-a12",
    userName: "ef*****",
    rating: 5,
    date: "2026.03.21",
    variant: "기본",
    content: "작은 원룸에 두기 딱 좋은 사이즈예요. 원목이라 그런지 플라스틱 식탁보다 훨씬 안정감이 느껴집니다.",
  },
  {
    id: "r-a13",
    userName: "xh*****",
    rating: 5,
    date: "2026.03.09",
    variant: "기본",
    content: "신혼 첫 가구로 골랐는데 두고두고 잘 쓸 것 같아요. 나뭇결이 자연스러워서 어떤 인테리어에도 잘 어울립니다.",
  },
];

export const sharedReviews: ReviewData = {
  ...calculateReviewSummary(reviewItems),
  items: reviewItems,
};

export const sharedQnaItems: QnaItem[] = [
  {
    id: "q-a01",
    category: "상품",
    question: "반타원이라 의자를 많이 놓지 못할 것 같은데 의자를 몇 개까지 놓을 수 있나요?",
    questioner: "dg*****",
    date: "2026.06.25",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 2인 기준으로 설계된 식탁이라 마주보는 두 자리가 가장 적합하며, 좁은 쪽에 보조 의자 하나를 더 두시는 것도 가능합니다. 감사합니다.",
    answerDate: "2026.06.26",
  },
  {
    id: "q-a02",
    category: "배송",
    question: "조립까지 배송기사님이 다 해주시나요?",
    questioner: "sk*****",
    date: "2026.06.10",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 네, 전문 배송팀이 방문하여 다리 조립과 수평 조정까지 완료해 드립니다. 감사합니다.",
    answerDate: "2026.06.11",
  },
  {
    id: "q-a03",
    category: "상품",
    question: "원목이라 습기에 약하지 않나요?",
    questioner: "wm*****",
    date: "2026.05.20",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 오일 마감으로 어느 정도 방습 처리가 되어 있으나, 물기는 바로 닦아주시고 직사광선을 피해 사용하시길 권장드립니다. 감사합니다.",
    answerDate: "2026.05.21",
  },
  {
    id: "q-a04",
    category: "기타",
    question: "체리색 등 다른 컬러 원목으로도 나오나요?",
    questioner: "hf*****",
    date: "2026.04.28",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 현재는 내추럴 오크 색상 단일 구성으로만 판매하고 있습니다. 감사합니다.",
    answerDate: "2026.04.29",
  },
  {
    id: "q-a05",
    category: "배송",
    question: "지방에도 설치 배송이 가능한가요?",
    questioner: "zb*****",
    date: "2026.07.15",
    answered: false,
  },
];
