import type { ReviewData, QnaItem, Review } from "@/app/lib/types";
import { calculateReviewSummary } from "@/lib/reviews";

const reviewItems: Review[] = [
  // ── 베이직 패키지 (거실+방2개) ──
  {
    id: "r-a01",
    userName: "jy*****",
    rating: 5,
    date: "2026.07.03",
    variant: "베이직 (거실+방2개)",
    content: "이사하면서 창 세 개를 한 번에 해결했어요. 실측 기사님이 꼼꼼하게 재주셔서 창에 딱 맞게 나왔습니다.",
    images: ["/images/reviews/1712100010/review-01-1.webp"],
  },
  {
    id: "r-a02",
    userName: "sh*****",
    rating: 5,
    date: "2026.06.25",
    variant: "베이직 (거실+방2개)",
    content: "거실은 커튼, 방 두 개는 블라인드로 골랐는데 조합이 자유로워서 좋았어요. 개별로 맞추는 것보다 확실히 저렴합니다.",
  },
  {
    id: "r-a03",
    userName: "mk*****",
    rating: 4,
    date: "2026.06.16",
    variant: "베이직 (거실+방2개)",
    content: "결과물은 만족스러운데 성수기라 시공까지 3주 꽉 채워 걸렸어요. 이사 일정이 급하신 분은 여유 있게 주문하세요.",
  },
  {
    id: "r-a04",
    userName: "dp*****",
    rating: 5,
    date: "2026.06.07",
    variant: "베이직 (거실+방2개)",
    content: "샘플을 직접 보고 고르니 화면으로 볼 때보다 실패가 없어요. 시공도 한 시간 만에 깔끔하게 끝났습니다.",
    images: ["/images/reviews/1712100010/review-04-1.webp", "/images/reviews/1712100010/review-04-2.webp", "/images/reviews/1712100010/review-04-3.webp"],
  },
  {
    id: "r-a05",
    userName: "wg*****",
    rating: 5,
    date: "2026.05.29",
    variant: "베이직 (거실+방2개)",
    content: "신혼집 입주에 맞춰 시공했는데 커튼 하나로 집 분위기가 완성됐어요. 기사님이 커튼 주름까지 정리해주고 가셨습니다.",
  },
  {
    id: "r-a06",
    userName: "eb*****",
    rating: 3,
    date: "2026.05.20",
    variant: "베이직 (거실+방2개)",
    content: "제품과 시공은 좋았지만 실측 방문 일정이 두 번 변경돼서 아쉬웠어요. 결과물 자체는 흠잡을 데 없습니다.",
  },
  {
    id: "r-a07",
    userName: "hj*****",
    rating: 5,
    date: "2026.05.11",
    variant: "베이직 (거실+방2개)",
    content: "20평대 아파트에 딱 맞는 구성이에요. 방 블라인드는 빛 조절이 자유로워서 재택근무할 때 특히 만족합니다.",
  },
  {
    id: "r-a08",
    userName: "cn*****",
    rating: 5,
    date: "2026.05.02",
    variant: "베이직 (거실+방2개)",
    content: "부모님 댁 리모델링하면서 진행했어요. 어르신들이 조작하기 쉬운 방식으로 추천해주셔서 편하게 쓰고 계십니다.",
    images: ["/images/reviews/1712100010/review-08-1.webp"],
  },
  {
    id: "r-a09",
    userName: "yt*****",
    rating: 5,
    date: "2026.04.22",
    variant: "베이직 (거실+방2개)",
    content: "셀프로 재서 주문했다가 실패한 경험이 있어서 실측 서비스가 정말 든든했어요. 창틀 안쪽까지 딱 떨어집니다.",
  },
  {
    id: "r-a10",
    userName: "ls*****",
    rating: 4,
    date: "2026.04.13",
    variant: "베이직 (거실+방2개)",
    content: "구성 대비 가격은 만족스러운데 원단 선택지가 조금 더 많았으면 해요. 기본 원단도 퀄리티는 좋습니다.",
  },
  {
    id: "r-a11",
    userName: "bm*****",
    rating: 5,
    date: "2026.04.04",
    variant: "베이직 (거실+방2개)",
    content: "전세 만기로 이사가 잦은데 이 가격에 시공까지 포함이면 부담이 없어요. 두 번째 집도 여기로 할 생각입니다.",
  },
  // ── 플러스 패키지 (거실+방3개) ──
  {
    id: "r-b01",
    userName: "kd*****",
    rating: 5,
    date: "2026.07.07",
    variant: "플러스 (거실+방3개)",
    content: "방 세 개 집이라 플러스로 했는데 집 전체 톤이 통일되니 인테리어 완성도가 달라져요. 시공 기사님도 친절하셨습니다.",
    images: ["/images/reviews/1712100011/review-01-1.webp"],
  },
  {
    id: "r-b02",
    userName: "on*****",
    rating: 5,
    date: "2026.06.28",
    variant: "플러스 (거실+방3개)",
    content: "아이 방은 암막 커튼형, 서재는 블라인드형으로 공간마다 다르게 구성했어요. 패키지인데 맞춤처럼 유연합니다.",
  },
  {
    id: "r-b03",
    userName: "vs*****",
    rating: 5,
    date: "2026.06.19",
    variant: "플러스 (거실+방3개)",
    content: "창 네 개를 개별로 알아보다 지쳐서 패키지로 돌렸는데 훨씬 편하고 저렴했어요. 견적 비교해보시면 답 나옵니다.",
  },
  {
    id: "r-b04",
    userName: "rq*****",
    rating: 4,
    date: "2026.06.10",
    variant: "플러스 (거실+방3개)",
    content: "전체적으로 만족하는데 거실 커튼 봉 마감재가 살짝 아쉬워요. 원단과 시공 퀄리티는 좋습니다.",
  },
  {
    id: "r-b05",
    userName: "az*****",
    rating: 5,
    date: "2026.05.31",
    variant: "플러스 (거실+방3개)",
    content: "30평대 초반인데도 창 개수가 맞아서 플러스로 진행했어요. 실측 때 창 크기 상관없이 가능하다고 안내받았습니다.",
    images: ["/images/reviews/1712100011/review-05-1.webp", "/images/reviews/1712100011/review-05-2.webp"],
  },
  {
    id: "r-b06",
    userName: "tf*****",
    rating: 5,
    date: "2026.05.22",
    variant: "플러스 (거실+방3개)",
    content: "입주 청소 다음 날 바로 시공받았는데 반나절 만에 온 집이 완성됐어요. 새 아파트 입주라면 무조건 추천합니다.",
  },
  {
    id: "r-b07",
    userName: "gi*****",
    rating: 5,
    date: "2026.05.13",
    variant: "플러스 (거실+방3개)",
    content: "커튼과 블라인드 톤을 맞춰 골라주셔서 집 전체가 하나의 무드로 이어져요. 혼자 골랐으면 못 냈을 조합입니다.",
  },
  {
    id: "r-b08",
    userName: "uj*****",
    rating: 4,
    date: "2026.05.04",
    variant: "플러스 (거실+방3개)",
    content: "시공 결과는 대만족인데 예약이 밀려서 실측까지 일주일 기다렸어요. 미리 주문하시길 권합니다.",
  },
  {
    id: "r-b09",
    userName: "nx*****",
    rating: 5,
    date: "2026.04.24",
    variant: "플러스 (거실+방3개)",
    content: "방마다 창 크기가 제각각인 구축 아파트인데도 전부 딱 맞게 제작됐어요. 맞춤 시공의 힘을 느꼈습니다.",
    images: ["/images/reviews/1712100011/review-09-1.webp"],
  },
  {
    id: "r-b10",
    userName: "pw*****",
    rating: 5,
    date: "2026.04.15",
    variant: "플러스 (거실+방3개)",
    content: "가족 모두 만족한 소비였어요. 특히 거실 커튼은 호텔 로비 느낌이 난다고 손님들이 다 물어봅니다.",
  },
];

export const sharedReviews: ReviewData = {
  ...calculateReviewSummary(reviewItems),
  items: reviewItems,
};

export const sharedQnaItems: QnaItem[] = [
  {
    id: "q-a01",
    category: "상품",
    question: "베이직 패키지에서 방 하나만 커튼형으로 하고 나머지는 블라인드형으로 섞을 수 있나요?",
    questioner: "dg*****",
    date: "2026.06.20",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 네, 공간별로 블라인드형과 커튼형을 자유롭게 조합하실 수 있습니다. 실측 방문 시 기사님과 공간별 구성을 확정하시면 됩니다. 감사합니다.",
    answerDate: "2026.06.21",
  },
  {
    id: "q-b01",
    category: "상품",
    question: "30평형대인데 플러스 패키지(거실+방3개)로 진행 가능한가요?",
    questioner: "sk*****",
    date: "2026.06.05",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 패키지는 창 개수 기준 구성으로, 거실 1개와 방 3개 창 구성이라면 평형과 관계없이 진행 가능합니다. 다만 표준 규격을 크게 초과하는 대형 창은 실측 시 추가 비용이 안내될 수 있습니다. 감사합니다.",
    answerDate: "2026.06.06",
  },
  {
    id: "q-a02",
    category: "배송",
    question: "실측부터 시공까지 보통 얼마나 걸리나요? 이사 날짜에 맞추고 싶습니다.",
    questioner: "wm*****",
    date: "2026.05.18",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 실측 방문 후 제작과 시공까지 통상 2~3주 소요됩니다. 이사 일정이 확정되어 있다면 주문 시 요청사항에 남겨주시면 일정에 맞춰 조율해 드립니다. 감사합니다.",
    answerDate: "2026.05.18",
  },
  {
    id: "q-b02",
    category: "상품",
    question: "기존에 달려 있는 커튼 철거도 해주시나요?",
    questioner: "hf*****",
    date: "2026.04.30",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 시공 당일 기존 커튼·블라인드 철거를 무상으로 지원해 드립니다. 철거물 수거가 필요하신 경우 실측 시 미리 말씀해 주세요. 감사합니다.",
    answerDate: "2026.05.01",
  },
  {
    id: "q-a03",
    category: "기타",
    question: "주말 시공도 가능한가요?",
    questioner: "zb*****",
    date: "2026.07.06",
    answered: false,
  },
];
