import type { ReviewData, QnaItem, Review } from "@/app/lib/types";
import { calculateReviewSummary } from "@/lib/reviews";

const reviewItems: Review[] = [
  // ── 렌지대 60cm ──
  {
    id: "r-a01",
    userName: "hj*****",
    rating: 5,
    date: "2026.07.22",
    variant: "화이트",
    content: "가스레인지 옆에 뒀는데 조리도구 정리가 확 편해졌어요. 화이트 컬러가 주방을 밝게 만들어줍니다.",
    images: ["/images/reviews/1212100030/review-01-1.webp", "/images/reviews/1212100030/review-01-2.webp"],
  },
  {
    id: "r-a02",
    userName: "sm*****",
    rating: 5,
    date: "2026.07.13",
    variant: "메이플",
    content: "서랍에 조리도구, 선반에 양념통 나눠 담으니 동선이 짧아졌어요. 메이플 톤도 자연스럽습니다.",
  },
  {
    id: "r-a03",
    userName: "kt*****",
    rating: 5,
    date: "2026.07.04",
    variant: "화이트",
    content: "상판에 전자레인지를 올려두니 공간 활용도가 훨씬 좋아졌어요. 설치도 깔끔했습니다.",
    images: ["/images/reviews/1212100030/review-03-1.webp"],
  },
  {
    id: "r-a04",
    userName: "yn*****",
    rating: 5,
    date: "2026.06.25",
    variant: "메이플",
    content: "60cm라 좁은 주방에도 부담 없이 들어갔어요. 마감도 꼼꼼한 편입니다.",
  },
  {
    id: "r-a05",
    userName: "dw*****",
    rating: 5,
    date: "2026.06.16",
    variant: "화이트",
    content: "화구 옆이라 걱정했는데 마감이 열에 강해서 안심하고 씁니다. 설치 기사님도 친절하셨습니다.",
  },
  {
    id: "r-a06",
    userName: "bg*****",
    rating: 5,
    date: "2026.06.07",
    variant: "메이플",
    content: "조리 동선 바로 옆이라 양념통 꺼내기가 훨씬 편해졌어요. 메이플 컬러도 고급스럽습니다.",
    images: ["/images/reviews/1212100030/review-06-1.webp"],
  },
  {
    id: "r-a07",
    userName: "ej*****",
    rating: 5,
    date: "2026.05.29",
    variant: "화이트",
    content: "가격 대비 수납력이 좋아요. 화이트라 어디에도 잘 어울립니다.",
  },
  {
    id: "r-a08",
    userName: "ps*****",
    rating: 5,
    date: "2026.05.20",
    variant: "메이플",
    content: "서랍이 부드럽게 열려서 사용감이 좋아요. 마감도 꼼꼼합니다.",
    images: ["/images/reviews/1212100030/review-08-1.webp"],
  },
  {
    id: "r-a09",
    userName: "wc*****",
    rating: 4,
    date: "2026.05.11",
    variant: "화이트",
    content: "전체적으로 만족하는데 설치가 하루 밀렸어요. 완성도는 기대 이상입니다.",
    images: ["/images/reviews/1212100030/review-09-1.webp"],
  },
  {
    id: "r-a10",
    userName: "mr*****",
    rating: 5,
    date: "2026.05.02",
    variant: "메이플",
    content: "조리도구 수납이 확실히 편해졌어요. 메이플 톤이 자연스럽습니다.",
  },
  {
    id: "r-a11",
    userName: "hb*****",
    rating: 5,
    date: "2026.04.23",
    variant: "화이트",
    content: "가스레인지 옆 공간이 정리되니 주방이 훨씬 깔끔해 보여요. 화이트 컬러도 깨끗합니다.",
    images: ["/images/reviews/1212100030/review-11-1.webp"],
  },
  {
    id: "r-a12",
    userName: "jy*****",
    rating: 5,
    date: "2026.04.14",
    variant: "메이플",
    content: "설치까지 문제없이 잘 끝났어요. 마감도 훌륭합니다.",
  },
  {
    id: "r-a13",
    userName: "on*****",
    rating: 5,
    date: "2026.04.05",
    variant: "화이트",
    content: "60cm 사이즈가 저희 주방에 딱 맞았어요. 수납력도 넉넉합니다.",
  },
  {
    id: "r-a14",
    userName: "vs*****",
    rating: 3,
    date: "2026.03.27",
    variant: "메이플",
    content: "제품은 괜찮은데 배송이 예정보다 늦어졌어요. 완성도 자체는 좋습니다.",
  },
  {
    id: "r-a15",
    userName: "rq*****",
    rating: 5,
    date: "2026.03.18",
    variant: "화이트",
    content: "가성비 좋은 렌지대라 만족해요. 화이트라 밝은 느낌입니다.",
    images: ["/images/reviews/1212100030/review-15-1.webp"],
  },
  {
    id: "r-a16",
    userName: "az*****",
    rating: 5,
    date: "2026.03.09",
    variant: "메이플",
    content: "조리도구 정리가 한결 편해졌어요. 메이플 컬러가 고급스럽습니다.",
  },
  // ── 코너렌지대 85cm ──
  {
    id: "r-b01",
    userName: "tf*****",
    rating: 5,
    date: "2026.07.17",
    variant: "화이트",
    content: "모서리 공간을 알차게 활용할 수 있어서 좋아요. 85cm라 수납력도 훨씬 넉넉합니다.",
    images: ["/images/reviews/1212100031/review-01-1.webp"],
  },
  {
    id: "r-b02",
    userName: "gi*****",
    rating: 5,
    date: "2026.07.08",
    variant: "메이플",
    content: "코너형이라 자투리 공간이 사라졌어요. 메이플 컬러도 자연스럽습니다.",
  },
  {
    id: "r-b03",
    userName: "uj*****",
    rating: 5,
    date: "2026.06.29",
    variant: "화이트",
    content: "설치 기사님이 수평까지 꼼꼼하게 맞춰주셨어요. 화이트라 밝은 느낌입니다.",
  },
  {
    id: "r-b04",
    userName: "nx*****",
    rating: 5,
    date: "2026.06.20",
    variant: "메이플",
    content: "코너 자리를 활용하니 주방이 훨씬 넓어 보여요. 수납력도 기대 이상입니다.",
  },
  {
    id: "r-b05",
    userName: "pw*****",
    rating: 5,
    date: "2026.06.11",
    variant: "화이트",
    content: "상판이 넓어서 전자레인지, 커피포트를 함께 올려둘 수 있어요. 마감도 깔끔합니다.",
    images: ["/images/reviews/1212100031/review-05-1.webp", "/images/reviews/1212100031/review-05-2.webp", "/images/reviews/1212100031/review-05-3.webp"],
  },
  {
    id: "r-b06",
    userName: "lc*****",
    rating: 5,
    date: "2026.06.02",
    variant: "메이플",
    content: "모서리 사각지대를 완벽하게 채웠어요. 메이플 톤이 우드 식탁이랑 잘 어울립니다.",
  },
  {
    id: "r-b07",
    userName: "fe*****",
    rating: 5,
    date: "2026.05.24",
    variant: "화이트",
    content: "가격은 있지만 그만큼 수납력이 확실해요. 화이트라 어디에 둬도 깨끗합니다.",
  },
  {
    id: "r-b08",
    userName: "hj*****",
    rating: 5,
    date: "2026.05.15",
    variant: "메이플",
    content: "코너렌지대라 공간 활용도가 최고예요. 설치도 깔끔하게 끝났습니다.",
  },
  {
    id: "r-b09",
    userName: "sm*****",
    rating: 4,
    date: "2026.05.06",
    variant: "화이트",
    content: "전체적으로 만족하는데 설치 예약이 조금 밀렸어요. 완성도는 훌륭합니다.",
  },
  {
    id: "r-b10",
    userName: "kt*****",
    rating: 5,
    date: "2026.04.27",
    variant: "메이플",
    content: "모서리 공간을 이렇게 알차게 쓸 수 있는지 몰랐어요. 메이플 컬러도 고급스럽습니다.",
  },
  {
    id: "r-b11",
    userName: "yn*****",
    rating: 5,
    date: "2026.04.18",
    variant: "화이트",
    content: "85cm라 수납량이 정말 넉넉해요. 화이트 컬러가 주방을 밝게 만들어줍니다.",
    images: ["/images/reviews/1212100031/review-11-1.webp"],
  },
  {
    id: "r-b12",
    userName: "dw*****",
    rating: 5,
    date: "2026.04.09",
    variant: "메이플",
    content: "코너형이라 동선이 훨씬 자연스러워졌어요. 마감도 꼼꼼합니다.",
  },
  {
    id: "r-b13",
    userName: "bg*****",
    rating: 5,
    date: "2026.03.31",
    variant: "화이트",
    content: "가족 모두 만족한 구매였어요. 모서리 공간 활용이 탁월합니다.",
  },
  {
    id: "r-b14",
    userName: "ej*****",
    rating: 3,
    date: "2026.03.22",
    variant: "메이플",
    content: "제품은 좋은데 가격이 부담스러운 편이에요. 그래도 수납력은 확실합니다.",
  },
  {
    id: "r-b15",
    userName: "ps*****",
    rating: 5,
    date: "2026.03.13",
    variant: "화이트",
    content: "설치까지 깔끔하게 마쳐주셔서 만족스러워요. 코너형이라 공간 효율이 좋습니다.",
  },
];

export const sharedReviews: ReviewData = {
  ...calculateReviewSummary(reviewItems),
  items: reviewItems,
};

export const sharedQnaItems: QnaItem[] = [
  {
    id: "q-a01",
    category: "상품",
    question: "60cm 렌지대와 85cm 코너렌지대 중 어떤 걸 골라야 할지 모르겠어요.",
    questioner: "dg*****",
    date: "2026.06.20",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 일자형 공간에는 60cm 렌지대를, 모서리 공간을 활용하고 싶으시면 85cm 코너렌지대를 추천드립니다. 감사합니다.",
    answerDate: "2026.06.21",
  },
  {
    id: "q-b01",
    category: "배송",
    question: "설치까지 얼마나 걸리나요?",
    questioner: "sk*****",
    date: "2026.06.05",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 방문 설치 기준 40~60분 내외로 완료됩니다. 감사합니다.",
    answerDate: "2026.06.06",
  },
  {
    id: "q-a02",
    category: "상품",
    question: "가스레인지 화구와 어느 정도 거리를 두고 설치해야 하나요?",
    questioner: "wm*****",
    date: "2026.05.18",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 화구와 최소 10cm 이상 간격을 두고 설치하시길 권장드립니다. 감사합니다.",
    answerDate: "2026.05.19",
  },
  {
    id: "q-b02",
    category: "기타",
    question: "화이트, 메이플 외 다른 색상 계획 있나요?",
    questioner: "hf*****",
    date: "2026.04.22",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 현재는 화이트, 메이플 두 가지 색상으로만 판매하고 있습니다. 감사합니다.",
    answerDate: "2026.04.23",
  },
  {
    id: "q-a03",
    category: "배송",
    question: "60cm 렌지대만 먼저 설치하고 나중에 다른 제품을 추가해도 되나요?",
    questioner: "zb*****",
    date: "2026.03.15",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 네, 개별 구매 후 순차적으로 설치하실 수 있습니다. 감사합니다.",
    answerDate: "2026.03.16",
  },
  {
    id: "q-b03",
    category: "상품",
    question: "코너렌지대 상판 내구성이 궁금해요. 무거운 냄비를 올려도 괜찮을까요?",
    questioner: "ip*****",
    date: "2026.07.19",
    answered: false,
  },
];
