import type { ReviewData, QnaItem, Review } from "@/app/lib/types";
import { calculateReviewSummary } from "@/lib/reviews";

const reviewItems: Review[] = [
  {
    id: "r-a01",
    userName: "mj*****",
    rating: 5,
    date: "2026.07.08",
    variant: "화이트",
    content: "도마를 눕혀 두면 늘 축축했는데 세워서 말리니 반나절이면 뽀송해요. 화이트 컬러가 주방 타일이랑 잘 어울립니다.",
    images: ["/images/reviews/1711120020/review-01-1.webp", "/images/reviews/1711120020/review-01-2.webp"],
  },
  {
    id: "r-a02",
    userName: "ks*****",
    rating: 5,
    date: "2026.07.01",
    variant: "블랙",
    content: "블랙은 색 배임이 없어서 관리 부담이 없어요. 칼 여러 자루에 수저 세트까지 딱 들어갑니다.",
    images: ["/images/reviews/1711120020/review-02-1.webp"],
  },
  {
    id: "r-a03",
    userName: "wy*****",
    rating: 5,
    date: "2026.06.24",
    variant: "화이트",
    content: "싱크대 한 켠이 이거 하나로 정리됐어요. 만원대인데 무게감 있고 흔들리지 않아 만족스럽습니다.",
  },
  {
    id: "r-a04",
    userName: "dr*****",
    rating: 4,
    date: "2026.06.17",
    variant: "블랙",
    content: "통풍 구조라 위생적인 건 확실한데 대형 통도마는 살짝 빡빡하게 들어가요. 일반 도마 기준으로는 최고입니다.",
  },
  {
    id: "r-a05",
    userName: "hz*****",
    rating: 5,
    date: "2026.06.10",
    variant: "화이트",
    content: "주방 정리템 중에 제일 잘 산 물건이에요. 바닥 트레이가 분리돼서 물 버리고 씻기 편합니다.",
    images: ["/images/reviews/1711120020/review-05-1.webp"],
  },
  {
    id: "r-a06",
    userName: "pn*****",
    rating: 5,
    date: "2026.06.03",
    variant: "블랙",
    content: "칼꽂이가 막혀있는 통이 아니라 열린 구조라 안까지 마르는 게 마음에 들어요. 세균 걱정이 확 줄었습니다.",
    images: ["/images/reviews/1711120020/review-06-1.webp"],
  },
  {
    id: "r-a07",
    userName: "bg*****",
    rating: 5,
    date: "2026.05.27",
    variant: "화이트",
    content: "이사하면서 주방 소품을 화이트로 통일했는데 톤이 딱 맞아요. 코팅이 매트해서 싸 보이지 않습니다.",
  },
  {
    id: "r-a08",
    userName: "sn*****",
    rating: 3,
    date: "2026.05.20",
    variant: "블랙",
    content: "기능은 만족하는데 모서리 코팅이 한 군데 살짝 벗겨진 채로 왔어요. 교환하기 번거로워 그냥 쓰지만 검수가 아쉽습니다.",
  },
  {
    id: "r-a09",
    userName: "yu*****",
    rating: 5,
    date: "2026.05.13",
    variant: "화이트",
    content: "가위랑 브러시까지 꽂아 쓰고 있어요. 자리 차지가 적은데 수납력은 좋아서 좁은 주방에 딱입니다.",
    images: ["/images/reviews/1711120020/review-09-1.webp"],
  },
  {
    id: "r-a10",
    userName: "eh*****",
    rating: 5,
    date: "2026.05.06",
    variant: "블랙",
    content: "자취 5년 만에 칼도마 정리가 처음으로 됐습니다. 튼튼하고 디자인도 깔끔해서 친구들한테도 추천했어요.",
  },
  {
    id: "r-a11",
    userName: "cm*****",
    rating: 5,
    date: "2026.04.29",
    variant: "화이트",
    content: "설거지 후 도마 놓을 자리가 늘 고민이었는데 해결됐어요. 물받이에 고인 물만 버려주면 관리 끝이라 편합니다.",
  },
  {
    id: "r-a12",
    userName: "vq*****",
    rating: 5,
    date: "2026.04.22",
    variant: "블랙",
    content: "선물용으로 하나 더 샀어요. 받은 분도 주방이 정돈됐다고 좋아하십니다. 포장도 튼튼하게 와요.",
  },
  {
    id: "r-a13",
    userName: "ig*****",
    rating: 5,
    date: "2026.04.15",
    variant: "화이트",
    content: "칼날이 안 보이게 수납돼서 아이 있는 집에 안심이에요. 세워두니 도마 곰팡이도 안 생깁니다.",
    images: ["/images/reviews/1711120020/review-13-1.webp"],
  },
  {
    id: "r-a14",
    userName: "nt*****",
    rating: 4,
    date: "2026.04.08",
    variant: "화이트",
    content: "구성이나 마감은 좋은데 화이트는 김치 국물 같은 게 튀면 바로 닦아줘야 해요. 부지런히 관리할 자신 있으면 화이트 추천합니다.",
  },
  {
    id: "r-a15",
    userName: "ru*****",
    rating: 5,
    date: "2026.04.01",
    variant: "블랙",
    content: "스텐 뼈대라 그런지 묵직하고 미끄러지지 않아요. 몇 달째 물때 없이 새것 같습니다.",
  },
  {
    id: "r-a16",
    userName: "az*****",
    rating: 5,
    date: "2026.03.25",
    variant: "화이트",
    content: "주방 리모델링 마무리로 들였는데 존재감 없이 스며드는 디자인이에요. 이런 소품이 살림의 질을 올려줍니다.",
  },
  {
    id: "r-a17",
    userName: "jp*****",
    rating: 5,
    date: "2026.03.18",
    variant: "블랙",
    content: "부모님 댁 주방이 어두운 톤이라 블랙으로 드렸어요. 도마 두 개 쓰는 집이라면 무조건 사라고 하고 싶네요.",
  },
  {
    id: "r-a18",
    userName: "fl*****",
    rating: 5,
    date: "2026.03.11",
    variant: "화이트",
    content: "이 가격에 이 마감이면 고민할 이유가 없어요. 도마 사이 간격이 넓어서 두꺼운 원목 도마도 잘 마릅니다.",
  },
  {
    id: "r-a19",
    userName: "qo*****",
    rating: 5,
    date: "2026.03.04",
    variant: "블랙",
    content: "온라인 후기 보고 반신반의했는데 실물이 더 좋네요. 주방 상판 위 지저분함이 사라져서 요리할 맛이 납니다.",
  },
];

export const sharedReviews: ReviewData = {
  ...calculateReviewSummary(reviewItems),
  items: reviewItems,
};

export const sharedQnaItems: QnaItem[] = [
  {
    id: "q-a01",
    category: "상품",
    question: "칼은 최대 몇 자루까지 꽂을 수 있나요?",
    questioner: "gd*****",
    date: "2026.06.21",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 칼꽂이 슬롯은 총 4개로 식도·과도 기준 4자루까지 수납 가능합니다. 도마는 2장까지 함께 거치하실 수 있습니다. 감사합니다.",
    answerDate: "2026.06.22",
  },
  {
    id: "q-a02",
    category: "상품",
    question: "유리 도마도 거치 가능한가요? 무게 때문에 넘어질까 걱정됩니다.",
    questioner: "sv*****",
    date: "2026.06.05",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 스테인리스 뼈대와 무게중심이 낮은 구조로 일반 가정용 유리 도마(약 2kg 내외)까지 안정적으로 거치 가능합니다. 감사합니다.",
    answerDate: "2026.06.06",
  },
  {
    id: "q-a03",
    category: "상품",
    question: "화이트와 블랙 재질 차이가 있나요? 코팅이 다른 건지 궁금해요.",
    questioner: "ib*****",
    date: "2026.05.17",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 두 컬러 모두 동일한 스테인리스 뼈대에 무광 파우더 코팅으로 컬러만 다르게 마감되었습니다. 재질과 내구성은 동일합니다. 감사합니다.",
    answerDate: "2026.05.18",
  },
  {
    id: "q-a04",
    category: "배송",
    question: "다른 침구 상품과 함께 주문하면 묶음 배송되나요?",
    questioner: "pz*****",
    date: "2026.04.26",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 택배 출고 상품 간에는 동일 주문 건 기준 가능한 합포장으로 발송됩니다. 출고지가 다른 경우 개별 배송될 수 있으나 배송비는 1회만 부과됩니다. 감사합니다.",
    answerDate: "2026.04.27",
  },
  {
    id: "q-a05",
    category: "기타",
    question: "사은품으로 나온 실리콘 받침은 언제까지 증정인가요?",
    questioner: "km*****",
    date: "2026.04.03",
    answered: true,
    answer: "안녕하세요, 한샘입니다. 실리콘 받침 증정 이벤트는 4월 30일 주문 건까지 적용됩니다. 이벤트 종료 후에는 기본 구성으로 발송되는 점 참고 부탁드립니다. 감사합니다.",
    answerDate: "2026.04.04",
  },
  {
    id: "q-a06",
    category: "상품",
    question: "물받이 트레이만 따로 구매할 수 있나요?",
    questioner: "uy*****",
    date: "2026.07.07",
    answered: false,
  },
];
